### ISSUE TITLE
Enhanced form-data serialization

### ISSUE THREAD

**Issue by kennethreitz** [psf/requests#2987]
Would be great to include the functionality of `requests_toolbelt.utils.formdata.urlencode` in Requests. 

http://toolbelt.readthedocs.org/en/latest/formdata.html

Thoughts? 

/cc @Lukasa @sigmavirus24

**Comment by Lukasa** [comment]
No objection from me, but the tool belt is @sigmavirus24's baby so he may have a stronger position,

**Comment by kennethreitz** [comment]
To be clear, I mean making that the default behavior.

**Comment by sigmavirus24** [comment]
I think I'm the only contributing author of that code and both requests and the toolbelt are Apache-2.0.

If we want to move that into requests by default, we absolutely can and I'm happy to do that. We'll leave it in the toolbelt for people who are using requests prior to whatever version we ship that in.

**Comment by sigmavirus24** [comment]
> I think I'm the only contributing author of that code and both requests and the toolbelt are Apache-2.0.

I only bring this up because copyright is a huge PITA ;)

**Comment by Lukasa** [comment]
That's true, but I think that definitionally requests can use that code by reproducing the license: any other contributors have by definition made that code available under Apache 2.0.

Otherwise, I'm happy to do this. I'll happily do the (probably cursory) code review. 

This is another great use of the toolbelt by the way: letting ideas marinate and get tested outside the core codebase.

**Comment by sigmavirus24** [comment]
> This is another great use of the toolbelt by the way: letting ideas marinate and get tested outside the core codebase. 

My thoughts exactly.

> Otherwise, I'm happy to do this. I'll happily do the (probably cursory) code review. 

I think you did the original CR too ;)

**Comment by Lukasa** [comment]
> I think you did the original CR too ;)

Oh god in that case we should do a really thorough code review!

**Comment by sethmlarson** [comment]
In an effort to clean up the issue tracker to only have issues that are still relevant to the project we've done a quick pass and decided this issue may no longer be relevant for a variety of potential reasons, including:

* Applies to a much older version, unclear whether the issue still applies.
* Change requires a backwards incompatible release and it's unclear if the benefits are worth the migration effort from the community.
* There isn't a clear demand from the community on the change landing in Requests.

If you think the issue should remain open, please comment so below or open a new issue and link back to the original issue. Again, thank you for opening the issue and for the discussion, it's much appreciated.
