### ISSUE TITLE
Moving documentation translation to translating platform

### ISSUE THREAD

**Issue by caizixian** [psf/requests#3033]
#624 There're a bunch of translation repos under https://github.com/requests

They all started with a specific commit version of https://github.com/kennethreitz/requests , and then the translators worked on it.

But we lack a proper process to merge updates from upstream repo to these i18n repos. Translators cannot track what they need to retranslate if there's such change in upstream. As a result, some translation might be outdated, and therefore misleading. Maybe moving the whole translation project to Transifex or crowdin is a better idea.

**Comment by Lukasa** [comment]
I'm really intrigued by this idea. @kennethreitz?

**Comment by ghost** [comment]
Transifex has a really nice permissions system, you can set it to auto
update the source translation from a url and a useful API.

**Comment by caizixian** [comment]
For example, https://github.com/getsentry/sentry/blob/master/.tx/config

**Comment by caizixian** [comment]
@requests/translation-team

**Comment by kennethreitz** [comment]
I'm not at all familiar with Transifex, or how it works. 

I think our currently solution is "pretty good", and doubt that having a better workflow available will somehow encourage the translators to keep their translations up to date (a few translations are much more ad-lib and freeform, for example). These translations seem to be a "hack on it over the weekend, once" type of thing, and are pretty low priority.

**Comment by caizixian** [comment]
There is a guide for documentation internationalization.
http://www.sphinx-doc.org/en/stable/intl.html

The basic flow is ![](http://www.sphinx-doc.org/en/stable/_images/translation.png)

**Comment by caizixian** [comment]
There's an example of inconsistency between i18n repo and main repo

requests/requests-docs-cn#1

**Comment by sigmavirus24** [comment]
I think this is worth revisiting again. This definitely is valuable for our translators who do a lot of incredibly important work for this project.

**Comment by StewPoll** [comment]
Have you looked at Transifex?

Free for open source projects.

**Comment by sigmavirus24** [comment]
@TetraEtc I appreciate that you're replying from your email but that's exactly what we're discussing here. Please read existing issue history in the future.

**Comment by sethmlarson** [comment]
In an effort to clean up the issue tracker to only have issues that are still relevant to the project we've done a quick pass and decided this issue may no longer be relevant for a variety of potential reasons, including:

* Applies to a much older version, unclear whether the issue still applies.
* Change requires a backwards incompatible release and it's unclear if the benefits are worth the migration effort from the community.
* There isn't a clear demand from the community on the change landing in Requests.

If you think the issue should remain open, please comment so below or open a new issue and link back to the original issue. Again, thank you for opening the issue and for the discussion, it's much appreciated.
