### ISSUE TITLE
netrc reading does not respect NETRC environment variable

### ISSUE THREAD

**Issue by mitar** [psf/requests#4318]
As described [here](https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html), there is an environment variable `NETRC` which one can use to control where `.netrc` file is. Requests always searches in user's home directory.

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "14.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020cf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by chairmank** [comment]
Do we still want this feature? I want this feature, but I don't know overall sentiment among users.

I see that https://github.com/psf/requests/pull/4339 was closed because it wasn't finished. I volunteer to finish the work with appropriate test coverage and documentation.

**Comment by nik003** [comment]
This has been open very long without response. How will this case be handled? This would be a very good feature to implement.

**Comment by sigmavirus24** [comment]
This project has generally had a terrible experience with it's netrc support. It causes confusion and isn't convenient to disable. If anything, I'd expect the current maintainers to want to drop support for finding/parsing netrc files and close this as something they won't implement. (And they'd be right to do so)

**Comment by mitar** [comment]
Awesome! Thanks!
