### ISSUE TITLE
Reuse ssl.SSLContext across all SSL connections within a requests.Sesssion

### ISSUE THREAD

**Issue by alex** [psf/requests#4322]
requests should pass `ssl_context` to `urllib3.PoolManager`: https://github.com/requests/requests/blob/2a4dd64fb4c072c646277c9d057737b05351b86f/requests/adapters.py#L161-L162

Otherwise a new SSLContext is allocated for all requests. SSLContexsts can be huge, like 1MB, so doing this will be a performance and memory usage win.

**Comment by Stevoisiak** [comment]
It looks like Requests doesn't define `ssl_context` anywhere. Where should it be created?

**Comment by wagnerluis1982** [comment]
How is the status of this issue?

**Comment by echo4eva** [comment]
Hello, me and my group mates are going to be working on this issue.

**Comment by Echo-Lima-India** [comment]
@alex Could you tell me where you have an instance of ssl_context within the code? Thank you.

**Comment by nateprewitt** [comment]
This should be largely addressed in 9a40d1277807f0a4f26c9a37eea8ec90faa8aadc.
