### ISSUE TITLE
Problem with retries for HTTPS Connect proxy requests

### ISSUE THREAD

**Issue by railocius** [psf/requests#4470]
Summary.

I would like to solve this problem: https://github.com/requests/requests-ntlm/issues/104
and I narrowed it down to this line in requests\session.py:
```
        # Send the request
        r = adapter.send(request, **kwargs)  #<-- exception happens here for HTTPS case

        # Total elapsed time of the request (approximately)
        elapsed = preferred_clock() - start
        r.elapsed = timedelta(seconds=elapsed)

        # Response manipulation hooks
        r = dispatch_hook('response', hooks, r, **kwargs)
```
for a normal HTTP GET over a proxy, this will return an object r with an HTTP status code of 407. Then my auth hook will be called in the last line -> Authentication can take place.

However, for the HTTPS CONNECT case, the first line will throw an exception for 407 status code, and the command flow is interrupted! -> error

## Actual Result

Exception is thrown for HTTPS CONNECT instead of normal return from function with 407 status code set.

## Reproduction Steps

see the linked bug ticket above.

## System Information
I use the version installed by pip for Python 2.7.14, 32bit, windows 10, which is requests-2.7.0

```
python -m requests.help
C:\Python27\python.exe: No module named requests.help
```

But I also tried to copy the newest requests-2.18.4 and it has the same exception characteristic. Maybe I did something wrong there..

**Comment by railocius** [comment]
Ok, it seems the same issue was brought up here in 2013-2016: https://github.com/requests/requests/issues/1582
but was closed with no hope of fixing. Does anybody know, if anything changed relating to this ?

**Comment by nateprewitt** [comment]
Hi @railocius, this is still open in urllib3/urllib3#242 and is a blocker for Requests. Until a solution is made there, I don't know if we have a lot of options.

**Comment by sethmlarson** [comment]
Since https://github.com/urllib3/urllib3/issues/242 is closed, I am also closing this issue.
