### ISSUE TITLE
`RequestException` does not contain `request` as a field in some situation.

### ISSUE THREAD

**Issue by dong-zeyu** [psf/requests#4692]
`RequestException` does not contain `request` as a field in some situation.

## Expected Result

A `RequestException` (or its subclass) should contain a field named `request` if possible.

## Actual Result

I did not see any in 

https://github.com/requests/requests/blob/883caaf145fbe93bd0d208a6b864de9146087312/requests/models.py#L751-L756

Actually, I think it should be written like

```python
ChunkedEncodingError(e, request=self.request)
```

```python
ContentDecodingError(e, request=self.request)
```

```python
ConnectionError(e, request=self.request)
```

(Actually, the third line has another problem and had a fix in #4468 on version 3.0)

**Comment by sigmavirus24** [comment]
We omit it in these cases as you have a `response` which has `response.request` so if you're iterating over content you have the request that you can munge yourself if you're handling exceptions close to that response.

On top of that, those really aren't specific to a request as it is. Those happen after the response has been started so including the request may be misleading in those exceptions.

**Comment by dong-zeyu** [comment]
You are right since `RequestException.request` will be assigned in the following code if I already have `response` 

https://github.com/requests/requests/blob/883caaf145fbe93bd0d208a6b864de9146087312/requests/exceptions.py#L22-L24

However, what I want to do is just to log the information when an exception was raised. For example, when I trying to run the code like this
```python
try:
    requests.get("https://github.com/")
    requests.get("https://www.google.com/")
except RequestException as err:
    logging.warn('Failed in %s - %s', err.request.method, err.request.url)
```
All thing will work fine if `RequestException` was caused by `NewConnectionError` or `ConnectTimeoutError` in `urllib3`, but it will raise `AttributeError: 'NoneType' object has no attribute 'method'` if it was caused by `ReadTimeoutError` since `RequestException.request` was not initialized in such case.

What I want to express is that

- If a request was failed **in sending the request**, then I can get `RequestException.request` for logging

- If a request was failed **after receiving a bad response**, then I can get `RequestException.request` for logging

- However, if a request was failed **during the time receiving the content of a response**, then I get nothing but a `RequestException`

I don't know if it is reasonable, but I think in any case, I should get `RequestException.request` for logging or debugging
