### ISSUE TITLE
Wrong originating IP address with 2.21

### ISSUE THREAD

**Issue by znat** [psf/requests#4921]
Summary.

In a pod running on a Kubernetes cluster, a python app using `requests`.
When I look the `nginx-ingress` container logs 

With requests <= 2.20.1: the originating IP address of the requests belongs to the **cluster IP range** (which I think is correct)

With requests == 2.21: requests are coming from the **Node pool IP range** (which I don't think is correct)

## Expected Result

Requests should be coming from the cluster IP range

## Actual Result

Requests should be coming from the node pool IP range

## Reproduction Steps

Set up a K8S cluster, a deployment using `requests` and observe logs in the `nginx-ingress` controller pod

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.7"
  },
  "platform": {
    "release": "4.4.111+",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.20.0"
  },
  "system_ssl": {
    "version": "1010006f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
We don't pick our own source IP. I'm surprised that there's a difference between the versions. I think we need a smaller reproduction case because there's just too many moving pieces here.
