### ISSUE TITLE
Leakage of results from one request to another while using session

### ISSUE THREAD

**Issue by dilipvamsi** [psf/requests#4941]
Hi,
I was facing this issue when using the requests session in gevent workers threads. (https://github.com/ArangoDB-Community/pyArango/issues/65).
I faced the same issue when using Celery (which was not using the gevent for workers) while communicating to the db.
I have changed the code such that for every call to the db a new session is created and issue seemed to be resolved.
I think the issue may be due to large number of concurrent calls to db using the same session.

Regards,
Dilip Vamsi.

**Comment by madsmtm** [comment]
As far as I can tell, `requests.Session` is not thread safe, see https://github.com/kennethreitz/requests/issues/2766. So creating a new session per thread is probably the way to go?

**Comment by holmanb** [comment]
@sethmlarson is this issue resolved? Per your comment in https://github.com/psf/requests/issues/2766#issuecomment-2119324917 it seems you didn't think any threading issues remain.

**Comment by sigmavirus24** [comment]
@holmanb that seems an uncharitable read of Seth's statement which is that the issue had become stale and there needed to be new evidence of a threading problem to justify further investigation. I think this issue can also be closed though as stale.
