### ISSUE TITLE
iter_content returned size is far bigger than chunk_size

### ISSUE THREAD

**Issue by impredicative** [psf/requests#4979]
I expect `iter_content` to return me `chunk_size` number of bytes, but it never does. It returns me a far larger and random number of bytes. In contrast, `urllib.request` returns me exactly the number of bytes I request using its `.read(chunk_size)` method.

It is not acceptable for the returned chunk to use up to 5x more memory as evidenced below. Imagine this happening in say 64 threads at once. It should return exactly the number of bytes I asked for (or less at the end).

## Expected Result

```python
>>> import requests
>>> requests.__version__
'2.21.0'
>>> req = requests.get('http://docs.python-requests.org/en/latest/user/advanced/', stream=True)
>>> it = req.iter_content(8192)
>>> len(next(it))
8192
>>> len(next(it))
8192
>>> len(next(it))
8192
```

## Actual Result

```python
>>> import requests
>>> requests.__version__
'2.21.0'
>>> req = requests.get('http://docs.python-requests.org/en/latest/user/advanced/', stream=True)
>>> it = req.iter_content(8192)
>>> len(next(it))
3345
>>> len(next(it))
48672
>>> len(next(it))
47182
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.2"
  },
  "platform": {
    "release": "4.18.0-15-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

**Comment by rHuggler** [comment]
The docs mention that the returned item length may be different because of decoding, so I believe this is expected behavior.

> The chunk size is the number of bytes it should read into memory. This is not necessarily the length of each item returned as decoding can take place.

(See [docs for Response.iter_content](http://docs.python-requests.org/en/master/api/#requests.Response.iter_content))

EDIT: @kenneth-reitz can you confirm this?

**Comment by impredicative** [comment]
It may be documented and expected, but then the chunk_size loses any value for the user. urllib has no such problem. It works perfectly all the time for `read()` and returns exactly the number of bytes that were asked for. Please consider using an internal buffer or such for the extra bytes that the user hasn't asked for. Returning fewer bytes than chunk_size is even worse! I thought `requests` was supposed to present a clean and friendly interface to the user. For a GET request, the user may not care about how many bytes are internally read behind the scenes, as long as it's somewhat close to chunk_size.

**Comment by kennethreitz** [comment]
this is expected behavior, if what you're saying is correct @rHuggler

**Comment by impredicative** [comment]
Any update? I cannot use `requests` for a project until this issue is correctly resolved. Thanks.

**Comment by EvansJahja** [comment]
Does the problem go away if you don't use compression?
