### ISSUE TITLE
Need a clarification on adapters.py

### ISSUE THREAD

**Issue by user1493** [psf/requests#4985]
Can someone please tell me what is the use of the below lines in **adapters.py**?
Does it actually check for a proxy and uses it in get_connection?

```
        if proxy:
            proxy = prepend_scheme_if_needed(proxy, 'http')
            proxy_url = parse_url(proxy)
            if not proxy_url.host:
                raise InvalidProxyURL("Please check proxy URL. It is malformed"
                                      " and could be missing the host.")
            proxy_manager = self.proxy_manager_for(proxy)
            conn = proxy_manager.connection_from_url(url)
```
My system has no proxy enabled, I confirmed the same with `netsh winhttp show proxy` 
Output:
`Current WinHTTP proxy settings: Direct access (no proxy server)`

Not sure why the control is getting into `if proxy:` after `proxy = select_proxy(url, proxies)`

**Comment by vino1493** [comment]
This looks like a bug, please investigate on this further
