### ISSUE TITLE
Redirect with empty location header not followed

### ISSUE THREAD

**Issue by thollingshead** [psf/requests#4989]
I am working with an external service whose authentication pattern is to set a cookie authentication token and return a 302 redirect to the same location (the location header is an empty string). This redirect is not being followed, I believe due to [this line](https://github.com/kennethreitz/requests/blob/v2.21.0/requests/sessions.py#L151).

This forces code like the following:

```python
import requests

with requests.session() as session:
    session.cert = (cert, key)
    resp = session.get(url)

    # Extra code to handle redirect with empty location
    if resp.status_code == 302 and resp.headers["location"] == "":
        resp = session.get(url)
```

## System Information

Requests v2.21.0
Python 2.7.15
Windows Server 2012 R2

**Comment by Overv** [comment]
According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.2) the `Location` header is not allowed to be empty. Do most browser handle this as you describe?

**Comment by nateprewitt** [comment]
Given we haven't heard back on this in quite a while, I'm going to resolve. The current behavior of the service is objectively incorrect and I'm insistent to start adding behavior where we're guessing at the right thing to do. The best solution for this case will be to handle the redirect manually.
