### ISSUE TITLE
Custom HTTP Non RFC Error Code Handling

### ISSUE THREAD

**Issue by gnubyte** [psf/requests#5015]
Custom HTTP/Non-RFC error code handling is not supported - feature request to handle custom error codes.

## Expected Result

If an error code like 601 is thrown back instead of a typical RFC 404, 400, etc. then the requests library replies back with an HttpBadStatusLine

status_code response would be 601 or whatever the server sent back
## Actual Result

HttpBadStatusLine from urllib

## System Information

    Python v3

```
requests.put(someUrl, data=self.payload)
```

**Comment by timofurrer** [comment]
According to the HTTP protocol, I think those are invalid status codes.
Just out of curiosity - why would you want to use such status codes in the first place?

**Comment by gnubyte** [comment]
Apparently, in NodeJS you can craft custom Error Codes that python supports handling with the urllib.
My coworker is now presenting custom http codes to indicate different application statuses. Its common in other protocols in my workplace from what I'm seeing of the vendors where I'm at (well known video company).

I was thinking we extend the exception handling to allow custom error codes to be handled. As it stands if I use requests instead of the urllib I can handle these sorts of things, and I'd just like to see requests be able to do the same, natively, without refactoring.

**Comment by sethmlarson** [comment]
Since this error is raised by the standard library, not Requests, there isn't anything we can do here. Servers should stick with compliant HTTP status codes.
