### ISSUE TITLE
CBOR support

### ISSUE THREAD

**Issue by arkocal** [psf/requests#5016]
Requests is not accepting feature requests at this time.

Still, I would like to open the issue to find out whether this use case is relevant for more people and worth consideration.

I would like to have a `cbor` parameter when making requests, similar to `json`, which would prepare the request body and set the `Content-Type` header.

**Cons:**
-  `requests` is HTTP for humans, CBOR is not human readable.
- It would add a parameter to the most used and most high-level functions -> extra complexity for the API.

**Pros:** 
- In this use case JSON and CBOR are very similar. When interacting with an API that accepts both encodings it results in unidiomatic code to handle both in different ways (using the parameter for JSON and manually doing this with CBOR)
- It is much more beautiful to use a parameter instead of preparing the request manually. The existince of the `json` parameter also speaks for this argument, with the difference JSON being much more popular than CBOR.

**Comment by vashek** [comment]
+1. I recently needed this and had to code it myself so yes, I do find it relevant.

**Comment by sethmlarson** [comment]
CBOR is already "supported" in that you can use a CBOR library to encode and decode raw binary data over the wire. I don't think this is necessarily something Requests should be doing itself. Closing this for now.
