### ISSUE TITLE
Always get a CaseInsensitiveDict for headers.

### ISSUE THREAD

**Issue by kootenpv** [psf/requests#5020]
If we look at how headers are merged from session and request, only if both are set the result will be a `CaseInsensitiveDict`. I propose to always use a case insensitive dict, even when one of the two is missing.

## Expected Result

Always get a `CaseInsensitiveDict` for headers.

## Actual Result

If only `session.headers` or `request.headers` are set, then headers are not case insensitive.

See also:

https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L55

I am not sure whether we should only do it `isinstance(dict_class, CaseInsensitiveDict)`, or whether it would make sense to always convert to the `dict_class`.

**Comment by vinitwadgaonkar** [comment]
can i take up this issue @kootenpv

**Comment by kootenpv** [comment]
Sure

**Comment by sigmavirus24** [comment]
Actually don't. We deliberately allow any mapping type to allow for a variety of use-cases. A change here won't be accepted

**Comment by nateprewitt** [comment]
For posterity as I see this was linked in Typeshed, the premise here is wrong.

> If we look at how headers are merged from session and request, only if both are set the result will be a CaseInsensitiveDict. I propose to always use a case insensitive dict, even when one of the two is missing.

> If only session.headers or request.headers are set, then headers are not case insensitive.

The reporter was confusing the generalized behavior of `merge_settings` which handle many forms of input, and the case of `headers`. Session.headers will always be a `CaseInsensitiveDict` when [initialized](https://github.com/psf/requests/blob/bc04dfd6dad4cb02cd92f5daa81eb562d280a761/src/requests/sessions.py#L392-L395) and that's what it's documented as being. Setting it to `None` has never been a documented or intended use case, that's undefined behavior at that point.

Whether `request_settings` is None is moot at that point, it will either [return the Session's CaseInsensitiveDict](https://github.com/psf/requests/blob/c7e0fc087ceeadb8b4c84a0953a422c474093d6d/requests/sessions.py#L59-L60), or create a new one [[1](https://github.com/psf/requests/blob/c7e0fc087ceeadb8b4c84a0953a422c474093d6d/requests/sessions.py#L69)] [[2](https://github.com/psf/requests/blob/bc04dfd6dad4cb02cd92f5daa81eb562d280a761/src/requests/sessions.py#L493-L495)]. This was also true with the code in 2019. Requests accepts a `MutableMapping` through the `requests.request` APIs but it will always be resolved to CaseInsensitiveDict before being sent.
