### ISSUE TITLE
In [21]: import requests /usr/lib/python3/dist-packages/cryptography/x509/base.py:16: RuntimeWarning: coroutine 'wait' was never awaited   from cryptography.x509.extensions import Extension, ExtensionType RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by Ro0tk1t** [psf/requests#5027]
Summary.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

```
/usr/lib/python3/dist-packages/cryptography/x509/base.py:16: RuntimeWarning: coroutine 'wait' was never awaited
  from cryptography.x509.extensions import Extension, ExtensionType
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by timofurrer** [comment]
Can you please fill out the template: describe what your expected and actual result was and how to reproduce.
And please paste the traceback (if valuable) in to the post body and no the title. Please use a descriptive title instead.

Thank you 🎉

**Comment by nateprewitt** [comment]
There isn't enough information here to evaluate what is happening. Given this is an issue in cryptography and not Requests directly, I'm going to resolve. I'd recommend checking the issue tracker with cryptography if you're still able to reproduce the issue.
