### ISSUE TITLE
data: URLs won't fetch with requests, work in regular Python urllib

### ISSUE THREAD

**Issue by mvasilkov** [psf/requests#5032]
Summary: [`data:` URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) don't work, which is different from the Python 3 standard library.

## Expected Result

I expected the following to just work™:

```python
import requests
r = requests.get('data:text/plain;charset=utf-8,hello')
r.text  # 'hello'
```

## Actual Result

```
import requests
r = requests.get('data:text/plain;charset=utf-8,hello')

<the entire traceback omitted for brevity>

~\c\django-balkans\virtual\Lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    638
    639         # Get the appropriate adapter to use
--> 640         adapter = self.get_adapter(url=request.url)

InvalidSchema: No connection adapters were found for 'data:text/plain;charset=utf-8,hello'
```

## Reproduction Steps

The following Python 3 code works as intended:

```python
import urllib.request
a = 'data:text/plain;charset=utf-8,Алоха, православныя!'
with urllib.request.urlopen(a) as response:
    print(response.read().decode('utf-8'))
```

As well as the following JavaScript code (which might appear unrelated, but is included to demonstrate that the `data:` URLs are widely supported by bog-standard tooling):

```javascript
const test = async () => {
    const res = await fetch('data:text/plain;charset=utf-8,Алоха, православныя!');
    const data = await res.text();
    console.log(data);
}
test()
```

I'm convinced that the requests library would benefit from supporting this also.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1010008f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

**Comment by sethmlarson** [comment]
Requests is an HTTP library, the `data` scheme isn't supported by requests or the underlying urllib3 library.

**Comment by nateprewitt** [comment]
Seth is right here. Requests is an http client and not intended to have the full support of a browser. There is likely another library that may be better suited for your case if urllib isn't sufficient.
