### ISSUE TITLE
change contentType from application/x-www-form-urlencoded to multipart/form-data

### ISSUE THREAD

**Issue by Peerke1** [psf/requests#5036]
I am sending data to a webserver that does not understand application/x-www-form-urlencoded.
postman uses multipart/form-data to send the request and that works like a charm.

is there anyway to change the contentType so it will generate the needed boundary?
(if i just set the header myself it will not generate the boundary)

**Comment by prrvchr** [comment]
Hi,
Did you try:
`request.headers.update({'ContentType': multipart/form-data})`
If you use Session() simply substitute request to session.
Normally all the headers are kept.

**Comment by Peerke1** [comment]
Hi,
Thanks for the reply. somehow the updated header gets re-updated by the post itself. I found this article: 
https://franklingu.github.io/programming/2017/10/30/post-multipart-form-data-using-requests/
that pointed me to the solution. got it working now, all form fields are send in multipart/form-data (without any {dummy)files)

posted the link for others as there are quite a few with the same issue
