### ISSUE TITLE
unclosed socket

### ISSUE THREAD

**Issue by jemdad** [psf/requests#5040]
I am noticing this “warning” which making soap calls at high speed.

zeep/xsd/visitor.py:883: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=(‘x.x.x.x’, 39092), raddr=('y.y.y.y', 9001)>
zeep/xsd/types/complex.py:159: ResourceWarning: unclosed <socket.socket

There is an explanation on requests library thread at: https://github.com/kennethreitz/requests/issues/3912

Is it something that can be handled at zeep?
Thanks

**Comment by nateprewitt** [comment]
The stacktrace provided doesn't appear to be related to Requests. You may need to follow up with zeep.
