### ISSUE TITLE
Connection broken IncompletedRead

### ISSUE THREAD

**Issue by pyliangbo** [psf/requests#5051]
I'm crawling some websites. But I met a problem that makes me very depressed. 
The error:
('Connection broken: IncompleteRead(2048 bytes read)', IncompleteRead(2048 bytes read)) 

The code:    html=requests.post(url,data=json.dumps(payload),headers=headers,verify=False)

I have never met this problem before. Just one day, it came out.
I'm looking forward to your help.

**Comment by Thrimbda** [comment]
It will be better if you can provide more info about this error.
What websites you are crawling?
Does it appear every time?
the Version of requests & python?

Or straightforwardly, could you provide a script that would recur this error?

**Comment by pyliangbo** [comment]
Thanks for your response!
I use the multiprocessing module to crawler websites. This error happens frequently.  
![image](https://user-images.githubusercontent.com/35482019/55942515-1d109380-5c77-11e9-8d29-b9fdaf426b71.png)
The version of python: 3.6.6
The version of requests:  2.21.0
I'm afraid it's inconvenient to offer the scripts.

**Comment by pyliangbo** [comment]
> It will be better if you can provide more info about this error.
> What websites you are crawling?
> Does it appear every time?
> the Version of requests & python?
> Or straightforwardly, could you provide a script that would recur this error?

Thanks for your response!
I'm use the multiprocessing module and the proxies to crawler the websites.
Here is the code.
`html=requests.post(url,data=json.dumps(payload),headers=headers,verify=False,proxies=proxies)`
Here is the snapshot of the error. Unluckily, this error happens frequently, but not always.
<img width="770" alt="微信图片_20190412215135" src="https://user-images.githubusercontent.com/35482019/56042228-2c720880-5d6d-11e9-92a6-4ced472f5524.png">

In the processes, some works well, but some reports this error.

**Comment by pyliangbo** [comment]
The version of python : 3.7.1
The version of requests: 2.21.0

**Comment by nateprewitt** [comment]
The issue you're hitting here @pyliangbo is that the server is failing to send the full payload before closing the connection. You'll need to handle this excption case if crawling arbitrary websites.
