### ISSUE TITLE
socks4 proxies break after use

### ISSUE THREAD

**Issue by kelvinwop** [psf/requests#5056]
Summary.

## Expected Result

Socks4 proxies work

## Actual Result

![image](https://user-images.githubusercontent.com/30770221/56176064-705c4c00-5fbf-11e9-91ac-06b2431ec4b0.png)

The ips through the proxy and public ip are the same

Also, this code:
```python
sess.proxies.update({"https": "socks9000://0.0.0.0"})
sess.get("https://icanhazip.com")
```
Usually throws an exception because socks9000 doesn't exist. But when this bug appears, this line no longer throws an exception.

## Reproduction Steps

The problem only appears when charles proxy is on so there's probably some interference there

```python
import requests
def test_proxy(proxy, throw_exc=False):
    sess = requests.session()
    proxy_dict = {"https": "socks4://{}".format(proxy)}
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0'
    }
    sess.proxies.update(proxy_dict)
    if config.get_config()["charles"]:
        sess.verify = "cert.pem"
    try:
        r = sess.get('https://icanhazip.com/', headers=headers, timeout=15)
        # read response.text to release worker back to pool
        return r.text.strip()
    except requests.exceptions.ConnectionError as ex:
        if throw_exc:
            raise ex
        return False
    except requests.exceptions.InvalidSchema:
        print("ERROR! INSTALL PYSOCKS <pip install pysocks>!")
        sys.exit(501)
    except ProxyError as pe:
        raise pe
    except Exception as ex:
        if throw_exc:
            raise ex
        return False
```

I'm not too sure what causes this either, but this code here eventually starts returning non-proxy ip address which is super weird and mysterious

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.6.1"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.2"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010102f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
Unfortunately we can't help debug your proxy, you'll have to try debugging this yourself or using Stackoverflow. Good luck.
