### ISSUE TITLE
some issues about  proxy

### ISSUE THREAD

**Issue by wz343450860** [psf/requests#5059]
Dear Supporter

  I used a proxy when I request some website, I found that my ip agent is not in effect. In order to verify this ， I used a fake ip proxy such as http://123.123.123.123:123, but when I used this ip to 
request this url "https://mobile.yangkeduo.com/goods2.html?goods_id=473261", it seems not connect porxy first, but the response is returned  and it is the real content from this url.  I can't understand why ip doesn't take effect.  Because the ip is fake I thought it will raise a proxyError。

Could you tell me why？

Zhao

**Comment by wz343450860** [comment]
Hi Supporter
  I debugged this request when I add the proxy in requests.session().proxies,   in the adapters.py the method  "conn = self.get_connection(request.url, proxies)"  the proxies turn to None,

**Comment by yaniv-s** [comment]
Dear @wz343450860 

If you request an https url, you should configure an http**s** proxy, configuring an http (not https) proxy wouldn't affect an https request.

Can you please confirm that you've configured an https proxy and requested an https url  - or vice versa - configured an http proxy and requested an http url?

If you can confirm it, can you please paste an example code which demonstrate the issue, the requests library version and python version?

Thanks!
