### ISSUE TITLE
Question: Digest choose hash algorithm (HTTPDigestAuth)

### ISSUE THREAD

**Issue by damanuel** [psf/requests#5068]
I try to authenticate a post request using Digest authentication. The server returns a list of two authentication challenges with the hash algorithms MD5 & SHA-256. 

To authenticate I use a HTTPDigestAuth object. It creates the digest using the second hash in the list (in this case SHA-256). 

My question: is there a way to force the library to use MD5? Due to reasons, I don't want to use SHA-256, even though it is part of the authentication challenge.

**Comment by damanuel** [comment]
I used my own authentication method as a workaround. But still, I am wondering if there is a more straight forward way to prioritize which algorithm to choose.

**Comment by nateprewitt** [comment]
Hi @damanuel, it's not entirely clear what the challenge you're receiving looks like. There isn't formal way to specify which algorithm is used, so your current workaround is probably the best approach for now.
