### ISSUE TITLE
Client certificate authentication: Support certificates as string input

### ISSUE THREAD

**Issue by arvindsree** [psf/requests#5071]
Hi,

I am using requests for an HTTPS query with client certificate authentication. Requests currently only supports passing my key pair as a filename argument. I need to be able to pass my client auth key pair as a string

The python code is compiled and needs to be distributed to end users. I think passing the certificate as file name input in this use case is highly insecure.

Requests Version: 2.20.1

**Comment by sethmlarson** [comment]
This would require implementation in urllib3 first before Requests could use it. The only work-around is using an `SSLContext` object yourself. Closing this for now.
