### ISSUE TITLE
The vast majority of issues in the database do not have labels

### ISSUE THREAD

**Issue by zurbrugc** [psf/requests#5086]
The majority of the issues in the database are missing labels. Especially notable is the sparseness of issues with the "Contributor Friendly" label. When a potential contributor clicks the link in the second step of the README, they see five old issues:

![issue2_pic1](https://user-images.githubusercontent.com/40577023/57654716-b6d6a380-7589-11e9-92b2-9072070d629a.PNG)

It would be quite helpful for contributors--especially new contributors--if more issues were given tags.

**Comment by nateprewitt** [comment]
Thank you for the feedback. We allocate resources to issue triage when they're available.
