### ISSUE TITLE
Request instalation using conda

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [psf/requests#5091]
Summary.

I couldn't install request using conda as you see in the following message
conda install -c conda-forge/label/cf201901 requests
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/py27h453aca2_1/noarch/repodata.json>
Elapsed: 00:00.501324
CF-RAY: 4d7647510c20d121-TXL

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/py27h453aca2_1

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
This appears to be an issue with Conda infrastructure or your networking setup. I'd suggest reaching out to them if you're still experiencing issues.
