### ISSUE TITLE
Why are cookies private on PreparedRequests objects?

### ISSUE THREAD

**Issue by mctwynne** [psf/requests#5096]
I was hoping to check the state of cookies that were present on a `PreparedRequest` object but found that the cookies member is private. Is there a specific reason for this?

**Comment by kobayashi** [comment]
Could you let us know the use case of checking the state of cookies with `PreparedRequest`?

**Comment by mctwynne** [comment]
@kobayashi I was actually just using pdb to verify which cookies were being sent for a handful of requests as part of a test I was writing. I think I was just expecting it to have been a public member like it is on the response, which is why I asked.

**Comment by kennethreitz** [comment]
because they're just metadata. the cookies being sent are present in the headers.
