### ISSUE TITLE
allow creating a read-only session object

### ISSUE THREAD

**Issue by stardust85** [psf/requests#5100]
that will allow only read methods (GET, OPTIONS). It should block POST and PUT (=raise an error). It wold make it simple to enforce that the session users only read :) But maybe using a use with read-only permissions is better. So you can probably forget it. Adding it here only for reference if someone goes this same dead end way.

**Comment by michaelkolber** [comment]
GET requests can certainly be used to change things on the server, so they're not really read-only. Besides, these things are usually implemented on the server, not on the client. If you really need it, create a subclass of the existing object.

**Comment by nateprewitt** [comment]
Hi @stardust85, thanks for the suggestion! I don't believe this is something we'd introduce directly into Requests itself, but you're welcome to subclass Session to create your own module for doing this. I'm sure you'll find others who find it useful as well.
