### ISSUE TITLE
clarification of some items related to contributing 

### ISSUE THREAD

**Issue by moffetma** [psf/requests#5101]
It could help potential new contributors if the "How to Contribute" section included the content or a link to the "Good Bug Reports" section of the contributing.md and a link to some simple example tests in step 4

**Comment by kobayashi** [comment]
Great idea! Is it possible for you to submit PR for this?

**Comment by Glyphack** [comment]
I can work on CONTRIBUTING.md file.

**Comment by asifmallik** [comment]
@Glyphack any update on the CONTRIBUTING.md file? I am wondering how I should get started

**Comment by Glyphack** [comment]
Hi, I did not receive any response on this so I did not start it. I don't know should I start a PR and work on it or no

**Comment by sethmlarson** [comment]
We already have a guide on the documentation iirc.
