### ISSUE TITLE
Having problem trying to use module repeteadly

### ISSUE THREAD

**Issue by dagerob** [psf/requests#5102]
Hi!
 I am trying to  use this module to connect to a server. The system has to make a request repeatedly (every few minutes). I made a sub thread that makes the request. The issue is that the requests sometimes work and sometimes throw an exception even though I'm using the same url and methods. 

The error I get is: Failed to establish a new connection [Errno -3] Temporary failure in name resolution. 

the part that doesn't work is this:
{'passkey':passkey}
r = requests.get( url, params=pyload, headers={'Connection':'close'})

I have investigated an I realized I was not closing the previous connections, however the error occurs still

**Comment by dagerob** [comment]
I was trying and found that when there is no internet connection this is the error occuring. So maybe that was the problem

**Comment by rubenwap** [comment]
I see you found the issue! 🥇  However, this reminds me that for the use case you describe (connecting very often) I recommend that you look into using sessions.

**Comment by dagerob** [comment]
Ok thanks, will look into it
