### ISSUE TITLE
How to send a encrypted json string with requests

### ISSUE THREAD

**Issue by sunmoondeer** [psf/requests#5106]
Hi,  I need to send a json string with post type, but in my project, i need to encrypt it before send. After encrypt, the string like "h5QkXuq8mY4n73YX4mv/Ug\u003d\u003d", I can not find a way to send data like this, I can do this with jmeter easily, just put the encrypted string in request body. How should I do with requests?

**Comment by VeNoMouS** [comment]
Looks like binary base64 encoded payload in unicode to me, u'\u003d' is b'='

**Comment by nateprewitt** [comment]
This would be a better question on usage for StackOverflow. Resolving since it's not a defect in Requests. Thanks for the suggestion, VeNoMouS.
