### ISSUE TITLE
Response contains empty strings 

### ISSUE THREAD

**Issue by ahmedrazi** [psf/requests#5107]
I am sending a request with URL and three query parameters with one parameter is getting its value on command line but it  is not populating the values for "vendorDetails dictionary.
import requests
import sys
from collections import OrderedDict 

url = "https://api.macaddress.io/v1"
mac= str(sys.argv[1])
print(mac)
qs=OrderedDict()
qs = {"apiKey":"xxxxxxxxxxx","output":"json","search":sys.argv[1]}

for key, value in qs.items(): 
    print(key, value) 

response= requests.get(url,params=qs)
print(response.url)

print(response.text)

I am getting the below response but all the values are empty after a query for the below mac address. So If I hard code the mac value in the query string it works but when I use it as a command line argument then it is returning the response without any value

$ python  web2.py 4:38:39:ff:ef:57
4:38:39:ff:ef:57
('output', 'json')
('search', '4:38:39:ff:ef:57')
('apiKey', 'xxxx')
https://api.macaddress.io/v1?output=json&search=4%3A38%3A39%3Aff%3Aef%3A57&apiKey=at_o45w16Yxa6RDxXNSV7lAZkY4DMax2
https://api.macaddress.io/v1?output=json&search=4%3A38%3A39%3Aff%3Aef%3A57&apiKey=xxxxxxxxx
{"vendorDetails":{"oui":"","isPrivate":false,"companyName":"","companyAddress":"","countryCode":""},"blockDetails":{"blockFound":false,"borderLeft":"","borderRight":"","blockSize":0,"assignmentBlockSize":"","dateCreated":"","dateUpdated":""},"macAddressDetails":{"searchTerm":"4:38:39:ff:ef:57","isValid":false,"virtualMachine":"Not detected","applications":[],"transmissionType":"multicast","administrationType":"LAA","wiresharkNotes":"No details","comment":""}}

I am

**Comment by rubenwap** [comment]
Initially I thought that this didn't look like an issue related to requests. But I ran your code out of curiosity. I was unable to reproduce the problem. I received the correct response even when inputting the mac address via parameter.

**Comment by nateprewitt** [comment]
This doesn't appear to be a defect with Requests. I'm going to resolve this for now since it's not reproducible with a general example and there isn't enough evidence to show this isn't caused by the server.
