### ISSUE TITLE
get_encoding_from_headers methods return value

### ISSUE THREAD

**Issue by bainiwaj** [psf/requests#5113]
Summary.
The problem with this method is that for certain languages the ISO-8859 does not work.
## Expected Result
I would like all HTTP header text to be returned for any language and not just english.
What you expected.
Certain languages such as french http header text does not work.
## Actual Result
Encoding error with non english
What happened instead.
encoding error
## Reproduction Steps

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
I'm going to resolve this with the same reasoning Kenneth used on the PR. This is currently the best interpretation we have over the available RFCs and reference clients. You can always set `encoding` on the Response object yourself before trying to read its contents, and it should work as expected. That would be the advised path forward in cases where encoding isn't specified.
