### ISSUE TITLE
Python requests NOT Throwing an Exception When Using Session with HTTPAdapter

### ISSUE THREAD

**Issue by own3mall** [psf/requests#5115]
Anyone know how I can better handle this situation?  I can't have the script freezing indefinitely.  I appreciate any help.

https://stackoverflow.com/questions/56482980/python-requests-not-throwing-an-exception-when-using-session-with-httpadapter

**Comment by own3mall** [comment]
If you set the total property in the Retry object to `False`, an exception is thrown, and the script no longer runs indefinitely.  So why does it not terminate unless `total` is set to `False`?

**Comment by nateprewitt** [comment]
This issue appears to be specific to your environment configuration since both the responders on Stackoverflow and I cannot reproduce the issue. I don't believe this is a defect in Requests with the information provided.
