### ISSUE TITLE
Incomplete read but requests did not raise an error

### ISSUE THREAD

**Issue by koshy1123** [psf/requests#5124]
First, let me preface that this issue might be because of some misspecification on the server side, but I'm curious if anyone has any ideas here. This [URL](https://hazards.fema.gov/femaportal/NFHL/Download/ProductsDownLoadServlet?DFIRMID=10001C&state=DELAWARE&county=KENT%20COUNTY&fileName=10001C_20190130.zip)  points to a zip file I'd like to download. If I paste the URL in a browser window or `wget`, I successfully manage to download the zip file but I'm unable to download the zip file using `requests` or more accurately, `requests` only downloads a portion of the file and does not raise an error.

## Expected Result

Wanting to do this in python, I used `requests` and I had logic to stream the content and  `iter_content` from the response and write to a file. I expected to write to and create a ~67 MB zipfile, or raise an incomplete read error.

## Actual Result

The response content is only `2583` bytes but it did successfully redirect to the right URL.

## Reproduction Steps

 Simple code with outputs to replicate:
```
>>> import requests
>>> url = 'https://hazards.fema.gov/femaportal/NFHL/Download/ProductsDownLoadServlet?DFIRMID=10001C&state=DELAWARE&county=KENT%20COUNTY&fileName=10001C_20190130.zip'
>>> resp = requests.get(url)
>>> len(resp.content)
2583
>>> resp.headers['content-length']
'66892906'
>>> resp.url
'https://hazards.fema.gov/nfhlv2/output/County/10001C_20190130.zip'
```
Anecdotally, I used a relatively old [`wget`](https://pypi.org/project/wget/) package (which it looks like is just using `urllib`) and it gave me an incomplete read error.
```
>>> wget.download('https://hazards.fema.gov/nfhlv2/output/County/10001C_20190130.zip')
  0% [                                                                        ]     8192 / 66892906Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 2583 out of 66892906 bytes>
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.6.1"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "4.9.125-linuxkit",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010102f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.24.3"
  },
  "using_pyopenssl": true
}
```

**Comment by koshy1123** [comment]
**Update**: This might be related to the fact that I was running this in a `docker` container. When I run it outside of a `docker` container, it works as expected:
```
Python 3.7.3 (default, May 10 2019, 15:15:13)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.21.0'
>>> url = 'https://hazards.fema.gov/nfhlv2/output/County/10001C_20190130.zip'
>>> r = requests.get(url)
>>> len(r.content)
66892906
```

and outside of my docker container, this is the system info:
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "18.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.24.3"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
This is an issue in urllib3 (urllib3/urllib3#723) that's technically been patched but is considered breaking in Requests. We have a PR (#3563) merged to address the issue but it's on hold until the next major version of Requests.
