### ISSUE TITLE
upload file with tavern using content-type multipart/form-data

### ISSUE THREAD

**Issue by i4ali999** [psf/requests#5125]
I am trying to use tavern for uploading file. Heres what my postman request looks like

[![enter image description here][1]][1]

using tavern heres what I have tried

    name: add data
    request:
      url: "server/runs/cube/64409f3e-d78c-4788-909e-e50518b48d8a/well/c4a1e3e9-c7f7-461a-a5aa-d10d09153bfd/data"
      method: POST
      data:
        type: TOPS
        file: data/test.csv
    response:
      status_code: 200

But I get a 500 internal server error. The request through postman works just fine. What am I missing?

  [1]: https://i.stack.imgur.com/MgMbk.jpg
  [2]: https://i.stack.imgur.com/VOwxn.jpg

**Comment by kobayashi** [comment]
What's the response output with tavern?

**Comment by kobayashi** [comment]
I found tavern does not support in multipart/form-data format.
https://github.com/taverntesting/tavern/issues/233#issuecomment-453829482

**Comment by nateprewitt** [comment]
Hi i4ali999@, this is an issue with Tavern and not requests. I’m going to resolve since there’s no additional steps to take here.
