### ISSUE TITLE
requests.get stream keyword argument

### ISSUE THREAD

**Issue by orihomie** [psf/requests#5132]
Hi, I'm trying to launch my python daemon inside of docker container and getting error:
> 'Connection broken: IncompleteRead(0 bytes read)'
- it happens when get requests performed inside of daemon (async, loading about 20k data, totally ~40k get-requests)

As I googled I've find out that users advise to set "stream" value to false - I did it, but nothing changed and then I just went deep into your code and find out that actually this variable does nothing (below is the final destination where this variable is being used):

```py
    def add_headers(self, request, **kwargs):
        """Add any headers needed by the connection. As of v2.0 this does
        nothing by default, but is left for overriding by users that subclass
        the :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.

        This should not be called from user code, and is only exposed for use
        when subclassing the
        :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.

        :param request: The :class:`PreparedRequest <PreparedRequest>` to add headers to.
        :param kwargs: The keyword arguments from the call to send().
        """
        pass
```

So, could you provide me some info / help - how should I use requests lib to force it to download data on get requests immediately?

**Comment by DemetriosBairaktaris** [comment]
It actually gets used here in the codebase: https://github.com/kennethreitz/requests/blob/0b6c110a5cd65685c42702b27e2872ad9c234ab8/requests/sessions.py#L685

You can try simulating what the internal code is doing by doing something like `requests.get("...").content` in your script

When accessing the content attribute of the response, it will download the data.

**Comment by orihomie** [comment]
> It actually gets used here in the codebase:
> 
> https://github.com/kennethreitz/requests/blob/0b6c110a5cd65685c42702b27e2872ad9c234ab8/requests/sessions.py#L685
> 
> You can try simulating what the internal code is doing by doing something like `requests.get("...").content` in your script
> 
> When accessing the content attribute of the response, it will download the data.

Still, I cant get how does it work

I think there is a bug (I did as u advised, and its not obvious for me why it returns stream instead of content, look at the screen: 

**I've expected to get content, because I passed 'stream' argument as False and instead of content I've got a variable with content property - this is unexpected behaviour for me since I've checked out requests/requests/sessions.py at line 685**)

![requests_bug](https://user-images.githubusercontent.com/29889683/61626436-facede80-ac85-11e9-8e3b-a8d425f73a04.PNG)

**Comment by orihomie** [comment]
And when I used "stream" value as a "True" - it returned me a variable with "content" property being already there - so I think you got a bug there or could you explain such behavior?

![image](https://user-images.githubusercontent.com/29889683/61774618-eadb0a00-adff-11e9-86e0-167640db827d.png)

**UPD 1.**

Can you please provide me more info about this line:
https://github.com/psf/requests/blob/0b6c110a5cd65685c42702b27e2872ad9c234ab8/requests/sessions.py#L624

For what purpose do you set it to default value?

**UPD 2.**

I've figured out that while it's send method's loop - request is not executed yet and has no property 'content' and then loop jumps back here:
https://github.com/psf/requests/blob/0b6c110a5cd65685c42702b27e2872ad9c234ab8/requests/sessions.py#L533

request gets executed ('content' prop show up)

**UPD 3.**

Seems debugger tricked me

**UPD 4.**

It seems that server, which contains url which is being requested (I do a lot of responses under 16 cores), at some point closes connection (I dont know, maybe DDoS defense) - and thats why at some point I'm getting ChunkedEncodingError - and this is correct behavior.
