### ISSUE TITLE
Is it possible to manually set the ecdh curve?

### ISSUE THREAD

**Issue by michaelrice** [psf/requests#5137]
I am on ubuntu 18.04 and there seems to be a problem with the openssl version it ships with such that I cant successfully connect to our API unless I manually set the `set_ecdh_curve("secp384r1")`. Right now Im having to just use urllib and do something like:
```python
        ctx = ssl.create_default_context()
        ctx.set_ecdh_curve("secp384r1")
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
```
I would like to switch from urllib to requests for my project but am unsure how to set this with requests. Is it possible, and if so how do I do it?

**Comment by sethmlarson** [comment]
Thanks for opening this. This likely won't be implemented as a direct option as it's so low-level and already covered by `SSLContext`.
