### ISSUE TITLE
Requests3 Docs: Add migration path for api from Requests2

### ISSUE THREAD

**Issue by AnneTheAgile** [psf/requests#5139]
Summary.

## Expected Result

Docs page which has migration for 1-2 also has for 2-3 ; 
https://github.com/kennethreitz/requests3/blob/master/docs/api.rst

## Actual Result

Only 1-2 is still on docs/api.rst, even on repo requests3 (which has no issues only PR's)

## Reproduction Steps

browse ^^

## System Information

    This is for dev docs

**Comment by AnneTheAgile** [comment]
If right now everything is fully back compatible, I am happy to give a PR for that.
The only note then would be to ensure you are not using python  2, because Requests3 only supports python3.6+ per the readme.

**Comment by nateprewitt** [comment]
Hi @AnneTheAgile, this reply is a bit later than it should have been. This project doesn't have any plans for Requests3 at this time, so I don't believe we'll be distributing documentation on migrating. Thanks for the suggestion though!
