### ISSUE TITLE
Change The Project Logo

### ISSUE THREAD

**Issue by isidentical** [psf/requests#5143]
The logo reminds us kenneth reitz and what he did, IMO it is better to remove the logo or replace it with something that is not specific to a person.

**Comment by kennethreitz** [comment]
That would make me sad.

**Comment by isidentical** [comment]
> That would make me sad

Okey, then we can close? IMO you dont think this is serious but it is. 

I didn't think a `collaborator` will troll my issue but if that is the case, then i dont want to discuss it further. Lets rename the repo as `kenneth-reitzs-request` and close this issue
