### ISSUE TITLE
monkey patch requests.utils.requote_uri failed

### ISSUE THREAD

**Issue by boy-hack** [psf/requests#5148]
I want to escape the {} symbol, but requests default to escaping the parameters of the url. I looked at the source code and the problem appears in the requote_uri of requests.utils , so I tried hooking this function.
```python
from urllib.parse import quote

import requests


def hook2(uri):
    print(11111111)
    safe_with_percent = "!#$%&'()*+,/:;=?@[]~{}^"
    return quote(uri, safe=safe_with_percent)


requests.utils.requote_uri = hook2
requests.get("http://127.0.0.1:8000", params='a=111&b=222!@$%^&({}')
```
But why did it fail?

**Comment by nateprewitt** [comment]
@boy-hack this issue tracker is specifically for defects in Requests. Please direct questions to StackOverflow.com, thanks!

**Comment by VeNoMouS** [comment]
@boy-hack ive run into the same issue, did you get anywhere with monkey patching **requote_uri**
