### ISSUE TITLE
how wrapper requests, to bypass WAF

### ISSUE THREAD

**Issue by hktalent** [psf/requests#5151]
how wrapper requests, to bypass WAF

**Comment by wfarn** [comment]
WAF's incorporate a wide range of technologies which are usually highly customized for the application they are designed to protect.

It's impossible to answer your question as it involves a multitude of disparate technologies which are likely to employ very different forms of protection and traffic analysis.  There won't be a "one size fits all" solution to this and it's very likely Requests isn't the right tool for the job.

Besides if you own/manage the firewall you should be able to have your traffic whitelisted, right?  ;)
