### ISSUE TITLE
Add a parameter so that URL encoding does not occur when sending URLs

### ISSUE THREAD

**Issue by 422926799** [psf/requests#5152]
URL encoding is not required when encountering special situations. So consider adding a URL that controls whether the URL sent is url-coded or not.

**Comment by kennethreitz** [comment]
Use a connection adapter. :)

**Comment by nateprewitt** [comment]
Kenneth is right, this would be best handled with a custom adapter. I don't see us adding this functionality directly to Requests at this time. Thanks for the suggestion!
