### ISSUE TITLE
something strange about cookie in requests.session.

### ISSUE THREAD

**Issue by C4o** [psf/requests#5154]
Summary.

## Expected Result
follow all 'set-cookie' actions from website.

## Actual Result
the website i request would set cookie for three or times to change a specific cookie or add a new cookie. and i found that first time the website set three cookies, that's ok, second time the website set another three cookies, and it failed, and third time the website tried to change three cookies, and it failed too. 
i printed session.cookies each time, it' ok, but cookies in  http packets that i captured did not match session.cookie, there were still the first three cookies.
by the way, my friend found that this situation also appear at other normal browser like Chrome and Firefox, but 'set-cookie' takes effect in Tor browser which is based on Firefox, maybe it's something new?

## Reproduction Steps

```python
import requests
session = requests.session()
session.get(url1)
session.get(url2)
session.get(url3)
```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by C4o** [comment]
forget to say how i solve it temporarily..cause i found that 'session.cookies' is ok, but cookies in http packets that i captured did not match session.cookie,  i tried to change cookieJar to a DICT and then change this DICT to cookieJar, and assign session.cookies with the new cookieJar before every http request.

**Comment by divinehawk** [comment]
Apologies for not submitting a proper patch, but this resolves some of the cookie persistent issues for me:
```

--- contrib.py~ 2019-12-04 00:21:49.838526261 -0500
+++ contrib.py  2019-12-04 00:21:51.988501821 -0500
@@ -154,6 +154,6 @@
         orig.version = 20
         orig.status = resp.status
         orig.reason = resp.reason
-        orig.msg = FakeOriginalResponse(resp.headers.iter_raw())
+        orig.msg = FakeOriginalResponse(resp.headers)
 
         return response

```

**Comment by C4o** [comment]
thanks, i'll try this later...
