### ISSUE TITLE
Incorrect Content-Type Returned from Head

### ISSUE THREAD

**Issue by Kerl1310** [psf/requests#5156]
## Summary
When requesting the headers and then outputting the content-type for [this](https://www.arl.army.mil/arlreports/1999/ARL-CR-441.pdf) url, text/html; charset=utf-8 is output as the content-type, but running `curl -I https://www.arl.army.mil/arlreports/1999/ARL-CR-441.pdf` returns application/pdf

## Expected Result

application/pdf

## Actual Result

text/html; charset=utf-8

## Reproduction Steps

```python
import requests

url = 'https://www.arl.army.mil/arlreports/1999/ARL-CR-441.pdf'

headers = requests.head(url).headers
content_type = headers['Content-Type']
print(content_type)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.7"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010103f",
    "version": "17.2.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": true
}
```

**Comment by SatyajeetMahato** [comment]
The provided url (https://www.arl.army.mil/arlreports/1999/ARL-CR-441.pdf ) is not working properly.

**Comment by Kerl1310** [comment]
@SatyajeetMahato Fixed the issue - seems the page blocks based on User Agent. Changing from the default resulted in "application/pdf" being returned as the content type
