### ISSUE TITLE
syntax error with last version of requests

### ISSUE THREAD

**Issue by pilot1981** [psf/requests#5157]
Hi,
from HASSIO installation with python 3.7.3 I'm trying to launch this request:

python3 -c "import requests; print(requests.get(‘http://192.168.1.107/?action=command&command=value_temperature').text)"

but I obtain this error:

Command executed: python3 -c "import requests; print(requests.get(‘http://192.168.1.107/?action=command&command=value_temperature').text)": 1
  File "<string>", line 1
    import requests; print(requests.get(‘http://192.168.1.107/?action=command&command=value_temperature').text)
                                            ^
SyntaxError: invalid character in identifier

with previous versions all worked fine...

Anyone can help me? syntax is changed?

**Comment by nateprewitt** [comment]
Hi @pilot1981, you have a `‘` at the beginning of your string. In the future please direct usage questions to Stackoverflow. That helps us triage bugs more easily and reduces noise to the people monitoring this list for bugs. Thanks!

**Comment by pilot1981** [comment]
Hi,
thanks for reply.

I have to post here?

https://stackoverflow.com/questions/tagged/python-requests

I tried to remove ' but it don't solve my error...now I have:

SyntaxError: invalid syntax

**Comment by nateprewitt** [comment]
Yes, please post a question there if you’re continuing to see issues. This is not a Requests bug. Make sure you have the same character (`'`) on each end of the string.
