### ISSUE TITLE
can not use html charset decoding

### ISSUE THREAD

**Issue by hktalent** [psf/requests#5161]
### response header:
 'Content-Type': 'text/html'
no charset, but in html have:
```
print(r.encoding)
ISO-8859-1
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
```
### code
```
import requests # pip install requests
r = requests.get(url)
unicode_str = r.text # may use `chardet` to auto-detect encoding
display:

'title': 'ÉÂÎ÷Ê¡ÈËÁ¦×ÊÔ´ºÍÉç»á±£ÕÏÌü',
```

**Comment by nateprewitt** [comment]
Requests doesn't parse HTML or the contents of the body. If the information isn't specified in the Content-Type, we'll default back to ISO-8859-1. You are free to update the encoding as needed by setting `r.encoding` before calling text, you may also be interested in the util function `get_encodings_from_content`.
