### ISSUE TITLE
Missing `?` and extra `&` in the `response.url` when getting from a url of double http

### ISSUE THREAD

**Issue by KenTsui** [psf/requests#5165]
The url of the following response is wrong.

```
baseurl = "http://www.google.com/?https//www.helloworld.com/query"
r = requests.get(url, params = {'abc':"1"})
print(r.url)
```

## Expected Result

'http://www.google.com/?https//www.helloworld.com/query?abc=1'

## Actual Result
Missing `?` behind the string `query` and extra `&` behind the string `query`

'http://www.google.com/?https//www.helloworld.com/query&abc=1'

## Reproduction Steps

```python
import requests
baseurl = "http://www.google.com/?https//www.helloworld.com/query"
r = requests.get(url, params = {'abc':"1"})
print(r.url)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.4"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010103f"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": false
}
```

**Comment by kennethreitz** [comment]
i believe this is expected behavior. thanks for the writeup, though!

**Comment by KenTsui** [comment]
> i believe this is expected behavior. thanks for the writeup, though!

why is it an expected behavior? I am not familiar with web and html. Can you provide me some resources to read on this topic? Thanks.
