### ISSUE TITLE
SSLError when accessing *.dm5cdn.com

### ISSUE THREAD

**Issue by eight04** [psf/requests#5166]
I got an `SSLError` when accessing `*.dm5cdn.com` while it works fine with `urllib.request.urlopen`. Here is an example:

```py
URL = "https://manhua1033-104-250-150-12.cdndm5.com/"

import urllib.request
try:
  urllib.request.urlopen(URL)
except Exception as err:
  print(err)

import requests
try:
  requests.get(URL)
except Exception as err:
  print(err)
```

## Expected Result

They should produce the same result.

## Actual Result

```
HTTP Error 403: Forbidden
HTTPSConnectionPool(host='manhua1033-104-250-150-12.cdndm5.com', port=443): Max
retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[S
SL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local is
suer certificate (_ssl.c:1076)')))
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.4"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010103f"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": false
}

```

After some searching, I found that [this solution](https://stackoverflow.com/questions/42981429/ssl-failure-on-windows-using-python-requests) works for me, but I still wonder why it failed. Does it mean that `certifi` needs to be updated? I do not know how SSL works.

Python x64 v3.7.4
certifi 2019.6.16

**Comment by nateprewitt** [comment]
The server in question is issuing an unverifiable local cert which is why we're raising an exception. The reason urllib works is because it isn't do any checks to validate the connection is secure.
