### ISSUE TITLE
urllib3.connection.VerifiedHTTPSConnection - not able to authenticate the company webpage 

### ISSUE THREAD

**Issue by goldi28** [psf/requests#5168]
I am trying to do a basic authentication using the code

import requests
from requests.auth import HTTPBasicAuth
import csv
import urllib3
urllib3.disable_warnings()
r = requests.get('https://partnermarketplace-qa-adm.dmzmo.xyz.corp/export/Orders_Entries.csv',stream = True , verify = False ,auth=('bwp', '00k'))

But I am getting the below error:

![image](https://user-images.githubusercontent.com/6632016/63288327-0855a380-c2da-11e9-9c07-5596a08a44d1.png)

The same code works on my friend's anaconda but I am getting the issue - not sure if it has something to do with proxy.
Please help

**Comment by nateprewitt** [comment]
Hi @goldi28, 

This appears to be a request for help with your network and DNS configurations. This issue tracker is intended for reporting defects in Requests. Please open a question on Stackoverflow if you need further assistance. Thanks!
