### ISSUE TITLE
SSL error ~5 times, then success ... any idea why?

### ISSUE THREAD

**Issue by acu192** [psf/requests#5169]
Using requests 2.19.1; python 3.6; running on raspberry pi

I have a script to run on-boot and connect to my HTTPS server (certificate is Let's Encrypt). My script will continually attempt to connect until it is successful.

I often see several CERTIFICATE_VERIFY_FAILED in the logs before, suddenly, it connects just fine!

Any ideas why those CERTIFICATE_VERIFY_FAILED are thrown several times (like 3-10 times, attempts are made once every ~2 seconds), until finally it connects just fine?

**Comment by StarLightPL** [comment]
Just a wild guess, maybe certificate store is made available in later boot stages?

**Comment by acu192** [comment]
Yeah I was looking for certificate caches, but I never found any. The `requests` library doesn't seem to cache them, and neither does `urllib3` as far as I could find.

Raspbian/Debian stores root certificates in `/etc/ssl/certs`. They don't ever get updated AFAIK (they come with the Raspbian image and are valid until 2030). More info at: [update-ca-certificates](http://manpages.ubuntu.com/manpages/xenial/man8/update-ca-certificates.8.html).

If you know of a place where, perhaps, _intermediate_ certificates are cached somewhere, please let me know.

**Comment by acu192** [comment]
In fact, `requests` doesn't even use the root certificates in `/etc/ssl/certs`.

It instead uses the certificates which come with [certifi](https://certifiio.readthedocs.io/en/latest/).

So, yeah, not sure why I would get `CERTIFICATE_VERIFY_FAILED` a few times, then suddenly the connection succeeds. It makes me wonder if the real error is something like "cannot connect" or "network down" and that causes a `CERTIFICATE_VERIFY_FAILED` to be (misleadingly) raised.  (???)

**Comment by nateprewitt** [comment]
It sounds like there may have been some sort of issue with certifi during boot but it's not immediately clear that this is related to Requests. Since we don't have hardware to debug this readily available, I'm not sure there's much we can do here. At a minimum we'd need a stack trace to better understand what's happening.

**Comment by acu192** [comment]
Actually, I (finally) figured this out a few months ago. Although I forgot I had opened this ticket >2 years ago! Sorry about that.

The issue was that the RPi's clock was "in the past" (due to it being turned off for some amount of time), so it was rejecting certificates as being "from the future". Eventually, the clock would be updated via [NTP](https://www.ntp.org/) and then all would work fine after that.

**Comment by nateprewitt** [comment]
Thanks for the follow up, @acu192! Glad you got it sorted.
