### ISSUE TITLE
Why is requests logging a 401 and 200 status code in the same request

### ISSUE THREAD

**Issue by JimFawkes** [psf/requests#5176]
I am running the following from the python repl with logs set to DEBUG:
```python
response = requests.get(
    url=endpoint_url,
    auth=requests.auth.HTTPDigestAuth(username, password),
)
```

This results in:
```
[2019-08-27 13:47:23,361 - DEBUG - connectionpool.py:815] Starting new HTTPS connection (1): my.url.com:port
[2019-08-27 13:47:23,532 - DEBUG - connectionpool.py:396] https://my.url.com:port "GET /some/important/endpoint?$skiptoken='12345' HTTP/1.1" 401 0
[2019-08-27 13:47:24,086 - DEBUG - connectionpool.py:396] https://my.url.com:port "GET /some/important/endpoint?$skiptoken='12345' HTTP/1.1" 200 951999
```

Why am I seeing a 401 response logged before the final 200?
Is there something wrong with the authentication? 

In addition to this I sometimes (very rarely) have a situation where the request never returns and only printed the 401 log. What is causing this error.

See also my [stackoverflow](https://stackoverflow.com/questions/57670089/why-is-python-requests-not-terminating-and-why-are-these-seperate-logs-printed) question for more details.

**Comment by epenet** [comment]
Hi @JimFawkes,

The 401 response is part of the way HTTP digest authentication, regardless of the http client (browser, curl, wget, requests, etc.) : the server provides the "WWW-Authenticate" header as part of the 401 response, which can then be used to generate and send the hash for the second attempts.

See [Digest access authentication](https://en.wikipedia.org/wiki/Digest_access_authentication) on Wikipedia

**Comment by JimFawkes** [comment]
Hi @epenet,

thanks for your reply and for clearing this up. So basically I should expect this behaviour for HTTPDigestAuth.

**Comment by nateprewitt** [comment]
Hi @JimFawkes, yeah epenet is correct. This is a challenge response mechanism used with DigestAuth, Requests will automatically try to authenticate itself against a 401 with your provided auth hook.

**Comment by epenet** [comment]
Regarding the second issue (that it never returned), this is a design choice by the requests module. If you do not provide a specific timeout, it will wait for ever for a response from the server. You should definitely add a timeout to your request:

```python
response = requests.get(
    url=endpoint_url,
    auth=requests.auth.HTTPDigestAuth(username, password),
    timeout=60,
)
```

**Comment by JimFawkes** [comment]
Thank you very much for both of your responses and time.
