### ISSUE TITLE
Documentation says there should be 4 hooks

### ISSUE THREAD

**Issue by valmack** [psf/requests#5181]
Documentation says there should be 4 event hooks but there is only 1 in the code.

## Expected Result

4 available hooks per documentation: args, pre_request, post_request, response
https://2.python-requests.org//en/v0.10.6/user/advanced/#event-hooks

## Actual Result

<img width="720" alt="requests_hook_error" src="https://user-images.githubusercontent.com/8445610/64031455-71c58580-cb16-11e9-8108-5125ea54546d.png">

Only 1 valid hook: response

```python

"""
requests.hooks
~~~~~~~~~~~~~~

This module provides the capabilities for the Requests hooks system.

Available hooks:

``response``:
    The response generated from a Request.
"""
HOOKS = ['response']


def default_hooks():
    return {event: [] for event in HOOKS}

# TODO: response is the only one
```

## Reproduction Steps

```python
import requests

requests.get('<any_url>', hooks=dict(post_request=print_req))

def print_req(request):
    print(request)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.7"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "18.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010103f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi valmack@, this is a link to the docs from 7 years ago. You’ll find current documentation by looking at version 2.22.0.
