### ISSUE TITLE
Requests module get method response says "JavaScript has been disabled on your browser"

### ISSUE THREAD

**Issue by vempasiddhartha** [psf/requests#5189]
Summary.
I have a url whose html response has to be assigned to a variable. In order to do that I am using the below code
resp = requests.get(url, timeout=05, verify=False)
html_output = resp.text
from the above html_output variable I am expecting the total html response of the page. However I am seeing a intermediate html output which says "**If you're seeing this message, that means <strong>JavaScript has been disabled on your browser**"
## Expected Result
The response should contain actual html source code of the url which i have given.
What you expected.
The response should contain actual html source code of the url which i have given.
## Actual Result
The below is the output of resp.text
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="manifest" href="/manifest.json"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="react boilerplate"><link rel="apple-touch-icon" sizes="120x120" href="/icon-120x120.png"><link rel="apple-touch-icon" sizes="152x152" href="/icon-152x152.png"><link rel="apple-touch-icon" sizes="167x167" href="/icon-167x167.png"><link rel="apple-touch-icon" sizes="180x180" href="/icon-180x180.png"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"><link rel="icon" href="/favicon.ico"/><title>F1</title></head><body><noscript>If you're seeing this message, that means <strong>JavaScript has been disabled on your browser</strong>, please <strong>enable JS</strong> to make this app work.</noscript><div id="app" style="height:100%"></div><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet"><script type="text/javascript" src="/main.7be1cefcdb84757d693b.js"></script></body></html>
What happened instead.

## Reproduction Steps

```python
import requests
url = "http://adwords-iq-staging-84824396.us-east-1.elb.amazonaws.com"
resp = requests.get(url, timeout=05, verify=False)
print resp.text
```

## System Information

    $ python -m requests.help

```
python 2.7 and OS is both Amazon linux and Mac OS
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by AndTheDaysGoBy** [comment]
Could be my ignorance, but to me that has nothing to do with requests. I.e. this has to with the page being able to render before responding to your GET. I.e. sort of like how you need selenium for certain tasks because it allows certain necessary browser functionalities to exist.

**Comment by nateprewitt** [comment]
Hi @vempasiddhartha, 

@AndTheDaysGoBy is correct. The server is rendering a page that requires JavaScript to load content. Requests is an http client rather than a browser, so we won’t have output that requires script execution. I’d recommend looking at something like selenium for this use case.
