### ISSUE TITLE
Timeout parameter is ignored when using HTTP proxy

### ISSUE THREAD

**Issue by juancroldan** [psf/requests#5198]
When I use a HTTP proxy, the `timeout` parameter is ignored.

## Expected Result

The request raising a TimeoutError after a given time.

## Actual Result

A blocking request that sometimes finishes with a 200 code, after much more than the given timeout.

## Reproduction Steps

```python
import requests
requests.get('http://example.com/', proxies={'http': '108.61.186.207:8080'}, timeout=5)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "5.0.0-29-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1010102f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by jcarlosroldan** [comment]
As I read in the requests reference: ```timeout is not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds (more precisely, if no bytes have been received on the underlying socket for timeout seconds).```

So it seems that after starting the response there is no way to timeout requests.
