### ISSUE TITLE
Python 2.7 Build Still Broken - Incompatible Requirements

### ISSUE THREAD

**Issue by AndTheDaysGoBy** [psf/requests#5199]
E.g. looking at https://travis-ci.com/psf/requests/jobs/237028717 or some of the more recent builds, we notice that there are issues in installing dependencies during the Python 2.7 build. In particular, the issue arises due to attempting the install `more-itertools==7.2.0`.
Looking at https://pypi.org/simple/more-itertools/ we find that it does exist and that the hashes do match those in the Pipfile.lock https://github.com/psf/requests/blob/146291795130cbe73e2a64f53c2a819244a4bd6b/Pipfile.lock#L435
However, inspect element on https://pypi.org/simple/more-itertools/ reveals that every version > 5.0 requires a Python version of the 3.X series (>= 3.4 in particular).

The solution is to either lower the used version of more-itertools to 5.0.0 or to drop Python 2.7 support.

Update:
We can see that this was the commit that resulted in this issue (load the second diff and CTRL+ f more-iter). So it seems it was originally kept at 5.0.0. Presumably reverting that is the desired approach?
https://github.com/psf/requests/commit/6c322457a219f9f18e3aa8ed83ad1326aa565210#diff-46bb8405eeb4d8a11deb635f562f7c48L500

**Comment by abraham** [comment]
Python 2.7 support is ending at the end of 2019. It might be better to just drop 2.7 support in requests too. https://pythonclock.org/

**Comment by nateprewitt** [comment]
Hi @AndTheDaysGoBy, I've resolved the issue by pinning more-itertools at 5.x (a5f4f3c9), thanks for letting us know.

@abaham, Requests has a large user base with varying needs which means we'll need to maintain 2.7 support for sometime beyond EoL. Once pip is migrated to being Python 3 only (no ETA to my knowledge), we would be able to consider it, but there aren't any concrete plans at the moment.
