### ISSUE TITLE
Re-consider the occult imagery.

### ISSUE THREAD

**Issue by antlong** [psf/requests#5203]
The occult logo evokes strong emotion in viewers of certain faiths. An uninitiated looking for [more information](https://gnosticteachings.org/books-by-samael-aun-weor/the-doomed-aryan-race/1305-the-caduceus-of-mercury.html) on the logo would [easily](http://www.occultopedia.com/c/caduceus.htm) come to this [information](https://www.samaelaunweor.org/en/the-solar-bodies/the-caduceus-of-mercury) with a google search...

>The Gnostic Movement teaches its disciples that from their seminal system (during the esoteric practices of sexual transmutation) the lunar atoms ascend through the nervous canal of Ida and the solar atoms victoriously ascend through Pingala.

[RIU](https://www.rollitup.org/t/the-rod-of-asclepius-vs-the-caduceus-of-mercury.374706/):

>Mercury was the god of merchants and merchandise. Also the conductor of the dead to the afterlife, and protector of thieves and deceit. The Caduceus is a herald's staff representing Mercury (Hermes) and his undertakings, that was a gift from Apollo. It did not and does not represent medicine. An officer in the U.S. Army Medical Corps mistook the Caduceus for the Staff of Asclepius and introduced the new Medical Corps symbol at the beginning of the twentieth century. Not too long after that, everyone was adopting the same mistake. Including the American Medical Association (AMA), the largest association of physicians and medical students in the United States.

>Asclepius was the son of Apollo, and the god of medicine and healing. Asclepius's daughter is Hygieia, whose bowl is the well known international symbol of pharmacy and pharmacist. Asclepius's staff has many interpretations, but basically means, the snake is thought to signify a new beginning from old problems, as in shedding of the skin. The staff or rod, is thought to mean support and structure to help deal with the turmoil of life and death and being associated with them. Asclepius was so good as a healer that he was reputed to be able to bring people back from the dead. For this he angered Hades and Zeus because he raised Hippolytus from the dead and accepted gold for it, and was killed by Zeus with a thunder bolt. Zeus then placed him amongst the stars as the constellation Ophiuchus ("The Serpent Holder").

**Comment by motleytech** [comment]
Its a pretty common logo used by hospitals, ambulances and in healthcare. Its a common symbol of medicine in the US. At least, that's the first thing I was reminded of when I saw the logo. Google image search for `logo hospital` shows many similar images...

https://www.google.com/search?q=logo+hospital&rlz=1C1GGRV_enUS752US754&sxsrf=ACYBGNQP1Pms8SvMIXQkbCuUROw9p84gMg:1568938296648&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjOlOLOjt7kAhUEuZ4KHZhaD8cQ_AUIEigB&biw=1626&bih=1141

Its also used in Simcity 2013 for healthcare.

Also, here is some history about the use of that symbol in medicine in US - http://mentalfloss.com/article/30751/what-do-snakes-and-sticks-have-do-doctors

> The mark was used by several publishers in their books because they thought of themselves, like Hermes, as messengers and diffusers of knowledge.

I guess Kenneth Reitz would be able to give the reasoning for his choice.

Either way, let the bikeshedding commence.

**Comment by antlong** [comment]
............. Because you included the word hospital...

**Comment by fiveham** [comment]
There is no occult imagery.

But maybe adding a little would be a good idea...

![image](https://user-images.githubusercontent.com/12902107/65325940-3864c080-db7e-11e9-9e2e-c8169c150e1d.png)

**Comment by antlong** [comment]
Seeing a trend of people not actually reading the sources, and perhaps even
the initial post. Quite troubling you’d even take it a step further to
comment with anti-Christian imagery.

**Comment by muffinwasright** [comment]
> Quite troubling you’d even take it a step further to
comment with anti-Christian imagery.

@antlong 

![](https://i.imgur.com/7yUMhaK.gif)

**Comment by barneygale** [comment]
@antlong do you have a faith-based objection to the logo? And if so, what is it?

**Comment by antlong** [comment]
I think my objection of the behavior of this community is more important
than my prior objection. This is reprehensible. PSF will be reached for
comment.

**Comment by barneygale** [comment]
OK, but on the original issue of "occult imagery" - is there anything inherently anti-Christian about it? The existence of Greek paganism is not itself anti-Christian, and it's worth noting the Christian New Testament itself makes reference to Greek pagan authors, e.g.:

- Menander, Thais 218 (1 Cor. 15:33)
- Epimenides, de Oraculis, (Titus 1:12-13, where Paul introduces Epimenides as "a prophet of the Cretans," see Epimenides paradox)
- Aratus, Phaenomena 5, (Acts 17:28, where Paul refers to the words of "some of your own poets")

**Comment by antlong** [comment]
- Explicit/sexualized/unsavory material associated with logo elements.
- Completely avoidable, use something else.

The Anti-Christian commentary is unacceptable. Is this an edginess problem
or discrimination, you tell me.

**Comment by ewdurbin** [comment]
The disruptive and inflammatory responses to this issue have been removed. Please keep discussion of this issue on-topic and respectful. If necessary, this issue may be temporarily locked to contributors if it continues to devolve.

**Comment by barneygale** [comment]
> Explicit/sexualized/unsavory material associated with logo elements.

So this is not a religious objection?

**Comment by muffinwasright** [comment]
@antlong, don't take it the wrong way, but the most Anti-Christian attitude showcased in this thread is your own intolerance.

**Comment by lordmauve** [comment]
I'm not sure the sources you link to make any sort of coherent case.

The rollitup.org link talks only about the history of the Caduceus and the confusion with the Rod of Asclepius. Similarly the occultopedia link. The other two links are duplicates of the same passage, ostensibly from the same book, *The Doomed Aryan Race* by Samael Aun Weor in 1967, which [abuse.wikia.org](https://abuse.wikia.org/wiki/Aryan_race) describes thus:

> [Samael Aun Weor] asserted that the Aryan "Root Race" is doomed to be destroyed by hydrogen bombs unless the people of the Aryan race learn tantric yoga.

Several sources say that "Aryan" here is not meant with racist/antisemitic connotations. Nevertheless this all sounds like an extremely tenuous link to the Caduceus.

Can you elaborate on how exactly this offends you?

**Comment by flying-sheep** [comment]
None of the sources provide unbiased information.

If a site called “gnosticteachings.com” paints something as “occult”, that's not evidence for anything being wrong with it. Symbols get used in all kinds of contexts, anyone can adopt a symbol for any positive or negative purpose. Also it's easy to make cheap shots: Anything rodlike can be interpreted as “phallic” if one wants. But that doesn't mean anything is wrong with the symbol, it just means that conspiracy nutjobs have an easy time linking anything to everything.

I'd agree that there has to be change if there was be solid evidence that the main usage of the symbol has shifted to something problematic (like the Hindu swastika having beim tainted by the Nazis). But since there isn't the slightest bit of problem with this symbol, let's close this and stop wasting our breath.

**Comment by antlong** [comment]
The antagonistic behavior like the satanic imagery linked in the thread
pointed toward me, the image of a butt-plug and libel also, wtf? Easily the
most toxic thread I’ve ever seen. Will be in touch, prefer not to discuss
here any further.

**Comment by flying-sheep** [comment]
Libel? Stay realistic, not everything is about you. E.g. in case you somehow interpreted my “conspiracy nutjobs” to be about you.

And about the antagonistic comments: this thread was posted on the internet because of the hilarity of your accusations. Everybody can comment on GitHub, not only the python community. The python community removed the spam.

You still didn't say in any way how the logo could have possibly offended you. If you want to be taken seriously, you need to explain this to us without quoting more than dubious sources.

**Comment by antlong** [comment]
Cognitive dissonance, mundane; paired with narcissism. Gets old. I’ve been
on the internet a while. Philipp, if you need me to be more explicit, do
not mention me any further. You’re harassing me, and your behavior is sad
and atrocious. Go away - seriously.

**Comment by nateprewitt** [comment]
It doesn’t look like this thread is serving a productive purpose for discussion anymore. I’m going to resolve for now.

**Comment by antlong** [comment]
Sad to have been attacked and bullied.

**Comment by kennethreitz** [comment]
https://en.wikipedia.org/wiki/Alchemical_symbol

**Comment by kennethreitz** [comment]
The true meaning is serialized here, for those curious: https://www.kennethreitz.org/values

You were close — :sparkles: :cake: :sparkles:

**Comment by motleytech** [comment]
@antlong

I too was sad to see the thread hijacked by aggressive and ugly comments. But those were deleted by the community and they are in no way representative of the people now in discussion with you.

I hope you can get over that and engage in useful discussion, rather than continuing to be sad about those comments.

Either way, since you brought up this issue, it is upto you to make an argument to back up your assertions. That's the only way to convince people to see things your way.

**Comment by antlong** [comment]
You don’t always get a second chance. Take care.

**Comment by barneygale** [comment]
It's a little on the nose to complain about lack of polite discussion, and then decline the opportunity to have a polite discussion on multiple occasions.

**Comment by kennethreitz** [comment]
Please restore the logo. When I transferred the project to the PSF, per textual agreement with @ewdurbin, my only requirement was that the logo stayed in place. It is my mark on the world — and is actually a tattoo that is on my body. It is my personal emblem, and I placed it on this project, as it is my Magnum Opus. 

I put my blood, sweat and tears into this project. Please restore the logo ASAP.
