### ISSUE TITLE
Obtain all the content from https://free-ss.site/ by requests.

### ISSUE THREAD

**Issue by hongyi-zhao** [psf/requests#5205]
Hi,

I try to obtain the content from https://free-ss.site/ by requests.

But it seems that the above tools cannot get all of the content as the
stuff obtained by the firefox.

Is is possible to get all of the content just as the results via firefox
for this website by using requests?

Regards

**Comment by AndTheDaysGoBy** [comment]
Not necessarily. Reference https://github.com/psf/requests/issues/5189

**Comment by nateprewitt** [comment]
@hongyi-zhao, Requests is not a browser, it's an HTTP client. It won't perform asynchronous calls or evaluate scripts in response bodies. I believe the issue you're hitting may be better solved with something like Selenium or Ghost.js.
