### ISSUE TITLE
request timeouts connect vs read - clarification needed

### ISSUE THREAD

**Issue by adithyaonline** [psf/requests#5227]
documentation reads :

`requests.get('https://github.com/', timeout=0.001)`

> timeout is not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds (more precisely, if no bytes have been received on the underlying socket for timeout seconds). If no timeout is specified explicitly, requests do not time out.

description seems to indicate the timeout specified is used as a "connect" timeout

however tracing the code i see : 
same timeout value is being used for `connect` and `read`
https://github.com/psf/requests/blob/master/requests/adapters.py#L435

looking for some clarity on the matter,
do i trust the documentation (am i missing something here?)
or does the documentation need an update ?

**Comment by liampauling** [comment]
It expects a tuple in the format (connect timeout, read timeout) which you can see being used [here](https://github.com/psf/requests/blob/master/requests/adapters.py#L425)

Ln435 is what happens if only one value is passed (else).

**Comment by adithyaonline** [comment]
hmm, then the documentation needs an update... 

`requests.get('https://github.com/', timeout=0.001)`
> timeout is not a time limit on the entire response download

this is clearly not the case, as the same timeout value is getting duplicated for `connect` and `read` in Ln435

**Comment by nateprewitt** [comment]
Hi @adithyaonline,

This should all be covered in our [timeout docs](https://requests.readthedocs.io/en/master/user/advanced/#timeouts). Passing a single value will be used for both the connect and read timeout. Passing a tuple will allow you to modify the two independently. The section quoted in the first comment is referencing the read timeout and that we'll wait <timeout> seconds between response packets.

**Comment by adithyaonline** [comment]
oh, I think I got mislead by the Note on the quickstart guide thats all 
https://2.python-requests.org/en/master/user/quickstart/#timeouts

thanks for clarifying...
