### ISSUE TITLE
Support for HTTP/3 (QUIC)

### ISSUE THREAD

**Issue by mikehwang** [psf/requests#5231]
Is there currently a way to have requests to use HTTP/3 and thus QUIC as the transport protocol?  If not, has there been discussion about supporting this in future releases?

Thank you

**Comment by nateprewitt** [comment]
Hi mikehwang@, we don't have a way to support HTTP/3 or QUIC directly with Requests right now. I'd suggest taking a look at either the Python-Hyper project or httpx to see if they have plans for integrating that support.
