### ISSUE TITLE
Python crashed while run requests.get() in a daemon process with pandas.

### ISSUE THREAD

**Issue by virus-warnning** [psf/requests#5235]
Run requests.get() in a daemon process with `import pandas` then python would be crashed.

* Comment `import pandas` it would be fine.
* Comment `.. os.fork() ...` it would be fine.

The problem was found on macOS only. (macOS Mojave 10.14.6)

## Expected Result

200

## Actual Result

```
objc[89863]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[89863]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

## Reproduction Steps

Would be crashed.

```python
import os

import pandas
import requests

def main():
    if os.fork() > 0:
        exit(0)

    resp = requests.get('https://duckduckgo.com')
    print(resp.status_code)

if __name__ == '__main__':
    main()
```

It's OK!

```python
import os

# import pandas
import requests

def main():
    if os.fork() > 0:
        exit(0)

    resp = requests.get('https://duckduckgo.com')
    print(resp.status_code)

if __name__ == '__main__':
    main()
```

It's OK!

```python
import os

import pandas
import requests

def main():
    #if os.fork() > 0:
    #    exit(0)

    resp = requests.get('https://duckduckgo.com')
    print(resp.status_code)

if __name__ == '__main__':
    main()
```

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "18.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

**Comment by iapyeh** [comment]
This is hard to say to be issue of the requests. It crashes on purpose in case of user does n't know what  he is doing. 

> objc[1936]: +[NSValue initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

If you do know what you are doing, the "crashing script"(test.py) can avoid to crash by :
`$export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ; python3 test.py`

**Comment by nateprewitt** [comment]
This is definitely an issue outside of Requests. It looks like you're running into an issue with Pandas. I would suggest posting something on StackOverflow and reviewing the bug tracker for Pandas.

**Comment by dentarg** [comment]
Sounds related to #4768
