### ISSUE TITLE
Docsearch on the left menu bar is not working

### ISSUE THREAD

**Issue by Mariatta** [psf/requests#5254]
Enter any text into the search bar on the left where it says "Search the doc" (see screenshot)
Press enter

![Screen Shot 2019-11-04 at 8 03 17 PM](https://user-images.githubusercontent.com/5844587/68234016-439c7000-ffb5-11e9-9fa5-fd1dffdf186d.png)

## Expected Result

I expected to see some search results.

## Actual Result

It sends me to another url like https://2.python-requests.org/en/master/...

I think that search is hosted by community.algolia.com, and the url probably should be updated from that website.

Using the sphinx quick search works, but since that search box appears first on the top, that was the one I tried first.

It would be great to have it fixed. Thanks.

**Comment by Mariatta** [comment]
Forgot to attach screenshot. It's been added.

**Comment by nateprewitt** [comment]
This was fixed last year but this wasn't resolved.
