### ISSUE TITLE
Documentation for trust_env not accessible.

### ISSUE THREAD

**Issue by chrzhang** [psf/requests#5264]
[The link for trust_env documentation](https://2.python-requests.org//en/latest/api/#requests.Session.trust_env) fails to load.

**Comment by nicktimko** [comment]
Duplicate of #5214

[Here's a working link](https://requests.kennethreitz.org/en/latest/api/#requests.Session.trust_env)

**Comment by xmo-odoo** [comment]
The proper / canonical link should be https://requests.readthedocs.io/en/master/api/#requests.Session.trust_env however both indexation and intra-doc linking is currently a mess.
