### ISSUE TITLE
3.python-requests.org documentation says it's for version 2.21.0

### ISSUE THREAD

**Issue by nicktimko** [psf/requests#5266]
Documentation at https://3.python-requests.org/ says it's for Release 2.21.0 which is confusing for users. (#5265).

![image](https://user-images.githubusercontent.com/5297556/68976963-b9c28300-07bc-11ea-8f41-0cc50bfc4c55.png)

It's not clear to new users that "Requests III" means "the pending 3.x release of Requests" (e.g. other libraries like urllib3 are on a 1.x release).

The version stated at the top should be 3.x.y, not an actual version to which the data doesn't correspond. I don't know what branch the 3.x docs are built from, so I don't know how to fix this.

Alternatively, a banner on all the pages mentioning it's for 3.x, a prerelease (how do you get it?)

**Comment by llamafilm** [comment]
Also, the download link on this page leads to this Github repo, so it's not clear how you can actually download version 3 or if it's vaporware.

**Comment by nateprewitt** [comment]
Hi @nicktimo,

We don't have access to that domain or control of the contents on it. You might be able to reach out to @kennethreitz on how it's being updated.

**Comment by nicktimko** [comment]
@nateprewitt what is the canonical domain/URL to be used? I'm slightly confused about it, and I often find links on StackOverflow that are broken.

**Comment by nateprewitt** [comment]
Both http://python-requests.org and https://requests.readthedocs.io/en/master/ should point to current documentation.
