### ISSUE TITLE
Two Host header are being sent when doing chunk transfer with Session

### ISSUE THREAD

**Issue by contactparthshah** [psf/requests#5274]
Two Host header are being sent when doing chunk transfer with Session
---------------
>>> import requests
>>> requests.__version__
'2.22.0'
```
import requests
import time
from requests.packages import urllib3

#Disable https insecure warnings for verify=False
urllib3.disable_warnings()

with open('1.ts','rb') as fh:
    file_data = fh.read()

def chunk_trans():
    for i in range(0, 3):
        time.sleep(0.1)
        yield file_data

req = requests.Request('POST', 'http://192.168.123.151/1.ts', data=chunk_trans(), headers={'Host':'a.b.c.d'})
prep = req.prepare()
s = requests.Session()
s.send(prep, timeout=2, verify=False, allow_redirects=False)

```

Actual Output: Two host headers are seen on server side.
```
Host: 192.168.123.151
Host: a.b.c.d
Transfer-Encoding: chunked
```
-------------

only "a.b.c.d" host header should come.

**Comment by contactparthshah** [comment]
can anyone look into this and help?

**Comment by mzpqnxow** [comment]
I see that there is a PR for this (and has been for a while) but it is not yet merged.

I am also having this issue. I can apply the patch on my own fork, but is there any reason this hasn't been merged? Just forgotten about maybe?

I guess it is kind of an edge-case..
