### ISSUE TITLE
requests can't handle http response header correctly

### ISSUE THREAD

**Issue by beruhan** [psf/requests#5277]
when there were two status lines in http response,for example
```
HTTP/1.0 200 OK
Date: Thu, 28 Nov 2019 01:27:10 GMT
Server: Boa/0.94.13
Connection: close
HTTP/1.0 200 OK
Connection: close
Content-Length: 75746
Content-Type: image/jpeg

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
The requests lib can only parsed the headers before the second status line as follows,
```
import requests
req = requests.get("http://121.156.161.92/cgi-bin/get_jpeg?ch=1")
print(req.headers)
{'Date': 'Thu, 28 Nov 2019 01:22:44 GMT', 'Server': 'Boa/0.94.13', 'Connection': 'close'}
```
is there a way to parse all http headers and skip the bad http status line?

**Comment by nateprewitt** [comment]
This is a malformed http response if you’re expecting the headers to occur in a single request. Interpreting that response any differently would be incorrect in this case.

You can reach out to the owner of the server to see what’s going on with the responses they’re emitting.
