### ISSUE TITLE
Cannot keep 302 using session

### ISSUE THREAD

**Issue by navysummer** [psf/requests#5278]
Requests can not keep 302 using session，I need to get some cookies in 302
`s = requests.Session()
response = s.post(__login_url,data=__login_data,headers=__login_headers,allow_redirects=False)`

**Comment by arvindkhadri** [comment]
@navysummer `s.cookies` will give you the cookie for that request made to `login_url`.

**Comment by nateprewitt** [comment]
@navysummer you can access the `history` variable on your response object to see all of the redirects. They will each have the cookies for that stage attached to them.
