### ISSUE TITLE
Test case, test_total_timeout_connect failed

### ISSUE THREAD

**Issue by templetontsai** [psf/requests#5279]
Summary.
When getting the latest release, v2.20, and run the test case it failed in the case test_total_timeout_connect. The test case is expecting, ConnectTimeout exception but instead it gets ConnectionError. The error message is as follows:

```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
## Expected Result
I would expect all the test cases should be passed without any modification.

## Actual Result
4 test case fail.
Error message is consistent with the following:

```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
## Reproduction Steps
It seems a symptom only happens when using WiFi. You need to make sure to use WiFi not landline.

Run the following test case:
pytest tests/test_requests.py::TestTimeout::test_total_timeout_connect

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.5"
  },
  "platform": {
    "release": "4.15.0-70-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010100f"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": false
}

```

**Comment by templetontsai** [comment]
Upon investigation, it is a mismatch of exception is thrown and the expected exception of test case.

Exception thrown:  requests.exceptions.ConnectionError
Expected exception in the test case: ConnectTimeout

```
    def test_total_timeout_connect(self, timeout):
        try:
            requests.get(TARPIT, timeout=timeout)
            pytest.fail('The connect() request should time out.')
        except ConnectTimeout:
            pass
```

Furthermore, ConnectionTimeout is child class of ConnectionError.

```
class ConnectTimeout(ConnectionError, Timeout): 
```

This is the root cause. A fix can be throwing ConnectTimeout specifically as follow:

```
        except (ProtocolError, socket.error) as err:
            raise ConnectTimeout(err, request=request)
```

**Comment by nateprewitt** [comment]
Hi @templetontsai, this appears to be something on your wireless connection is either blocking the connection or routing it to another endpoint. It may be a firewall, proxy or the symptom of a MITM. The exception we're expecting for these test cases is correct (a timeout). The exception you're getting is the connection being forcibly closed by whatever server receiving the request.

I'd double check your host/network configuration, and maybe see which host you're connecting to on your wireless network.
