### ISSUE TITLE
incorrect coding of location under 302 response

### ISSUE THREAD

**Issue by billwyy** [psf/requests#5282]
When I use headers.get('location') I got http://xxx.xxx.xxx/2019/é????°????1????????-|?????3?o????????-|?????|?±????è??.[è?±] ???????·é????·???..2018-1.epub

Obviously there is problem of encoding. It should be Chinese after '/2019/'

What shall I do to sovle this problem?

HTTP/1.1 302 Found
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 04 Dec 2019 08:36:48 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Set-Cookie: advanced-frontend=4lo57sauj74js561pjth714bq2; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
location: http://xxx.xxx.xxx/2019/é????°????1????????-|?????3?o????????-|?????|?±????è??.[è?±] ???????·é????·???..2018-1.epub
Connection: keep-alive

**Comment by nateprewitt** [comment]
Hi @billwyy, can you clarify if the server is returning an indiscernible location or if Requests is performing incorrect decoding on it?

We want to do the best we can with non-english encodings, but we'd only expect iso-8859-1 and utf-8 with the current HTTP RFCs for headers.

**Comment by nateprewitt** [comment]
Resolving since we haven't heard back.
