### ISSUE TITLE
mypy is failing on type checking Response

### ISSUE THREAD

**Issue by mateusduboli** [psf/requests#5283]
We're using mypy internally to check for type errors, on an specific interaction with `requests.models.Response` object it gives you an error about a missing attribute, which is declared on the class.

Minimal example

## Expected Result
Type check successful

## Actual Result
```
$ python3.6 -m mypy test.py
test.py:3: error: "Response" has no attribute "next"
```

## Reproduction Steps
```txt
# requirements.txt
certifi==2019.11.28
chardet==3.0.4
idna==2.8
mypy==0.720
mypy-extensions==0.4.1
psutil==5.4.3
requests==2.22.0
typed-ast==1.4.0
typing==3.7.4.1
typing-extensions==3.7.4
urllib3==1.25.7
```

```python
# test.py
import requests
response = requests.get('https://google.com')
print(response.next)
```

Running:
```
python3.6 -m mypy test.py
```

## System Information

    $ python -m requests.help

```
$ python3.6 -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.9"
  },
  "platform": {
    "release": "3.10.0-862.14.4.el7.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": false
}
```

**Comment by sethmlarson** [comment]
This was fixed in typeshed on October 18th in this commit: https://github.com/python/typeshed/commit/bf862d907957e46b97419565a5bb90314d074ee4

The requests repo doesn't maintain it's own type hints. Maybe you need to upgrade your MyPy version to get a newer typeshed version? Not sure.

**Comment by mateusduboli** [comment]
Yes, upgrade resolved thanks for info!
