### ISSUE TITLE
Ignore normalization URL

### ISSUE THREAD

**Issue by everping** [psf/requests#5289]
In cases I would like to test Path Traversal vulnerabilities in web applications, the target URL is usually `https://example.com/../../path`. Using the GET method in requests, that URL will be normalized as below. Consequently, this will lead to unintended results in the test.

```
r = requests.get('https://example.com/../../path')
print(r.url)
# https://example.com/path
```
With `curl`, we have an option to ignore the normalization : `--path-as-is`. So, do we have an equivalent option for `requests`?

**Comment by EDjur** [comment]
This behaviour is actually a part of urllib3's implementation of [RFC3986 ](https://tools.ietf.org/html/rfc3986#section-5.2.4) as can be seen here: https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/url.py#L247

**Comment by everping** [comment]
@EDjur Thank you for your information. Do you know a workaround to resolve this?

**Comment by EDjur** [comment]
Doesn't look like the requests library has much control over this. There is a `normalize_uri` flag in urllib3 https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/url.py#L365 but this is only false when the request scheme isn't http, https, or None.

`requests` just calls this `parse_url` function https://github.com/psf/requests/blob/master/requests/models.py#L380 that sits inside urllib3 with the `url` as the parameter.

**Comment by akmalhisyam** [comment]
Try using prepared request

```
url = "http://example.com/../something.txt"
s = requests.Session()
req = requests.Request(method='POST' ,url=url, headers=headers, data=data)
prep = req.prepare()
prep.url = url
r = s.send(prep, verify=False)
```

**Comment by everping** [comment]
@akmalhisyam Thank you very much. It works well.

**Comment by nateprewitt** [comment]
@akmalhisyam is correct here. Using the PreparedRequests workflow will typically solve issues like this if you MUST explicitly set something.
