### ISSUE TITLE
requests.get of this URL causes timeout and network failure (router reboots)

### ISSUE THREAD

**Issue by filipmu** [psf/requests#5294]
Summary.
when I use requests.get for a particular url it causes a network crash (lose connection and my router reboots). The only return message is a timeout error.   Here are two example URLs that cause the issue:
https://images.harrods.com/product/gucci/large-gg-tweed-rajah-tote-bag_000000006389623001.jpg
https://images.harrods.com/product/gucci/small-leather-soho-disco-bag_000000000005256593.jpg

I now understand how to avoid the issue, but without any error message it took a long time to debug, and crashed the network a number of times.  I ended up running the get in urllib3 and I got the SSL error message.  Doing the request.get with a custom header for 'User-Agent', the network does not crash.

## Expected Result
Timeout error with network error result 
In order to debug I did the same get with urllib3 - I got this error when I used urllib3 for the same URL:
MaxRetryError: HTTPSConnectionPool(host='images.harrods.com', port=443): Max retries exceeded with url: /product/gucci/large-gg-tweed-rajah-tote-bag_000000006389623001.jpg (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

## Actual Result
Time out error with network router rebooting and wifi card disconnecting.  Exception has no mention of any network error except timeout.

## Reproduction Steps

```python
import requests
url = 'https://images.harrods.com/product/gucci/large-gg-tweed-rajah-tote-bag_000000006389623001.jpg'
r  =  requests.get(url, timeout=4)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.8"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.5"
  },
  "platform": {
    "release": "4.15.0-72-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010104f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @filipmu,

The issue with your network card and router aren't related to Requests. Attempting a repro from what you provided correctly returns a read timeout error. It appears Harrods may be modifying server behaviour in some cases to stop web scraping. All non-trivial requests from Requests should be provided a timeout to catch cases like this.

The urllib3 exception you've provided doesn't seem to be related to this case.
