### ISSUE TITLE
`Session().get` not usuable with `with`

### ISSUE THREAD

**Issue by ouroborus** [psf/requests#5295]
Summary.

## Expected Result

Able to use `with session.get() as response`, same as `with requests.get() as response`.

## Actual Result

Throws exception:
```
AttributeError: __exit__
```

## Reproduction Steps

```python
import requests
session = requests.Session()
with session.get('http://some.domain') as response:
  print(response.headers)
```

## System Information

```
Linux Mint
Python 3.5.2
python-requests_2.9.1-3ubuntu0.1_all.deb
```

**Comment by songguoxiong** [comment]
upgrade requests version to >=2.18

**Comment by ouroborus** [comment]
@songguoxiong 2.9.1 is the latest available via `apt-get`

**Comment by songguoxiong** [comment]
try to install via `pip`?
```bash
python3 -m pip install "requests>=2.18"
```

**Comment by ouroborus** [comment]
Okay, that works.

Any chance of submitting something recent to get the `apt` repositories updated? I see now that 2.9.1 is 4 years old.

**Comment by sethmlarson** [comment]
Requests contributors aren't in control of `apt` repositories. Please open an issue on the Linux Mint tracker.
