### ISSUE TITLE
Document `requests.utils`

### ISSUE THREAD

**Issue by verhovsky** [psf/requests#5299]
Are the methods imported by `requests.utils` supposed to be public?

https://github.com/psf/requests/blob/eedd67462819f8dbf8c1c32e77f9070606605231/requests/utils.py

https://github.com/psf/requests/blob/eedd67462819f8dbf8c1c32e77f9070606605231/requests/compat.py

Is it okay to do 

```python
import requests.utils
requests.utils.urlparse(whatever)
```

in my code? If yes, shouldn't they be documented as if they were part of requests? Or at least the docs for them should be copy/pasted from the Python docs. I [don't see them mentioned anywhere](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Frequests.readthedocs.io%2F+urlparse), just the three encoding-related methods https://requests.readthedocs.io/en/master/api/#requests.utils.get_encodings_from_content

Or should I always import these methods directly `from urllib.parse import urlparse`, etc.?

**Comment by sigmavirus24** [comment]
I've been asked to comment on this. The answer in short is "No." those were never intended to be public parts of the API but people still do use them at their own risk. We've broken them unintentionally before and I'm sure whoever ends up maintaining this will do so again as they well should.
