### ISSUE TITLE
Getting ConnectionResetError(10054) while using Requests

### ISSUE THREAD

**Issue by jnkumar58** [psf/requests#5310]
Summary.
I am getting ConnectionResetError(10054) while running a POST against a webservice. I am getting successful output every time when I am using POSTMAN to do it.
## Expected Result
Should get HTTP Code:200 and successful output

## Actual Result

What happened instead.
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Admin/Services/Webservices/Testing/new_test.py", line 77, in <module>
    response = requests.request("POST", url, headers=headers, data = payload,verify=False)
  File "C:\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 686, in send
    r.content
  File "C:\Python37\lib\site-packages\requests\models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "C:\Python37\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

## Reproduction Steps

```python
import requests
response = requests.request("POST", url, headers=headers, data = payload,verify=False)
print(response.text.encode('utf8'))
```

## System Information

    $ python -m requests.help

```
λ python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.4"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010103f"
  },
  "urllib3": {
    "version": "1.25.6"
  },
  "using_pyopenssl": false
}
```
[error.txt](https://github.com/psf/requests/files/4041827/error.txt)

**Comment by AXu-Quest** [comment]
Did you get out of this problem?  i get this issue too and don't know what happened, can you share how to resolve this problem?
