### ISSUE TITLE
Response 412 from this website

### ISSUE THREAD

**Issue by terenceltl** [psf/requests#5311]
I keep getting response 412 and a blank webpage with only 4 blank lines from this webpage:

http://wjw.hubei.gov.cn/

## Expected Result

Both Chrome and Firefox can open the page fine. But I notice when the browser loads the page, it is a blank page at first and the browser reloads / loads more and the complete page is loaded eventually. 

## Actual Result

On both Windows 10 (Python 3.7.4) and Raspberry Pi (Python 3.5.3), requests cannot return the page like Chrome / Firefox did. 

## Reproduction Steps

```python
import requests
url = 'http://wjw.hubei.gov.cn/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36'}
res = requests.get(url,headers=headers)
print(res)
```

<Response [412]>

If you use print(res.content) you will also notice that the server return a bunch of HTML but just that not of the webpage returned by Chrome / Firefox.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.7.1"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.13"
  },
  "platform": {
    "release": "4.9.59-v7+",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "101000af",
    "version": "16.2.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101000cf"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": true
}

```
I also ask this over in stackoverflow but so far no luck:

https://stackoverflow.com/questions/59657613/response-412-when-using-the-requests-python-package-to-access-this-webpage-ho#59661448

A helpful fellow suggested that a valid cookie has to be sent along with the request, but so far this cannot solve the issue on my platforms.

Is there a way to read this particular webpage?

Supplement:

On the Raspberry Pi, even lynx cannot open the webpage.

**Comment by nicktimko** [comment]
This does not sound like an issue with Requests, but the server's configuration interacting with the request you send. If you could provide (e.g.) a cURL request like the below that *does* work or give unexpectedly different results than Requests could provide, that may be an issue.

```
curl --verbose http://wjw.hubei.gov.cn/ \
    -H"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
...
< HTTP/1.1 412 Precondition Failed 
...
```

I might recommend doing a request with Chrome with the Network dev tools open, the [copy the request as cURL](https://www.google.com/search?q=chrome+copy+request+as+curl). Verify that also works in the command line. You can convert that to requests then with [this tool](https://curl.trillworks.com/). Note that you'll generally end up with many many more headers.
