### ISSUE TITLE
HEAD request never gets timeout

### ISSUE THREAD

**Issue by lingsan43** [psf/requests#5312]
I am doing a HEAD request with a timeout=4.

Tried to ask on stackoverflow, incase this is something known, but it seems not to be the case. (https://stackoverflow.com/questions/59703532/requests-does-not-timeout)

## Expected Result

Timeout after 4 seconds.

## Actual Result

Timeout never happens.

## Reproduction Steps

```python
import requests
requests.head('https://50.79.153.56',verify=False,timeout=(4,4))
```

## System Information

    $ python -m requests.help

```
python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.16"
  },
  "platform": {
    "release": "5.0.0-13-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010102f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": false
}

python3 -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.3"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "5.0.0-13-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010100f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010102f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": true
}

```

**Comment by s104346** [comment]
This is an issue with the underlying urllib3 library. See their documentation on timeouts: https://github.com/urllib3/urllib3/blob/d369183f60749d735f0676efb22ecd64fc694768/src/urllib3/util/timeout.py#L78-L89

> if a server streams one byte every fifteen seconds, a timeout
        of 20 seconds will not trigger, even though the request will take
        several minutes to complete

**Comment by nateprewitt** [comment]
@s104346 is correct here. Requests can only support connection and read timeouts as we state in our [docs](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts). We cannot support total connection timeouts today in a case like this.
