### ISSUE TITLE
Unable to install settings module

### ISSUE THREAD

**Issue by DuckTooth** [psf/requests#5313]
For my code, there is an import at the top:
```
from settings import Settings
```
I need to install the settings module but whenever I try to install it, I get this error message:
```
ERROR: Could not find a version that satisfies the requirement settings (from versions: none)
ERROR: No matching distribution found for settings
```
Does anyone know how this can be resolved?

**Comment by nateprewitt** [comment]
@DuckTooth,

This isn’t a module supplied by Requests and isn’t the right forum to debug issues like this. I’d suggest reviewing the docs or reaching out to pypa through their recommended process.
