### ISSUE TITLE
Get post request works by using postman but dose not work in requests

### ISSUE THREAD

**Issue by nnit-kzhg** [psf/requests#5318]
Hello Mates,

i got a problem to post a HTTP request to a internal web server and it works when i using postman and dosent work in python request. the request is pretty simple just like below,

response=requests.post("https\\myserver",auth=('admin','****'),verify=False), i got following error log,

requests.exceptions.ProxyError: HTTPSConnectionPool(host='xx.xx.xx.xx', port=443): Max retries exceeded with url: /myserver (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 504 Gateway Timeout')))

can anyone give me some tips on where i should look into? thanks a lot

**Comment by nateprewitt** [comment]
Hi @nnit-kzhg,

This is an issue with your proxy configuration that we won’t be able to debug on this issue board. I’d encourage opening an question on Stackoverflow to debug further.
