### ISSUE TITLE
Incorrect Content-Length header in response

### ISSUE THREAD

**Issue by scpketer** [psf/requests#5319]
I've been debugging my script that is fetched file size (using `requests.head` and then processing `Content-Length` header) wrong; with HEAD request file size was ~17MB, with GET requests downloaded file has taken expected ~75MB. HEAD and GET requests were sent to `raw.github.com`, which responds with `Content-Length` both on HEAD and GET requests, so it wasn't the cause.

## Expected Result

I expected HEAD request and GET request to have the same `Content-Length` headers.
This is the result I have when I use `curl` or `urllib` to send requests.

## Actual Result

Using `requests`, HEAD and GET requests `Content-Length` headers differ (HEAD = ~17MB, GET = ~75MB).

## Reproduction Steps

```python
import requests
r_head = requests.head("https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv")
print(r_head.headers["Content-Length"])
```

```bash
$ curl -I https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv | grep Content-Length
```

Then compare what `requests` yields and what `curl` yields.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.1"
  },
  "platform": {
    "release": "5.4.12-arch1-1",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": false
}
```

**Comment by s104346** [comment]
https://stackoverflow.com/questions/36194656/http-content-length-and-content-encoding

Requests sends an `Accept-Encoding: gzip, deflate` request header by default, causing the response body to be compressed; curl doesn't.

Send `Accept-Encoding: identity` to get the "correct" size.

**Comment by ghost** [comment]
@s104346 thanks, that works!
