### ISSUE TITLE
How can I send a POST request without default headers attributes?

### ISSUE THREAD

**Issue by brunocamarggo** [psf/requests#5321]
Please,

Just a simple question.

Someone knows how can I send a POST request without default headeres attributes?

Thanks a lot.

Example:

```
@app.route('/foobar')
def get():
    headers = {
        'Authorization': 'Bearer Fooobaaaarrrrrr',
        'foo': 'bar',
        'bar': 'foo'
    }
    response = requests.post(url='http://127.0.0.1:5000/post', headers=headers)
    return response.text


@app.route('/post', methods=['POST'])
def post():
    return str(request.headers)
```
Reponse:
```
Host: 127.0.0.1:5000
User-Agent: python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: Bearer Fooobaaaarrrrrr
Foo: bar
Bar: foo
Content-Length: 0
```

**Comment by nateprewitt** [comment]
Hi @brunocamarggo,

These kinds of questions are best asked on Stackoverflow, as we’ve specified when you open a ticket.

I’d suggest looking at the PreparedRequests workflow, and opening a question on Stackoverflow if you’re still having issues. Thanks!
