### ISSUE TITLE
In [33]: print(requests.get("http://google.com").status_code)  429

### ISSUE THREAD

**Issue by guanchengliu17** [psf/requests#5322]
Summary.
run the command: print(requests.get("http://google.com").status_code)
it return : 429 not 200

![image](https://user-images.githubusercontent.com/25875643/72969374-3011d180-3d7a-11ea-93e0-ef1b8c2f04f2.png)

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @guanchengliu17,

You’re being rate limited by the server you’re calling. It’a best practice to be using sensible request limits and back off strategies in whatever scripts you’re writing.
