### ISSUE TITLE
Issue with Parsing URIs in urllib3 - Breaks Security Tools when testing for Path Traversal 

### ISSUE THREAD

**Issue by mazen160** [psf/requests#5324]
Hi all,

This is a ticket related to a bug I found when using requests. It appears that the root cause is in urlib3 that requests module use.

**Comment by nateprewitt** [comment]
Hi @mazen160,

From Requests perspective we’ve aimed to give users a simple interface to do http requests but may not support every use case, especially if it has potential security risks.

This is ultimately a decision urllib3 owns though. I’m going to resolve this ticket in favor of the one you linked. Thanks for bringing this to everyone’s attention!
