### ISSUE TITLE
Unable to connect to api.telegram.org through proxy

### ISSUE THREAD

**Issue by x86-64-32-16** [psf/requests#5330]
I've been dealing with that issue for 2 days and haven't come up with any sort of solution. I'm trying to write telegram bot with python using telebot library. Once i run the program, i get the following error:
'No connection could be made because the target machine actively refused it'
Well, i was disappointed and decided to look up the issue on the internet. After some time passed, i got that the proxy may be the possible solution, so i utilized it. And, full of joy and delight, i started writing some code. 
That's what i got so far:
import telebot
from telebot import apihelper
TOKEN = "token"
bot_obj = telebot.TeleBot(token=TOKEN, threaded=False)
@bot_obj.message_handler(comands=['start'])
def start(message):
    bot_obj.send_message(message.from_user.id, "Howdy")
bot_obj.polling()

And that's what i ended up with:
"Not supported proxy scheme socks5"

**Comment by nicktimko** [comment]
I'd try `pip install -U requests[socks]` to make sure you have the SOCKS proxy requirements. If that doesn't work, you may want to ask whoever is maintaining the telebot package you're using, rather than Requests.

**Comment by threadedstream** [comment]
So, i have installed necessary package. The only thing that changed is an error message,  which is ConnectTimeoutError now.

**Comment by nicktimko** [comment]
That's not an issue with requests; you can't connect. Try [asking your question on StackOverflow](https://stackoverflow.com/questions/ask)

**Comment by threadedstream** [comment]
Thank you, dear stranger.
