### ISSUE TITLE
Stop downgrading dependencies

### ISSUE THREAD

**Issue by KOLANICH** [psf/requests#5337]
`requests` has restricted dependencies versions with `<` conditions. This causes dependencies downgrades.

## Expected Result

It must never have been done.

## Actual Result

It has been done.

## Reproduction Steps

```bash
git clone --depth 1 https://github.com/chardet/chardet
cd chardet
python3 ./setup.py bdist_wheel
pip install --upgrade ./dist/*.whl
```

`Successfully installed chardet-4.0.0`

```bash
git clone --depth 1 https://github.com/psf/requests
cd requests
python3 ./setup.py bdist_wheel
pip install --no-index ./dist/*.whl
```

`No matching distribution found for chardet<3.1.0,>=3.0.2 (from requests==2.22.0)`

**Comment by nateprewitt** [comment]
Resolving in favor of #5341.
