### ISSUE TITLE
idna requirement causing problems now idna 2.9 has been released.

### ISSUE THREAD

**Issue by cjw296** [psf/requests#5341]
requrests pins idna to <2.9, which causes problems for pip now that 2.9 has been released.

## Expected Result

projects that require requests to install cleanly when new second-point idna releases are made.

## Actual Result

```
pip install .[dev]
...
Collecting idna>=2.0.0; extra == "secure"
...

ERROR: requests 2.22.0 has requirement idna<2.9,>=2.5, but you'll have idna 2.9 which is incompatible.
...
```

Then, when you try and use a setuptools entrypoint script:

```
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.9 (.../site-packages), Requirement.parse('idna<2.9,>=2.5'), {'requests'})
```

## Reproduction Steps

See above.

## System Information

```
Python 3.6
setuptools 45.2.0
pip 20.0.2
```

**Comment by cjw296** [comment]
See also https://github.com/psf/requests/issues/5337 and https://github.com/psf/requests/pull/5226

**Comment by jacobtomlinson** [comment]
I am also experiencing this.

**Comment by cjw296** [comment]
@sethmlarson  - any chance we could keep this issue open until the release goes out? Saves people reporting dupes...

**Comment by dralley** [comment]
Yes please. A timeline on the new release would also be appreciated.

**Comment by nateprewitt** [comment]
@dralley The release just went up onto PyPI.

**Comment by marcmaxson** [comment]
I resolved this by upgrading requests:
`pip install requests --upgrade`
from version 0.22 to 0.23, then dependency is `idna<3,>=2.5`

**Comment by tadejp** [comment]
> I resolved this by upgrading requests:
> `pip install requests --upgrade`
> from version 0.22 to 0.23, then dependency is `idna<3,>=2.5`

this actually worked, thanks
