### ISSUE TITLE
License hiccup?

### ISSUE THREAD

**Issue by HWiese1980** [psf/requests#5366]
You have a dependency `chardet` in your tree that is licensed under LGPLv2.1. Does this not mean that you have to adopt that license as well? Correct me if I'm wrong. **I'm not a lawyer** 

## Expected Result

License should be LGPLv2.1 because `chardet-3.0.4` is under LGPLv2.1. 

## Actual Result

License is Apache...

## Reproduction Steps

See license of `chardet-3.0.4` dependency.  

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.8"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.5"
  },
  "platform": {
    "release": "19.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010104f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": true
}
```

**Comment by HWiese1980** [comment]
A solution (and my personally preferred one too) would be to ditch `chardet` and use another lib for encoding detection that does not enforce LGPL... just sayin...

**Comment by HWiese1980** [comment]
My bad. It's LGPL without Copyleft, not GPL. Consider this issue solved.

**Comment by justinmclean** [comment]
LGPLv2.1 is also not compatible with the Apache license see [1] 

1. https://www.apache.org/legal/resolved.html#category-x

**Comment by sethmlarson** [comment]
Requests doesn't modify or distribute chardet therefore doesn't trigger the clause in LGPL. Python isn't the same as C or compiled languages.
