### ISSUE TITLE
Passing in public/private key as ASCII encoded strings.

### ISSUE THREAD

**Issue by tshrmthw** [psf/requests#5368]
I have the ASCII encoded public and private key that I want to pass along with the request. However I believe the library only takes in the cert argument as a file path or tuple of file paths. Is there a way around this?

**Comment by c2d628ba98** [comment]
You may want to read this, especially a part about the private keys - https://howhttps.works/

**Comment by tshrmthw** [comment]
@c2d628ba98 Thanks for responding with the link above! It was a good read but I don't think it was what I was looking for. I think what you were trying to convey is why and how certification works and the reason you don't just pass it around as a byte-string.

I do believe it also led up to restarting this https://bugs.python.org/issue16487 . This was basically what I was looking for, however I guess it is still an unresolved issue.

After some more researching on this topic I decided to go with a temp_file approach and using the temp_file path within a context so that it is unlinked after the request is made.

Thanks again! I am closing this for now.
