### ISSUE TITLE
Trying to access the latest en documentation from doc.python-requests.org domain causes a faulty redirect and a HTTP404

### ISSUE THREAD

**Issue by 1a8e** [psf/requests#5371]
When using the url `http://docs.python-requests.org/en/latest/`, it redirects to `https://2.python-requests.org//en/latest/` (notice the extra / before `en`). This causes a HTTP 404.

## Expected Result

The redirect should be to `https://2.python-requests.org/en/latest/`

## Actual Result

HTTP 404

## Reproduction Steps

Try to visit the latest en documentation for requests using the link `http://docs.python-requests.org/en/latest/`, for example from [certifi](https://github.com/certifi/python-certifi)

## System Information

Not applicable

**Comment by deveshks** [comment]
I wanted to contribute a fix for it, and was trying to find in the source code where this is defined but I couldn't find it.
But after looking at https://docs.readthedocs.io/en/stable/user-defined-redirects.html, seems like the redirects are defined somewhere else outside the source code. (It starts with `Log into your readthedocs.org account.`)

In that case, this might not be a good first issue for someone to look at, as it is listed in https://github.com/psf/requests/contribute

**Comment by ewdurbin** [comment]
@nateprewitt do you by chance have access to the project on read the docs? If so could you share access to my user? (same username: `ewdurbin`)

**Comment by nateprewitt** [comment]
@ewdurbin, I don’t have access to any of the doc infrastructure actually. We’d need @kennethreitz to get us added.

**Comment by ewdurbin** [comment]
@nateprewitt do you have a RTD username I can add to the project?

**Comment by nateprewitt** [comment]
It should be the same `nateprewitt`. Thanks!

**Comment by deveshks** [comment]
Hi @ewdurbin , @nateprewitt 

Thanks for responding. If I understand correctly, the RTD username will help solve this issue as it will grant access to readthedocs?

**Comment by nateprewitt** [comment]
Hi @deveshks, apologies for the back and forth. Yes, I think we're getting RTD setup so we have proper access and then can hopefully address the underlying issue.

**Comment by mulka** [comment]
Any update on this?

**Comment by nateprewitt** [comment]
Docs have been rendering correctly for a while now, but it looks like this never got closed.
