### ISSUE TITLE
Response object's text and json provides different output for specific input pattern "~{~}"

### ISSUE THREAD

**Issue by contactparthshah** [psf/requests#5376]
## Reproduction Steps

STEP-1) Create Dummy HTTP Server:
```
#-----------------------------
from BaseHTTPServer import BaseHTTPRequestHandler,HTTPServer

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'{"a":"~{~}"}')

httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
#-----------------------------
```
STEP-2) By using requests library get the details and check obj.text and obj.json output is different.
```
Python 3.6.9
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.22.0'
>>> obj = requests.get('http://localhost:8000/')
>>> obj.text
'{"a":""}'
>>> obj.json()
{'a': '~{~}'}
>>>
```
## Expected Result
For text, it should be 
```
'{"a":"~{~}"}'
```
## Actual Result
```
'{"a":""}'
```
What happened instead.

**Comment by ozzywalsh** [comment]
You have not included the `Content-Type` header in the response. 

Requests attempts to guess the character encoding using [chardet](https://github.com/chardet/chardet). Chardet detects `HZ-GB-2312` encoding when given your data.  Which I guess is a [bug](https://github.com/chardet/chardet/issues/82) in `chardet`.

Add this header and `requests` will no longer try to guess: 
`Content-Type: application/json; charset=utf-8`

**Comment by contactparthshah** [comment]
@ozzywalsh , Thank you for providing quick work around.

**Comment by nateprewitt** [comment]
Yep, @ozzywalsh is on point. Since `text` relies on chardet, this will likely remain an edge case until they're able to resolve the detection issue. The workaround provided should be able to unblock anyone else who hits this though, assuming they know the content to be JSON.

Thanks everyone!

**Comment by nateprewitt** [comment]
As an extra note, you can also set the `encoding` attribute on your response before calling `text` to force a specific encoding like JSON. That's what's happening when the Content-Type header is being passed.
