### ISSUE TITLE
Request returns broken encoding (how to use with BeautifulSoup)?

### ISSUE THREAD

**Issue by h56cho** [psf/requests#5398]
Hello,

I am trying to web scrap a site that contains lots of ELA questions (permission obtained). I have been trying to implement the code below:
```python
    login_url = 'https://www.helpteaching.com/registration/login.htm?'
    data = {
        'name': '<myUserName>',
        'password': '<myPassword>',
        'remember_me': 1
        }

    with requests.Session() as s:
        response = requests.post(login_url , data)
        s.encoding='utf_8'
        index_page= s.get('https://www.helpteaching.com/questions/Reading_Strategies')
        soup = BeautifulSoup(index_page.text, 'html.parser')
```

Note that the encoding used by the site is utf-8, and I even manually adjusted the encoding to 'utf-8'.
However, when execute the code above, the texts are all broken.

Is there any way that I can use Requests with BeautifulSoup?

I am using Python 3.7.0.

Thank you,

**Comment by nateprewitt** [comment]
Hi @h56cho,

`Session` objects don't have an `encoding` parameter. With the web today, it will rarely work to apply a single encoding to all response. You can try to set the encoding on the `Response` object, but that shouldn't be needed in this case.

You should validate the output from Requests before passing it to BeautifulSoup. If it's still coming back broken (with and without setting the encoding), the response from the webserver isn't in UTF-8. This unfortunately is outside of the scope for this issue tracker. You'll probably have the best luck asking a question on Stackoverflow.com with the `python-requests` tag.
