### ISSUE TITLE
Commercial Usage Rights

### ISSUE THREAD

**Issue by hi2rashid** [psf/requests#5408]
We are using this module in our application with Django.

Can you please confirm if its okay to be used commercially.

Thank you in advance

**Comment by nateprewitt** [comment]
Hi @hi2rashid, this project is released under the Apache-2.0 license as noted [here](https://github.com/psf/requests/blob/master/LICENSE). You can use it freely within the constraints of that licensing agreement.

Here's a quick explanation of expectations: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
