### ISSUE TITLE
missing implementation of "json" argument in "put" method

### ISSUE THREAD

**Issue by liyakun** [psf/requests#5409]
It seems that the implementation of "json" argument was forgot, see [1].

[1] https://github.com/psf/requests/blob/bebf5250b0df1b922ff534e987a4481cc4dde99d/requests/api.py#L128

**Comment by sigmavirus24** [comment]
Nope. It's accepted via `**kwargs*`.

**Comment by liyakun** [comment]
@sigmavirus24 thanks, you are right.

It would be great to keep it in similar format as `post` method as they both accept this argument. Is there any specific reason why they are written in different ways?

**Comment by sigmavirus24** [comment]
Maintenance overhead is much higher if you have to keep argument lists updated in two places

**Comment by liyakun** [comment]
Okay, I see, thanks for your explanation.
