### ISSUE TITLE
Specifying number of retries in requests.get

### ISSUE THREAD

**Issue by ndvbd** [psf/requests#5415]
Is it possible to specify number of retries in requests.get?

**Comment by sigmavirus24** [comment]
No

**Comment by wadefletch** [comment]
Is this a feature that would be considered for a feature addition? I'd be happy to write if so.

**Comment by sigmavirus24** [comment]
No. The project's been under a feature freeze for years - most especially when it comes to the API

**Comment by nateprewitt** [comment]
Sigmavirus24 is right, we're currently under a feature freeze for Requests. There are a handful of guides available for using urllib3's `Retry` class with a Requests `Session`, but we don't support retries with the `requests.get` api.
