### ISSUE TITLE
Add a Pull request template

### ISSUE THREAD

**Issue by to09** [psf/requests#5416]
To make easier for the contributors and guide them in the right way to contribute with the deploy preview check.

**Comment by nateprewitt** [comment]
Hi @to09,

Thanks for the interest! You can find the full contribution guide [here](https://requests.readthedocs.io/en/master/dev/contributing/) which would be the best place to get that information.

That said, Requests is both on a semi-permanent feature freeze and under limited support. We're only able to reliably review security issues or critical bugs right now. For that reason, I think adding a template may generate more churn for all parties.
