### ISSUE TITLE
Downloading corrupted files with Python

### ISSUE THREAD

**Issue by Pablo-Marina** [psf/requests#5417]
Hello,
I have a XAMPP Server on Windows, from which I aim to download remotely a pdf file located in C:/xampp/htdocs/ using requests library from python to generate it in the very same folder but with another name (later I'll change the direction to downloads folder once it works)
The server is running in IP address 192.168.1.134 port 8081. 
This is the part of the code:
  ```
  url="http://192.168.1.134:8081/c:/xampp/htdocs/informe.pdf"
  response=requests.get(url)
  tofile=open('informelocal.pdf','wb')
  tofile.write(response.content)
  tofile.close()

```
The thing is, once I try to open the local file, I can't open it, because it's corrupted.
I think something is matter with that URL, but I don't know how to put it right.
Thanks for your time

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
