### ISSUE TITLE
How can I use sendfile?

### ISSUE THREAD

**Issue by ImSingee** [psf/requests#5421]
I tried

```
r = requests.get(SOME_URL, stream=True, verify=False)

with open('/path/to/dest', 'wb') as f:
    socket.fromfd(r.raw.fileno(), socket.AF_INET, socket.SOCK_STREAM).sendfile(f)
```

but it doesn't work.

**Comment by sigmavirus24** [comment]
You can't use sendfile.

**Comment by nateprewitt** [comment]
Hi @ImSingee,

This isn't something Requests supports and I don't think we can provide help on it. You'd need to do some more digging with the socket library.
