### ISSUE TITLE
Usage of SourceAddressAdapter to create multiple source ip

### ISSUE THREAD

**Issue by kaushik853** [psf/requests#5422]
Hi,
Can you tell how can i test it with multiple source ip address . Something i tried like
```python
from requests_toolbelt.adapters import source
session = PACSession(pac)
list_source_ip_and_url = [("10.129.xx.yy", "https://google.com"), ("10.189.yy.xx", "https://random.com/Surveyor.Web/")]
responses = []
try:
    for source_ip, url in list_source_ip_and_url:
        new_source = source.SourceAddressAdapter(source_ip)
        session.mount('http://', new_source)
        session.mount('https://', new_source)
        responses.append(session.get(url))
    print(responses)
except Exception as e:
    print(e)
```
I am getting error like:
HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x033D5547>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
Looks like im hitting some requests module error.
Is it because i can't assign source ip to my interface?

**Comment by sigmavirus24** [comment]
This isn't appropriate for this project. `requests_toolbelt` is a separate third-party project.

**Comment by kaushik853** [comment]
ok, i will open it there, thanks
