### ISSUE TITLE
Cannot download files larger than 124MB

### ISSUE THREAD

**Issue by dnroaffys** [psf/requests#5427]
I'm using requests to download files from my remote server. All files under 124MB are downloaded and saved properly. Files larger than that are only downloaded up to 124MB and the rest of the data is skipped. 

Originally I hadn't set **stream** to **True** and I was simply saving the data using **r.content**. I thought setting **stream** to **True** and iterating over chunks with **iter_content()** would fix my problem but it persists.

 Am I doing something wrong?

**Edit:** I previously stated that it downloaded up to 130MB, but it's actually 124MB. 

Here's my code
```python
for file in files_list:
    url = "http://server:8080/path/" + file
    r = requests.get(url, stream=True)
    with open(file, 'wb') as f:
        for chunk in r.iter_content(chunk_size=1024): 
            if chunk:
                f.write(chunk)
                f.flush()
```

**Comment by Ch4rm-Python** [comment]
What file type were you trying to download and what type of webserver are you running? (If you don't know what type you might be able to find it in the "X-Powered-By" or "Server" response headers) I think I have a solution but still trying to debug.

**Comment by stefanos-poriazis** [comment]
Webserver is:  **Apache/2.4.37 (Win64) PHP/7.3.1**
The file type is a Unity Engine binary file with **.resS** extension

I still haven't found a solution and I was forced to split the file in smaller pieces and combine them as they're being downloaded.

**Comment by VeNoMouS** [comment]
what does 

```python
r.headers["Content-Length"]
```

Say?

**Comment by stefanos-poriazis** [comment]
> what does
> 
> ```python
> r.headers["Content-Length"]
> ```
> 
> Say?

It says ~219 million bytes. Which is correct since the file is 219MB.

**Comment by VeNoMouS** [comment]
Stupid question but what happens if you increase the chunk size to like **8192**?

**Comment by stefanos-poriazis** [comment]
> Stupid question but what happens if you increase the chunk size to like **8192**?

Same thing. Downloads up to 124MB and stops. Last chunk was 514 bytes in size. I don't know why though.

**Comment by VeNoMouS** [comment]
And it downloads ok via wget / curl? can we get the url to test?

**Comment by VeNoMouS** [comment]
Dunno if related.. https://serverfault.com/questions/470403/apache-2-4-on-windows-2008-large-file-downloads-are-corrupt

**Comment by stefanos-poriazis** [comment]
> Dunno if related.. https://serverfault.com/questions/470403/apache-2-4-on-windows-2008-large-file-downloads-are-corrupt

That seems to be the solution! File downloads completely now. Thank you so much for your help! :heart:
