### ISSUE TITLE
Received response with content-encoding: gzip, but failed to decode it.

### ISSUE THREAD

**Issue by petasis** [psf/requests#5428]
I get an error while trying to download from https://www.huffingtonpost.gr/feeds/index.xml.

## Expected Result

To download the data.

## Actual Result

I get an exception.
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

## Reproduction Steps

```python
import requests
requests.get('https://www.huffingtonpost.gr/feeds/index.xml', timeout=5.0, allow_redirects=True)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.6.1"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.6"
  },
  "platform": {
    "release": "5.5.15-200.fc31.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010104f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
This isn't a bug in Requests. The server your talking to (or an intermediary) is mucking with the compression of the response.

**Comment by nateprewitt** [comment]
Going to resolve since there's nothing we can do here. This would need to be resolved with the server in the network chain.

**Comment by petasis** [comment]
On the other hand, other libraries (wget, firefox), seem to download the data.

**Comment by sigmavirus24** [comment]
Any fix for this would be in urllib3
