### ISSUE TITLE
Not able to import requests 

### ISSUE THREAD

**Issue by DutchviewSumit** [psf/requests#5429]
If I am trying to install requests it is showing requirement already satisfied but If I am trying to import then it is throwing error. Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'.
 I am running the command pip3 list then it is showing requests   2.23.0. but not able to import.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
