### ISSUE TITLE
Timeout exception not being raised

### ISSUE THREAD

**Issue by alexbode** [psf/requests#5432]
I am testing a backend api and expect an exception to be raised when the request takes longer than specified timeout. I am running a flask app behind nginx behind an aws elb. The app is running in a private subnet and the elb is in the public subnet. Don't know if this is an issue related to the backend architecture or a requests bug. When I go to the url in a browser flask returns the json response immediately. Interestingly, using the requests library, the response is returned at a time about double the specified timeout (see screenshots). 

## Expected Result

Raised exception

## Actual Result

Returns response after specified (2 * timeout)

## Reproduction Steps
<img width="510" alt="image" src="https://user-images.githubusercontent.com/25521899/79810594-3fc49600-8328-11ea-96d4-c067679433a4.png">
<img width="497" alt="image" src="https://user-images.githubusercontent.com/25521899/79810605-45ba7700-8328-11ea-9fb5-fbcc32a12c52.png">

```python
import time
start = time.time()
print(requests.get("https://******.com/test", timeout=2).json())
print(time.time() - start)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.4"
  },
  "platform": {
    "release": "19.4.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.25.6"
  },
  "using_pyopenssl": false
}
Python 3.7.4
requests==2.22.0
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @alexbode,

If you look at the [docs](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts) or source code on timeouts, we’ve got a couple call outs on this. The timeout you’re specifying here is a Read Timeout, not a Total Timeout.

> timeout is not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds (more precisely, if no bytes have been received on the underlying socket for timeout seconds). If no timeout is specified explicitly, requests do not time out.

The extra time you’re seeing is either because we’ve received some data from the server, resetting the timeout, or because the connection step is taking up the rest of the time.

**Comment by alexbode** [comment]
@nateprewitt 

Thank you for your quick response.
Solved: Misconfigured Aws Elastic Load Balancer.
Very interesting how the miscofigured load balancer affected the requests client in that way but the issue was on my end. I deployed the elb in a public and private availability zone, should have been only in a public availability zone. Thanks for the help again.
