### ISSUE TITLE
QUES: Default port for Dockerfile

### ISSUE THREAD

**Issue by joehoeller** [psf/requests#5435]
What port do I need to map to in Dockerfile so requests can make a request out?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by daddydrac** [comment]
Thanks for your Shitty developer pedantry —  I tried Stack and I labeled
this ques as a question.

**Comment by sigmavirus24** [comment]
>  I labeled this ques as a question.

The project doesn't accept questions in issues. If you'd followed the issue template then you'd have seen that and not opened this in the first place.
