### ISSUE TITLE
Unexpected Prepared Request behavior

### ISSUE THREAD

**Issue by hairygeek** [psf/requests#5438]
`requests.Session.send` raises random error if you change `headers` in Prepared Request and send a `POST` request with `json` parameter.

## Reproduction Steps

```python
import requests as rq
s = rq.Session()
r = rq.Request('POST', 'https://google.com', json={'foo':'bar'})
p = r.prepare()
p.headers = {}
s.send(p)
```
**Error:**
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/hairygeek/.local/share/virtualenvs/slink-9m8Vdza8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/hairygeek/.local/share/virtualenvs/slink-9m8Vdza8/lib/python3.8/site-packages/requests/adapters.py", line 470, in send
    low_conn.send(hex(len(i))[2:].encode('utf-8'))
TypeError: object of type 'int' has no len()
```
However this works:
```python
r = rq.Request('POST', 'https://google.com')
p = r.prepare()
p.headers = {}
s.send(p)
<Response [405]>
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.2"
  },
  "platform": {
    "release": "5.5.10-arch1-1",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1010105f"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": false
}
```

**Comment by chanyshv** [comment]
Also this works too:
```python 
r = rq.Request('POST', 'https://google.com', json={'foo':'bar'})
p = r.prepare()
p.headers.update({'bar':'baz'})
s.send(p)
<Response [405]>
```

**Comment by sigmavirus24** [comment]
Calling `prepare` generates all the headers that Requests has to pass to urllib3 including content-length and content-type. You're altering those and it seems you're expecting magic to happen. Removing essential headers will never Just Work.

**Comment by chanyshv** [comment]
You're right. But in this case it would be better to throw a specialized exception, something about there are missing essential headers.

**Comment by sigmavirus24** [comment]
Why? The presumption is that if you're using the PreparedRequest flow you know enough to not need safety rails

**Comment by nateprewitt** [comment]
I don’t think we can easily special case every possible action a user can take with a PreparedRequest. The PreparedRequest flow is for users making targeted changes that still operate within the realm of reasonable requests.

This specific case will actually go away if we move to using urllib3 for chunked encoding but that still needs through testing. I’m going to close this out since we don’t have any immediate actions take here.
