### ISSUE TITLE
How to access token based API using requests in python?

### ISSUE THREAD

**Issue by vvksahoo** [psf/requests#5442]
I want to call one API from another API. So external API is having jwt token based authentication .
```
import requests
response = requests.get('http://host:port/api/users', auth= ("username","password"))
````
I am getting error :
```
{"error":"authentication failed: jwt parse error: token contains an invalid number of segments","code":16,"message":"authentication failed: jwt parse error: token contains an invalid number of segments","details":[]}
```
Or , First i need to call login API ,get the token and while calling another API apply that token in header.
Please suggest here.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by vvksahoo** [comment]
Please find the StackOverflow link for the same issue. 
https://stackoverflow.com/questions/61482014/how-to-access-token-based-api-using-requests-module-in-python

**Comment by nateprewitt** [comment]
Looks like the StackOverflow issue has some answers in it, resolving this.
