### ISSUE TITLE
Modified file content after upload

### ISSUE THREAD

**Issue by ssy-lehmann** [psf/requests#5446]
Also I have been looking into documentation I didn't found the problem/explanation.

## Szenario:

- The server does use WebDav and I can use a PUT request for uploading
- In addition it must be digest authentication
- it works with curl using --digest and --user "xxxxxxx:yyyyyy"

The difference between curl and the Python script after here is
that the script seems to modify the content of the file while uploading.
If I look at http://internal-demo-url/uploads/demo.properties the
content looks like following:

## The uploaded file

```
--6cb2e8363c8d7f9191d2068b62828985
Content-Disposition: form-data; name="file"; filename="demo.properties"
Content-Type: text/plain

title=demo
context=upload
message=hello world 3!

--6cb2e8363c8d7f9191d2068b62828985--
````   

Of course I just would like to have the three lines in the middle.
**What did I wrong?**

## The Python code (upload.py)

```python
from requests import put
from requests.auth import HTTPDigestAuth

url = 'http://internal-demo-url/uploads'
with open('demo.properties', 'rb') as handle:
    headers = {}
    files = {'file':('demo.properties', handle, 'text/plain')}
    response = put(url, auth=HTTPDigestAuth('xxxxxx', 'yyyyyy'),
                        files=files, headers=headers)
    print(response.status_code)
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by ssy-lehmann** [comment]
I'm cautious to say "it is a bug" however I see that the library is doing the stuff (while curl does not) and I don't see it documented on your side (except I missed it). From this I think the issue should be ok. Anyway I will ask on stackoverflow to make you happy ...

**Comment by sigmavirus24** [comment]
You've filed an issue that `files` is doing a `multipart/form-data` upload and that's not what cURL does with no description of how you're using curl or what format you expect the data to be in. `files` is documented to send data this way (that's its entire point) and thus either you've not read the docs and are using the wrong options (and need help from stackoverflow) or you think there's a bug in the encoding being used (which there decidedly is not).
