### ISSUE TITLE
How to set an effective useragent for Session?

### ISSUE THREAD

**Issue by raisoon** [psf/requests#5447]
I have set a useragent for the requests session:

session = requests.session()
headers = {}
headers['user-agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36'
resp = session.get('http://www.gov.cn',headers=headers)
print(session.headers)

but in the result, the user-agent is 'python-requests/2.22.0'.
{'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

how can i set an effective useragent?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by VeNoMouS** [comment]
@raisoon the `headers=headers` is only passed onto the get request itself... 

However if you want to set it permanently..

```python
import requests
from requests_toolbelt.utils import dump

session = requests.session()
session.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36'
resp = session.get('http://www.gov.cn')

print(dump.dump_all(resp).decode('utf-8'))
```

I've included you a better debug to see the request sent as well :)

**Comment by nateprewitt** [comment]
It looks like this ended up answered, going to resolve.
