### ISSUE TITLE
Make content-type be multi-part without being given files

### ISSUE THREAD

**Issue by dasyad00** [psf/requests#5460]
Currently, to post a multipart/form-data with boundaries, you either need to give a File or make the data File-like. This feature aims to allow uploading of data without uploading files.

I am working on a fix with @Marti2203

**Comment by Marti2203** [comment]
When you want to send a form without a file but the form has to be of type 'multipart/form-data' we need to write down the explicit boundary in the content-type header, but this is generated by urllib3 and we cannot predict it or pregenerate it as it is supposed to be random, so we have to "spoof" the API by sending the data as a file.

**Comment by sigmavirus24** [comment]
There are other libraries that provide you a way to do this without changing the core functionality that millions of people rely on.

**Comment by Marti2203** [comment]
Here is example code that uses this "functionality".
```
import requests
url = "foo.bar"
payload = {'thing: (None,"""{'blah':  0 }""")}
response = requests.post(url, files = payload)
```
When inspecting [the logic for making a PreparedRequest](https://github.com/psf/requests/blob/9ed5db8ed28e816b597dafd328b342ec95466afa/requests/models.py#L502), it can be seen that if the user gives a content type, it will be placed, but to reach a proper multipart/form-data we need to know the boundary beforehand as the previous comment mentioned. We will make a pull request with a simple fix that changes the logic such that this issue is overcomed.

**Comment by Marti2203** [comment]
@sigmavirus24 We saw http.client and requests and requests is more simple. I just saw your comment

**Comment by sigmavirus24** [comment]
@Marti2203 there are already existing libraries you can use and should be using instead of trying to make this work in Requests core functionality. The project is basically in security-fix-only mode at this point

**Comment by sigmavirus24** [comment]
https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-multipart-data-encoder will allow you to do this (since you haven't looked very far on Google it seems)

**Comment by Marti2203** [comment]
Okay, that I had not known about the "security-fix-only mode"

**Comment by Marti2203** [comment]
Yeah, we have not looked too much into it because we needed something simple and postman recommended requests and http.client

**Comment by Marti2203** [comment]
"Requests has support for multipart uploads, but the API means that using that functionality to build exactly the Multipart upload you want can be difficult or impossible."(that speaks a lot about some parts of the elegance of the library)

**Comment by dasyad00** [comment]
@sigmavirus24 Apologies for not taking the time to Google very far. We weren't aware of [requests_toolbelt](https://toolbelt.readthedocs.io/en/latest/index.html) and assumed that all functionalities involved with making requests would be available in one package. Apparently, this wasn't the case and now we see why.

**Comment by dasyad00** [comment]
@sigmavirus24 On a separate note, it would be nice to have a reference from the **official repository** to [requests_toolbelt](https://pypi.org/project/requests-toolbelt/)

**Comment by sigmavirus24** [comment]
There was one once upon a time. I'm not a maintainer here though
