### ISSUE TITLE
`.json()` degrades `stream=True`

### ISSUE THREAD

**Issue by reinderien** [psf/requests#5466]
The current logic in `.json()` forces a load of `self.content`, removing any advantage from `stream=True`. For large JSON payloads this creates memory problems. The memory footprint could be halved(ish) by:

- Using `Content-Length` instead of `len(self.content)`
- Using `json.load(raw)` rather than `loads`, also avoiding `content.decode()`

## Expected Result

That the memory footprint of `.json()` be O(1) against input length, not counting the output object.

## Actual Result

The memory footprint is O(n) in input length due to reliance on `.content`.

## Reproduction Steps

Call `requests.get('something-large.json', stream=True).json()`

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.2"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
>     * Using `Content-Length` instead of `len(self.content)`

`Content-Length` only works if the content hasn't been encoded and had to be decoded, e.g., gzip compressed. It's not an accurate representation of what the JSON content length might be

> Using `json.load(raw)` rather than `loads`, also avoiding `content.decode()`

That might be an enhancement, if the project were accepting them.

**Comment by akx** [comment]
This doesn't really matter. [`json.loads()` is defined](https://github.com/python/cpython/blob/b3c77ecbbe0ad3e3cc6dbd885792203e9e6ec858/Lib/json/__init__.py#L274-L296) as (paraphrased here)

```python
def load(fp, **kw):
    return loads(fp.read(), **kw)
```

so attempting to be fancy in `requests` wouldn't help at all. You would also need a streaming-supporting JSON parser.
