### ISSUE TITLE
Stale requests2 package on pypi

### ISSUE THREAD

**Issue by ccope** [psf/requests#5467]
I'm not totally sure where the right place to report this is, but there is a confusing stale copy of requests on pypi, called requests2: https://pypi.org/project/requests2/

It is:
*  3 years old
* uploaded by the original maintainer
* showing a README with some healthy-looking badges
* listed as Development Status: 5 - Production/Stable in pypi
* getting used accidentally in new projects: https://libraries.io/pypi/requests2/usage
* easy to find when searching for requests:
![Selection_142](https://user-images.githubusercontent.com/412019/82508158-12027680-9ab9-11ea-9c41-45f7ee47d0d3.png)

I believe it should be [yanked](https://www.python.org/dev/peps/pep-0592/) and/or [replaced with a redirect](https://www.dampfkraft.com/code/how-to-deprecate-a-pypi-package.html#provide-a-redirect).

**Comment by sigmavirus24** [comment]
The pepole who own that project don't work on this project. You'll need to report this to PyPI

**Comment by ccope** [comment]
I'm not sure what you mean. I am not very familiar with the history of ownership/maintenance of requests, but it seems that over time it has been transferred from kennethreitz to the Python Software Foundation. If none of the current maintainers have access to the requests2 pypi package, I believe the correct method is to follow https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer

**Comment by sigmavirus24** [comment]
@ccope Kenneth doesn't work on this project and isn't affiliated.

**Comment by ccope** [comment]
That may be the case, but the `requests2` package on pypi is an **exact**\* copy of this project at that version, so I don't believe it should be considered a separate project. I agree that there is a process to follow with pypi, but I believe it needs to be initiated by the current maintainers of this package, as they are the ones who should receive control over it.

\*: With the exception of a couple of metadata files which specify `requests2` instead of `requests`.

**Comment by sigmavirus24** [comment]
@ccope people are allowed to fork projects and re-upload them to PyPI. Entire companies do this by prefixing the names of dependencies they want exact-ish copies with their company name. You can't expect those maintainers to update those forks as well, somehow, can you? No. You can't expect these maintainers to attempt to maintain two packages, 1 of which isn't owned by anyone on the maintenance team.

**Comment by nateprewitt** [comment]
Yeah, there's nothing we can really do about this. We don't own that package and names through at least Request5 are currently being squatted. The plan for the foreseeable to future is to keep the project (regardless of version) under just `requests`. Anything else should be treated as unrelated at this time.
