### ISSUE TITLE
Does `Response.content` decode the unicode character in JSON implictly?

### ISSUE THREAD

**Issue by Phi-Li** [psf/requests#5469]
Python 3.8.2, requests 2.23.0

Code for reproduce:

```python
headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0'
}
resp = requests.get('https://api.bgm.tv/subject/12', headers=headers)
print(resp.content)
```

Expect `resp.content` to be bytes containing the original payload bytes (https://requests.readthedocs.io/en/master/user/quickstart/#binary-response-content), but unicode character in the JSON is decoded as unicode representation with a prefix `\u`.

**Comment by sigmavirus24** [comment]
No, resp.content is bytes and resp.text is the decoded unicode text.

**Comment by Phi-Li** [comment]
> No, resp.content is bytes and resp.text is the decoded unicode text.

Thanks for the reply. I decompressed the raw response body and figured out the `\uxxxx` transformation was made on the server side, so the issue has nothing to do with Requests.
