### ISSUE TITLE
about session?

### ISSUE THREAD

**Issue by sjm1992st** [psf/requests#5471]
If I generate a seesion for different domain names in the same program,
 for example :
    url1:
       session1 = requests.session ()
    url2:
       session2 = requests.session ()

What's the difference with me only generating a session for url1 and url2?
Will there be any difference in performance?
thanks!

**Comment by wxllow** [comment]
### From the source code of request.sessions:
>This module provides a Session object to manage and persist settings across requests (cookies, auth, proxies).

An example of this is any cookies a request returns will be there whenever you call a request from that session you call the request from (if you made a session), however, if you didn't make a session (or used a different session, in your case) that different session would not have those cookies that were set.
(Also, correct me if I'm wrong, but "not making/using a session" just makes a session, sends the request, then forgets about the session.)

*I'm new to contributing to others' projects on GitHub, so PLEASE give me feedback or correct me if you can, thanks all :D*

**Comment by wxllow** [comment]
Also, you should probably have asked this on a website like StackOverflow, as this isn't an issue with the library, rather a question on how it works.

**Comment by nateprewitt** [comment]
Thanks for chiming in @ItzMeWilliam 😊

It looks like the initial question is covered so I'm going to resolve, and you're right these should usually be asked on Stackoverflow.
