### ISSUE TITLE
Problem with python3.6

### ISSUE THREAD

**Issue by FathiHamed** [psf/requests#5472]
When I try to send a request via python3.6 to this url: "https://www.khaneyeshoma.ir/", it waits until Timeout exception is raised. But when I try the same request via python2.7 it is successfully completed with status code: 200. Can you help me?
Thanks!

**Comment by sigmavirus24** [comment]
No. This is not a support forum. Go to stackoverflow.com. Provide the exact versions of python, your system dependencies, requests, etc. and the exact results you get.
