### ISSUE TITLE
module 'requests' has no attribute 'settings'

### ISSUE THREAD

**Issue by OscarVanL** [psf/requests#5479]
I want to print verbose logs from requests to see the headers and cookies in each request.
I followed [this page](https://requests.readthedocs.io/en/v0.6.6/user/advanced/), which says to run:

```
requests.settings.verbose = sys.stderr
````

I suspect this may be a case of outdated documentation, but I can't find anything more up to date.

## Expected Result

Verbose logging should be enabled.

## Actual Result

My IDE gives a warning about `settings not being a reference in __init__.pyi`. Running the program throws the exception `AttributeError: module 'requests' has no attribute 'settings'`

## Reproduction Steps

```python
import requests
requests.settings.verbose = sys.stderr
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.9.2"
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.3"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010107f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.8"
  },
  "using_pyopenssl": true
}

```

**Comment by sigmavirus24** [comment]
The page you followed is for requests version 0.6 and you're using 2.23. Please read the correct documentation

**Comment by OscarVanL** [comment]
Oh my bad - I just googled requests verbose logging. I can't seem to find the same documentation for the new version. Do you know where I can find this?

I just want to see the full HTTP POST/GET requests sent with the URL, headers and cookies used.

**Comment by sigmavirus24** [comment]
It doesn't exist. It was ripped out in v1. There's something to dump the request/response cycle in toolbelt.readthedocs.io though

**Comment by netjunki** [comment]
For the other poor sods who run across this thread the same way I did. This is what I wanted to have found when I ran across this:

You want to use [requests_toolbelt](https://toolbelt.readthedocs.io/en/latest/)'s [dump](https://toolbelt.readthedocs.io/en/latest/dumputils.html) module.

Here's a quick example showing how to dump the requests and responses.

```
import requests
from requests_toolbelt.utils import dump

resp = requests.get('https://httpbin.org/redirect/5')
data = dump.dump_all(resp)
print(data.decode('utf-8'))
```

**Comment by businessK8T** [comment]
100,000% thank you for posting this.
