### ISSUE TITLE
One server fails ping -Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(\"bad handshake: SysCallError(104, 'ECONNRESET')

### ISSUE THREAD

**Issue by ruttrow** [psf/requests#5483]
New to Ansible, having trouble with one server failing ping: 

"msg": "kerberos: HTTPSConnectionPool(host='xxxxxl', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(\"bad handshake: SysCallError(104, 'ECONNRESET')\",),)), ssl: HTTPSConnectionPool(host='xxxx', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(\"bad handshake: SysCallError(104, 'ECONNRESET')\",),))",
    "unreachable": true,
    "changed": false,
    "skip_reason": "Host xxxx is unreachable"
}

I replaced host name with xxxx

We have several hundred servers, this is the only one giving this error.

I tried running the ConfigureRemotingForAnsible.ps1
Verified network settings
I can telnet to the host on port 5986 from another server
Verified IIScrypto has not disabled SSL's or TLS.
ran command - winrm e winrm/config/listener
which shows listener running on 5986
I am unable to open the URL of the server on port 5986

**Comment by sigmavirus24** [comment]
There is no bug here. The server or an intermediary is resetting the connection during the TLS handshake.

>  I am unable to open the URL of the server on port 5986

This is unclear if you mean you're generally unable to open it (i.e., in a browser, curl, or requests) or if you're only unable to open it with Requests. Either way, the TLS configuration (besides on/off) could be a problem and you should know what version of requests/urllib3 you're using.

**Comment by ruttrow** [comment]
We do ping sweeps on our servers. One server in question is part of a group that fails the ping test, the code above is the output.

**Comment by sigmavirus24** [comment]
> We do ping sweeps on our servers. One server in question is part of a group that fails the ping test, the code above is the output.

That doesn't answer anything and doesn't negate that there is no bug here. The server is resetting the connection during the TLS handshake

**Comment by ruttrow** [comment]
The server's clock it set to UTC, which shows four hours in the future than Eastern Time Zone. The above issue does not occur when Eastern is set. So this appears to be either a bug, or Anisble does not like the time difference.

**Comment by sigmavirus24** [comment]
> The server's clock it set to UTC, which shows four hours in the future than Eastern Time Zone. The above issue does not occur when Eastern is set. So this appears to be either a bug, or Anisble does not like the time difference.

This really isn't appropriate for this project. You've given no evidence as to the fact that there's a bug in Requests. And now you're involving at least 1400 people in your stream of consciousness debugging. It's really not what those people are likely watching the project for. Please debug this with StackOverflow or the Ansible community. This isn't a Requests issue
