### ISSUE TITLE
Newly created Response object fails on boolean test

### ISSUE THREAD

**Issue by rtatishvili** [psf/requests#5485]
A newly created `Response` object fails boolean test in if statement (when under the hood `__bool__` method is called). Based on conventions used in Python, I expect an empty response object to be resolved to `False`. Although it is a design decision to which value to resolve, throwing an exception in this trivial case is unexpected behavior.

## Expected Result

```
2.23.0
Response is empty
```

## Actual Result

```
2.23.0
Traceback (most recent call last):
  File ".../local/reqeusts_error.py", line 6, in <module>
    if not response:
  File "/opt/miniconda/lib/python3.6/site-packages/requests/models.py", line 677, in __bool__
    return self.ok
  File "/opt/miniconda/lib/python3.6/site-packages/requests/models.py", line 703, in ok
    self.raise_for_status()
  File "/opt/miniconda/lib/python3.6/site-packages/requests/models.py", line 934, in raise_for_status
    if 400 <= self.status_code < 500:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

Process finished with exit code 1
```

## Reproduction Steps

```python
import requests

print(requests.__version__)

response = requests.Response()
if not response:
    print('Response is empty')

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.3.1"
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.0"
  },
  "platform": {
    "release": "3.10.0-957.21.3.el7.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1000210f",
    "version": "18.0.0"
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1000215f"
  },
  "urllib3": {
    "version": "1.25.8"
  },
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
No one uses the library this way in reality, so there's no harm in this behaviour

**Comment by nateprewitt** [comment]
I agree with @sigmavirus24. Status code, headers, and some representation of a body (empty or otherwise) are all required parameters to successfully generate a Response in Requests. I don't think it's worth the time or verbosity to harden the code base against every possible mock when the state isn't reachable in production.
