### ISSUE TITLE
Open a stream from POST request

### ISSUE THREAD

**Issue by andreafresa** [psf/requests#5490]
Hello,
I am trying to open a stream from a POST request. The idea is to open the stream and to attach the response to an SSE client.
is this the correct way to do it?
`response= requests.post(url_request , stream= True)`
If it is true, why it seems like the client is closing the socket at a certain point?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
