### ISSUE TITLE
Instacrack termux bruteforce 

### ISSUE THREAD

**Issue by gehanshanaka** [psf/requests#5493]
Traceback (most recent call last):
  File "crack.py", line 108, in <module>                  sess = instabrute.Login(password)
  File "crack.py", line 83, in Login                      sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by gehanshanaka** [comment]
Any solution to fix this error

**Comment by sigmavirus24** [comment]
Don't access a key that isn't in the dictionary? There's no bug in this library based off of what very little information you've provided

**Comment by gehanshanaka** [comment]
> Don't access a key that isn't in the dictionary? There's no bug in this library based off of what very little information you've provided

Any code for this error

**Comment by gehanshanaka** [comment]
Cupp.py

**Comment by nateprewitt** [comment]
Hi @gehanshanaka, as Sigmavirus24 pointed out, the cookie your code is looking for doesn't exist in this case. This isn't a defect in Requests from what you've provided. You'll need to update the referenced code to be more fault tolerant.
