### ISSUE TITLE
2.24.0 requests and boto3 appear to be incompatible

### ISSUE THREAD

**Issue by jw-maynard** [psf/requests#5502]
boto3 calls broken since upgrade to requests 2.24.0. Running `pip install 'requests<2.24.0' before installing boto3 fixes the issue. I'm not sure if this is a problem with the new version of requests or if boto3 is using requests in some unexpected way that is causing this issue. Since reverting to the old version seems to workaround the issue I thought I'd start here.

## Expected Result

Calls using boto3 to succeed as they always have.

## Actual Result

Get an error:
`An HTTP Client raised and unhandled exception: 'SSLSocket' object has no attribute 'connection'`

## Reproduction Steps

Just attempt to access S3 using boto3

## System Information

Using Docker image `python:3.7-slim`

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.9.2"
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.7"
  },
  "platform": {
    "release": "5.4.0-7634-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010107f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @jw-maynard, Boto3 hasn't used Requests since 2018 and at that time was using a vendored copy. It should only be relying on urllib3 since version 1.8.0.

Could you open a ticket in the [Boto3](https://github.com/boto/boto3) repository with a minimal set of steps you used to recreate the issue, including the output of `python -m pip freeze`.

Thanks!

**Comment by jw-maynard** [comment]
@nateprewitt Sorry about that. Sure will do that!
