### ISSUE TITLE
requests HTTP2

### ISSUE THREAD

**Issue by lei375809291** [psf/requests#5506]
requests怎么发送http2版本的情求呢？
How can requests send http2 request?

**Comment by sigmavirus24** [comment]
It can't

**Comment by nateprewitt** [comment]
@lei375809291, [`hyper`](https://github.com/python-hyper/hyper) is a possible Python alternative. I believe they still support using the [Requests interface over the top of their H2 stack](https://hyper.readthedocs.io/en/latest/api.html#requests-transport-adapter).

**Comment by lei375809291** [comment]
thanks
