### ISSUE TITLE
incremental rest api data 

### ISSUE THREAD

**Issue by oguzhan10** [psf/requests#5510]
Hello, I am trying to fetch incremental data from localhost:8080/test url. This url has json rest api data and it has incremental data inside of it. I fetched data but When I fetch it, it finishes. When I run the code again or run the function every 5 seconds, it gets all data again. How can I get the new data? 

```
import requests
import json
request = requests.get("http://localhost:8080/test").text
a = json.loads(request)
print(a['items'])

```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
