### ISSUE TITLE
How can I send HTTP/1.0 request ?

### ISSUE THREAD

**Issue by contactparthshah** [psf/requests#5512]
Would like to send HTTP/1.0 request using python requests library. can anyone help me here?

UseCase:
Need to test, proxy (Device under Test) upgrades the protocol version automatically.
So let's say If I send HTTP/1.0 request, it automatically upgrades it to HTTP/1.1 and send that request to server.

https://stackoverflow.com/questions/37816596/restrict-request-to-only-ask-for-http-1-0-to-prevent-chunking-error
This is the only help till now I have found, apart from that anything else I can try to send HTTP/1.0 request?

#python-requests

**Comment by nateprewitt** [comment]
Hi @contactparthshah,

As the issue originally stated, please avoid posting requests for assistance on this issue tracker. We try to keep it clear for defects in Requests.

We state both in the docs and in a handful of issues on StackOverflow that Requests is an http/1.1 client.

https://stackoverflow.com/questions/31728124/how-to-define-the-http-protocol-version-in-requests

**Comment by contactparthshah** [comment]
@nateprewitt, makes sense. Thank you.
