### ISSUE TITLE
[Question] Is there a way to get file size of downloaded(chunk) file while downloading. 

### ISSUE THREAD

**Issue by DEEP7696** [psf/requests#5516]
How can I get size of file while downloading it in Python so that I can show downloaded size and pending size of file to download? if file size is 2GB and 700mb is downloaded then how will we get that in python. Currently using Python requests module to download file.

import requests
r = requests.get(download_link)
with open('setup.exe','wb') as file:
    file.write(r.content)

**Comment by Shotaos** [comment]
Hi,

You can get the total size of the file from the `Content-Length` header. 
As for the the download progress, you need to  pass a` stream=True` parameter to the request and then use `iter_content` method on the response to read the output in chunks. As you read the chunks you can keep track of the size of the data received. It's a pretty basic functionality of requests described thoroughly in documentation.

https://requests.readthedocs.io/en/master/user/advanced/#body-content-workflow

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by DEEP7696** [comment]
Thanks for the reply. Same has been pending for answer at stackOverflow.
https://stackoverflow.com/questions/62508831/how-can-i-get-size-of-file-while-downloading-it-in-python
