### ISSUE TITLE
Remove copyrighted media from documentation

### ISSUE THREAD

**Issue by brandondube** [psf/requests#5519]
The [advanced usage](https://requests.readthedocs.io/en/master/user/advanced/) page contains a derivative of a [copyrighted album cover](https://wilderun.bandcamp.com/album/veil-of-imagination) the copyright for which is not owned by the PSF.

This must be removed.

**Comment by nateprewitt** [comment]
Hi @brandondube,

I believe the work is question is actually Veil of Summer by Adrian Cox from an art gallery in San Franciso. That and the photo in question both predate the album by several years. That said, I don't think it's necessary here and opens the psf to unnecessary liability. I've merged 1b41763 to resolve the issue.

**Comment by sigmavirus24** [comment]
@nateprewitt more generally speaking, I think all of the images in the docs are copyright Kenneth who hasn't provided a license to the PSF or project to use those. We should probably just wipe them all and maybe commission a new logo since that was also copyright Kenneth and not licensed.

**Comment by nateprewitt** [comment]
@sigmavirus24, sure I think that's totally fair. Seth sent out an email to Ernest earlier this week about options for cleaning the docs up on a wider scale. We're waiting for some input and then I think we'll be going down that route.

**Comment by brandondube** [comment]
For what it's worth, the contributing page also contains Tool lyrics - https://requests.readthedocs.io/en/master/dev/contributing/
