### ISSUE TITLE
Requests and chrome browser requests behave differently when params contains '|'

### ISSUE THREAD

**Issue by beruhan** [psf/requests#5526]
when request URL: `http://192.168.12.202/cgi-bin/rtpd.cgi?echo&AdminPasswd_ss|tdb&get&HTTPAccount`,It urlencode the '|' char to '%7C' when use requests.But when I use chrome request the url,It seems the chrome doesn't encoded the '|' char, I have try the flowing way to disable url encode,but It seem not work.Does there any way disable requests encode url?
```python
def raw_url_request(method,url, **kwargs):
    req = requests.Request(method, url, **kwargs)
    prepped = req.prepare()
    prepped.url = url
    with requests.Session() as s:
           return s.send(prepped, timeout=timeout, verify=verify)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.6.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.8"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010102f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1000211f"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
