### ISSUE TITLE
Test test_https_warnings is not functional with pytest-httpbin 1.0

### ISSUE THREAD

**Issue by hroncok** [psf/requests#5530]
test_https_warnings is expecting the certificates from pytest-httpbin to produce SubjectAltNameWarning.

pytest-httpbin 1.0 was released, but it has newer certificates that do not produce the warning:

https://github.com/kevin1024/pytest-httpbin/pull/53

And hence the version of pytest-httpbin is pinned here:

https://github.com/psf/requests/blob/1b417634721ec377abb7f17bc1f215e07202c2f7/Pipfile#L16

However with old certificates from pytest-httpbin \< 1.0, we are [no longer unable to test requests on recent Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1676023), because we get:

    pytest-httpbin server hit an exception serving request: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:4020)

Hence we need to update pytest-httpbin in Fedora to 1.0+ in order to test requests, but that way, test_https_warnings fails.

## Expected Result

test_https_warnings should pass with recent pytest-httpbin, possibly by bundling its own certificates.

## Actual Result

test_https_warnings fails:

```
=================================== FAILURES ===================================
_______________________ TestRequests.test_https_warnings _______________________

self = <tests.test_requests.TestRequests object at 0x7fc802ebaa60>
httpbin_secure = <function prepare_url.<locals>.inner at 0x7fc8031980d0>
httpbin_ca_bundle = None

    def test_https_warnings(self, httpbin_secure, httpbin_ca_bundle):
        """warnings are emitted with requests.get"""
        if HAS_MODERN_SSL or HAS_PYOPENSSL:
            warnings_expected = ('SubjectAltNameWarning', )
        else:
            warnings_expected = ('SNIMissingWarning',
                                 'InsecurePlatformWarning',
                                 'SubjectAltNameWarning', )
    
        with pytest.warns(None) as warning_records:
            warnings.simplefilter('always')
            requests.get(httpbin_secure('status', '200'),
                         verify=httpbin_ca_bundle)
    
        warning_records = [item for item in warning_records
                           if item.category.__name__ != 'ResourceWarning']
    
        warnings_category = tuple(
            item.category.__name__ for item in warning_records)
>       assert warnings_category == warnings_expected
E       AssertionError: assert () == ('SubjectAltNameWarning',)
E         Right contains one more item: 'SubjectAltNameWarning'
E         Full diff:
E         - ()
E         + ('SubjectAltNameWarning',)

tests/test_requests.py:855: AssertionError
----------------------------- Captured stderr call -----------------------------
127.0.0.1 - - [11/Jul/2020 00:24:33] "GET /status/200 HTTP/1.1" 200 0
======== 1 failed, 526 passed, 12 skipped, 1 xfailed in 175.72 seconds =========
```

## Reproduction Steps

Unpin the pytest-httpbin version, run tox.

```
$ tox -e py38
$ .tox/py38/bin/python -m pip install -U pytest-httpbin pygments
$ tox -e py38
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.3"
  },
  "platform": {
    "release": "5.7.6-201.fc32.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": false
}
```

**Comment by sethmlarson** [comment]
Thanks for reporting this issue, we've known of this problem for some time but would take some work to fix, would you be willing to provide a patch?

**Comment by hroncok** [comment]
Not sure how to approach it. Certainly, the warning can be made not expected with the new pytest-httpbin, that I can do. However actually testing the warning happens might require having a custom fixture with the old cert and that seems rather tedious. Not sure I could dedicate some time for that.

**Comment by koobs** [comment]
Confirmed QA'ing www/py-requests FreeBSD port on:

```
platform freebsd13 -- Python 3.8.6, pytest-4.5.0, py-1.9.0, pluggy-0.13.1 -- /usr/local/bin/python3.8
cachedir: .pytest_cache
rootdir: /var/tmp/tmpfs0/usr/home/koobs/repos/freebsd/ports/www/py-requests/work-py38/requests-2.25.0, inifile: pytest.ini
plugins: mock-1.10.4, forked-1.0.2, httpbin-1.0.0, xdist-1.32.0
```

Pinned dependencies make it super difficult downstream, but everything appears to pass tests except this one with the latest versions of test dependencies.

**Comment by vishwin** [comment]
Generating a malformed, ie one without or an invalid subjectAltName, certificate (bundle) may be the way to go here. The current bundle in pytest-httpbin, looking at the comments from the relevant issues, were in response to other consumers needing valid certificates in the wake of other libraries and programs, particularly urllib3 and Chromium, more strictly enforcing RFC 2818.

Otherwise, in order to silence this "error":
```
--- tests/test_requests.py.orig 2020-12-16 17:43:25 UTC
+++ tests/test_requests.py
@@ -838,7 +838,7 @@ class TestRequests:
     def test_https_warnings(self, httpbin_secure, httpbin_ca_bundle):
         """warnings are emitted with requests.get"""
         if HAS_MODERN_SSL or HAS_PYOPENSSL:
-            warnings_expected = ('SubjectAltNameWarning', )
+            warnings_expected = ()
         else:
             warnings_expected = ('SNIMissingWarning',
                                  'InsecurePlatformWarning',
```
