### ISSUE TITLE
I get 403 from a get request

### ISSUE THREAD

**Issue by UWTD** [psf/requests#5531]
I don't know if it's ok to post this url? 
[url](https://gcpvuclip-a.akamaihd.net/exp=1594464888~acl=%2f11125cc917d31e89f39b04e48017551f%2f*~data=cid%3d1165763700%2ciid%3dc85a94cc-1674-4eda-b955-fb54269101a6%2csid%3dakamai-890d3df2-8143-41ae-a5ca-2d6e8a8d1be4%2csiteId%3dviu%2cslotId%3dwebapp2%2cclientId%3dnone%2cn%3d1594452428397%2ch%3d63150D199AB469D014D2F6C869D5CA1D%2cip%3d103.78.114.109%2ccdnid%3dakamai%2ccdnprefix%3dgcpvuclip-a.akamaihd.net%2f~hmac=88bef1822223760250961d1ff745a9e4995af5d804ca88155146267ca3289e65/11125cc917d31e89f39b04e48017551f/vp63207_V20200707045412/hlsc_e2931_7.m3u8)
When I make a get request on the above url I get 403 from requests but if I use curl, urllib or anything else I get 200

## Expected Result
A 200 response

## Actual Result

403 response

## Reproduction Steps

```python
import requests
r = requests.get(url)
print(r)
```

## System Information

    $ python -m requests.help

```
The problem seems to be on all systems with latest requests version
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by UWTD** [comment]
> 
> 
> Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

ok. I thought it was a bug when all other libs managed to make a get request to the url I entered with a response code 200 except just requests

**Comment by sigmavirus24** [comment]
Nope. 403 means the server thinks you're forbidden. That means Requests did everything correct but you're missing something the server wants. Hence user error and thus it being proper for this to be on StackOverflow

**Comment by UWTD** [comment]
Thanks for the answer.. I hope someone will find what the issue is.

**Comment by sigmavirus24** [comment]
There is no bug here
