### ISSUE TITLE
Erroneous response headers parsing in some cases

### ISSUE THREAD

**Issue by fbparis** [psf/requests#5532]
## Summary

Information can be lost during the parsing of some complex headers response, like for example these ones [https://developers.google.com/search/reference/robots_meta_tag#xrobotstag](https://developers.google.com/search/reference/robots_meta_tag#xrobotstag)

Simulating something like this with httpbin gives us: [http://httpbin.org/response-headers?X-Robots-Tag=googlebot:%20nofollow&X-Robots-Tag=otherbot:%20noindex,%20nofollow&X-Robots-Tag=noarchive&X-Robots-Tag=unavailable_after:%2025%20Jun%202010%2015:00:00%20PST](http://httpbin.org/response-headers?X-Robots-Tag=googlebot:%20nofollow&X-Robots-Tag=otherbot:%20noindex,%20nofollow&X-Robots-Tag=noarchive&X-Robots-Tag=unavailable_after:%2025%20Jun%202010%2015:00:00%20PST)

## Expected Result

Something like the httpbin output would be nice:
`{
  "Content-Length": "227", 
  "Content-Type": "application/json", 
  "X-Robots-Tag": [
    "googlebot: nofollow", 
    "otherbot: noindex, nofollow", 
    "noarchive", 
    "unavailable_after: 25 Jun 2010 15:00:00 PST"
  ]
}`

## Actual Result

Instead response headers returned by _requests_ are like this:

`{'Date': 'Mon, 13 Jul 2020 15:14:21 GMT', 'Content-Type': 'application/json', 'Content-Length': '227', 'Connection': 'keep-alive', 'Server': 'gunicorn/19.9.0', 'X-Robots-Tag': 'googlebot: nofollow, otherbot: noindex, nofollow, noarchive, unavailable_after: 25 Jun 2010 15:00:00 PST', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true'}`

Note that using `raw._original_response.getheaders()` is returning more useful results:

`[('Date', 'Mon, 13 Jul 2020 15:14:21 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '227'), ('Connection', 'keep-alive'), ('Server', 'gunicorn/19.9.0'), ('X-Robots-Tag', 'googlebot: nofollow'), ('X-Robots-Tag', 'otherbot: noindex, nofollow'), ('X-Robots-Tag', 'noarchive'), ('X-Robots-Tag', 'unavailable_after: 25 Jun 2010 15:00:00 PST'), ('Access-Control-Allow-Origin', '*'), ('Access-Control-Allow-Credentials', 'true')]`

## Reproduction Steps

```python
import requests
r=requests.get('http://httpbin.org/response-headers?X-Robots-Tag=googlebot:%20nofollow&X-Robots-Tag=otherbot:%20noindex,%20nofollow&X-Robots-Tag=noarchive&X-Robots-Tag=unavailable_after:%2025%20Jun%202010%2015:00:00%20PST')
print(r.headers)
print(r.raw._original_response.getheaders())
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.3"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": false
}

```

**Comment by sigmavirus24** [comment]
This is totally valid HTTP/1.1 header behaviour and has been discussed in numerous closed issues.

**Comment by fbparis** [comment]
OK so, if it's _valid_... I'll keep using `requests.Response.raw._original_response.getheaders()` instead of `requests.Response.headers` I can't trust (but I guess the X-Robots-Tag specification is legit too).
Sorry for the duplicate, I only checked the open issues before posting.
