### ISSUE TITLE
Allow [] in params

### ISSUE THREAD

**Issue by Luttik** [psf/requests#5549]
Currently, it seems to not be possible to have [] in query parameters at all using requests since it url-encodes them even though these characters are essential parts of many API's (e.g. they require filters like `?filters[key1]=val1&filters[key2]=val2`). There seems to be no other method to obtain the filters as mentioned above either.

## Expected Result

The `[` and `]` characters should not be encoded when they are present in the key of a query parameter.

## Actual Result

They are url-encoded.

## Reproduction Steps

```python
import requests

request = requests.get('http://example.com', params={'filter[key1]': 'val1'})
print(request.url)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "4.14.181-142.260.amzn2.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.25.9"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @Luttik,

It sounds like there may be some confusion about valid query params. Query parameters are defined in [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.4) to explicitly be a `pchar`*.

If your application isn't able to properly decode URIs, you may be able to look at using PreparedRequests and manually modifying the URL. That service is likely going to have issues with other clients going forward though. If you need further help getting the above setup, StackOverflow would be the best place to get assistance.

* `pchar` = ([a-zA-Z]/[0-9]/ "-" / "." / "_" / "~"/ "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "=" / ":" / "@"), all other chars **MUST** be percent encoded.
