### ISSUE TITLE
Requests module detected by antibot protection, but curl not

### ISSUE THREAD

**Issue by yojuwahajeke** [psf/requests#5553]
I am tring to get pixabay.com content.
Requests module detected by antibot protection, but curl command working perfectly.
(Please don't tell anything about javascript, ...)
This is the second website I seen detected with python module requests.

## Expected Result
Response status code: 200
pixabay website content

## Actual Result
Response status code: 403
cloudflare page

## Reproduction Steps

python requests code to load page
```
import requests
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'en-US;q=0.5,en;q=0.3',
    'Connection': 'keep-alive',
}

response = requests.get('https://pixabay.com/photos/search/?cat=animals&min_height=2400&min_width=3000&orientation=horizontal&pagi=2', headers=headers)
print(response.text)
print(response.status_code, len(response.text))
print(response.request.headers)
```
curl command (for windows)
```
curl "https://pixabay.com/photos/search/?cat=animals&min_height=2400&min_width=3000&orientation=horizontal&pagi=2" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US;q=0.5,en;q=0.3" -H "Connection: keep-alive" --output f
```

## System Information
Python version: 3.6.10 :: Anaconda, Inc.
requests==2.24.0

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
