### ISSUE TITLE
about redirection

### ISSUE THREAD

**Issue by daffapaggani** [psf/requests#5557]
i know python requests is dynamic httplib, but some problem with requests. 

'requests.exceptions.TooManyRedirects: Exceeded 30 redirects.'
i am already increase max redirect , but same response.

i am try using other ISP 'requests' is perfect and nothing problem. and cross check , problem is ISP . there injection ads from my ISP

how i can baypass injection ads  ?

**Comment by sigmavirus24** [comment]
> how i can baypass injection ads ?

That's not a feature of any HTTP client and does not and will not exist in Requests. You'll need to ask StackOverflow questions like this
