### ISSUE TITLE
[Doc] ALL_PROXY is undocumented 

### ISSUE THREAD

**Issue by jiasli** [psf/requests#5558]
## Expected Result

The doc for [Proxies](https://2.python-requests.org/en/master/user/advanced/#proxies) should include `ALL_PROXY` introduced by https://github.com/psf/requests/pull/3185 and its precedence compared to `HTTP_PROXY` and `HTTPS_PROXY`.

## Actual Result

The document [Proxies](https://2.python-requests.org/en/master/user/advanced/#proxies) lacks the description for `ALL_PROXY`, and the only appearance of `ALL_PROXY` is in the [Release History](https://2.python-requests.org/en/master/community/updates/#id37).

**Comment by nateprewitt** [comment]
If anyone would like to provide a PR for this, we'd be fine reviewing it.
