### ISSUE TITLE
Proper scope for session object

### ISSUE THREAD

**Issue by janheindejong** [psf/requests#5559]
I'm using requests in the back-end of my web-app, to get sensor data from another REST API, at 1 Hz. I'm using _one_ session instance for my entire app, which is used in ~5 threads to perform the HTTP requests; typically around 5-10 per cycle. There's some error handling and all the fun stuff, to make sure the program just skips to the next cycle if one of the requests fails. In a nutshell, it looks something like this:

```python 
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests 
import threading
import time

from requests_negotiate_sspi.requests_negotiate_sspi import HttpNegotiateAuth

class MyAPI: 
    
    def __init__(self, host):
        self._host = host
        self._session = Session()
        self._session.auth = HttpNegotiateAuth()
        
    def get_a_lot_of_stuff(end_points: list): 
        with ThreadPoolExecutor(max_workers=5) as executor: 
            futures = []
            for end_point in end_points:
                futures.append(executor.submit(self._get_a_bit_of_stuff, end_point)) 
            for future in as_completed(futures): 
                r = future.result()
                r.raise_for_status()

    def _get_a_bit_of_stuff(end_point: str): 
        return self._session.get(self._host + end_point)
    

def main(): 
    my_api = MyAPI("http://my.host.com")\
    end_points = ["/0", "/1", "/2", "/3", "/4"]
    while True: 
        try:
            my_api.get_a_lot_of_stuff(end_points)
        except: 
            print("Whatever, m8...")
        time.sleep(1)

```

Works fine, nothing out of the ordinary there (at least I think)...

However... I noticed that after running smoothly for several hours, at some point the number of timeout errors starts to increase exponentially - eventually stopping the whole thing altogether - until suddenly everything returns to normal. 

After some tinkering, I found out this behavior could be prevented by calling `self._session.close()` whenever an exception occurs. The program just continues as normal afterwards. 

My limited expertise leads me to believe there is some connection pool buffer that is overflowing, or something of the sorts. Am I thinking in the right direction? 

What would be the 'proper' way to deal with this? It's important for me to re-use my connections, since I'm making ~5-10 calls per second to the same host, and NTLM authentication also requires an additional 2 calls per connection.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
