### ISSUE TITLE
Accept-Encoding can't be removed  

### ISSUE THREAD

**Issue by Dao258** [psf/requests#5564]
I am using requests  2.21.0

headers={
            'Connection':None,
            'Accept-Encoding':None,
            'Accept':None,
            'User-Agent':None
        }

session = requests.Session()
session.keep_alive = False

session.post(url,headers=headers, data=postData,verify=False)

I tired to remove "Accept-Encoding" for post request header

however it still shows Accept-Encoding: identity  which is NOT the same as Accept/User-Agent

How do I remove Accept-Encoding in the header?

Thanks!

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by nateprewitt** [comment]
Hi @Dao258, I'd check documentation for using [Prepared Requests](https://requests.readthedocs.io/en/master/user/advanced/#prepared-requests). If you have further questions, please route them to StackOverflow. Thanks!
