### ISSUE TITLE
Response time differences between different OS(e.g. Windows and Ubuntu)

### ISSUE THREAD

**Issue by PurpleRedHand** [psf/requests#5566]
Hi, I send simple request to a website and get a response with requests library. When I run this code on Ubuntu I get response at 3secs but if I run this on Windows I get response below 1 second. What is problem?

I try with same versions. (requests 2.22, 2.23, 2.24)

Test Code:
`
def responseTime():
    start_time = time.time()
    requests.get("https://github.com/")
    stop_time = time.time()
    print(stop_time - start_time)
`

In Windows:
    0.2963371276855469 secs

In Ubuntu:
    5.247551441192627 secs

**Comment by sethmlarson** [comment]
This is a tough thing for us to figure out as we don't have access to your systems or know anything about how they're configured. I recommend using Wireshark to see where in the request process things are getting hung up.

Closing this as not an issue, in the future use StackOverflow for questions like this.
