### ISSUE TITLE
Customize message error in Response.raise_for_status()

### ISSUE THREAD

**Issue by pozzolana93** [psf/requests#5569]
I had to write a client to interact with CouchDB using `requests`. When calling `response.raise_for_status()` the message shown is the usual HTTP error message (like 404: Not found), but in the response body I have a more detailed explanation of the error (something like: {"error": "Not found", "reason": "The document has been deleted"}). To print this error I had to override the method of the response with a custom function.
Since I believe this could be a common situation, it would be very helpful to have the possibility to print different error messages passing a parameter to the call to `raise_for_status`.

**Comment by sigmavirus24** [comment]
The project's under feature freeze and even if it weren't, this is why wrapping libraries should follow a pattern like:

```py
# mylib/exceptions.py
class MyLibError(Exception):
    pass

class MyLibHTTPError(MyLibError):
    pass

# mylib/client.py

try:
   response.raise_for_status()
except requests.exceptions.HTTPError as e:
  raise MyLibHTTPError(...)
```
