### ISSUE TITLE
requests.get() fails with SOCKS5 proxy on python 3.7.8 64bit on some urls

### ISSUE THREAD

**Issue by shinrax2** [psf/requests#5579]
Summary.
requests.get() with a SOCKS5 proxy fails on 64bit python with some urls but works on 32bit python
## Expected Result

getting the data

## Actual Result

```requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/shinrax2/PS3GameUpdateDownloader/releases/latest (Caused by SSLError(SSLError(9, '[X509] PEM lib (_ssl.c:4140)')))```

## Reproduction Steps

```python
import requests
url = "https://api.github.com/repos/shinrax2/PS3GameUpdateDownloader/releases/latest"
proxies = {
    "http": "socks5://foo:bar@localhost:1080",
    "https": "socks5://foo:bar@localhost:1080"
}

r = requests.get(url, proxies=proxies)
print(r.content)
```

## System Information

    $ python -m requests.help

32bit python:
```{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.8"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.10"
  },
  "using_pyopenssl": false
}
```

64bit python:
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.8"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.10"
  },
  "using_pyopenssl": false
}
```
## Additional Info

SOCKS5-Server: from [simple-socks](https://www.npmjs.com/package/simple-socks/) "examples/createServerWithAuthentication.js"

**Comment by shinrax2** [comment]
i just tested the same code on python 3.7.8 64bit on debian buster 64bit and it works flawless there

i think this might be a windows specific issue

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by shinrax2** [comment]
im sorry if i expressed myself not good
im not requesting help i want to report a malfunction in requests on python 3.7.8 64bit on windows 64bit

the same code works on 32bit python but fails on 64bit python (same machine)
i doubled checked that requests & PySocks are the same on both installation and they are

i know how to use socks proxies with requests all other requests go through fine only this one throws an error on my 64bit python installation

also reproduction code is just a simple write up to easily represent the issue

**Comment by sigmavirus24** [comment]
@shinrax2 Requests and urllib3 are pure python libraries. They operate identically on 64bit machines as they do on 32bit machines and likewise with windows versus a *nix. If there's an underlying exception from `_ssl.c` (which is part of your Python installation) that isn't a bug in Requests. That's a bug in Python and you'll have better luck finding someone help you figure out how to fix that on StackOverflow.

**Comment by shinrax2** [comment]
@sigmavirus24 i just noticed my certifi package was corrupted on the 64bit installation im sorry for bothering
