### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by gelodefaultbrain** [psf/requests#5583]
Summary.

I am just trying to make a http request on a certain website, the thing is I am making requests for a lot of website and I am doing it in a for loop and that error on the title SOMETIMES shows up! YES SOMETIMES! there would be times that it occurs and not

What you expected.

Expect to have a good result

What happened instead.

This is what happened
![image](https://user-images.githubusercontent.com/55988471/92898416-8ab68580-f450-11ea-81c2-79b506bfbf29.png)

```python
#My Python version is 3.8.2

import requests
url = "somesite.com"
r = requests.get(url)


```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by gelodefaultbrain** [comment]
By the way this is my version of the requests library 

![image](https://user-images.githubusercontent.com/55988471/92898892-f0a30d00-f450-11ea-8343-896f0a32d528.png)

**Comment by gelodefaultbrain** [comment]
i have also read some fixes from other people here is the site

https://github.com/psf/requests/issues/4248

There is a guy here that has the solution but I was thinking that maybe the developers could have another which is of course the developers are the one that I am going to consider first...

Please I needed this badly Thank you!

**Comment by sigmavirus24** [comment]
Your server is sending chunked data without following the HTTP specification. Nothing here to be fixed as the actual error you're encountering is the Incomplete read exception at the bottom of your screenshot (which isn't friendly for future folks searching or using screen readers).

**Comment by gelodefaultbrain** [comment]
There is definitely need to be fixed I think cause some people experience this too... They have provided solutions on it I was just thinking if the devs can somehow make a way through this?

https://github.com/psf/requests/issues/4248

**Comment by sigmavirus24** [comment]
Nope. I'm a former dev and I can promise there's no solution to broken servers

**Comment by gelodefaultbrain** [comment]
Then thanks to this guy right here cause a random guy just fixed everything 

https://github.com/psf/requests/issues/4248

**Comment by nateprewitt** [comment]
To be clear, this isn't a universal fix. It will cause breakages elsewhere for valid use cases, so urllib3 can't implement this fix. I'm going to resolve this since it's not a defect in Requests but in the external server implementation.
