### ISSUE TITLE
[DOCS] Quickstart Cookies link doesn't exist

### ISSUE THREAD

**Issue by RomanKornev** [psf/requests#5585]
On https://requests.readthedocs.io/en/master/user/quickstart/ clicking on `Cookies` in `Table of Contents` does nothing. It doesn't link to anything. `Cookies` part is completely missing in documentation.

## Expected Result

`Cookies` documentation to be present in the quickstart guide as described in `Table of Contents`.
https://requests.readthedocs.io/en/master/user/quickstart/#cookies links to `Cookies` part of the `Quickstart`.

## Actual Result

`Cookies` part is completely missing in documentation.
Links to the beginning of the page or does nothing.

**Comment by TeenageMutantCoder** [comment]
I just tried clicking on the links that you posted to see what you were referring to, but they seem to work just fine. Both the "Cookies" link in the table of contents and the https://requests.readthedocs.io/en/master/user/quickstart/#cookies permalink work.

**Comment by Jsn2win** [comment]
> I just tried clicking on the links that you posted to see what you were referring to, but they seem to work just fine. Both the "Cookies" link in the table of contents and the https://requests.readthedocs.io/en/master/user/quickstart/#cookies permalink work.

**Comment by nateprewitt** [comment]
Hi @RomanKornev,

The anchor for "cookies" definitely exists in the page returned at https://requests.readthedocs.io/en/master/user/quickstart/#cookies. Beyond that anchor, this functionality is dictated by your browser and I'm unable to replicate the issue on any major browser. I'd ensure your browser is working correctly and perform any updates if needed.

**Comment by RomanKornev** [comment]
@nateprewitt Thanks for confirming that it works! 
I found the problem: it was the `uBlock Origin` Chrome extension. Seems that by default it was blocking Cookies content.
What I was seeing until I clicked `Disable cosmetic filtering on this site`:
![image](https://user-images.githubusercontent.com/5807561/93124704-b0eb5800-f6d2-11ea-9bab-17237d8a58dc.png)
