### ISSUE TITLE
Special characters getting replaced using `params` keywarg

### ISSUE THREAD

**Issue by ktoldham** [psf/requests#5586]
Special characters are getting replaced when sending them through the `params` kwarg. The same result occurs on mac and pc. Tested with the `get` and `post` methods.

## Expected Result

For the string to be added to the url as it was given to the requests module.

## Actual Result

Special characters getting replaced. Here are output some examples.

input: `email='kevin@test.com'`
output: `/cart?email=kevin%40test.com`

input: `email='kevin%test.com'`
output: `/cart?email=kevin%25test.com`

input: `email='kevin&test.com'`
output: `/cart?email=kevin%26test.com`

## Reproduction Steps

```python
import requests

url = url_factory()
params = {'email': 'kevin@test.com'}
response = session.post(url=url, params=params)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.1"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.10"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @ktoldham,

This is the correct behavior for URI queries. You can read the full specification in [RFC 3986 section 3.4](https://tools.ietf.org/html/rfc3986#section-3.4). Those characters are required to be percent encoded before sending them across the network.

If you *must* violate that for some reason, you can use the [PreparedRequest](https://requests.readthedocs.io/en/master/api/#requests.PreparedRequest) workflow to modify your final parameters before sending. We'd discourage this though and recommend fixing the recipient if you have control of the receiving service.

**Comment by ktoldham** [comment]
Ah, gotcha. Ok, I'll get in touch with my devs. Thanks for the quick answer!
