### ISSUE TITLE
Seems `requests.packages` is not installed, please install and try again!

### ISSUE THREAD

**Issue by sanswarn** [psf/requests#5588]
I am running idcssearch binaries that seems calling requests but somehow its not present in virtual python word. multiple times I tries uninstall and install but no results. 

[sswarnka@sswarnka-linux idcs-tools]$ python
Python 2.7.5 (default, Nov 27 2019, 09:57:45) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named request
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests-2.24.0-py2.7.egg/requests/__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3
>>> 

## System Information

    $ python -m requests.help
[sswarnka@sswarnka-linux idcs-tools]$ python -m requests.help
/usr/bin/python: No module named urllib3
[sswarnka@sswarnka-linux idcs-tools]$ 

[sswarnka@sswarnka-linux idcs-tools]$ pip3 freeze 
certifi==2020.6.20
chardet==3.0.4
freeze==3.0
idna==2.10
requests==2.24.0
six==1.15.0
urllib3==1.25.10
[sswarnka@sswarnka-linux idcs-tools]$ 

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by s104346** [comment]
Your `python` is Python2, but you are using `pip3`, the Python3 version of pip, to show your installed packages. Take a look at the output of `python -m pip freeze`.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
