### ISSUE TITLE
About proxy

### ISSUE THREAD

**Issue by JohnnyHardway** [psf/requests#5589]
Accodring to the document about proxy should like this:
proxies = {"http":"http://ip:port"},
but if i wrote like this :
proxies = {"http":"ip+port"}
some url also can got the response, but not all urls,
I think should ban like this  proxies = {"http":"ip:port"} so as to achieve unity.

**Comment by YashVadhadiya** [comment]
I think you should try like this (http://<address>:<port>) it is possibly work.

> Accodring to the document about proxy should like this:
> proxies = {"http":"[http://ip:port"}](http://ip:port%22%7D),
> but if i wrote like this :
> proxies = {"http":"ip+port"}
> some url also can got the response, but not all urls,
> I think should ban like this proxies = {"http":"ip:port"} so as to achieve unity.

I think you should try like this (http://<address>:<port>) it is possibly work.

**Comment by YashVadhadiya** [comment]
I think you should try like this (http://<address>:<port>) it is possibly work.

**Comment by YashVadhadiya** [comment]
I think you should try like this ( http://address : port )  it is possibly work.

**Comment by JohnnyHardway** [comment]
I know, is not the problem, the problem is
when u use {"http":"ip+port"}, some url can get response, i know this format is wrong, but it can use in some where, so suggest make this format become totaly wrong
