### ISSUE TITLE
  raise InvalidSchema("No connection adapters were found for {!r}".format(url)) pip._vendor.requests.exceptions.InvalidSchema: No connection adapters were found for 'javascript: void(0)'

### ISSUE THREAD

**Issue by souravsharan97** [psf/requests#5590]
import unittest
from datetime import datetime
from pip._vendor import requests
from selenium import webdriver

class Index(unittest.TestCase):
    @classmethod
    def setUpClass(cls) :
        chrome_options = webdriver.ChromeOptions()
        #chrome_options.add_argument('headless')
        #prefs = {"profile.default_content_setting_values.notifications": 2}
        #chrome_options.add_experimental_option("prefs", prefs)
        #chrome_options.add_argument("start-maximized")
        cls.driver = webdriver.Chrome(chrome_options=chrome_options,
                                      executable_path=r'/home/sharan/Desktop/chromedriver')
        cls.driver.maximize_window()

    def test_all_links_test(self):
        now = datetime.now()
        date_time = now.strftime("%m%d%Y%H%M%S")
        pageUrl = "https://www.amazon.in/dp/B01EU2M62S/"
        driver = self.driver
        driver.get(pageUrl)
        links = []
        elems = self.driver.find_elements_by_xpath("//a[@href]")
        for elem in elems:
            #href = [requests.head(elem.get_attribute("href"))]
            href = [elem.get_attribute("href")]
            page = requests.get(href)
            #print(elem.get_attribute('href'), href.status_code)
            print(page)
            links.append(href)
        file1 = open("/home/sharan/Desktop/flowace1/"+ date_time + ".xlsx", "x")
        file1.write("\n".join(links))
        file1.close()

    @classmethod
    # def tearDown(self):
    def tearDownClass(cls):
        cls.driver.close()
        print("jao")

if __name__== "main":
   # unittest.main(testRunner=HTMLTestRunner.HTMLTestRunner(output = "home/sharan/Desktop/Testing/Reports/"))
    unittest.main()
    #file1 = open("/home/sharan/Desktop/Testing/Reports/1.html", "x")
    #unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output=file1))

**Comment by nateprewitt** [comment]
Hi @souravsharan97,

There's a couple issues here. You're importing a very old version of requests from a package private vendoring in pip. This is a *very* bad idea for stability in your code. I'd recommend installing Requests and updating to the latest version. Secondly, you can't pass calls to javascript into Requests, as they are not http URIs. If you have further questions about usage, please open an issue on StackOverflow. Thanks!
