### ISSUE TITLE
multipart/form-data request preparation possible issues

### ISSUE THREAD

**Issue by karanveersp** [psf/requests#5591]
I've been trying to send a POST multipart/form-data request using the following function

```python
def upload_file(token, filepath, table_id):
    url = "https://h.app.wdesk.com/s/wdata/prep/api/v1/file"
    headers = {
        "Authorization": f"Bearer {token}",
    }
    files = {
        "file": open(filepath, "rb"),
        "tableId": (None, table_id)
    }
    resp = requests.post(url, headers=headers, files=files)
    print(resp.request.headers)
    return resp.json()
```

## Expected Result

Status 201 created JSON response.

## Actual Result

Status 400, with error message that contentType is missing from the request headers.
If `Content-Type` is added explicitly in the headers as `multipart/form-data` the response is a Status 500, unknown error.

Running the same request in NodeJS and with Postman don't produce these errors. 

## Reproduction Steps

N/A since invoking the API requires an auth token.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.2"
  },
  "platform": {
    "release": "5.4.0-47-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1010100f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by sethmlarson** [comment]
Try examining your request with Wireshark to see exactly what's getting sent over the wire compared to other HTTP clients. This likely isn't a defect with Requests.
