### ISSUE TITLE
My kanboard is locked with an error - Internal Error: Identifier "container" is not defined.

### ISSUE THREAD

**Issue by Jsn2win** [psf/requests#5592]
My kanboard is locked with an error - Internal Error: Identifier "container" is not defined.

__Originally posted by @plyaskin in https://github.com/CoMPaTech/kanboard_plugin-done_column_highlight/issues/1__

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
