### ISSUE TITLE
Setting SSLContext for Session or operation

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#5599]
The `certifi` library often runs into issues with domain certificates, but in the standard `urllib.request` library has no issue. 

If I set the context to use the certifi's file, I get the SSL error, 

```python
import ssl
import certifi
import requests.urllib as urlrq

resp = urlrq.urlopen(url="https://<web address>/rest/info?f=json", 
                                  context=ssl.create_default_context(cafile=certifi.where()))
```

if I use the standard library and set the context as follows:

```python
import ssl
import certifi
import requests.urllib as urlrq

resp = urlrq.urlopen(url="https://<web address>/rest/info?f=json", 
                                  context=ssl.SSLContext(ssl.PROTOCOL_TLSv1))
```

No SSL error.

How can I get requests to honor this `SSLContext`?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by achapkowski** [comment]
It's actually a usage question for the API, stackoverflow isn't the best place to get help.

**Comment by sigmavirus24** [comment]
It's a "How do I use this?" which is exactly the type of every `python-requests` question on StackOverflow

**Comment by achapkowski** [comment]
https://stackoverflow.com/questions/64063235/how-to-use-sslcontext-with-python-requests-library

**Comment by sethmlarson** [comment]
I left an answer on your question. Closing this now.
