### ISSUE TITLE
Exception instead of following 302 redirect

### ISSUE THREAD

**Issue by jozo** [psf/requests#5602]
Requests throw an exception instead of following 302 redirect. Curl returns a response and browsers follow redirect.

## Expected Result

Requests follow redirect

## Actual Result

Exceptions is thrown:
```
ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8a70874e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## Reproduction Steps

```python
import requests
requests.get("http://localhost:8000/")
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.5"
  },
  "platform": {
    "release": "4.19.76-linuxkit",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.10"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

> [Errno 111] Connection refused

Implies the server refused your connection. This isn't a Requests issue
