### ISSUE TITLE
How can I create requests without actually executing them ( to get instance )

### ISSUE THREAD

**Issue by realsirjoe** [psf/requests#5603]
I want to do this in order to log the requests myself, in order to reproduce them when an error is thrown, for better debugging.

If there is no way to do so how can I log the requests ( all http requests: GET, POST, PUT,..) preferably as cURL string

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
