### ISSUE TITLE
BUG "except requests.HTTPError as e:" at error 500 doesnt work

### ISSUE THREAD

**Issue by marcdubois71450** [psf/requests#5606]
Hi! 
This expect doesnt work with error 500

`except requests.HTTPError as e:`

Why did you do that? Do you like the difficulty? 

It should be noted that the success of the call to r.json() does not indicate the success of the response. Some servers may return a JSON object in a failed response (e.g. error details with HTTP 500). Such JSON will be decoded and returned. To check that a request is successful, use r.raise_for_status() or check r.status_code is what you expect.

So what's the point?  `except requests.HTTPError as e:`

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
