### ISSUE TITLE
requests.get(url, proxies=proxy_list), Failed to parse if username is Email

### ISSUE THREAD

**Issue by sandman6578** [psf/requests#5609]
Hey at all.

I have an Issue with request.get to use proxies function if the username for the proxy server contains an @ or some "unsafe characters".

## Expected Result

To get successfully logged in to my proxy and get the IP from proxy server

## Actual Result

Failed to parse: https://username@email.com:password@proxy.com

## Reproduction Steps

```python
import requests
proxys = {
        'http': "http://username@email.com:password@proxy.com,
        'https': "https://username@email.com:password@proxy.com,
    }
requests.get("https://www.wieistmeineip.at/", proxies=proxys)
```

## System Information

    $ python -m requests.help

{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "3.1"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010107f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010108f"
  },
  "urllib3": {
    "version": "1.25.10"
  },
  "using_pyopenssl": true
}

**Comment by sigmavirus24** [comment]
In RFC 3986 `@` is exclusively reserved for separating the user info from the hostname in the authority section (`authority = userinfo @ host : port`) so you should replace `@` with `%40`. This has been covered in open and closed issues and is likely well documented on stackoverflow.
