### ISSUE TITLE
Docs and Readme: [GitHub] Deprecation Notice

### ISSUE THREAD

**Issue by giuliohome** [psf/requests#5615]
I've followed the main example you present at the start of your Docs

```python
>>> r = requests.get('https://api.github.com/user', auth=('user', 'pass'))
>>> r.status_code
200
>>> r.headers['content-type']
'application/json; charset=utf8'
>>> r.encoding
'utf-8'
>>> r.text
'{"type":"User"...'
>>> r.json()
{'private_gists': 419, 'total_private_repos': 77, ...}
```
and I've received the following **[GitHub] Deprecation Notice**:

>On October 6th, 2020 at 11:19 (UTC) you used a password to access an endpoint through the GitHub API using python-requests/2.18.4:
>
>https://api.github.com/user
>
>Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
>
>Thanks,
>The GitHub Team

**Comment by sigmavirus24** [comment]
The example code is not broken. GitHub is just changing their policies around using basic authentication. This could be changed to something else easily. GitHub's deprecation is not a bug in our project though.
