### ISSUE TITLE
RESPONSE 500 on Heroku

### ISSUE THREAD

**Issue by krutoypan3** [psf/requests#5616]
On Heroku and localhost 
![image](https://user-images.githubusercontent.com/65137814/95205064-8aaa6b00-07ed-11eb-89a9-2b48ffaec2d6.png)
![image](https://user-images.githubusercontent.com/65137814/95205071-8da55b80-07ed-11eb-9c75-264f90f12947.png)

Response 200 (on localhost) its good
Response 500 (on Heroku) its BAD. How fix it?

url = 'https://animego.org/anime/filter/status-is-released/apply?&direction=desc&page='
headers = {
                'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36,', 'Origin': 'http://example.com', 'Referer': 'http://example.com/some_page'}
            response = requests.request("get", url, headers=headers)
            print(response)

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
