### ISSUE TITLE
Keep-alive after pickling a session

### ISSUE THREAD

**Issue by jsmedmar** [psf/requests#5618]
I'm trying to implement TLS session resumption for my command line application.

This issue https://github.com/psf/requests/issues/2522 explains how to pickle a `requests.session`. 

However, the TLS handshake is repeated when I rerun my application, loading a pickled session.

I was wondering what I'm I missing?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
