### ISSUE TITLE
README mentions Python 2.7 support

### ISSUE THREAD

**Issue by Helveg** [psf/requests#5619]
_(Bug template was not applicable)_

The README states that requests officially supports Python 2.7. Shouldn't that support be dropped now that Python 2 has been sunset?

**Comment by nateprewitt** [comment]
Hi @Helveg, the documentation is correct. There are still a number of tools that use Requests and require Python 2.7 support, including pip. Our support may change as we get into 2021 but we'll provide advanced notification on that.
