### ISSUE TITLE
Requests library (python) with http proxies

### ISSUE THREAD

**Issue by Blakeboy02** [psf/requests#5623]
Hello I have recently been attempting to use http proxies for something im making however when I use http proxies it instead uses my ip but when I use https proxies it actually uses the proxies ip. Slightly confused about this I do not know if there is something stopping this from working, thanks a lot for reading.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
