### ISSUE TITLE
Preparing request with Session obj

### ISSUE THREAD

**Issue by ShurayukiHime** [psf/requests#5625]
Hi,
this is actually a question more than an issue.

```
req = requests.Request(method=None, url=url, cookies=self.cookies)
prepped = self.session.prepare_request(req)
```

raises error because method is None, and this is actually because of `method.upper()`. [Code here](https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/sessions.py#L457) -- specifically _AttributeError: 'NoneType' object has no attribute 'upper'_.
(suppose I have an object incapsulating a `session = requests.Session()`; this explains why `self.session` in the above snippet)

On the other hand, 
```
req = requests.Request(method=None, url=url, cookies=self.cookies)
prepped = req.prepare()
```

works fine. In this second case, the same `prepare()` method is called ([code here](https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/models.py#L254)).

I don't understand if there is a reason for requests made with sessions not to have None method, or if this is a bug.

Thank you!

**Comment by sigmavirus24** [comment]
I'd say it's a bug that `req.prepare()` doesn't raise an exception for a `None` method. It shouldn't raise an `AttributeError` but we can't swap that out for something more reasonable at this point or break `req.prepare()`.
