### ISSUE TITLE
Inconsistent host behaviour when request is redirected

### ISSUE THREAD

**Issue by javixeneize** [psf/requests#5626]
Summary.

Hi

Im trying to implement a script to test a host header injection. It is quite simple, it sends a valid request to an endpoint, but modifies the Host header injecting a fake domain (evil.com)

When the request is not a redirection, this header is ignored, and the request reaches the original url, however, if the request ends in a redirection (302), and you enable redirections (allow_redirects=True), this redirection is done to the host specified in the header (evil.com)

To summarise:

if i send a request to test.com/blah with Host: evil.com and it returns a 200, the requests goes to test.com/blah

if i send a request to test.com/blah with Host: evil.com and it returns a 302 that redirects to test.com/redirected_site, then, i see the first request going to test.com/blah with a 302, but the redirection, instead of going to test.com/redirected_site, goes to evil.com/redirected_site

So it looks like this redirection is using the host header instead of taking the url generated by the 302 request

Thanks

**Comment by sigmavirus24** [comment]
This isn't behaviour in Requests. We don't look at the `Host` header at all while [handling redirects](https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/sessions.py#L96).

**Comment by javixeneize** [comment]
Hi

I have written a quick example for that

import requests

headers = {}
r = requests.get('https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=11&ct=1602619024&rver=6.0.5286.0&wp=MBI_SSL&wreply=https:%2F%2fwww.bing.com%2Fsecure%2FPassport.aspx%3Fpopup%3D1%26ssl%3D1&lc=2057&id=264960&checkda=1', headers = headers, allow_redirects=True)
print (r.content)
print (r.status_code)
print (r.history)


This prints

b'<html><head><title>Bing</title></head><body>Loading...<script type="text/javascript">//<![CDATA[\nvar _w = window; var o = _w.opener; var mainWindow; (mainWindow = o) || (mainWindow = _w.parent); if (mainWindow) {mainWindow.sj_evt && mainWindow.sj_evt.fire("wl:cancel"); };if (o) _w.close();;\n//]]></script></body></html>'
200
[<Response [302]>]


If i inject a host:

import requests

headers = {'Host': 'test.com'}
r = requests.get('https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=11&ct=1602619024&rver=6.0.5286.0&wp=MBI_SSL&wreply=https:%2F%2fwww.bing.com%2Fsecure%2FPassport.aspx%3Fpopup%3D1%26ssl%3D1&lc=2057&id=264960&checkda=1', headers = headers, allow_redirects=True)
print (r.content)
print (r.status_code)
print (r.history)

Now i have:

b"<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>00geGXwAAAADwzgMcscuaQ5OB5okcfVVvTFRTRURHRTEzMTcARWRnZQ=="
400
[<Response [302]>]


If i try with any url that returns a 200 instead of a 302:

import requests

headers = {'Host': 'test.com'}
r = requests.get('https://login.live.com/', headers = headers, allow_redirects=True)
print (r.content)
print (r.status_code)
print (r.history)


b'< blahblahblah'
200
[]

Can you have another look at this please?

Thanks
