### ISSUE TITLE
Is it possible to support ftp  transfer ?

### ISSUE THREAD

**Issue by eaglegai** [psf/requests#5627]
I see 'class HTTPAdapter' in adapters.py，if it's possible to deal with ftp requests?
Looking forward to your reply ，thanks！

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
