### ISSUE TITLE
content-type: media subtypes of "text" using ISO-8859-1 as default charset may be inappropriate

### ISSUE THREAD

**Issue by stanpao** [psf/requests#5629]
https://github.com/psf/requests/blob/143150233162d609330941ec2aacde5ed4caa510/requests/utils.py#L497
From [RFC 2616](https://tools.ietf.org/html/rfc2616#section-3.7.1):  
   When no explicit charset parameter is provided by the sender, media subtypes of the "text"
   type are defined to have a default charset value of "ISO-8859-1" when received via HTTP. 

However, from [RFC7231](https://tools.ietf.org/html/rfc7231#appendix-B):
  The default charset of ISO-8859-1 for text media types has been removed;

Actually, if requests uses the default charset of ISO-8859-1, the property text of response will  always lose the efficiency of chardet and cause messy code problem.
I think these lines should be deleted.

**Comment by sigmavirus24** [comment]
It's a backwards incompatible change.

In the future, please search **closed and** open issues before creating new ones that are duplicates.
