### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by RajehTXD** [psf/requests#5631]
I have tried multiple things from removing python 2.7 to installing last version. 
I tried in multiple ways installing using PIP.
I keep getting this 'ModuleNotFoundError'
pylint says that it is unable to import the package.
My error
`Exception has occurred: ModuleNotFoundError
No module named 'requests'
  File "file-hidden", line 1, in <module>
    import requests`

**Comment by purpshell** [comment]
Also everything is satisfied if i try reinstalling in pip

**Comment by purpshell** [comment]
I just realized that I am using the windows 10 version of python 3.8. Installing the normal version to see if that is the issue

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
