### ISSUE TITLE
Segmentation Fault - Core Dumped

### ISSUE THREAD

**Issue by codinghedgehog-python** [psf/requests#5634]
Hi, since I'm not 100% sure whether it's a bug or not I'm putting it under "Request for Help".
I looked up what the error actually means and apparently my program attempted to access restricted part of RAM.
You go figure.

I had to use Python debugger to find out that the module throws seg fault on the method call.

Anyway, I'd appreciated any feedback on the below

Request I'm sending:

   ```
 data = {
            'first_name': self.first_name,
            'middle_name': self.middle_name,
            'last_name': self.last_name,
            'new_comment': self.comment
        }
        files = {'image_file1': open(self.file_path1, 'rb')}
        #print(data)
        #pdb.set_trace()
        response = requests.post('http://localhost/users/add', json=data, files=files)
        if response.status_code == 201:
            print('ADDED !')
        else:
            print(response)
```

output from debugger:

```
/home/mark/front_end_android/venv/lib/python3.7/site-packages/requests/api.py(119)post()
-> return request('post', url, data=data, json=json, **kwargs)

Segmentation fault (core dumped)
```

**Comment by sigmavirus24** [comment]
It's likely this is coming from a lower-level library that's using C but at first blush, you can't (and this is documented) combine `json=` and `files=`. So I'm sure the JSON library you're using is doing something to cause this with the open file you're using.

Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here. (Using Stackoverflow is also well documented in this issue template)
