### ISSUE TITLE
Ocassionally getting temporary failure in name resolution

### ISSUE THREAD

**Issue by priyanshujain** [psf/requests#5635]
I am getting name resolution error with requests occasionally, it's happening approx once in 10 requests.

My stackoverflow question https://stackoverflow.com/questions/64357458/failed-to-establish-a-new-connection-errno-3-temporary-failure-in-name-resol

**Comment by priyanshujain** [comment]
@sigmavirus24 Can you help me this issue?

**Comment by sigmavirus24** [comment]
You asked on StackOverflow which is the correct place. For what it's worth, I maintain systems making thousands of requests per minute with requests that don't have this issue. And a DNS issue is firmly outside of our control given that we use the standard library to query DNS.

**Comment by priyanshujain** [comment]
@sigmavirus24 Thanks for the response. I will check my DNS server config.
