### ISSUE TITLE
Prepared Post Requests Timeout after changing body

### ISSUE THREAD

**Issue by VainlyStrain** [psf/requests#5636]
I am trying to do a POST request using the requests library. However, for this specific request, it is important that the POST data stay unaltered (e.g. do not get URL-encoded).

I have seen in the documentation under "advanced usage" that you can do PreparedRequests. So, I did as shown in the docs, however it does not yield results as expected.

## Expected Result

We should get a response to our request.

## Actual Result

Prepared POST requests with changed body timeout.

## Reproduction Steps

```
python
import requests
s = requests.session()
data = {"file": "../p1.png"}
req = requests.Request(method='POST', url="http://localhost:8000", data=data)
prep = s.prepare_request(req)
prep.body = unquote(prep.body) #from urllib.parse, however the behavior is reproducible with any string, e.g. prep.body = "1234"
r = s.send(prep, timeout=timeout)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.8"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.6"
  },
  "platform": {
    "release": "5.8.15-201.fc32.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010104f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": true
}
```

Tested on local php server. PHP 7.4.11 (cli) (built: Sep 29 2020 10:17:06) ( NTS )

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by VainlyStrain** [comment]
Upgraded some packages, but issue still persists:

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.9"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.6"
  },
  "platform": {
    "release": "5.8.15-201.fc32.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010106f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

You also likely should introspect the generated headers for clues.
