### ISSUE TITLE
Ability to specify default timeout value in session object

### ISSUE THREAD

**Issue by mdavis-xyz** [psf/requests#5637]
> Requests is not accepting feature requests at this time.

I've just read [this section](https://requests.readthedocs.io/en/latest/dev/contributing/#feature-requests), and I believe my feature request is still worthwhile and simple, and I'm happy to write it myself. I'm just [getting early feedback](https://requests.readthedocs.io/en/latest/dev/contributing/#get-early-feedback).

I would like the ability to set a default timeout value for a session object, rather than passing in the same argument for every single call.

Existing usage:

```
s = requests.Session()
s.get(url_a, timeout=10)
s.get(url_b, timeout=10)
```

Proposed Usage:

```
s = requests.Session()
s.timeout = 10 # seconds
s.get(url_a)
s.get(url_b)
```

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
