### ISSUE TITLE
Session.send() does not check for environment variables like proxy

### ISSUE THREAD

**Issue by spreiter** [psf/requests#5642]
I was following the mechanism of the usage of the PreparedRequest class.
But the `send()` does not call the `merge_environment_settings()` of the session automatically.

## Expected Result

So it would be helpful to enable this via an option or at least update the documentation, that it is necessary to call the `merge_environment_settings()` manually.

## Actual Result

It results in a ConnectionError.

## Reproduction Steps

using Python 3.6:
```
>>> import requests
>>> req = requests.Request('GET', 'https://httpbin.org/get')
>>> r = req.prepare()
>>> r
<PreparedRequest [GET]>

>>> s = requests.Session()
>>> s.send(r)
<Response [200]>
```

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.8"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.5"
  }, 
  "platform": {
    "release": "3.10.0-1062.9.1.el7.x86_64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.21.0"
  }, 
  "system_ssl": {
    "version": "100020bf"
  }, 
  "urllib3": {
    "version": "1.24.1"
  }, 
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
This is what `r = s.prepare(req)` is for and it's documented as such
