### ISSUE TITLE
PyPI page formatting

### ISSUE THREAD

**Issue by pedro-w** [psf/requests#5644]
Sorry if this is the wrong place to report but the 'Project Description' for your entry on the PyPI site looks all mixed up with formatting and raw HTML tags.
https://pypi.org/project/requests/

**Comment by sethmlarson** [comment]
We're aware of the issue. Please read [closed issues](https://github.com/psf/requests/issues/5601) before opening new ones.

**Comment by pedro-w** [comment]
Thanks. Not easy if you close issues without fixing them.

**Comment by sethmlarson** [comment]
@pedro-w There's nothing left for us to fix, it's fixed in master and on the next release to PyPI there will be no issue.
