### ISSUE TITLE
Unable to turn off Keep-Alive

### ISSUE THREAD

**Issue by abitrolly** [psf/requests#5646]
Documentation doesn't specify how to turn off Keep-Alive
https://requests.readthedocs.io/en/latest/user/advanced/#keep-alive

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by abitrolly** [comment]
I thought I searched. My bad. The duplicate is #4913. However, no answer was given and no docs updated.

**Comment by sigmavirus24** [comment]
Turning off keep-alive means closing the connection. So set a session default for the `Connection` header of `close`. The server will close the connection and respects what the server does.

**Comment by abitrolly** [comment]
@sigmavirus24 how does it look in code?

I try to wait until a container is up and turning off Keep-Alive is the last thing I left to try. I start container on Fedora with port mapping that has no listening server inside the container.
```
$ podman run -d -p 9990 -it bash
```

The code below should timeout in 2 seconds. Instead if hangs indefinitely. At least more than a few minutes. I can not close the connection, because it hangs at `s.head()`.
```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
from requests.packages.urllib3.util import Timeout

with requests.Session() as s:
    retry = Retry(connect=3, backoff_factor=0.5)
    adapter = HTTPAdapter(max_retries=retry)
    s.mount('http://', adapter)
    s.mount('https://', adapter)
    r = s.head('http://localhost:9990', timeout=Timeout(2), stream=False)
    print(r)
```

requests 2.24.0 on Python 3.9

**Comment by sigmavirus24** [comment]
`s.headers["Connection"] = "close"`
