### ISSUE TITLE
HEAD Request never returns

### ISSUE THREAD

**Issue by cstayyab** [psf/requests#5648]
Summary.
When used `requests.head` with `url='https://mega.nz'` is stuck forever.
## Expected Result

Either a response or a Timeout error or any exception.

## Actual Result

The function never returns.

## Reproduction Steps

```python
import requests
r = requests.head("https://mega.nz")
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.5"
  },
  "platform": {
    "release": "4.19.104-microsoft-standard",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": false
}
```

I have also verified this on [Google Colab](https://colab.research.google.com)

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by cstayyab** [comment]
@sigmavirus24  The purpose of filing the issue was that there should a timeout mechanism *inside requests library* to prevent these types of events from happening.

**Comment by sethmlarson** [comment]
@cstayyab [Try reading the documentation before asking questions](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts).
