### ISSUE TITLE
Requests 2.25.0 issue

### ISSUE THREAD

**Issue by mchristopher** [psf/requests#5655]
## Summary.

Our CI suite just ran and failed with the latest release of requests 2.25.0. Nothing in our code has changed aside from the version of requests installed.

## What you expected.

Our CI tests to pass as normal.

## What happened instead.

You can see the full test run on https://github.com/panoramichq/panoramic-cli/runs/1387129299?check_suite_focus=true for more details, but the important part is we received the following import error:

```
________ ERROR collecting tests/panoramic/cli/test_supported_version.py ________
  ImportError while importing test module '/home/runner/work/panoramic-cli/panoramic-cli/tests/panoramic/cli/test_supported_version.py'.
  Hint: make sure your test modules/packages have valid Python names.
  Traceback:
  .tox/py36/lib/python3.6/site-packages/responses.py:27: in <module>
      from requests.packages.urllib3.connection import HTTPHeaderDict
  E   ImportError: cannot import name 'HTTPHeaderDict'
  
  During handling of the above exception, another exception occurred:
  /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py:126: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  tests/panoramic/cli/test_supported_version.py:1: in <module>
      import responses
  .tox/py36/lib/python3.6/site-packages/responses.py:29: in <module>
      from urllib3.connection import HTTPHeaderDict
  E   ImportError: cannot import name 'HTTPHeaderDict'
```

**Comment by nateprewitt** [comment]
Hi @mchristopher, this was a change in urllib3 that was reverted in 1.26.1. If you update urllib3 as well, you should stop seeing this exception.

**Comment by mchristopher** [comment]
That fixed it, but I'm not sure why pip didn't automatically pick up the correct dependencies. It may have been an issue with caches on the pypi side... 🤷 

Either way, fixed now. Thanks for the quick response!
