### ISSUE TITLE
How to requests without removing the ./ or ../ in Python 3

### ISSUE THREAD

**Issue by shelld3v** [psf/requests#5656]
Hi, if you do this:

```python
requests.get('http://127.0.0.1/hello/../blah')
```

Your server will receive:

```
GET /blah HTTP/1.1
```

But what I want here is to send the request with the dot-slash:

```
GET hello/../blah HTTP/1.1
```

In python2, I can use this (it worked in my test):

```python
import urllib

u = urllib.quote('http://127.0.0.1/./foo/../bar', safe=':/.')
```

But in python 3, it does not work for some reasons:

```python
import urllib.parse

u = urllib.parse.quote('http://127.0.0.1/./foo/../bar', safe=':/.')
```

```
GET /bar HTTP/1.1
```

How can I solve this?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by shelld3v** [comment]
Hey, I didn't see any answer that can solve this question on StackOverflow. The solutions are only for python 2. That is why I am asking here

**Comment by sigmavirus24** [comment]
That's why you ask on StackOverflow or search open and closed issues before opening new ones. See also #5324 and #5289.
