### ISSUE TITLE
a post request body has one key corresponds to multiple values。

### ISSUE THREAD

**Issue by mabeijing** [psf/requests#5669]
requests version = 2.22.0
I had some trouble sending a post request。
headers = {'Content-Type': 'application/x-www-form-urlencoded'}，
the body_data has a key corresponds to multiple values，

![12231BC6-03B4-4D4D-AE56-36CD5F9D08B4](https://user-images.githubusercontent.com/48149977/100365628-b8b46a80-303a-11eb-833c-67971bc4a01c.png)

my scripts
![9207E0D4-4033-4101-BFF7-3E2D75FC4BB2](https://user-images.githubusercontent.com/48149977/100366431-c74f5180-303b-11eb-9784-ab30a2590ae6.png)

data = cargo_info.update(important_info)
requests.post(url, data=data, headers=headers)

the result  takes the cargo_info['cargoName'] as one good('["无烟煤", "铝合金"]')  not two.

and I don't know what to do。please help me。thinks

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
