### ISSUE TITLE
Offline installation in python2.7

### ISSUE THREAD

**Issue by heart-scalpel** [psf/requests#5674]
Thank you for taking the time to review this request,I want install this package , but I use python2.7, I can't install urllib3,So what can I do to finish this installation
requires = [
    'chardet>=3.0.2,<4',
    'idna>=2.5,<3',
    'urllib3>=1.21.1,<1.26,!=1.25.0,!=1.25.1',
    'certifi>=2017.4.17'

]

**Comment by heart-scalpel** [comment]
I need work in python2.7, I can't change the version.(cry)

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
