### ISSUE TITLE
request defaulting to GET if url missing ending '/' on rasberry pi

### ISSUE THREAD

**Issue by newnativeabq** [psf/requests#5678]
Summary.

If I send a POST request with http://...., the request is sent as GET and the body is stripped.  If I add the ending '/' http://.../, the request sends as expected.

## Expected Result

requests.request("POST", **kwargs) sends a POST request regardless of URL.   Same for requests.POST(url, **kwargs)

## Actual Result

```python
url = "http://192.168.1.37:8080/api
r = requests.request(url, data={'sid':'test', 'value':911})
# Yields GET request being sent to endpoint

url = "http://192.168.1.37:8080/api/
r = requests.request(url, data={'sid':'test', 'value':911})
# Yields POST request being sent to endpoint
```

## Reproduction Steps
On Rasberry Pi 4, rasbian, using pipenv (requests installed via: pipenv install requests)

```python
import requests
url = "http://192.168.1.37:8080/api
r = requests.request(url, data={'sid':'test', 'value':911})
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "5.4.72-v7l+",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.26.2"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
Sounds like the API you're hitting is returning a redirect that for compatibility reasons transforms POST to GET. Try the request with redirects=False and inspect the status code to verify this.

If you control the API I recommend using 307/308 redirect status codes.

**Comment by newnativeabq** [comment]
You nailed it.  If I use allow_redirects=False in the request, the endpoint doesn't process the request at all.  I'll look into adding redirect catches.  

Thanks for helping guide my search further.  Found someone with practically the exact problem: https://rtfm.co.ua/en/http-redirects-post-and-get-requests-and-lost-data/ (python app, golang webserver).
