### ISSUE TITLE
[DOC] Misleading Statement in Chinese Translation of Documentation

### ISSUE THREAD

**Issue by zhan-zhang** [psf/requests#5679]
In the first line of the [Chinese translation](https://requests.readthedocs.io/zh_CN/latest/#id3), the translator used a statement as:

> "Requests 唯一的一个非转基因的 Python HTTP 库，人类可以安全享用。"

which means:

> "Requests is the only non-genetically-modified HTTP library in Python, safe for human beings to use"

This statement is scientifically misleading with the improper metaphor and apparently diverged from the English version 

> "Requests is an elegant and simple HTTP library for Python, built for human beings."

**Comment by zhan-zhang** [comment]
I'd be happy to open a PR to make it match the English version but failed to find the file that contains the translation - can anyone give me a pointer?

**Comment by sigmavirus24** [comment]
https://github.com/requests/requests-docs-cn is the repository with that translation. It's from an older version of the english docs
