### ISSUE TITLE
Broken sponsor link

### ISSUE THREAD

**Issue by shelld3v** [psf/requests#5683]
Summary.

## Expected Result

I and others can sponsor your team for this awesome project

## Actual Result

I can't because the sponsor link has been broken

## Reproduction Steps

N/A

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.6"
  },
  "platform": {
    "release": "4.4.0-18362-Microsoft",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.0"
  },
  "system_ssl": {
    "version": "1010108f"
  },
  "urllib3": {
    "version": "1.24.3"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
Hi there,

Thanks for bringing this to our attention. Unfortunately, the folks who maintain this project don't control that form. Supporting the PSF (especially during the Q4 drive right now: https://www.python.org/psf/donations/2020-q42020-drive/ ) will undoubtedly benefit this project.

Cheers,
Ian

cc @ewdurbin in the event you know what's up with the form link

**Comment by ewdurbin** [comment]
Thanks for this notification @shelld3v, I've opened a PR at #5684 to update with the new link after the PSF relaunched our sponsorship program.
