### ISSUE TITLE
Support Chardet version 4

### ISSUE THREAD

**Issue by dwt** [psf/requests#5690]
It was released yesterday: https://github.com/chardet/chardet/releases and I would like to use it together with requests.

**Comment by bignose-debian** [comment]
Someone will need to investigate how to test compatibility of Requests with the new `chardet` version.

**Comment by mishankov** [comment]
PR for this is already in progress 
https://github.com/psf/requests/pull/5688

**Comment by nateprewitt** [comment]
#5688 is merged. It should be available in the next release.
