### ISSUE TITLE
BUG REPORT: 2.25.1 breaks SSL for proxy connections. Reverting back to 2.24.0 fixes issue.

### ISSUE THREAD

**Issue by vgoklani** [psf/requests#5703]
Using requests 2.25.1:

		session = requests.session()
		session.proxies.update(proxies_dict)

should setup connections over our proxy server. 

Unfortunately this is what we see:

    SSLError: HTTPSConnectionPool(host='api.xyz.com', port=443): Max retries exceeded with url: /my/url (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))

The error disappears when reverting back to 2.24.0

Please help!

thanks 👍

**Comment by vanHoi** [comment]
I guess this urllib3 bug is related: https://github.com/urllib3/urllib3/issues/2075
Since requests 2.25.1 urllib 1.16 is used, which fixed a bug regarding proxies and https connections.

The 'solution' posted there fixed the issue for me.
