### ISSUE TITLE
Documentation bug - missing cookies documentation

### ISSUE THREAD

**Issue by ascopes** [psf/requests#5704]
On the current latest documentation, there is a `cookies` link under the `quickstart` option.

![image](https://user-images.githubusercontent.com/73482956/102895815-4d08c600-445d-11eb-8ab5-fa98620efc85.png)

We can see that this section should be displayed between `Response Headers` and `Redirection History`.

![image](https://user-images.githubusercontent.com/73482956/102895893-76295680-445d-11eb-996a-edf5dd6dcebb.png)

This section does not currently exist, and the link in the sidebar list is dead - clicking it does nothing.

Is this section missing, or should this link be removed?

**Comment by ghost** [comment]
This section is missing!

**Comment by ascopes** [comment]
Do we have a template for what information we would want to put in here? I would happily put up a PR if so.

**Comment by baodrate** [comment]
The `Cookies` section under `Developer Interface` is missing as well

**Comment by nateprewitt** [comment]
What domain are you accessing the documentation at? Both sections appear at:

https://requests.readthedocs.io/en/master/
https://requests.readthedocs.io/en/master/user/quickstart/#cookies
https://requests.readthedocs.io/en/master/api/#cookies

They are also present in the source files under the docs in this repository. 

Of those affected, how many are using 3rd party browser extensions? Is it possible this content is being removed client side?

**Comment by ascopes** [comment]
Looks like the problem I originally reported is fixed now, and I can see it at the links you gave! Perhaps GitHub was serving an outdated cache at the time?

I am happy to close this, but will leave it for you guys to decide since it sounds like some other people might be having issues too.

Thanks for getting back to me.

**Comment by sigmavirus24** [comment]
> Looks like the problem I originally reported is fixed now

Nothing changed
