### ISSUE TITLE
Can requests work with file:/// urls?

### ISSUE THREAD

**Issue by xcodz-dot** [psf/requests#5708]
for example my application uses requests for downloading some special data. i want that to be compatible with `file:///` type urls while also supporting `http://`. does requests have that ability builtin or not?

Also if you know a work around please help me

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
