### ISSUE TITLE
PUT call to unify does not work, curl call does

### ISSUE THREAD

**Issue by pverhoye** [psf/requests#5713]
Hi all!

Best wishes (first things first!)

I want to enable/disable a PoE port on my UniFi switch. For this I aim using Python 3.9.1 (first time) with the following code:

```
import requests
import json
import sys
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

gateway = {"ip": "MYSERVER.COM", "port": "8443"}
headers = {"Accept": "application/json", "Content-Type": "application/json"}

login_url = f"https://{gateway['ip']}:{gateway['port']}/api/login"
login_data = {
    "username": "MYUSERNAME",
    "password": "MYPASSWORD"
}

session = requests.Session()
login_response = session.post(login_url, headers=headers, data=json.dumps(login_data), verify=False)

if (login_response.status_code == 200):
    poe_url = f"https://{gateway['ip']}:{gateway['port']}/api/s/default/rest/device/MYDEVICEID"
    json_poe_state_off = '{"port_overrides": [{"port_idx": 6, "portconf_id": "MYPROFILE2"}]}'
    post_response = session.put(poe_url, headers=headers, data=json.dumps(json_poe_state_off))   
    print('Response HTTP Request {request}'.format(request=post_response.request ))
else:
    print("Login failed")
```

The login works (I get the 2 security cookies and tried them in Paw (a macOS REST API client) to see if these were ok)) but the second call, the. PUT, returns OK but noting happens.
Before I've done this in Python, I tried all my calls in Paw first and there it works. I tried everything in bash with curl and there it works too. So I am a bit at a loss here.

Anyone has an idea?

Thank you for your time!

Best regards!
Peter

**Comment by sethmlarson** [comment]
It's likely your device is being super picky about how the HTTP request looks.

Try using Wireshark to capture the exact bytes / headers that are being sent by Requests and curl and compare them. If you aren't able to discern a difference attach the output/.pcap files here and we can maybe lend an eye. Without this information it'll be tough to figure out what's causing this.

**Comment by pverhoye** [comment]
Hi Seth!
Thanks for your hint! I tried with Wireshark and saw indeed that the payload was different. The culprit was the json.dumps function which encoded the string by putting a backslash in front of each double quote.
It works now!

Thanks!
