### ISSUE TITLE
Old Dependencies

### ISSUE THREAD

**Issue by gtoph** [psf/requests#5719]
Just wondering why the dependencies haven't been updated for a while now.   Seems to be requiring a pretty old version of IDNA

**requests 2.25.1 requires idna<3,>=2.5**

Ran it with the latest 3.1 and still seems to work fine.  Wonder if the older version is a real requirement?

**Comment by nateprewitt** [comment]
Hi @gtoph,

idna 3.0 was only released 2 weeks ago. We've restricted version caps at major version bumps to avoid pulling in breaking API changes without testing. There's currently a PR (#5711) open discussing this, so we'll close this in favor of that. Thanks.

**Comment by gtoph** [comment]
No worries, it's just my ocd to have the latest versions ;)
