### ISSUE TITLE
Requests is using dependencies with copyleft licenses

### ISSUE THREAD

**Issue by farooquiyasir** [psf/requests#5720]
We are using request's latest version but it uses certifi as depedency which is under MPL 2.0 license. This makes certifi a plugin with a copyleft license. Our company does not want to use any copyleft license plugin. I know that requests added certifi as separate plugin dependency after v 2.16 and onwards but I am not sure if its okay to use v2.15 because a lot of other bugs would also be fixed in latest versions. Is there a way we can exclude certifi depedency to avoid using a copyleft license plugin?

**Comment by sethmlarson** [comment]
The MPL-licensed code included in certifi is not modified so doesn't trigger the MPL license terms. Please search for existing closed issues before opening a new one.
