### ISSUE TITLE
requests library code walkthrough

### ISSUE THREAD

**Issue by samrohon** [psf/requests#5721]
Wannabe opensource contributor and intermediate python developer here. I am wondering if any contributors of this  library has done or could do a code walkthrough video ?
- It is difficult for newbies to undestand the code base from a bigger perspective, what are the patterns used, design decisions made etc merely going throught the code
- Most of the time there is a lot of context that is required by the reader, around why code is written the way it is - which cannot be understood simply reading the code
- There are a lot of tutorials on how to use the repo functionality, but I could not find any on the implementation details and the design.
- This library has  been reccomended by many as  a good case study of readable python code. It would highly benifit the community if there is a free-form walkthrough of the code base - which gives a good intro to the internal of the library - and give a bigger picture on how a successful python opensource project is structured and run.

**Comment by sigmavirus24** [comment]
>     * This library has  been reccomended by many as  a good case study of readable python code.

As a maintainer for several years, I've always disagreed with this notion. That said, those folks would be the people who should be doing the walk-through. I would never feel honest giving such a walk through, nor does anyone directly involved in the project have the sufficient free time to write, record, edit, and post such a walk through (or series of such)

**Comment by ujjwaltwitx** [comment]
I am also a begineer and got overwhelmed by the code so, I would also request someone to give us a full walkthrough of the entire codebase.

**Comment by sethmlarson** [comment]
I also don't recommend this project as somewhere that beginners should get their start. We're unlikely to create any resources for this either as our limited time is better spent maintaining the project itself. Good luck finding a project that speaks to you and finding time to invest in OSS if you'd really like to make an impact those two components are critical.
