### ISSUE TITLE
GET Method + HTTPS does not append request Body

### ISSUE THREAD

**Issue by MimounMen** [psf/requests#5728]
I'm writing a Script to interact with an Elasticsearch Instance. The ES Server blocks POST Requests, therefore i have to use GET Methods with a request body.

## Expected Result

A HTTP GET Request with Content-type and Content-length set with the corrensponding body
## Actual Result

The Headers are always been set, but if the protocol is HTTPS the body will not be appended.

## Reproduction Steps

```python
import requests, json

proxies={'http':'http://localhost:8080',
         'https':'https://localhost:8080'
        }
test={'test':'test'}
payload=json.dumps(test)

#Does not append Body (GET,HTTPS)
r=requests.request(method='get',url='https://google.com',json=payload,proxies=proxies)
#Does Append Body (GET, HTTP)
r=requests.request(method='get',url='http://google.com',json=payload,proxies=proxies)
#Does append Body (POST HTTPS)
r=requests.request(method='post',url='https://google.com',json=payload,proxies=proxies)

```

**Comment by sethmlarson** [comment]
Hey, I know about Elasticsearch because I'm the Python ES client maintainer. Elasticsearch accepts POST in place of GET for all requests that require a body. The client automatically uses POST for you for this reason.

**Comment by MimounMen** [comment]
Hi Sethmlarson, thanks for the quick answer.
There is a Proxy between the client and the ES instance.
The proxy is blocking any POST Method.

**Comment by sigmavirus24** [comment]
A few things:

1. Semantically according to the RFCs, GET bodies are meaningless and _any intermediary_ (i.e., a proxy) can decide to strip it
2. `json=json.dumps(...)` negates the purpose of the `json=` parameter. Stop that
3. The issue sounds completely isolated to your proxies and not to requests as I know for a fact that Requests adds the body regardless.
