### ISSUE TITLE
Cookies d'ont work

### ISSUE THREAD

**Issue by UnknownSourceCode** [psf/requests#5729]
Well i wanted to Login to my textnow account  to send smsusing cookies
i copied from firefox to curl and the request done and worked very well
when i use python
requests.get("https://www.textnow.com/api/sessions",
    headers={
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
    },
    cookies={},
)
i tried use Cookies in Cookies KeyWord i tried use requests.cookies.set ,set-cookie header, cookie header , tried injecting cookies to cookie jar and tried use alot of things and everything i found on stackoverflow i tried

Every New thing i try Cookies Fail
## Reproduction Steps

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by UnknownSourceCode** [comment]
I TRIED ALl StackOVerflow posts no solution

**Comment by UnknownSourceCode** [comment]
but none of them did help sir

**Comment by UnknownSourceCode** [comment]
that why i did come here to demand Solution in CURL , PyCurl Works Perfectly but i prefer Requests but is don't know why if you can help thanks you d'ont send a solution that you didn't try because as i did say no solution found till now
