### ISSUE TITLE
endless redirection because of rewriting query containing "[]".

### ISSUE THREAD

**Issue by darkfader** [psf/requests#5732]
It's probably a combination of python3 libraries, since I am not seeing this effect on my webbrowser nor cURL.
I tried disabling automatic redirection but my subsequent prepare_request calls ends up in the same rewriting.

## Expected Result

[] should not rewrite save characters %5B%5D I think because those are safe characters?. For redirection, It probably just should take the redirection from the server as granted anyways.

## Actual Result

[] in queries gets rewritten to %5B%5D. Server rewrites %5B%5D back to [] in Location response header in a redirect.

## Reproduction Steps

```python
import requests
session = requests.Session()
session.send(session.prepare_request(requests.Request(method='get', url='https://www.suruga-ya.jp/search?category=&search_word=&restrict[]=brand=ATARI')), allow_redirects=False)
# ( just some example URL with [] )
```

## System Information

    $ python -m requests.help
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "3.3.1"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.1"
  },
  "platform": {
    "release": "20.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010109f",
    "version": "20.0.1"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "1010109f"
  },
  "urllib3": {
    "version": "1.26.2"
  },
  "using_pyopenssl": true
}
```
(the server runs Drupal 8 with PHP/7.3.11 if that matters)

## Workaround

In urllib3.util.url I replaced
`QUERY_CHARS = FRAGMENT_CHARS = PATH_CHARS | {"?"}`
to
`QUERY_CHARS = FRAGMENT_CHARS = PATH_CHARS | {"?","[","]","(",")","=",":","_"}`
(I think there are more safe characters though)

**Comment by sethmlarson** [comment]
urllib3 follows RFC 3986 on URLs. If you look at the [ABNF](https://tools.ietf.org/html/rfc3986#appendix-A) for query you'll see that `[` and `]` are not allowed (they are characters in `gen-delims` so not in `pchar`) so I would argue that the server is not handling your request correctly.

**Comment by sigmavirus24** [comment]
Further, not escaping the Location header can lead to a host of security issues, which is frankly unacceptable as a solution

**Comment by darkfader** [comment]
Thank you for the elaborate answer. Accepted.
I am a bit shocked however of the many client interpretations. It's probably all about compatibility with old/buggy sites.

Funny to see how `curl/7.64.1` gives `GET /test?&wow[]=test HTTP/1.1` and `GET /test?&wow=test%5B%5D HTTP/1.1` depending on position relative to the `=`. (Using -G and --data-urlencode) 
Chrome doesn't care and just passes along the URL.
Of course some characters are still percent-encoded.
