### ISSUE TITLE
How to force session pool connections to reestablish?

### ISSUE THREAD

**Issue by ikhmyz** [psf/requests#5737]
I have an app (desktop) that use sessions for keepalive connections, there is a case when users restart internet connection or switch vpn on/off, the next 2-3 requests (no matter how much time passed after switching internet) made from session hang until read timeout but internet connection is already up (script that runs in parallel in separate thread that making same requests but without session is already started to receive responses). How can I force session to reeastablish all connections or any other workaround?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
