### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by surenjanath** [psf/requests#5738]
Summary.

## Expected Result
div with temp email and not loading after couple seconds of loading
<input class="emailbox-input opentip" data-original-title="Your 10 Minute Mail address" data-placement="bottom" id="mail" onclick="select(this);" readonly="" type="text" value=**""**/>
What you expected.

## Actual Result
blank

## Reproduction Steps
No paused between timeout

```python

import requests
with requests.Session() as s:
  post = s.get('https://temp-mail.org/en/10minutemail',headers=headers,timeout=20)
  data = bs(post.text,'html.parser')
  email = data.find('input',{'id':'mail'})
  print(email)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "3.2.1"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.0"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010108f",
    "version": "20.0.1"
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": true
}

google callaborator
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
