### ISSUE TITLE
Params list with one item

### ISSUE THREAD

**Issue by iBobik** [psf/requests#5749]
If parameter has list with only one item, then the list is converted to a string.

## Expected Result

`params={'fields': ['fieldname']}` should convert to `?fields[]=fieldname`

## Actual Result

`params={'fields': ['fieldname']}` converts to `?fields=fieldname`

## Reproduction Steps

```python
import requests
requests.request(method,
                             posixpath.join(self.base_url, url),
                             params={'fields': ['fieldname']},
                             data=payload,
                             headers=self.headers)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.1"
  },
  "platform": {
    "release": "4.19.121-linuxkit",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.26.3"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @iBobik,

The behavior you're seeing is what's intended. Our documentation shows how we handle parameter encoding for lists and it's identical regardless of the length of the list. We'll generate a key-value pair for every list element.

The proposed expectation is non-standard and violates ABNF for the [URI query component](https://tools.ietf.org/html/rfc3986#section-3.4), so we won't be changing anything at this time.
