### ISSUE TITLE
Post request using https proxies returning encoded text after update to python 3.9.1

### ISSUE THREAD

**Issue by bloxploits** [psf/requests#5750]
Summary.
I am making a request to a url with a proxy, however, after I updated from python 3.8.3 to 3.9.1, the response started to be encoded.
When I request this url without a proxy, there are no problems and it worked before with a proxy in 3.8.3. I don't know which of requests I used in 3.8.3, but I've seen a few open and closed issues about proxies in the new requests update. 
I also tried using the latest version of urllib3 (1.2.6), and the requests just never got sent, I was stuck on an empty console screen so I was forced to use an older version of urllib that worked.

Expected result:

{
    "fingerprint": "810034976510050356.i2OpgwJJalp3uKzcq7sakA10bMY"
}

Actual result:

!   c�R������� � ��TX���p8��,��,�cO�L5��Lޙ�R��A�z���'��

Code example:

```python
import requests

session = requests.Session()
adapter = HTTPAdapter(max_retries=Retry(connect=15, backoff_factor=0.5))
session.mount("http://", adapter)
session.mount("https://", adapter)
proxy = "example:port"
proxy_dict = {"http": "http://" + proxy, "https": "http:s//" + proxy}

headers = {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "no-cache",
        "pragma": "no-cache",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
}

r = session.post("https://example.com/", headers=headers, proxies=proxy_dict)

print(r.text)
```

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.1"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.2"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
What do the response headers look like? I have a suspicion as to what this is related to, but it likely is related to you having different versions of Requests, not different versions of Python.

**Comment by bloxploits** [comment]
> What do the response headers look like? I have a suspicion as to what this is related to, but it likely is related to you having different versions of Requests, not different versions of Python.

{'Date': 'Sat, 13 Feb 2021 23:05:03 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d7fc9575f417fc238cfe0aedb530af9a31613257503; expires=Mon, 15-Mar-21 23:05:03 GMT; path=/; domain=.discord.com; HttpOnly; SameSite=Lax; Secure', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-envoy-upstream-service-time': '5', 'Via': '1.1 google', 'Alt-Svc': 'h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '083f3d0bc200003e27c6148000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"group":"cf-nel","endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=%2BbaRFUhx35RUeoOIL%2Fpfif9luP3A9yqZSQo7siR7WmD83NLf3AK3P5xJs8QLBxP1Rxfx3I3YZFe%2BRvhXZBTD5cBdEkM2hwjRP7Su7w%3D%3D"}],"max_age":604800}', 'NEL': '{"report_to":"cf-nel","max_age":604800}', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6212312609273e27-EWR', 'Content-Encoding': 'br'}

Status code: 200

Yes, it is because of the version of requests most likely because it was working on an older version yesterday but I removed it when I updated it from 3.8.3 to 3.9.1

**Comment by sigmavirus24** [comment]
Try setting `r.encoding = None` before printing `r.text` and let me know what happens

**Comment by bloxploits** [comment]
> Try setting `r.encoding = None` before printing `r.text` and let me know what happens

same thing

**Comment by sigmavirus24** [comment]
Well then that rules out my idea

**Comment by bloxploits** [comment]
> Well then that rules out my idea

Well, i guess ill wait for a new update.
Tested on postman using the same proxy and it worked so I think its a requests problem not necessarily a problem with the website

**Comment by sigmavirus24** [comment]
Some websites change behaviour based on user-agent. It's possible they've something that's causing this problem for you. I'd also compare the raw bytes (`r.content`) to the raw bytes postman gets back.

**Comment by bloxploits** [comment]
Fixed by removing the headers
