### ISSUE TITLE
Issue while issuing GET requests to Google owned services.

### ISSUE THREAD

**Issue by teisseire117** [psf/requests#5756]
GET Requests to Google owned services don't work or work very very slowly(minutes). Example of urls having problems : Google.com Google.fr Youtube.fr Youtube.com Googleapis.com
I have no issue with any other website(I tried github.com, facebook.com and a bunch of others)
It worked an hour ago, it doesn't work anymore, I didn't change anything.
I can still access those urls fine on my browser.

## Expected Result

I expect to get a response, but the program seems to be loading(?) indefinitely

## Actual Result

It seems to be loading indefinitely. Rarely, I get a response, 99% of cases(Only 2 worked) it just doesn't do anything and the program doesn't stop or show anything

## Reproduction Steps

```python
import requests

a = requests.get("https://www.youtube.fr")
print(a)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.0"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.26.3"
  },
  "using_pyopenssl": false
}```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Lyfhael** [comment]
It fixed by itself... Not sure what it was since no error messages. I haven't restarted my computer or done anything.
