### ISSUE TITLE
Would anyone know why using requests with proxies through repl.it would cause this SSLError?

### ISSUE THREAD

**Issue by jonathanlin0** [psf/requests#5764]
As the title stated, I'm attempting to ping google to check the quality of the proxy through an api in repl.it but when I try it gives this error: 

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))

![image](https://user-images.githubusercontent.com/67934523/109589099-6ff3ce00-7acf-11eb-92a2-a8b91fc370c5.png)

**Comment by sigmavirus24** [comment]
This isn't a Q&A forum and is likely best asked to someone familiar with `repl.it`.
