### ISSUE TITLE
Invalid JSON serialization of data with NaNs when using `json` request argument

### ISSUE THREAD

**Issue by soxofaan** [psf/requests#5767]
When passing data to `json` argument in a `requests.post()` (or comparable) request and data contains "nan" floats (`float("nan")`), the data payload will be invalid JSON (in strict sense). Example:

    >>> import requests
    >>> requests.__version__
    '2.25.1'
    >>> data = {"foo": float("nan")}
    >>> resp = requests.post("https://httpbin.org/post", json=data)
    >>> resp.json()["data"]
    '{"foo": NaN}'

While the `NaN` in this result (the JSON serialized data payload that is sent) is valid JavaScript, it is not valid JSON.

The reason is that stdlib's `json.dumps` has `allow_nan` option which is `True` by default and consequently generates invalid JSON by default:

    >>> json.dumps(data)
    '{"foo": NaN}'

## Expected Result

A ValueError should be raised (at least by default). E.g.:

    >>> json.dumps(data, allow_nan=False)
    ...
    ValueError: Out of range float values are not JSON compliant

## Actual Result

library silently sends invalid JSON

**Comment by amansr02** [comment]
I am a first-time contributor and I would like to work on this issue and implement it if possible? Do let me know. Thank you!

**Comment by tallalnparis4ev** [comment]
Hello, I am not sure if I have fixed this with the PR #5810 , can someone check it out ?
