### ISSUE TITLE
model.RequestEncodingMixin._encode_files does not work for 3 or 4 elements tuple

### ISSUE THREAD

**Issue by hefvcjm** [psf/requests#5768]
https://github.com/psf/requests/blob/913880c45a3a8c3bf6b298e9c38709cd95a9c97c/requests/models.py#L110-L118
Anotation for this function mentions "The tuples may be 2-tuples (filename, fileobj), 3-tuples (filename, fileobj, contentype) or 4-tuples (filename, fileobj, contentype, custom_headers).", but it does not work for 3 or 4 elements tuple.

It will throw exception in following line
https://github.com/psf/requests/blob/913880c45a3a8c3bf6b298e9c38709cd95a9c97c/requests/models.py#L141

My test code:
```python
import requests

with open("file.txt", "r") as f:
    requests.get("http://www.example.com", files=[("file.txt", f, "multipart/form-data")])
```

And exception:
```
...
...
    for (k, v) in files:
ValueError: too many values to unpack
```

would you comfire which one, the anotation or the code, is right? thx~

**Comment by sigmavirus24** [comment]
That is not the documentation or annotation you should be reading for that parameter. Please read the appropriate documentation
