### ISSUE TITLE
Session proxies definition raise error on Get method

### ISSUE THREAD

**Issue by bbuzens** [psf/requests#5772]
I want to pass proxies definition through session's proxies attribute.
It is described in [the documentation](https://2.python-requests.org/en/master/user/advanced/#proxies).

In my configuration, it raises a ProxyError

## Expected Result

This should work
```Python
import requests

proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}

requests.get('http://example.org', proxies=proxies)

```

That too

```Python
import requests

proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
session = requests.Session()
session.proxies.update(proxies)

session.get('http://example.org')
```

So, i wrote something like that

```Python
import requests

proxies = {
  'http': 'http://localhost:53128',
  'https': 'http://localhost:53128',
}

session = requests.sessions.Session()
session_response = session.get('https://www.google.com', proxies=proxies).status_code
print(session_response)

session_with_proxies = requests.sessions.Session()
session_with_proxies.proxies.update(proxies)
print(session_with_proxies.proxies)
try:
    session_with_proxies_response = session_with_proxies.get('https://www.google.com').status_code
except requests.exceptions.ProxyError:
    print("Proxy error catched")
```

The *session_with_proxies_response* should work and no *"Proxy error catched"* should be catched.

## Actual Result

And i got

```
200
{'http': 'http://localhost:53128', 'https': 'http://localhost:53128', 'ftp': 'ftp://localhost:53128'}
Proxy error catched

Process finished with exit code 0
```

The `session_with_proxies.get('https://www.google.com').status_code` command raises a proxy error.
But the proxy is defined as it is recommanded by the documentation.

## Reproduction Steps

Install *requests*

```python
import requests

```

Run that script with a local proxy running (Squid or what you like...)

```Python
import requests

proxies = {
  'http': 'http://localhost:53128',
  'https': 'http://localhost:53128',
}

session = requests.sessions.Session()
session_response = session.get('https://www.google.com', proxies=proxies).status_code
print(session_response)

session_with_proxies = requests.sessions.Session()
session_with_proxies.proxies.update(proxies)
print(session_with_proxies.proxies)
session_with_proxies_response = session_with_proxies.get('https://www.google.com').status_code
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.3"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.26.3"
  },
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @bbuzens, there's no information on the actual error you're receiving. From the information provided, it looks like there's a legitimate issue connecting to your proxy.

If you have more information on the exact traceback you're receiving we can take a look. I'm going to close this for now since there isn't anything actionable, feel free to reopen with more info.
