### ISSUE TITLE
POST request is resent as GET when the status code is 301

### ISSUE THREAD

**Issue by Maelstro** [psf/requests#5805]
Hello, 

I'd like to report a bug with `requests` behavior towards processing a 301 response. The 301 response to a POST request causes the user agent to automatically redirect the request to a given address, but it also changes the request type from POST to GET. The RFC 2616 mentions such behavior as shown below:
```
Note: When automatically redirecting a POST request after
      receiving a 301 status code, some existing HTTP/1.0 user agents
      will erroneously change it into a GET request.
```

Therefore, I think that `requests` isn't compliant with the RFC [(10.3.2 301 Moved Permanently)](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) in this matter.

## Expected Result

When the response to a POST request has a status code 301, the automatic redirect should also be a POST request.

## Actual Result

Having sent a POST request to a given endpoint and receiving a response with a status code 301, the automatic redirect request becomes a GET request. Example shown below:
```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2021 16:43:03] "POST /test_route HTTP/1.1" 301 -
127.0.0.1 - - [29/Apr/2021 16:43:03] "GET /test_route HTTP/1.1" 405 -
```

## Reproduction Steps

Create two scripts - a server and a client.

`test_server.py`
```
import flask

app = flask.Flask(__name__)

@app.route("/test_route", methods=["POST"])
def test_response():
    return flask.redirect("http://localhost:5000/test_route", code=301)

if __name__ == "__main__":
    app.run()
```

`test_request.py`:
```
import requests

if __name__ == "__main__":
    print(requests.request("POST", "http://localhost:5000/test_route"))
```

After creating them, start the `test_server.py`. When the server starts, run the `test_request.py`. In the server logs you'll see the aforementioned base request and the redirected request.

## System Information

The library is system-independent, the behavior occurs on any device, from Raspberry Pi with Raspbian Buster, to x64 Debian Bullseye (testing).

**Comment by nateprewitt** [comment]
Hi @Maelstro,

This is expected behavior, the RFC you’re referencing has been obsolete for several years now.

Please make sure to search open and closed issues as we’ve requested before opening new ones in the future. You’ll be able to find this [answered](https://github.com/psf/requests/issues/5494#issuecomment-644314490) and the link to the relevant RFC there. Thanks!
