### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

### ISSUE THREAD

**Issue by aymenbnl** [psf/requests#5806]
Summary.
Cant import json data into Mysql Database because of this issue

What you expected.

A proper import of course.

What happened instead.
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

## Reproduction Steps

```
if args.input:
        with open(args.input, 'r') as f:
            for e in f:
                event = json.loads(e)
                misp.add_event(event)
```

## System Information
{
   "response":[
      {
         "Event":{
            "id":"1",
            "orgc_id":"1",
            "org_id":"1",
            "date":"2017-09-27",
            "threat_level_id":"4",
            "info":"ZeuS IP blocklist (Standard) feed",
            "published":true,
            "uuid":"59cb4f10-4190-4f76-988e-66a239b59801",
            "attribute_count":"108",
            "analysis":"2",
            "timestamp":"1506496272",
            "distribution":"3",
            "proposal_email_lock":false,
            "locked":false,
            "publish_timestamp":"1533556422",
            "sharing_group_id":"0",
            "disable_correlation":false,
            "extends_uuid":""
}}]}

This is running on up-to-date Ubuntu 20.04 and Python 3.8.5

**Comment by nateprewitt** [comment]
Hi @aymenbnl,

This doesn't appear to be related to Requests from the info provided. We'd recommend posting general Python questions on [StackOverflow](https://stackoverflow.com/).
