### ISSUE TITLE
2.25.1: requests requires idna < 3

### ISSUE THREAD

**Issue by kloczek** [psf/requests#5807]
Looks like requests  modulehas hardcoded dependency to require `idna >= 2.5 and idna< 3` and latest idna is 3.1.
Is it any reason why it cannot be idna is 3.1?
amd/or if it is could requests module can be adjusted to be able use it with latest idna?

**Comment by nateprewitt** [comment]
Hi @kloczek, there are a number of issues around this including very recent ones like #5804. Please make sure to check open and closed issues before opening new ones in the future. Thanks!

**Comment by kloczek** [comment]
> Hi @kloczek, there are a number of issues around this including very recent ones like #5804. Please make sure to check open and closed issues before opening new ones in the future. Thanks!

Hmm .. you've just closed the ticket without provide answers on any of my questions  :(
