### ISSUE TITLE
Chardet Licence

### ISSUE THREAD

**Issue by pokecheater** [psf/requests#5809]
Hey :),

I have an question regarding the licensing and a sub module you are using. As builded our application which uses flask (and flask uses requests) I noticed that a tiny package with the name chardet appeared in our installation that is licenced under GNU. As far as I understand has GNU a copyleft. 

Since your package uses the chardet lib and builds up on the top of it's coding source I am confused that the requests lib is licenced under Apache 2.0 and not GNU. As far as I understand has GNU a strict copyleft which means that even if only library calls are used the whole software that is using it should be licenced under gpl.

Maybe it is just me that misinterpret the rights and duties that come along with GNU. Just want to be sure I do not redistribute our closed source software when I have to put it under GNU.

Thanks in advance :).

**Comment by pokecheater** [comment]
Okay forget about it just found out that it is fine with Lesser GPL and chardet is licensed under this terms.

**Comment by farooquiyasir** [comment]
Hey I have the same question. Chardet is using LGPL 2.1 licensing. Isn't it a copyleft license?
