### ISSUE TITLE
SSL error with verify=False and mitmproxy

### ISSUE THREAD

**Issue by marmaladeseismic** [psf/requests#5812]
Running mitmdump and trying to `requests.get` with mitmdump set as proxy and `verify=False`, I receive `SSL: CERTIFICATE_VERIFY_FAILED`.  Problem on linux/macOS, **not a problem on Windows**. If I set the path to `http://...` instead of `https://...` then it does work, but I don't think I should have to do this and it's not a great solution in the actual client I'm writing.

## Expected Result

Valid response in Python, no exceptions.

mitmdump output:
```
% mitmdump
Proxy server listening at http://*:8080
[::1]:57986: clientconnect
[::1]:57986: GET https://example.com/
          << 200 OK 648b
[::1]:57986: clientdisconnect
```

## Actual Result
Python exception:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))`

mitmdump output:
```
% mitmdump
Proxy server listening at http://*:8080
[::1]:55825: clientconnect
[::1]:55825: Cannot connect to server, no server address given.
[::1]:55825: clientdisconnect
```

## Reproduction Steps

Run `mitmdump` and then run the following python:

```python
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

verify = False
#verify = '/path/to/mitmproxy/cert' # this gives a 502 but anyway shouldn't be necessary?

requests.get(
    'https://example.com',
    proxies = {
        'http' : 'http://localhost:8080',
        'https' : 'https://localhost:8080'
    },
    verify = verify
)
```

## System Information

macOS (fails)
```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": "3.3.2"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.4"
  },
  "platform": {
    "release": "20.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010109f",
    "version": "20.0.1"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.4"
  },
  "using_pyopenssl": true
}
```

linux (fails)
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.8"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.7"
  },
  "platform": {
    "release": "5.11.14-100.fc32.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010104f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.25.7"
  },
  "using_pyopenssl": true
}
```

Windows (works)
```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "3.3.2"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.2"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010109f",
    "version": "20.0.1"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1010104f"
  },
  "urllib3": {
    "version": "1.25.8"
  },
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
Is mitmproxy even listening on `https://`?

**Comment by marmaladeseismic** [comment]
Honestly that confuses me given the first line of the mitmdump output, but `curl --proxy localhost:8080 https://example.com` is fine and it works on Windows again with the same run params and request from Python. curl works on all of linux/mac/windows.

**Comment by sigmavirus24** [comment]
> Honestly that confuses me given the first line of the mitmdump output

Instead of guessing at what other things are doing, can you use a tool like `ss` to determine if it is listening to `https://` on the same port? You seem to be asking me to do all the heavy lifting and I just don't have time for that and in the past I haven't had an issue with mitmproxy and `verify=False` (and the code through that path hasn't changed very much in _years_ on our end).

**Comment by marmaladeseismic** [comment]
My intention was not to guess or ask you to do heavy lifting, I was hoping for pointers on what to do next.

I tried `httpx` and it "just works" so I'm closing this.
