### ISSUE TITLE
Requests ignores KeyboardInterrupt

### ISSUE THREAD

**Issue by mrx23dot** [psf/requests#5822]
Requests ignores CTRL+C KeyboardInterrupt when it does it's timeout.

## Expected Result
It should give up waiting when requested and exit immediately.

## Actual Result
Keeps doing it's timeout until elapse then exits.

## Reproduction Steps

```python
import requests
# an invalid url
resp = requests.get('http://192.1.5.2', timeout=50)
# press CTRL+C while executing

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": "3.1.1"
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010108f",
    "version": "19.1.0"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.26.3"
  },
  "using_pyopenssl": true
}
```

**Comment by nateprewitt** [comment]
Hey @mrx23dot,

Thanks for the report. I took a quick look and was able to reproduce the issue. It's specific to Windows 10 and doesn't appear to happen in *nix flavor environments. A quick look at the stack trace shows the culprit isn't actually Requests, but the Python standard library. Specifically `socket.py`'s `connect` call.

You can reproduce the same issue without Requests or Urllib3 with the code below. Unfortunately, I don't think there's anything we can do here.

```python
from http.client import HTTPConnection
conn = HTTPConnection('192.1.5.2', 80, timeout=50)
conn.request('GET', '/')
conn.getresponse()
```

**Comment by mrx23dot** [comment]
Thank you, created other ticket in urlib
https://github.com/urllib3/urllib3/issues/2237
