### ISSUE TITLE
page 404 through Requests but can access through browser

### ISSUE THREAD

**Issue by garagesteve1155** [psf/requests#5828]
Trying to view a page with Requests but getting page 404 with Requests but I can access the page no problem through my browser

My Code (Sorry about how it looks, Im not familiar with using Github):
string_page = str(page)
with requests.Session() as s:

> resp = s.get('https://bscscan.com/token/generic-tokentxns2?m=normal&contractAddress=0x470862af0cf8d27ebfe0ff77b0649779c29186db&a=&sid=f58c1cdefacc680b799412c7645ed7f7&p='+string_page)

> page_info = str(resp.text)

print(page_info)

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by garagesteve1155** [comment]
Seems like a defect to me. Page works on browser, not on code. Other
similar pages work fine with my code but that one specific page does not
