### ISSUE TITLE
limit the data transfer of individual HTTP requests

### ISSUE THREAD

**Issue by Chiragasourabh** [psf/requests#5829]
I have a system with limited network bandwidth.  if I make an upload or download large file operation using the requests library, the single request is consuming the whole available bandwidth of the system. is there a way to add latency to these requests (which slows down throughout of serial requests but not consume overall bandwidth)? 

A direct solution to set download/upload bandwidth for an individual HTTP request or to keep a part of the total available bandwidth free would be great.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

See also #1690, #4330
