### ISSUE TITLE
Minor: pip install complains (not fails) with current

### ISSUE THREAD

**Issue by griswolf** [psf/requests#5834]
Summary.
During pip install -U requests this message is sent to the terminal:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.25.1 requires idna<3,>=2.5, but you have idna 3.2 which is incompatible.

## Expected Result
No such message

## Actual Result
See above

## Reproduction Steps
pip install -U idna re

## System Information

{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.5"
  },
  "platform": {
    "release": "19.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_pyopenssl": false
}

**Comment by sethmlarson** [comment]
We're aware, please look for existing issues before opening new ones.
