### ISSUE TITLE
http call throwing error in background mode

### ISSUE THREAD

**Issue by ujjaldey** [psf/requests#5840]
I am trying to make an HTTP call using `python-requests`. When I am running the script in the background as `python main.py &`, it works perfectly ok. But as soon as I close the terminal, it starts giving me the error "_[Errno 5] Input/output error_". The process keeps running in the background.

Any idea how to make the HTTP call while running the python script in the background (and no terminal open)?

My sample code:

```
import logging
import time

import requests

logging.basicConfig( format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO,filename='log.log')
logger = logging.getLogger(__name__)

def make_req() -> None:
    res = requests.get('https://w3schools.com/python/demopage.htm')
    return res.text

def main() -> None:
    logger.info("----------------------------------------------")
    try:
        out = make_req()
        print(out)
        logger.info(out)
    except Exception as e:
        logger.error("-->"+ str(e))

if __name__ == '__main__':
    while True:
        main()
        time.sleep(5)
```

Output:
```
2021-06-10 14:03:51,840 - __main__ - INFO - ----------------------------------------------
2021-06-10 14:03:52,061 - __main__ - ERROR - -->[Errno 5] Input/output error
2021-06-10 14:03:57,081 - __main__ - INFO - ----------------------------------------------
2021-06-10 14:03:57,317 - __main__ - ERROR - -->[Errno 5] Input/output error
```

Thanks in advance.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
