### ISSUE TITLE
SSL ERROR - WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by eilgug** [psf/requests#5843]
While i'm using proxies just get always this error.
I've try several times at least i resolved by removing the "s" in the https: proxy too as suggested in [this topic](https://stackoverflow.com/questions/65516325/ssl-wrong-version-number-on-python-request):

I think this problem is related to the last version, because i've tried on an older one and it works great.
## Solution Steps

```python
import requests
...
self.proxies = {
    'http': f'http://...:8080/',
    'https': f'http://...:8080/'
}
def get(self, url):
     request_url = self.base_url + url
     return requests.get(request_url, headers=self.headers, proxies=self.proxies)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_pyopenssl": false
}
```

**Comment by sha016** [comment]
Sounds kind of like #5943 

Can you check that issue and see if it answers your question? If not, I think you need to provide some more complete example code & errors.

**Comment by sethmlarson** [comment]
Almost certain this is the same issue mentioned in the comment above. Try changing https->http. Closing as duplicate.
