### ISSUE TITLE
Request fails for subdomains of localhost

### ISSUE THREAD

**Issue by Mixermachine** [psf/requests#5847]
Requesting subdomains of localhost fails with error message on Windows.
This error does not appear on Linux (tested on an ARM64 server).
Tested on a Windows laptop (Lenovo T14s, AMD 4750u) and a Windows desktop (AMD 2600)

## Expected Result

I need to make a get request to an url in the following format:

http://XXX.localhost (where XXX is replaced with an arbitrary value.)
example: http://ark8s-844db1a4-2988-4f30-9ff6-e78df428bad3-test.localhost

An nginx server inside kubernetes listens to this url.
When I use the url in the browser the desired site is fetched.

## Actual Result

I get the following error:
`HTTPConnectionPool(host='ark8s-844db1a4-2988-4f30-9ff6-e78df428bad3-test.localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D1E89E4940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`

## Reproduction Steps

```python
import requests

requests.get('http://test.localhost')
```
Same result for when 'test' is replaced with any other value no matter if a server is listening there or not.
Requesting localhost works as expected.
Subdomains of localhost do not work.

## System Information
Windows 10
Ryzen 4750U

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.6"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
The error here `getaddrinfo failed` indicates that Python (not requests) can not find your domain name. You should be able to reproduce this with

```py
import socket

print(socket.getaddrinfo("ark8s-844db1a4-2988-4f30-9ff6-e78df428bad3-test.localhost", 80, family=socket.AF_INET, proto=socket.IPPROTO_TCP))
```

**Comment by Mixermachine** [comment]
Thank you for your answer.
Yes I get the same error there

`socket.gaierror: [Errno 11001] getaddrinfo failed`

Do you know where I can raise this issue?

**Comment by sigmavirus24** [comment]
It's not even just a Python issue. You could write C code and code in other languages that would encounter this. It means your machine isn't configured to resolve those addresses. Unfortunately I don't know how to do that on Windows but I suspect StackOverflow knows

**Comment by Mixermachine** [comment]
Mh that is really weird.
When I enter the address on the same machine in the browser it will fetch the page.

Looked into it, the host file of Windows does not seem to support wildcards...
Damn, I guess I have to find another solution.
The subdomains are generated with entropy so i can't add them to the host file.

Thx @sigmavirus24 for pointing me in the right direction
