### ISSUE TITLE
How to upload large chunks of file in requests ?

### ISSUE THREAD

**Issue by pghole** [psf/requests#5849]
Hello team,

I have to upload large files (~5GB). I am dividing the file in small chunks (10MB), can't send all together(as the api I am requesting fails for large data 5GB if sent in one request). The api I am uploading to,  has a specification that it needs minimum of 10MB data to be sent. I did use read(10485760) and send it via requests which works fine.

However, I do not want to read all the 10MB in the memory and if I leverage multithreading in my script, so each thread reading 10MB would cost me too much memory.

Is there a way I can send a total of 10MB to the api requests but read only 4096/8192 bytes at a time and transfer till I reach 10MB, so that I do not overuse memory.

Pls.note I don't want to send the fileobj in the requests as that will use less memory but I will not be able to break the chunk at 10MB and entire 5GB data will go to the request, which I do not want.

Is there any way via requests. I see the httplib has it. https://github.com/python/cpython/blob/3.9/Lib/http/client.py - I will call the send(fh.read(4096) function here in loop till I complete 10MB and will complete one request of 10MB without heavy memory usage.

Pls. suggest. Urgent

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
