### ISSUE TITLE
How to get the response from CONNECT while using proxy on a HTTPS target url

### ISSUE THREAD

**Issue by lilanleo** [psf/requests#5853]
Hi,

I'm trying to send a GET to a **HTTPS** target using proxy. 
Normally(like in curl), I will receive **two** response, one is from CONNECT <https://target>, the other is from GET <https://target>
But the returning response obj from requests.get(url, proxy) only contains the second response.

Could I ask how can I get the first response from CONNECT method? And is there any method to send only CONNECT but not GET? 

Thanks a lot.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
