### ISSUE TITLE
How to set requests to use ipv4 by default?

### ISSUE THREAD

**Issue by demonguy** [psf/requests#5865]
When i tried to use `requests.get("www.google.com")` and it hangs for 3 minutes and then succeed.
after debug i found it connect to ipv6 address first and then tries to ipv4.
So far i use `timeout=3` to force ipv6 try to timeout ASAP. but it's tricky. is there anyway to make it use ipv4 by default?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
