### ISSUE TITLE
Support for Certificate Transparency

### ISSUE THREAD

**Issue by RJPercival** [psf/requests#5873]
[OpenSSL 1.1 supports checking of Signed Certificate Timestamps](https://www.openssl.org/docs/man1.1.0/man7/ct.html) (SCTs) when establishing a TLS connection, but `requests` does not provide a way to enable or configure this. Doing so would allow for a higher degree of security for users that wish to opt into this.

**Comment by sethmlarson** [comment]
Requests can't take advantage until this API it's exposed via the standard library `ssl` module. I recommend opening an issue in [Python's issue tracker instead](https://bugs.python.org).
