### ISSUE TITLE
Prepare URL coerces to lower-case

### ISSUE THREAD

**Issue by dmitrypolo** [psf/requests#5886]
https://github.com/psf/requests/blob/916d171f2bf01155f2c115159ec475e8d76a690b/requests/models.py#L369

When passing in a URL with an upper-case letter after a `-` character the host is coerced to lower case.

Python Version: 3.9.1
Requests Version: 2.26.0
OS: MacOS

Steps to reproduce
--------------------
```
from requests.models import PreparedRequest
p = PreparedRequest()
url = "http://service-A/abc"

p.prepare_url(url, None)
print(p.url)
"http://service-a/abc"
```

Notice how the `A` has been changed to `a`. This behavior is not expected. I have also submitted [this bug report](https://github.com/urllib3/urllib3/issues/2337) as the behavior arises from the use of `urllib3`.

**Comment by sigmavirus24** [comment]
This is 100% correct. RFC 3986 describes the part of any URI as such:

- scheme (part of the URL preceding the first `:`)
- authority (part of the URL starting with `//` before the path; this includes username/password, hostname, and port)
- path (part of the URL starting with `/`)
- query (part of the URL starting with `?`)
- fragment (part of the URL starting with `#`)

`"http://service-A/abc"` thusly gets parsed as `scheme=http, authority=service-A, path=/abc`. The host portion of the authority is to be treated case-insensitively. In other words, `service-A` is actually functionally equivalent to `service-a`.

Finally, spamming multiple projects is not appropriate, especially when you've done 0 research into how the standards define the behaviour here.

**Comment by TaquitoSlayer** [comment]
Imagine not realizing that we're getting to a point with Web where there are vastly more companies handling stuff like authorizations, header orders, and even case sensitivity per request, even in a production environment and dismissing a very real issue that is now becoming more common.

**Comment by sethmlarson** [comment]
@TaquitoSlayer Your sarcastic comment isn't appreciated. I suggest you read up on existing standards for the web before claiming you know how the web works:

- [WHATWG URL](https://url.spec.whatwg.org) which is the most modern standard for URLs [calls for lowercasing the host section of URLs](https://url.spec.whatwg.org/#idna).

- [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) which is the standard that Requests and urllib3 primarily use as a reference for their URL parsers also calls for normalization of the host component via lowercasing (quote from [Section 3.2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2)):

  > Although host is case-insensitive, producers and normalizers should use lowercase for registered names and hexadecimal addresses for the sake of uniformity, while only using uppercase letters for percent-encodings.

Anyone depending on any different behavior should expect their services to break completely as they're throwing 20+ years of standards out the window.
