### ISSUE TITLE
get invalid url in InvalidSchema

### ISSUE THREAD

**Issue by aliraad79** [psf/requests#5897]
Requests is not accepting feature requests at this time.
Hi,
I do a get request on a url that redirects to a intent:// or market:// url which are the meaningful url in android.
After raising requests.exceptions.InvalidSchema i want to get this invalid url and do something else with it but there isn't a perfect way to do it so i do something like 
``` e.args[0].split("'")[1] ```
that is a very bad and weird way to do it.
python=3.9 and requests = "2.23.0"

**Comment by sigmavirus24** [comment]
> Requests is not accepting feature requests at this time.

Also this isn't cogent so it's not as if we could assist you with suggesting what to do instead. For questions, please use StackOverflow.
