### ISSUE TITLE
Cannot import requests on python 3.10 rc1

### ISSUE THREAD

**Issue by rkhwaja** [psf/requests#5901]
Cannot import requests on python 3.10. The problem is that python 3.10 requires urllib3 >= 1.26.

## Expected Result

I expected the module to import without errors.

## Actual Result

Import failed due to urllib3 version. You get the following callstack:
```    from requests import Session
.../site-packages/requests/__init__.py:43: in <module>
    import urllib3
.../site-packages/urllib3/__init__.py:8: in <module>
    from .connectionpool import (
.../site-packages/urllib3/connectionpool.py:29: in <module>
    from .connection import (
.../site-packages/urllib3/connection.py:39: in <module>
    from .util.ssl_ import (
.../site-packages/urllib3/util/__init__.py:3: in <module>
    from .connection import is_connection_dropped
.../site-packages/urllib3/util/connection.py:3: in <module>
    from .wait import wait_for_read
.../site-packages/urllib3/util/wait.py:1: in <module>
    from .selectors import (
.../site-packages/urllib3/util/selectors.py:14: in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (.../Python/3.10.0-rc.1/x64/lib/python3.10/collections/__init__.py)
```

## Reproduction Steps

```python
import requests
```

## System Information

GitHub CI ubuntu-latest with python version 3.10.0-rc.1

**Comment by nateprewitt** [comment]
Hi @rkhwaja, the failure you’re receiving is for a code path that hasn’t existed in urllib3 for over 4 years, so the solution would be to update to a newer version (>1.23 at the minimum).

This isn’t an issue with Requests and we can’t raise our pin version range without breaking a large portion of the Python ecosystem. There shouldn’t be anything inhibiting you from installing the correct version of urllib3 though.
