### ISSUE TITLE
If the length of the response header is less than the actual length of the body, a read timeout occurs

### ISSUE THREAD

**Issue by sihan-bit** [psf/requests#5905]
If the length of the response header is less than the actual length of the body, a read timeout occurs.

**Comment by nateprewitt** [comment]
Hi @sihan-bit, this is expected behavior. If the server tells us there is more data coming, Requests will wait until it arrives or until we reach our read timeout. There's no way for Requests to disambiguate between the two situations, and it likely shouldn't.
