### ISSUE TITLE
Adapter uses 0 for max_retries instead of the explicit value in DEFAULT_RETRIES

### ISSUE THREAD

**Issue by Monal5031** [psf/requests#5920]
Summary.

## Expected Result

I'm using a package that uses requests under the hood but doesn't support max_retry config.
So to get around that I came across the constant `DEFAULT_RETRIES`  which is used in the initialization of HttpAdapter here:
https://github.com/psf/requests/blob/main/requests/adapters.py#L117

I expected the Adapters to be initialized with the explicit value in the retry constant.

## Actual Result

I explicitly set this constant to some value in my code, which didn't make any difference to the adapters being initialized in the Session. This is due to the next line in above link which uses `0` instead of the constant to create a Retry object.

## Reproduction Steps

```python
import requests

requests.adapters.DEFAULT_RETRIES = 3

for _, adapter in requests.session().adapters:
    print(adapter.max_retries)

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.6"
  },
  "platform": {
    "release": "20.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
This is how Python works, unfortunately. That variable isn't intended for you to change as a way of changing other package's behaviour. The signature for `__init__` has `max_retries=DEFAULT_RETRIES` which may as well be `max_retries=0`. This isn't a Requests bug. We don't advertise this as functionality.
