### ISSUE TITLE
Python 3.10 Readiness

### ISSUE THREAD

**Issue by nateprewitt** [psf/requests#5925]
Python 3.10 is just a little over a month away and we have some issues that need to be addressed in Requests. Currently our test suite relies heavily on `httpbin` which has been largely unmaintained since 2017. As a dependency, it relies on `brotlipy` which has since migrated to a new package [`brotlicffi`](https://github.com/python-hyper/brotlicffi). Given these are both C-based, we can't compile them in CI environments and rely on wheels being available.

It looks unlikely that we'll get a new wheel for `brotlipy`, so we'll need to either find a way to migrate `httpbin` to `brotlicffi`, or work out another alternative for the test suite. I still have PyPI credentials for `httpbin` to cut a new release, but there's a matter of ownership to be worked out now that it's under [Postmanlabs](https://github.com/postmanlabs/httpbin). It also appears to have several versions in the commit history that have never been published that we'll need to consider.

**Comment by sigmavirus24** [comment]
I was removed from `httpbin` when it was sold/transferred to Postman. Maybe it's time to fork/use something different? #5915 has the start of something we might be able to use instead

**Comment by sethmlarson** [comment]
@nateprewitt I can get you a new wheel of brotlipy for Python 3.10. I've never built a wheel from a build candidate however. Is the way to go there to build a wheel from a build candidate and then once Python 3.10 is officially released upload a new wheel for 3.10 with an incremented build number? If that works for you I can take care of that step.

**Comment by nateprewitt** [comment]
If we can push a new wheel from the brotlipy tag, that may be _much_ easier than the alternatives in the short term. I would assume the wheels would be virtually identical between the rc and official release. If we have issues though, we can definitely revisit updating the build number with a wheel from the official 3.10 release. Thank you!!

**Comment by sethmlarson** [comment]
Uploaded `abi3` wheels for brotlipy which are compatible with Python 3.10 and all future Python 3 versions: https://twitter.com/sethmlarson/status/1433488043529359369

**Comment by nateprewitt** [comment]
Now that @sethmlarson has been kind enough to get us unblocked, I think we should be set with #5928.

**Comment by theGOTOguy** [comment]
@sigmavirus24 If it's decided that #5915 is the future of requests' testing, I will refactor all of the tests to use it and then remove the existing test server.
