### ISSUE TITLE
Restore logo

### ISSUE THREAD

**Issue by flying-sheep** [psf/requests#5926]
@kennethreitz mentioned he had a single condition for transferring stewardship for this repository:

> When I transferred the project to the PSF, per textual agreement with @ewdurbin, my only requirement was that the logo stayed in place.

I therefore assume that the removal in #5562 (along other images) was accidental and this will swiftly rectified. I’ll do a PR.

**Comment by nateprewitt** [comment]
Hi @flying-sheep, we're aware and this has already been addressed in #5923. Thanks.
