### ISSUE TITLE
Stuck on starting a HTTPS connection

### ISSUE THREAD

**Issue by CyanBook** [psf/requests#5932]
Hi, seems a stupid problem but i cannot figure it out.
This issue seems to happen only with this URL, but i cannot be sure.
Using a different HTTPX on my machine or Requests client on another machine works.
Although i wasn't able to replicate it on another machine, i think it's a good idea to try and resolve the problem.

URL:  https://nominatim.openstreetmap.org/search?q=Milan&format=json&polygon=0

## Expected Result
Get the body of the URL using requests.get.

## Actual Result
It gets stuck and seems to be in an infinite loop.
With logging on DEBUG, the only info it prints is:

`[14-Sep-21 23:17:30] [DEBUG] - Starting new HTTPS connection (1): nominatim.openstreetmap.org:443`

and nothing more.

## Reproduction Steps
```python
import requests
url = "https://nominatim.openstreetmap.org/search?q=Milan&format=json&polygon=0"
response = requests.get(url)
print(response.text)
```

## System Information
```
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.5"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.5"
  },
  "platform": {
    "release": "5.11.0-7633-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "101010af"
  },
  "urllib3": {
    "version": "1.26.6"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false

```

Note:
I know that issues which are hard to replicate are usually not that helpful, but i also know that reporting a bug (that is happening on my machine) is better than doing nothing.

**Comment by sigmavirus24** [comment]
Have you tried setting a connect timeout?

I can not reproduce this either. The DNS seems to only have 1 entry, so if that server is unreachable via your network or overloaded for some period of time, retrying might work.

I also noted that the response I got back was that I was blocked for abusing the service. Maybe it's seeing your headers (which include the `python-requests` name and version) and throttling you to disincline you from abusing the service? A different client with different `User-Agent` headers and a different machine (with a different IP) would not trigger the abuse detection.

Either way, this isn't a bug in Requests but a problem between you and OpenStreetMap
