### ISSUE TITLE
I hope the send method of the Session Object can support the Request Object

### ISSUE THREAD

**Issue by MengMengDeLiLaoShi** [psf/requests#5935]
I will define multiple Request objects in advance, define the request data and parameters in the Request object, and then want to send the Request through the send method of session, but the send method requires preparedrequests object. 

Why not convert the Requests object into a PreparedRequests object when sending

**Comment by sigmavirus24** [comment]
Because there's a different API that's been explicitly defined and well-documented for this and we're not changing it. This project is under a feature-freeze and the API is quite stable. Changing this would destabilize it.

**Comment by MengMengDeLiLaoShi** [comment]
Thank you for your quick reply. Can you clarify what "a different API" is？
