### ISSUE TITLE
request and response to bytearrray and back

### ISSUE THREAD

**Issue by mijosch** [psf/requests#5937]
Hi,
i want to make a encrypted tunnel and therefore I need to convert request/response to a bytearray, encrypt the bytearray, transport it, decrypt it and then recreate the request/response from bytearray.

So i need a to_bytearray() and a from_bytearray() for both, request and response

**Comment by sigmavirus24** [comment]
Start with #969 this library is under a feature-freeze. New features and API surface area are not being added
