### ISSUE TITLE
how to get the dict in server ?

### ISSUE THREAD

**Issue by ucasiggcas** [psf/requests#5945]
server:
```
app = flask.Flask(__name__)
@app.route("/http/",methods=['GET','POST'])
def tryOnce():
    params = flask.request.data.decode("utf-8")
    print(params)
```
request:
```
params={'appid': '123', 'checkin_type': '6', 'role': '1', 'stunum': '158122','keys':{"k1":'1',"k2":'2',"k4":4}}
requests.post(url3,params,headers={"Content-Type":"application/json"}).json()
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
