### ISSUE TITLE
requests with Retry, unexpected kwarg allowed_methods 

### ISSUE THREAD

**Issue by jly36963** [psf/requests#5946]
I want to retry on failed POST requests (questionable pattern, I know). I tried using the `allowed_methods` kwarg in Retry and got an error.

## Expected Result

I expect the `allowed_methods` to work, and to allow for retries on POST requests. 

## Actual Result

 I tried the kwarg with both `requests.packages.urllib3.util.retry.Retry` and `urllib3.util.retry.Retry`. both resulted in the same error:
```
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

## Reproduction Steps

```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
# from urllib3.util.retry import Retry

with requests.Session() as r:
    max_retries: Retry = Retry(
        total=3,
        backoff_factor=240,  # factor * (2 ** (num_of_retries - 1))
        status_forcelist=[500, 502, 503, 504, 520, 524],
        allowed_methods=frozenset(['GET', 'POST'])
    )
    r.mount('http://', HTTPAdapter(max_retries=max_retries)) 
    r.mount('https://', HTTPAdapter(max_retries=max_retries))

    # make request
    # raise for status
    # etc

```

## System Information

Mac, Big Sur, Version 11.5.2

### relevant Pipfile details

requests = "==2.22.0"
python_version = "3.6"

### python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.12"
  },
  "platform": {
    "release": "20.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
You need to be using urllib3 1.26+ to use `allowed_methods`. I recommend upgrading your Requests and urllib3 versions.

**Comment by jly36963** [comment]
Thank you for the prompt response! I'm using a cloud environment with locked versions, so I can't upgrade. I found the old parameter, so all is well.
