### ISSUE TITLE
Wrong JSON output!

### ISSUE THREAD

**Issue by kransk** [psf/requests#5949]
If I make a request using Python3 requests lib - the JSON output is completely wrong. But if I make the same response using other language or cURL or Postman or others.. All is good.
I think it's the body decoding trouble in Python3, because all is good using JavaScript request or others... 
 
## Expected Result

```python
print(r.json().get('offer').get('state').get('mileage')) # Should be 170000
```

## Actual Result

```python
print(r.json().get('offer').get('state').get('mileage')) # But its 199000! Wtf?
```

## Reproduction Steps

```python
import requests

url = {
    'url': 'https://apiauto.ru/1.0/offer/cars/1105235269-6558d30b?rid=225',
    'headers': {
        "X-Authorization": "Vertis ios-62ca2575df9c74b3958d118afcbb7602",
    },
}

r = requests.get(**url)
print(r.json().get('offer').get('state').get('mileage')) # Try make this the same request in e.g. Postman, the mileage should be 170000 
```

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.6"
  },
  "platform": {
    "release": "19.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.24.0"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

You can confirm what is being returned to you by looking at `r.text`. I suspect you'll see `199000` in the response making this an issue with the server.

**Comment by kransk** [comment]
@sigmavirus24 No. Its not the easy-fix problem. I tried a lot of stuff - from requests headers to response raw bytes. Moreover if python version is 3.4 - everything is ok. I think there is an error in decoding, but I dont know where

**Comment by sigmavirus24** [comment]
@kransk you've given no details to actually prove this is a requests bug. We rely heavily on the standard library. If there's actually an issue decoding somewhere it's likely there.
