### ISSUE TITLE
Requests verify cannot take multiple ssl_ca certs 

### ISSUE THREAD

**Issue by pghole** [psf/requests#5952]
Summary.
Like the ```http.client``` library, in which we can use the ```load_verify_locations()``` multiple times for multiple ca certs can be added. The python requests cannot take multiple certs for the ```verify``` parameter

## Expected Result
All the certs should be taken in account for SSL verification.

What you expected - I expected to verify against multiple certs.

## Actual Result

What happened instead -SSL verify failed.

## Reproduction Steps

```python
import requests
crt1 = '/path_to_cert1'
crt2 = 'path_to_cert2'
requests.get(url, verify=crt1)
or requests.get(url, verify=crt2)

# Cannot give both paths somehow.

```

## System Information

    $ python -m requests.help

```
I am using a linux machine.
```
**If this is not supported, is there any way to do that ??**

**Comment by pghole** [comment]
How is this "Add doc build requirements for RTD # 5956"  related to this issue ?

**Comment by sethmlarson** [comment]
This is a restriction of urllib3 which only allows configuring TLS on pool creation, not per request. Closing this issue as we can't do anything here.
