### ISSUE TITLE
autodoc type hints and intersphinx aren't working with the `requests` public API

### ISSUE THREAD

**Issue by bhrutledge** [psf/requests#5954]
It looks like autodoc is resolving type hints like `requests.Response` to their internal definition, e.g. `requests.models.Response`. This means the intersphinx references to the [Requests API docs](https://docs.python-requests.org/en/latest/api/) don’t work, resulting in build messages like `WARNING: py:class reference target not found: requests.models.Response`.

Originally reported as https://github.com/sphinx-doc/sphinx/issues/9653, but reported here as suggested in https://github.com/sphinx-doc/sphinx/issues/9653#issuecomment-939272975:

> It seems the document of requests was built by Sphinx-1.8.5. So an index entry for `requests.models.Reponse` is not generated. This problem will be resolved by upgrading Sphinx to 4.0 or newer. https://readthedocs.org/projects/requests/builds/14778070/

## Expected Result

It'd be nice if the types for `requests` classes in argument defaults and parameters were linked to the Requests documentation.

## Reproduction Steps

I put an example repo with instructions up at https://github.com/bhrutledge/sphinx-requests-typehints, generated via [sphinx-apidoc](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html). The rendered docs are at https://sphinx-requests-typehints.readthedocs.io/en/latest/example_package.html.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.5"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.2"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.7"
  },
  "platform": {
    "release": "20.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "101010cf"
  },
  "urllib3": {
    "version": "1.26.6"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @bhrutledge, it looks like we're just using the versions provided out of the box by RTD. I've put up a PR (#5956) to add a requirements.txt file for the docs using the latest version (4.2.0). It builds fine locally, so it appears fine for us to move.

**Comment by sigmavirus24** [comment]
Closing with #5956

**Comment by bhrutledge** [comment]
Confirmed that this is working as desired:

https://sphinx-requests-typehints.readthedocs.io/en/latest/example_package.html
https://twine.readthedocs.io/en/latest/internal/twine.commands.upload.html

Thank you!

**Comment by tk0miya** [comment]
Good to know :-)
