### ISSUE TITLE
Change the Repo Description (short) on GitHub

### ISSUE THREAD

**Issue by http-samc** [psf/requests#5955]
The GitHub repository description (homepage, top left) has a small but noticeable grammatical error.

Currently, it is "A simple, yet elegant HTTP library." However, in the README, you can see the grammatically correct version "A simple, yet elegant, HTTP library."

Please add the comma after "elegant" and save my sanity.

**Comment by nateprewitt** [comment]
Hi @http-samc, I've updated the description to keep ourselves consistent. I'll preface this by stating I'm not a professional editor, but I'm not certain the original change in the README was "more correct". These are coordinating adjectives, and have no strict requirement to be followed by another comma.

Either way, rest easy, I hope there wasn't too much distress ;)

**Comment by http-samc** [comment]
Thanks! 💯
