### ISSUE TITLE
Post file upload Content-Length always 0

### ISSUE THREAD

**Issue by MPW1412** [psf/requests#5957]
When uploading a file via post, the content-length is always zero, which might cause problems.

## Expected Result
Properly calculate content-length as e. g. `pycurl` does.

## Actual Result
`Header Content-Length 0`

## Reproduction Steps

```python
import requests

heads = { 'Authoriziation': 'Bearer ...'
          'Content-Type': 'multipart/form-data',
          'Accept': 'application/json'
        }

files = { 'file': ('dummpy.pdf', open(filename, 'rb'), 'application/pdf') }
ret = requests.post('https://my.apiendpoint.io/jadajadajada',
          files=files, headers=heads)

```

## System Information

```
$ python3 --version
Python 3.8.10
$ pip3 list|grep requests
requests               2.23.0
```
Best,
Matthias

**Comment by sigmavirus24** [comment]
This works for me. Although, i don't specify the `Content-Type` header because Requests must manage that.

Pleas elet us know if you have additional information about how to reproduce this

**Comment by MPW1412** [comment]
Thanks for the hint about leaving out `Content-Type`. Surprisingly to me that works, contradicting the API documentation:

https://developers.lexoffice.io/docs/#vouchers-endpoint-upload-a-file-to-a-voucher

**Comment by sigmavirus24** [comment]
That API documentation is poorly written. `multipart/form-data` requires a boundary. Curl may add it to the header for you (I don't care to verify that theory) but Requests assumes that you know better and doesn't modify it, so it generates the content and your server can't handle it.
