### ISSUE TITLE
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

### ISSUE THREAD

**Issue by wyhhyw123** [psf/requests#5960]
I am trying to download 100GB+ files using requests.get. To avoid out of memory, i set stream = True, and read data from response using iter_content。 For example:
![image](https://user-images.githubusercontent.com/63039413/137586862-57b5ab5a-f2b2-4bf4-a3b3-64a6a9e2e707.png)

but i got this error,  requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)).

How to solve this problem

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
