### ISSUE TITLE
HTTPS proxies not working with Python's requests module

### ISSUE THREAD

**Issue by Temp666-b** [psf/requests#5961]
Summary

We try request module with below code spinet 

Our Proxy srver running on https
```

import requests
url = 'https://google.com'
roxies = {'https': '10.x.x.x:443'}
if __name__ == '__main__':
    print(url)
    print(roxies)
    response = requests.get(url, proxies=roxies)
    if response.status_code == 200:
        print(response.text)
    else:
        print ('Response ERROR', response.status_code)
```
Same connection we tried from curl its working fine.
`   curl -v -x https://10.x.x.x:443 https://google.com
` 

## Expected Result
Request module should connect to proxy server over https

What you expected.

Request module should connect to proxy server over https

## Actual Result

Request module giving following error while connecting to proxy server over https
OSError('Tunnel connection failed: 400 Bad Request')))

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by Temp666-b** [comment]
python --version
Python 3.7.7

**Comment by sigmavirus24** [comment]
Hi there,

Thanks for reaching out. Unfortunately, there's too little detail in this issue to be able to help you and it's not reproducible. That indicates a likely problem in your environment which we are not responsible for debugging and which the maintainers of this project do not have the time to help you with. As a result, I'm closing this issue.

In the future, please search **closed and** open issues before creating new ones that are duplicates.
