### ISSUE TITLE
Disable url encoding for multipart/form data

### ISSUE THREAD

**Issue by ogre2007** [psf/requests#5967]
curl -F allows to upload multipart for raw data w/o encoding - as bytes
how to disable it for files being sent via `request.post(..., files = files)`?
I know that one can send it with `request.post(...data=data)`, but if you do so, there will be no special `Content-Disposition` and boundaries data, and you should put them on your own, thats not handy at all.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by ogre2007** [comment]
`Unfortunately, it seems this is a request for help instead of a report of a defect in the project`
I tried to find answer there, but seems like requests lib lacks this feature, so in fact his is not only a request for help, but feature request too.

**Comment by ArVar** [comment]
I'm very interested in a clarifacation or a better documentation regarding such cases. I ran into some problems exactly because of this issue.
EDIT:
Found this one: https://franklingu.github.io/programming/2017/10/30/post-multipart-form-data-using-requests/
