### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by skakarl2** [psf/requests#5981]
When running a python program, I see the following error: It is only happening sometimes, not sure why.

One thing I found is using requests 2.5.3, fixes this issue - but using latest versions like 2.22.0 throws the above error.

I looked into code difference and found there's no else condition in adapters.py in latest versions of requests (it is present in 2.5.3). It looks like a bug to me. Is that intentional? If so, how can I solve this issue?

This is the error and else condition that's missing:

```
   return session.request(method=method, url=url, **kwargs)
 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
   resp = self.send(prep, **send_kwargs)
 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
   r = adapter.send(request, **kwargs)
 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
   raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

```
      else:
         # All is well, return the connection to the pool.
              conn._put_conn(low_conn)
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
