### ISSUE TITLE
url "schema" should be "scheme"

### ISSUE THREAD

**Issue by DanLipsitt** [psf/requests#5984]
https://github.com/psf/requests/blob/590350f8d094c216051510ed1dd18fe871b53b72/requests/models.py#L388-L392

I don't believe the first part of a URL is ever called a "schema." Exceptions and error messages referring to an incorrect schema are confusing, especially in contexts where actual schema errors are possible. If it isn't possible to change the `MissingSchema` exception (it looks like it is slated to be fixed in 3.x) please consider at least changing the error message.

References:
https://www.w3.org/Addressing/URL/url-spec.txt
https://github.com/psf/requests/issues/4495

**Comment by nateprewitt** [comment]
Hi @DanLipsitt,

We agree the minomer isn't great and did address this in #2961 as you've noted. I'm open to reviewing a PR, although that too has an argument for whether it's "breaking". I'm not sure how the other maintainers feel on the subject.

**Comment by sigmavirus24** [comment]
There's a backwards compatible way to change the exception class that's not great. The message is definitely safe to change though
