### ISSUE TITLE
Response hook does not accept user supplied arguments

### ISSUE THREAD

**Issue by abelcheung** [psf/requests#5985]
Currently response hook does not accept any user supplied arguments. The keyword argument supplied to response hook is a dict of fixed keys generated by `Session.request()`:

https://github.com/psf/requests/blob/590350f8d094c216051510ed1dd18fe871b53b72/requests/sessions.py#L537-L544

It would be more versatile if user supplied data can be made available to response hooks, without resorting to global variables or subclassing (both Session and HTTPAdapter), only because method signatures don't have `**kwargs`. 

About use cases... for example, validation on request body/file is done before sending request, and response hook behaves differently according to such validation result. It doesn't make sense to repeat such validation again from within response hooks, especially when it is expensive.

I can try working on a PR if it's desirable.

## System Information

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.7"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.12"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "101010cf"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
Quoting https://github.com/psf/requests/blob/main/.github/ISSUE_TEMPLATE/Feature_request.md

> Requests is not accepting feature requests at this time.
