### ISSUE TITLE
ssl handshake fail for timing out

### ISSUE THREAD

**Issue by Long199for** [psf/requests#5997]
My sample is this:

import requests
host = "https://api.kucoin.com/api/v1/market/candles?symbol=BTC-USDT&type=1min"
r = requests.request('GET', host, timeout=30)
print(r.json())

I expect that the candle data would be returned as json. While I got this each time:

Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\xxxxx\AppData\Roaming\Python\Python37\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.kucoin.com', port=443): Max retries exceeded with url: /api/v1/market/candles?symbol=BTC-USDT&type=1min (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out')))

While if I use:

import urllib.request
web = 'https://api.kucoin.com/api/v1/market/candles?symbol=BTC-USDT&type=1min'
req = urllib.request.Request(web)
data = urllib.request.urlopen(req).read().decode("utf-8",'ignore')
print(data)

I could get these candle data (time is about 10 seconds, if you wonder).

This web site could be open and returned data on chrome or with urllib. Since the market data could NOT need the auth parts. I wonder why I got this for requests. Same issues happened for me on website: https://api.bybit.com/spot/quote/v1/kline?symbol=ETHUSDT&interval=1m

**Comment by sigmavirus24** [comment]
You have a proxy configured, ostensibly in your environment, that we can't connect to. It's in your exception message.

This is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
