### ISSUE TITLE
Python requests library call works on Windows but not Linux... WHY?

### ISSUE THREAD

**Issue by doverradio** [psf/requests#6005]
Long time user of python requests here. Trying to do a simple call to this endpoint: 
`https://www.overstock.com/api/product.json?prod_id=10897789`

My current code:
```
import requests

headers = { 'User-Agent': 'Mozilla/5.0', 'Accept': 'application/json' }
url = 'https://www.overstock.com/api/product.json?prod_id=10897789'
r = requests.get( url, headers=headers )
result = r.json()
print( result )
```

## Expected Result
(Shortened)
```
{'categoryId': 244, 'subCategoryId': 31446, 'altSubCategoryId': 0, 'taxonomy': {'store': {'id': 1, 'name': 'Rugs', 'apiUrl': 'https://www.overstock.com/api/search.json?taxonomy=sto1', 'htmlUrl': 'https://www.overstock.com/Home-Garden/1/store.html'}, 'department': {'id': 3, 'name': 'Casual Rugs'...
```

## Actual Result

Unfortunately, from that same script on Linux, I am not getting the identical result. So far I am stumped as to why this is happening...

Here is the ugly Linux error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/online-project-7j1lNF7P/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

## Reproduction Steps

```
import requests

headers = { 'User-Agent': 'Mozilla/5.0', 'Accept': 'application/json' }
url = 'https://www.overstock.com/api/product.json?prod_id=10897789'
r = requests.get( url, headers=headers )
result = r.json()
print( result )

```

## System Information

1. Windows 10
2. Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-163-generic x86_64)

**Comment by nateprewitt** [comment]
Hi @doverradio,

Something is triggering the server to return a non-JSON response when calling the service on Linux. Using the `json()` api requires that the payload be valid json, and you may need to add code to verify that before invoking `json()`. You're likely encountering some form of bot detection which is changing the response for Linux.

Unfortunately this isn't an issue with Requests. We'd recommend opening an issue on StackOverflow if you're interested in finding alternative solutions to your issue. Thanks!
