### ISSUE TITLE
No Error when iteration over streamed content randomly stops

### ISSUE THREAD

**Issue by AplhaSlayer1964** [psf/requests#6007]
## Expected Result
An error is thrown when iterating over streamed content and the connection is closed/timed out by server.

## Actual Result
Iterating over streamed content randomly think it has all the content when it doesn't.

## Reproduction Steps
If you try to use this function to download a large file with and the download speed is slow it will sometimes eventually just think it has completed writing all the content when it has not. I have tried including different headers and it didn't prevent this from happening. Sorry if this doesn't count as a bug, I can not find any similar issues online.

edit: found that setting chunk_size=1 on a large video file will have the same effect as a slow connection.

```python
import requests

def requests_download(url:str, file_name:str):
    responce = requests.get(url=url, stream=True)
    with open(file_name, 'wb') as f:
        for chunk in responce.iter_content(chunk_size=1024):
            f.write(chunk)
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {        
    "version": "4.0.0"
  },
  "cryptography": {   
    "version": ""     
  },
  "idna": {
    "version": "2.10" 
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.5"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.4"
  },
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
In no case do we raise an error when a server sends less data than they promised, streaming or otherwise. Further, we don't raise an error when it sends more than it promised. Case in point, if a server compresses its response, the Content-Length header will be the length of the compressed response. If we raised an error after decompressing that the lengths were different, that would be nonsensical.
