### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by unjello** [psf/requests#6013]
Requests cannot be installed under Python 3.10. Python 3.10 removed importing abc from collections directly.

## Expected Result

Successful `pip install requests`

## Actual Result

```
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

## Reproduction Steps

```sh
pip install requests

```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.9"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.0"
  },
  "platform": {
    "release": "5.10.60.1-microsoft-standard-WSL2",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @unjello, this is not an issue with Requests. As you can see from the provided stacktrace, this is an old copy of requests vendored in `pipenv`. You'll need to either upgrade your version of `pipenv` to one that supports Python 3.10 or file a ticket in the [pypa/pipenv](https://github.com/pypa/pipenv) repo to get support.

**Comment by unjello** [comment]
Hey, sorry for the alarm. You're absolutely right. I have for some reason changed manually installed `pipenv` to `apt` installed one, which happened to be (surprise, surprise) old. I haven't connect the dots so I thought it was requests fault when I tried to install it in a new project :)
