### ISSUE TITLE
requests 2.26.0 is forbidding NaN values in JSON

### ISSUE THREAD

**Issue by micdestefano** [psf/requests#6014]
It is not possible to send NaNs (and I suppose also Infinity) double values through JSON.
The cause is in file https://github.com/psf/requests/blob/main/requests/models.py, where, at line 473, you have `allow_nan=False`.
Please restore the previous behavior, because it is now impossible for me to pass NaNs to computational microservices that need NaNs to mark not recorded values.
Setting `allow_nan=True` fixes the issue.
If this is not possible, at least allow the user to specify this flag from request calls.

Thanks.
Best regards.

## Expected Result

It should be possible to pass NaNs (and +/- Infinity) as numeric floating point values.

## Actual Result

An exception is raised every time I have a NaN into a floating point value.

## Reproduction Steps

```python
import requests
import numpy as np

input_dict = { 'value': np.nan }
endpoint = 'whatever is your endpoint'

requests.post(endpoint,json=input_dict)

```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "charset_normalizer": {
    "version": "2.0.6"
  },
  "cryptography": {
    "version": "2.8"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.10"
  },
  "platform": {
    "release": "5.11.0-43-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010106f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
99.9% of people don't need or want `NaN` and those that do can serialize the data themselves, e.g.,

```py
import json

import requests
import numpy as np

input_dict = { 'value': np.nan }
endpoint = 'whatever is your endpoint'

requests.post(endpoint,data=json.dumps(input_dict), headers={"Content-Type": "application/json"})
```

**Comment by kc-fiddler** [comment]
@sigmavirus24 it's often times not in our control as to whether a `NaN` or an `inf` can be transformed to something else.

In addition, I think this is a regression between 2.25.1 and the newer versions. The `requests` package supported `NaN` and `inf` in 2.25.1 and moving to 2.26.0+ is causing brokenness. So, exposing a knob to help users who were dependent on that behavior is reasonable? Thoughts?

**Comment by sigmavirus24** [comment]
I've expressed my thoughts. Further, requests is in feature freeze and the tiniest but if looking into past similar issues shows a consistent attitude - if you don't like how requests encodes your request data in any given format, the are documented ways to do it yourself. Knobs will not be added
