### ISSUE TITLE
Auth is rarely working for anything

### ISSUE THREAD

**Issue by 108806** [psf/requests#6016]
I find this module pretty much useless as for its auth:

```
# Even the example from the docs is not working:
In [36]: requests.get('https://api.github.com/user', auth=('108806', 'my_password'))
Out[36]: <Response [401]>
In [37]: with requests.Session() as sess:
    ...:     print ( requests.get('https://api.github.com/user', auth=('108806', 'my_password')).status_code )
Out[37]: <Response [401]>
```

Also, a lot of websites are returning 200 on everything, so how can I know if I'm logged or not?
Idk, checking cookies? Some sites are working without any, with ie JWT.
But even with the simplest scenario this module can't log me in when I pass the correct credentials on 9/10 of websites.

**Comment by nateprewitt** [comment]
Hi @108806, thanks for the feedback. It sounds like there may be some misunderstandings about how authentication works in the HTTP protocol. You'll find Github [hasn't supported Basic Auth](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/) for almost 2 years, which is the behavior you're observing.

We'd recommend doing some reading on how HTTP auth works and directing further questions to StackOverflow. We won't be able to provide support for that on this issue tracker.

**Comment by nateprewitt** [comment]
I've added #6018 to remove the current ambiguity in the documentation.
