### ISSUE TITLE
Requests doesn't add `boundary` when passing `Content-Type: multipart/form-data` header manually

### ISSUE THREAD

**Issue by verhovsky** [psf/requests#6024]
Requests with `Content-Type: multipart/form-data` need to also have a `; boundary=someUniqueString` in that header. I think this is actually true for all `multipart/*` MIME types.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#multipartform-data

This is how curl works, if you pass `Content-Type: multipart/form-data` it'll still add a boundary because users shouldn't need to know how all the HTTP headers work, that's the library's job. We are running into this issue when trying to convert curl commands into requests code https://github.com/curlconverter/curlconverter/issues/248 and it would be convenient if Requests did the same thing as curl.

I don't see why anyone would ever want to pass `Content-Type: multipart/form-data` without a `boundary`, unless they just don't know about it. If you do actually need to not have a boundary you would have to explicitly add an empty one `; boundary=` to your header. But I can also see how it might surprise users that even if they pass a header manually it gets modified. 

## Expected Result

Requests still adds a `boundary` to my header if I don't, i.e. when I pass `headers={'Content-Type': 'multipart/form-data'}` and `files=`

## Actual Result

Requests uses the header as-is and the request fails.

## Reproduction Steps

```pycon
>>> import requests
>>> 
>>> files = {
...     'hello': (None, 'world'),
... }
>>> requests.post('http://example.com', files=files).request.headers['Content-Type']
'multipart/form-data; boundary=498931185311c522b8ca559425b2b965'
>>> 
>>> headers = {
...     'Content-Type': 'multipart/form-data',
... }
>>> 
>>> requests.post('http://example.com', headers=headers, files=files).request.headers['Content-Type']
'multipart/form-data'
```

Compare with curl:

```sh
$ curl -vvv example.com -H "Content-Type: multipart/form-data" -F "hello=world"
[...]
> Content-Type: multipart/form-data; boundary=------------------------ff92aa2ea98d6cc3
```

**Comment by nateprewitt** [comment]
Hi @verhovsky,

Thanks for reaching out. I believe you may be looking for something like the [MultipartEncoder](https://toolbelt.readthedocs.io/en/latest/user.html) which is part of the [Requests Toolbelt](https://github.com/requests/toolbelt) package. We don't provide this directly through Requests and I'm not sure we have intentions to change that currently. That would be our recommendation for what you're currently trying to accomplish.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
