### ISSUE TITLE
How do i request this full page?

### ISSUE THREAD

**Issue by John-ison** [psf/requests#6040]
When I request this page
`https://dictionary.writtenchinese.com/#sk=yi&svt=pinyin`
I only get half of it.

Is there a way to get the search results as well?

**Comment by nateprewitt** [comment]
Hi @John-ison, Requests isn't a browser and won't execute JavaScript which is likely the issue you're hitting. We can't provide general web troubleshooting support on this issue tracker though. Your best option is to check https://StackOverflow.com for what you're trying to do.
