### ISSUE TITLE
I got the following error  ImportError: cannot import name 'FastAPI'

### ISSUE THREAD

**Issue by themeswordpress** [psf/requests#6045]
[cymetricx@ip-172-31-30-0 fast]$ sudo python3 -m pip install fastapi
Collecting fastapi
  Using cached fastapi-0.72.0-py3-none-any.whl (52 kB)
Requirement already satisfied: starlette==0.17.1 in /usr/local/lib/python3.6/site-packages (from fastapi) (0.17.1)
Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2
  Using cached pydantic-1.9.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.0 MB)
Requirement already satisfied: anyio<4,>=3.0.0 in /usr/local/lib/python3.6/site-packages (from starlette==0.17.1->fastapi) (3.5.0)
Requirement already satisfied: contextlib2>=21.6.0 in /usr/local/lib/python3.6/site-packages (from starlette==0.17.1->fastapi) (21.6.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/site-packages (from starlette==0.17.1->fastapi) (4.0.1)
Requirement already satisfied: dataclasses>=0.6 in /usr/local/lib/python3.6/site-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi) (0.8)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.6/site-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi) (3.3)
Requirement already satisfied: contextvars in /usr/local/lib/python3.6/site-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi) (2.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.6/site-packages (from anyio<4,>=3.0.0->starlette==0.17.1->fastapi) (1.2.0)
Requirement already satisfied: immutables>=0.9 in /usr/local/lib64/python3.6/site-packages (from contextvars->anyio<4,>=3.0.0->starlette==0.17.1->fastapi) (0.16)
Installing collected packages: pydantic, fastapi
Successfully installed fastapi-0.72.0 pydantic-1.9.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[cymetricx@ip-172-31-30-0 fast]$ python3 fastapi2.py 
Traceback (most recent call last):
  File "fastapi2.py", line 2, in <module>
    from fastapi import FastAPI
  File "/home/cymetricx/fast/fastapi.py", line 11, in <module>
    from fastapi import FastAPI
ImportError: cannot import name 'FastAPI'

**Comment by sigmavirus24** [comment]
This has nothing ot do with the library requests.

**Comment by siphr** [comment]
I have the same problem! Version 0.74.0.
