### ISSUE TITLE
Invalid Response Code (409) when "alertId" key is received in response body. 

### ISSUE THREAD

**Issue by PinchofLogic** [psf/requests#6047]
When the body of a valid response contains a Key of "alertId", like below:

{
    "Key1": "Value1",
    "Key2": "Value2",
    "alertId": "XX-6MH-QZ0-C8G-HC5-YYY"
}
The value of status_code throws 409 error.

response.status_code == 409

## Expected Result

response.status_code == 200

## Actual Result

response.status_code == 409

## Reproduction Steps

    try:
        response = requests.patch(
            "https://XXXXXX,
            headers=my_header,
            params=query,
            json={
                "Key": "Value"
            }
        )
 response.raise_for_status()

## System Information

AWS Lambda Python 3.9 runtime.

**Comment by sethmlarson** [comment]
This behavior you're seeing is not something we can control, Requests is only the messenger between your code and the server you're contacting. You'll have to read their documentation to see why you're receiving that status code.

**Comment by PinchofLogic** [comment]
Hi Seth,

Its an API that generate alert IDs when it receives requests. On postman,
we get the whole body with HTTP 200.
Even via Python 3.9 the "requests" library returns the correct data as long
as we do not use "response.raise_for_status()".

I noticed that if the response does not have the custom key of "alertId"
everything works well. In this case, even if the "alertId" is a custom
field in the body, "response.raise_for_status()" treats it as a HTTP
response code.

Regards,
Kuldeep Saxena

**Comment by nateprewitt** [comment]
Hi @PinchofLogic,

`raise_for_status()` is specifically for raising an exception on non-200 status codes. 409 is the service in question letting you know that there is some conflict with the resource. It may return relevant data in the response, but you'll need to check. If you don't want Requests to throw an exception for non-200 status codes, you'll want to remove that line from your code.

For more help with AWS products, I'd recommend reaching out to [AWS Support and Customer Service](https://aws.amazon.com/contact-us/). This isn't an issue with Requests and we won't be able to provide further help.
