### ISSUE TITLE
Request JSON body in custom auth contains extra spaces

### ISSUE THREAD

**Issue by AnilRedshift** [psf/requests#6049]
The request.body argument of custom auth is different than the bytes that the server receives when using json. Specifically, when inside the custom auth handler, the request.body includes spaces, e.g. `{"myKey":<SPACE>"myValue"}` where the final request sent does not include this space.

This is a problem for custom auth which tries to hash the body and add that as a header, as the hash will not match

## Expected Result
See the demo code below. The main issue is that if you pass in json=(someJson) then inside of MyCustomAuth r.body contains a string (well really bytes but...) which include spaces. However, the final request sent does not include spaces. I would expect the payload to match.

For the demo code below, x-hash returns
x-hash is f667340ebfa34b192bc594772679c8d461eb5455022442cdfcdb21ba30bdf0d5 which is the hash of `{"myKey":<SPACE>"myValue"}`

## Actual Result

the actual HTTP body has a hash of 090150119e53c870ca0da54fe88605c6ed57139e068d0ccbd2483ae212ea383b which is the hash of `{"myKey":"myValue"}` (no space)

## Reproduction Steps

```python
import requests
import requests
from hashlib import sha256

class MyCustomAuth:
  def __call__(self, r):
    r.headers['x-hash']=sha256(r.body).hexdigest()
    return r

requests.post('https://example.com', json={"myKey": "myValue"}, auth=MyCustomAuth())
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.10"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.1"
  },
  "platform": {
    "release": "5.15.12-1-MANJARO",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.27.1"
  },
  "system_ssl": {
    "version": "101010df"
  },
  "urllib3": {
    "version": "1.26.8"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by intentionally-left-nil** [comment]
Ah. Actually the client is doing the correct thing, but it's the server middleware that's changing the request body. Sorry for the noise
