### ISSUE TITLE
Timeline for v3.0

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#6050]
Is there a timeline on 3.x?  or is it dead?

**Comment by nateprewitt** [comment]
Hi @achapkowski, we don't have any timelines to share on a new major version.

In the event one is released, I'd like to temper expectations that it will not resemble what was originally promised by previous maintainers. We don't have the resources currently to deliver on those changes.

**Comment by achapkowski** [comment]
@nateprewitt thank you for the update.
