### ISSUE TITLE
why requests speed is very slow in same environment!

### ISSUE THREAD

**Issue by JmeterChen** [psf/requests#6052]
when i get response by curl !
![image](https://user-images.githubusercontent.com/34080816/151486453-01cb38d7-f8e0-4077-aaca-d1bbd4b24962.png)

when i get response by requests !
![image](https://user-images.githubusercontent.com/34080816/151486473-a8229d51-bc98-4153-9df7-ffc6e55ff7e1.png)

**Comment by sethmlarson** [comment]
Please fill out the template when creating an issue.

You can't compare two completely different tools in two different ways and expect a result that makes sense. If you need the performance that curl provides then use curl.

Also noting you're running an ancient version of Python, try upgrading for some free speedups.
