### ISSUE TITLE
Help! RemoteDisconnected('Remote end closed connection without response') 

### ISSUE THREAD

**Issue by hmzakhalid** [psf/requests#6055]
I'm using residential proxies from https://www.dreamproxies.io/ 
The proxies seem to be all live, checked it on multiple proxy checkers but i keep getting Proxy error
`HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))`

**Here's my code:**
```
import requests
try:
    proxies = {
        "http": 'http://unuzedbo1ioiwulwi:tQ7ix5yUWIKcvJFR_country-UnitedStates_session-nFfLZIfX@basic.unuzedproxies.com:31112',
        "https": 'http://unuzedbo1ioiwulwi:tQ7ix5yUWIKcvJFR_country-UnitedStates_session-nFfLZIfX@basic.unuzedproxies.com:31112'
    }
    r = requests.get('https://www.google.com/', proxies=proxies)
    print(r.status_code, "Proxy works")
except Exception as e:
    print(e)
```

**Here're two more proxies to test on.**
`http://unuzedbo1ioiwulwi:tQ7ix5yUWIKcvJFR_country-UnitedStates_session-Edgl75qB@basic.unuzedproxies.com:31112`
`http://unuzedbo1ioiwulwi:tQ7ix5yUWIKcvJFR_country-UnitedStates_session-G86KAwKw@basic.unuzedproxies.com:31112`

**Output for: `python -m requests.help`**
```
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.10"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.2"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.27.1"
  },
  "system_ssl": {
    "version": "101010df"
  },
  "urllib3": {
    "version": "1.26.8"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

Further, you have patted credentials into a public issue and should revoke those as quickly as you can to prevent abuse
