### ISSUE TITLE
Is there anyway that I can set system proxy using requests on Windows?

### ISSUE THREAD

**Issue by cugcuiyc** [psf/requests#6061]
When I get a url by setting proxy in requests, it doesn't change the proxy on my computer.
 How can I change the global proxy on my computer so that I can always use this proxy next time ?
  I know how to set proxy to my computer manually. I want to do that by coding.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
