### ISSUE TITLE
How to set multi same key in request header

### ISSUE THREAD

**Issue by djerryz** [psf/requests#6063]
To Bypass some WAF, I Wanna Send a Malformed HTTP request like this:
```
POST /123123 HTTP/1.1
Host: a.b.com
Hello: hello1
Hello: hello2

a=b
```
Request have two same key in headers.

Try:
```
headers = [('interests', 'football'), ('interests', 'basketball')]
headers = {'interests': ['football', 'basketball']}
```
are all execept.

Try:
```
from urllib3._collections import HTTPHeaderDict
headers = HTTPHeaderDict()
headers .add('interests', 'football')
headers .add('interests', 'basketball')
```
The request will be :
```
POST /123123 HTTP/1.1
Host: a.b.com
interests: football, basketball
```

Please help me to know , how to set same key with diff value in request header, thanks.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
