### ISSUE TITLE
Migrate test suite to support Flask>2.0

### ISSUE THREAD

**Issue by nateprewitt** [psf/requests#6070]
As shown in #5846 and #6069, our test suite is now thoroughly broken from Flask 2.0 onwards. We never did a deep dive to understand what caused the breakage and now changes in the underlying modules (markupsafe, werkzeug) are causing further problems. We need to sit down and work out the issue, unblocking upgrading Flask if possible.

**Comment by mgorny** [comment]
Ping.

**Comment by nateprewitt** [comment]
Resolved in #6496.
