### ISSUE TITLE
Problem with cert between python2 and python3

### ISSUE THREAD

**Issue by luanon404** [psf/requests#6073]
**My package i used**
+ requests: 2.27.0
+ openssl: 1.1.1m 2021
+ certifi: 2021.10.8

**Problem**
+ python2: can use param cert=**("cert.pem", "cert.key")** or add **br** to Accept-Encoding (python2 only has gzip and deflate), headers={"Accept-Encoding: "gzip, deflate, **br**"} to access cloudflare checking
+ python3: i used same method but seem like it is not working

i tried to fix the requests module but its still not working, if you know anything please tell me, your every word is a good suggestion :)

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
