### ISSUE TITLE
How to uinstall requests library using setup.py?

### ISSUE THREAD

**Issue by ashokchandran** [psf/requests#6080]
We are in a factory environment where we cannot use pip. 
We installed request library using python install setup.py.
Is it possible to uninstall requests library using setup.py. Please share the command.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
