### ISSUE TITLE
Connection broken: InvalidChunkLength error when adding custom request header value with uuid4()

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [psf/requests#6082]
When using UUID v4 as a value for the custom request header in POST request I am facing with error:
`{"errorMessage": "(\"Connection broken: InvalidChunkLength(got length b'', 0 bytes read)\", InvalidChunkLength(got length b'', 0 bytes read))", "errorType": "ChunkedEncodingError", "requestId": "844e5761-df0d-4627-8fc3-484bb35cd28d", "stackTrace": ["  File \"/var/task/handlers/mw_request.py\", line 23, in lambda_handler\n    mw_response = requests.post(\n", "  File \"/opt/python/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n", "  File \"/opt/python/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 687, in send\n    r.content\n", "  File \"/opt/python/requests/models.py\", line 838, in content\n    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\n", "  File \"/opt/python/requests/models.py\", line 763, in generate\n    raise ChunkedEncodingError(e)\n"]}`

## Expected Result

Successful POST request

## Actual Result

Got the error:
{"errorMessage": "(\"Connection broken: InvalidChunkLength(got length b'', 0 bytes read)\", InvalidChunkLength(got length b'', 0 bytes read))", "errorType": "ChunkedEncodingError", "requestId": "844e5761-df0d-4627-8fc3-484bb35cd28d", "stackTrace": ["  File \"/var/task/handlers/mw_request.py\", line 23, in lambda_handler\n    mw_response = requests.post(\n", "  File \"/opt/python/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n", "  File \"/opt/python/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 529, in request\n    resp = self.send(prep, **send_kwargs)\n", "  File \"/opt/python/requests/sessions.py\", line 687, in send\n    r.content\n", "  File \"/opt/python/requests/models.py\", line 838, in content\n    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\n", "  File \"/opt/python/requests/models.py\", line 763, in generate\n    raise ChunkedEncodingError(e)\n"]}

## Reproduction Steps

```python
import requests
import uuid
response = requests.post(
        config.api_url + "/external/customers",
        json={"request": {"customers": customer}},
        headers={"Troy-Correlation-Id": str(uuid.uuid4()}, # here is my custom request header
        auth=(
            config.username,
            config.password,
        ),
    )
```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by nateprewitt** [comment]
Hi @Bakhtiyar-Garashov,

I don't believe this is directly related to your supplied header. The server is responding claiming chunked encoding and violating the protocol. We'd need to see the bytes coming across the wire to confirm, but I don't believe there's anything for Requests to do here. If you are able to retrieve the response with a tool like Wireshark AND confirm the response is properly formatted, feel free to reopen.
