### ISSUE TITLE
Is there any disconnection detection exist on Stream feature?

### ISSUE THREAD

**Issue by VahidTa** [psf/requests#6092]
I have a post request to a stream API server. I tried to simulate disconnection during streaming. However, in my case, if I disconnect my connection to the API server which streams data, "requests" continues without breaking the connection or raising any exceptions. Is there any help to overcome this issue? Or is there a feature needs to be added to this kind of scenario?

**Comment by nateprewitt** [comment]
Hi @VahidTa,

If you're receiving incomplete data from the broken connection and no error, this is likely an issue in urllib3 that's been [fixed](https://github.com/urllib3/urllib3/pull/2514) in the upcoming urllib3 2.0. We don't have control over detecting this in Requests unfortunately though.

**Comment by VahidTa** [comment]
I think it is good idea to have "keep-alive" like mechanism for connection status in streaming.
