### ISSUE TITLE
request.get adds %20 to the end of the link and gives a 404 error

### ISSUE THREAD

**Issue by Turkmen1Mehmet** [psf/requests#6093]
I am browsing the links from a list, the links are working, the headers are also defined, but when I send a request with requests.get, the response returns 404. When I look at it with debug, it adds %20 to the end of the main url, so the links are broken and the error returns. How do I solve this?
i am giving an example
mylink= https://example.net///2022/V/0/1/p/2710/583/742/2/w/2048/2710583742_6_2_1.jpg?ts=1645610622959
error= https://example.net///2022/V/0/1/p/2710/583/742/2/w/2048/2710583742_6_2_1.jpg?ts=1645610622959%20

**Comment by nateprewitt** [comment]
Hi @Turkmen1Mehmet,

Please make sure to read the issue template before filing new issues. We won't be able to help with general usage questions on this issue tracker, those will need to be directed to [StackOverflow](https://stackoverflow.com/). Generally speaking, %20 denotes whitespace, so you'll likely want to take a close look at your url string.
