### ISSUE TITLE
Requests not returning full html

### ISSUE THREAD

**Issue by YeetmanLord** [psf/requests#6099]
When using requests.post/get(url...) The html that is returned by using request.content/request.text is not the full html.

For example I am trying to code a bot that will get data from a website called investopedia. This html is cut short and does not return the same html that can be seen in inspect element.

## Reproduction Steps

```python
import requests

with open("test.html", "w") as file:
    file.write(requests.get("https://www.google.com/").text)

If you compare the html of test.html to the actual google it is very different
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "charset_normalizer": {
    "version": "2.0.12"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.6"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.27.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.24.2"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @YeetmanLord, please check open and closed issues before filing new ones. You'll find most servers either truncate or completely change content for scrapers to reduce bandwidth or access. This is the behavior you're encountering with Google. The content you receive is still a complete and valid html file.
