### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [psf/requests#6100]
A potential security vulnerability has been disclosed for this repo https://huntr.dev/bounties/2c5789ab-213c-4568-9380-683d0612f1aa/ 3 months ago .
But i see it still not addressed .
Kindly validate the bug

**Comment by nateprewitt** [comment]
@ranjit-git we don't have an interest in third-party applications which require access to personal information to view the vulnerability.

Please follow our [security disclosure instructions](https://docs.python-requests.org/en/latest/community/vulnerabilities/).

**Comment by ranjit-git** [comment]
@nateprewitt huntr.dev team already sent you the report details  to provided email in https://docs.python-requests.org/en/latest/community/vulnerabilities/ .
You should have received the report details in mail already . In that mail there is a magick unique link , by using this you can view the report details without signup . In mail just search for "https://huntr.dev" .
I will ask the admin  to send the report details again .

**Comment by ranjit-git** [comment]
https://huntr.dev/ is opensource bugbounty platform running since last 2.5 year
