### ISSUE TITLE
Session.close() doesn't work within WSL2

### ISSUE THREAD

**Issue by RoadToDream** [psf/requests#6105]
## Actual Result

I have a nodejs server uses session to store user login info and the auth will immediately invalidated after session closed. However, it still has access to the server after session closed. 
## Reproduction Steps

```python
import requests
s=requests.Session()
url_login = 'http://localhost:8080/login'
url_postStatus = 'http://localhost:8080/postStatus'
loginInfo={'UserEmail':test@test.test','UserPassword':'test'}
s.post(url_login,data=loginInfo)
s.post(url_postStatus)
s.close()
s.post(url_postStatus)
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.0.12"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.2"
  },
  "platform": {
    "release": "5.10.16.3-microsoft-standard-WSL2",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.27.1"
  },
  "system_ssl": {
    "version": "101010bf"
  },
  "urllib3": {
    "version": "1.26.9"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
This isn't a bug. You haven't read the documentation to understand what session.close does

**Comment by RoadToDream** [comment]
> This isn't a bug. You haven't read the documentation to understand what session.close does

Hi @sigmavirus24 , it's my bad that I didn't understand what session.close does. As I read from the documentation, quotes here: "Closes all adapters and as such the session". If that doesn't mean invalidate the current session, I guess I totally misunderstand the purpose of this method.
May I ask what is the appropriate way to close the current session?
