### ISSUE TITLE
What is the correct way to pass the proxy username and proxy password ?

### ISSUE THREAD

**Issue by pghole** [psf/requests#6112]
Hey,

After reading and trying out many things, I am confused how the proxy username and password is passed in the follows -

proxy = {'https' : 'http://{username}:{password}@host:port',
              'http': 'http://{username}:{password}@host:port' }
requests.get(url, proxies=proxy)

1. Do I have to use quote() from urllib.parse to encode the username and password before making the proxy dict ?
2. My username , password having "@" sign works fine without encoding, Still do I have to encode for any other chars ?

Version
requests = 2.20.0
urllib3 = 1.24.2

**Comment by nateprewitt** [comment]
Hi @pghole,

It's not clear from the post if you're encountering an issue or asking for general information about URL syntax. You can find the relevant information on URL syntax in the [RFC](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1). Requests will simply proxy along whatever characters you provide, so as long as they conform to the RFC 3986 specification, we'd expect them to work.

**Comment by pghole** [comment]
@nateprewitt, I am interested in knowing the behaviour of request library and how the username/password is passed to the proxies dictionary

For example -(having special chars)
username = "username@#$"
password = "password@#"

which of the following is correct ?

'http://{username}:{password}@host:port'. format(username, password)

OR
from urllib.parse import quote
'http://{username}:{password}@host:port'. format(quote(username), (password))

**Comment by sigmavirus24** [comment]
@nateprewitt has answered your question then
