### ISSUE TITLE
Requests taking too long or stucking ( GNU-Linux ) 

### ISSUE THREAD

**Issue by CarloCattano** [psf/requests#6124]
requests are taking more than 1 minute to process if they succeed at all on 2 of my linux machines at home . 
On windows a simple : 
```
>>> import requests as r
>>> r.get("http://google.com")
```
takes miliseconds , 
on debian bullseye takes more than 1 minute for simple requests,
and sometimes they are "freezing"

Any hints on how to debug this welcome.
I just upgraded to latest and still the issue persist

**Comment by sethmlarson** [comment]
This isn't debuggable without a packet capture or logs, can you provide those? You can use Wireshark to capture packets and look at the timings.

**Comment by CarloCattano** [comment]
I added a small timeout and its fixed now. Thanks for the hint
