### ISSUE TITLE
Ability/option to automatically handle `Retry-After` in responses.

### ISSUE THREAD

**Issue by stevecj** [psf/requests#6160]
I am aware that "Requests is not accepting feature requests at this time." but am asking anyway.

Currently, there are many APIs that use the `Retry-After` header for throttling, but API client code generally does not take that into account. When thinking about how I would suggest adding throttling to atlassian-python-api, I realized that, just like following of redirects, this might make more sense to handle at a lower level in the Requests library.

**Comment by nateprewitt** [comment]
Hi @stevecj, this is already possible in Requests. We don't implement any of the Retry behavior, that comes from urllib3.

You can see in our adapter that we take a [`max_retries`](https://github.com/psf/requests/blob/2a6f290bc09324406708a4d404a88a45d848ddf9/requests/adapters.py#L140) argument that take an int to instantiate a urllib3 [`Retry`](https://github.com/urllib3/urllib3/blob/23af17403c965a90d98cd13785ed385db6b022e6/src/urllib3/util/retry.py#L92) object.

By default, Requests does not retry. If you'd like to enable that functionality, create a Session, re-mount a new HTTPAdapter instance with your Retry and you're set. Note that Retry has an explicit [`respect_retry_after_header`](https://github.com/urllib3/urllib3/blob/23af17403c965a90d98cd13785ed385db6b022e6/src/urllib3/util/retry.py#L257) which is defaulted to True.

e.g.
```python
import requests

adapter = requests.adapters.HTTPAdapter(max_retries=3)
s = requests.Session()
s.mount('http://', adapter)
s.mount('https://', adapter)
```
