### ISSUE TITLE
> ![Screenshot_2020-06-15-21-55-17-097_com termux](https://user-images.githubusercontent.com/66963067/84682209-f15ffc00-af52-11ea-9d3c-78b7bded9f57.jpg)

### ISSUE THREAD

**Issue by 7Kyra** [psf/requests#6161]

**Comment by nateprewitt** [comment]
Hi @7Kyra, this isn't an issue with Requests but a general Python question. You'll need to ensure the key you're retrieving exists. If you have further questions please open a question on [StackOverflow](https://stackoverflow.com).
