### ISSUE TITLE
How to write python script setting system-wide http proxy using requests

### ISSUE THREAD

**Issue by 1nrho12** [psf/requests#6164]
Hello,

I've written a Python script exporting http proxy:

```
import os

proxy = "http://proxy:port"

os.environ['http_proxy'] = proxy
os.environ['HTTP_PROXY'] = proxy

```

But the thing is that I want to set the http proxy on system wide without exporting the environment variables using the requests library.

How to do that? I am Python newbie.. Please help.

**Comment by 1nrho12** [comment]
I am using macOS by the way.

**Comment by malnjayz** [comment]
I don't have a mac to test this but I did find this answer from [stackoverflow](https://stackoverflow.com/a/39934154).
According to that I would set the proxy like this:
`os.system("networksetup -setwebproxy Ethernet {} {}".format(url, port))`
You can check the [networksetup documentation](https://keith.github.io/xcode-man-pages/networksetup.8.html) for more infos.

**Comment by 1nrho12** [comment]
Thank you for your answer. 
I executed the script but it has returned the following error:

```
Traceback (most recent call last):
  File "networksetup on.py", line 9, in <module>
    Proxy_on()
  File "networksetup on.py", line 7, in Proxy_on
    os.system('networksetup -setwebproxy Wi-Fi '+proxy+' '+port)
TypeError: can only concatenate str (not "int") to str
```

This is the script:

```
import os

proxy = "http://127.0.0.1"
port = 8080

def Proxy_on():
    os.system('networksetup -setwebproxy Wi-Fi '+proxy+' '+port)

Proxy_on()
```

**Comment by nateprewitt** [comment]
Hi @1nrho12, it appears this isn't related to Requests but rather a general Python question. We'd ask you move this to a platform like [StackOverflow](https://stackoverflow.com/). We try to reserve the issue tracker for Requests defects as responses to this issue emails 1400 people.
