### ISSUE TITLE
redirect https://requests.readthedocs.io/en/master to https://requests.readthedocs.io/en/latest

### ISSUE THREAD

**Issue by graingert** [psf/requests#6168]
the old https://requests.readthedocs.io/en/master page links to an old v2.26.0 with broken algolia search https://github.com/psf/requests/issues/5254 https://github.com/psf/requests/issues/6142 and is linked to by search engines and other documentation 

https://www.google.com/search?q=requests+readthedocs
https://developer-portal.driver-vehicle-licensing.api.gov.uk/apis/vehicle-enquiry-service/code-examples.html#python-using-requests
https://github.com/search?q=requests.readthedocs.io%2Fen%2Fmaster&type=code

**Comment by nateprewitt** [comment]
Thanks for letting us know, @graingert. I've tried a few things with prefix redirects but they don't work as one might expect. I found a pattern for exact redirects that appears to have most URLs migrated to /en/latest. The base url without a trailing slash (https://requests.readthedocs.io/en/master) doesn't appear to work with any combination though. If anyone has ideas, I'm willing to try them.

Given almost all relevant URLs appear to be forwarding correctly now, I'll resolve this.

**Comment by graingert** [comment]
The first hit on Google redirects here https://readthedocs.org/projects/requests/ which doesn't seem right

**Comment by graingert** [comment]
@dvla can you update your links?

**Comment by nateprewitt** [comment]
> The first hit on Google redirects here https://readthedocs.org/projects/requests/ which doesn't seem right

Hmm, this may be personalized based on geolocation or account. I'm seeing https://requests.readthedocs.io/en/latest/ as the first link on Google. I'm not sure what our options are to affect SEO on ranking though. If you have ideas, I'm happy to give them a try.

Edit: I'm also seeing the https://developer-portal.driver-vehicle-licensing.api.gov.uk/apis/vehicle-enquiry-service/code-examples.html#python-using-requests links working correctly. Is that not what you're seeing?

**Comment by graingert** [comment]
Yeah it's much much better than it was, thanks for fixing this!

Hopefully the SEO link juice will percolate through soon
