### ISSUE TITLE
[Debian Bullseye 11] Get calls take almost 3 minutes on some websites

### ISSUE THREAD

**Issue by willbprog127** [psf/requests#6176]
On Debian Linux Bullseye 11 AMD64, Requests.get() calls take almost 3 minutes on some websites.  

I tried several websites, but these two are good contrasts:
`r = requests.get("https://www.pismotek.com")`
`r = requests.get("https://www.github.com")`

## Expected Result
When doing a `requests.get()` call, I expect that it should take one or two seconds for the call to complete if the website I'm trying to contact is reasonably responsive.

## Actual Result
Some websites cause `requests.get()` to take almost three minutes to complete. 

## Reproduction Steps
This call causes a near three-minute wait until completion, and the website IS responsive and working well using other OSs:
```python
import requests

r = requests.get("https://www.pismotek.com")
```
I tried with `https://www.microsoft.com`, `https://www.youtube` as well as `https://www.apple.com` and they took a long time too.

This call only takes about one second:
```python
import requests

r = requests.get("https://www.github.com")
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.2"
  },
  "platform": {
    "release": "5.10.0-15-amd64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "101010ef"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_pyopenssl": false
}
```

* Debian Bullseye 11 Linux - AMD 64
* Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] on linux

### Wireshark pcapng files:
I did the best I could to filter out non-relevant data, but some could be there...
[requests-fail-pismotek-com.pcapng.tar.gz](https://github.com/psf/requests/files/8984259/requests-fail-pismotek-com.pcapng.tar.gz)
[requests-okay-github-com.pcapng.tar.gz](https://github.com/psf/requests/files/8984260/requests-okay-github-com.pcapng.tar.gz)

Thanks!  :+1:

**Comment by lovecoding32** [comment]
Hello Will!

If you are having a interceptor running in the background (Such as WireShark or Fiddler etc) you will have to do:

```python
import requests

r = requests.get("https://www.pismotek.com", verify=False)
```

or alternatively, try adding a timeout

```python
import requests

r = requests.get("https://www.pismotek.com", timeout=5)
```

finally if the solutions above do not work please do this for me:

first just curl the url and see if the request goes through or takes a while like in Python, if it does go through fine then check if you have iPv6 enabled on your machine.

Tell me how it goes!

**Comment by willbprog127** [comment]
@lovecoding32 Thanks for the reply.

> If you are having a interceptor running in the background (Such as WireShark or Fiddler etc) you will have to do

I don't usually have an interceptor or capture running, it was only for the benefit of reporting this issue

> first just curl the url and see if the request goes through or takes a while like in Python, if it does go through fine then check if you have iPv6 enabled on your machine.

curl works fine on both example websites mentioned in the issue.  Also, yes, IPv6 is enabled on the local network and internet connection.

Trying with `verify=False` works near-instantaneously, but I do get this warning repeatedly.  I don't know why it warns as the pismotek.com certificate is perfectly valid:
```
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.pismotek.com'. Adding certificate verification is strongly advised.
```

Thank you! :smile:

**Comment by lovecoding32** [comment]
It is because verify=False tells to skip SSL check on pismotek, however it is not recommended to use it this way unless you are sure that there is no malicious content on the site.

However, have you installed the security package for requests?

`pip3 install -U requests[security]`

try that then remove verify=False in your code.

Cheers.

**Comment by willbprog127** [comment]
Hi again @lovecoding32 ,

Based on your suggestion, I tried installing `python3-openssl` which then allowed me to remove the `verify=False` and now no more three-minute delays.  

I wish Debian had set this as a requirement along with `python3-requests` so other Debian users wouldn't run into this issue.  I will close this now.

@lovecoding32 , thanks so much for your help! :+1:
