### ISSUE TITLE
Werkzeug importing failed

### ISSUE THREAD

**Issue by Khabibulix** [psf/requests#6189]
Heya to all,

I already check Internet before botherin you all. Here's the deal: i installed all the requirements.txt and i wanted to launch the tests, but i raise an _**ImportError**_ with _**werkzeug.wrappers**_. Here is the complete error:

![Sans titre](https://user-images.githubusercontent.com/80721211/176997660-9ca8d709-4610-4c1f-93f4-948b428ac946.png)

Here is my Pip List:

![Sans titre](https://user-images.githubusercontent.com/80721211/176997804-cf619a8a-41f3-42ff-b6fe-4ccbc100fead.png)

So i upgraded Pip, i changed the version for werkzeug, i searched Google for answers but, the solutions that i found are not correct for my case. I'll be glad if someone could help me, i really want to:

- Run the tests

- Contribute to Requests

- Become the best programmer

But just not seeing that error will make me happy.

Thanks for reading and good day!

**Comment by AryanHamedani** [comment]
Hello there,
 I've read your issue and the werkzeug code,
 there is a command in their code that might help you
`    .. versionchanged:: 2.0
        Combine ``BaseResponse`` and mixins into a single ``Response``
        class. Using the old classes is deprecated and will be removed
        in Werkzeug 2.1.`
I think you should try :
`from Werkzeug.wrappers import Response`
Hope that helps you, 
GoodLuck 👍🏼

**Comment by sethmlarson** [comment]
Unfortunately we don't have time to help people debug their developer environments. You should ask on StackOverflow or do some additional learning about managing Python environments.
