### ISSUE TITLE
[2.28.1] IncompleteRead errors on large file download using iter_content (working 2.28.0)

### ISSUE THREAD

**Issue by Moandco** [psf/requests#6191]
Receiving ChunkedEncodingErrors with IncompleteRead while receiving a reponse with a large binary using transfer-encoding: chunked.

## Expected Result

A response with a large binary body (500MB+) send using `transfer-encoding: chunked` with the appropriate header gets processed in steps using `inter_content` without error. 

Behavior as it was in 28.0.0.

## Actual Result

The processing fails with a random number of missing bytes raising `ChunkedEncodingError (Connection Broken: IncompleteRead(X bytes read, Y bytes more expected))`

## Reproduction Steps

Send a request to an endpoint returning a large binary (500MB+) in the reponse body using transfer encoding chunked.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "5.0.0"
  },
  "charset_normalizer": {
    "version": "2.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.10"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "101010df"
  },
  "urllib3": {
    "version": "1.26.9"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}

```

**Comment by nateprewitt** [comment]
Hi @Moandco, could you provide some more information on the issue?

A few questions that are raised immediately are

a.) is this specific to a single server/service or broadly reproducible?
b.) is this error happening consistently with every large download?
c.) if it is consistent, downgrading immediately resolves the issue?


There was a minor change with iter_content in 2.28.1 but it should be largely cosmetic. The ChunkedEncodingError comes from a ProtocolError in urllib3 which has always been possible. We haven’t changed anything around that logic.

**Comment by Moandco** [comment]
The issue is caused by the server-side. The package upgrade was a coincidence. Thanks for your time.
