### ISSUE TITLE
Incorrect work of requests

### ISSUE THREAD

**Issue by beqabeqa473** [psf/requests#6194]
For some reason, making request via requests library forces a site to return page for enterring captcha.
The same request made with urllib gives expected result.

## Expected Result
The same response as made with urllib, i.e. get a full page response

## Actual Result
Request made with requests caused to get a response with captcha

## Reproduction Steps

```python
import requests

url = "https://yandex.ru/pogoda/tbilisi"

headers = {"Host": "yandex.ru"}

resp = requests.get(url, headers=headers, verify=False)
print(res.text
```

```python
import urllib.request

req = urllib.request.Request("https://yandex.ru/pogoda/tbilisi")
res = urllib.request.urlopen(req)
print(res.read()))
```

## System Information

    $ python -m requests.help

```json
{

  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.9"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.26.9"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false

  "paste": "here"
}
```

**Comment by beqabeqa473** [comment]
I suspect it is something related with ssl, because, when i decided to capture traffic from these two methods and compare, i was using httpdebugger and their certificate.
In this case everything worked as expected.

**Comment by nateprewitt** [comment]
Hi @beqabeqa473, the service you're trying to connect to is performing user-agent fingerprinting and rejecting your requests. This is done by a number of services to prevent webscraping with common tools like Requests. We won't be able to provide help with that on this issue tracker though.

**Comment by beqabeqa473** [comment]
Hello.

Yes, of course i know about user-agent, and i passed correct user-agent from my browser as a header, but it redirects to captcha page.

I was seeing something similar earlier with requests, and in that case also, i was not able to reproduce issue with http debugger with enabled https encryption.
