### ISSUE TITLE
request google search news fails

### ISSUE THREAD

**Issue by vagosbas** [psf/requests#6222]
when i run this code
monitored_tickers = ['GME', 'TSLA', 'BTC']
![image](https://user-images.githubusercontent.com/112481361/187419609-584b04eb-1b7e-4d6c-aefb-da8112282d11.png)

i get these results
![image](https://user-images.githubusercontent.com/112481361/187419717-fc2f955a-7346-443f-9e9d-f19bc1072d20.png)

why doesn't return the urls ?
is the problem in the request statement or in google account ?

i am using the greek version of chrome, and i am in greece .

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
