### ISSUE TITLE
Posting with data seems to truncate the response

### ISSUE THREAD

**Issue by fredericoschardong** [psf/requests#6227]
Posting with data over SSL truncates the response. For example take this `app.py`:

```python
from flask import Flask
app = Flask(__name__)

@app.route('/', methods=["GET", "POST"])
def hello_world():
    return {"access_token": "aa" * 50000}
```

Running with `python3 -m flask run --cert=adhoc`. 

PS: It works as expected without SSL;
PS 2: Using GET produces the same behaviour;

## Expected Result

The following two snippets should return the same result (i.e. `100020`):
```python
>>> import requests
>>> len(requests.post('https://127.0.0.1:5000/', verify=False).content)
100020
>>> len(requests.post('https://127.0.0.1:5000/', data={'a':'b'}, verify=False).content)
100020
```

## Actual Result
However, if I add some data to the request, the response is truncated.
```python
>>> import requests
>>> len(requests.post('https://127.0.0.1:5000/', verify=False).content)
100020
>>> len(requests.post('https://127.0.0.1:5000/', data={'a':'b'}, verify=False).content)
81920
```

Curl produces the correct result:
```bash
$ curl -s -k -X POST https://127.0.0.1:5000/ -H 'Content-Type: application/json' -d '{"a":"b"}' | wc -m
100020
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "4.0.0"
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.4"
  },
  "platform": {
    "release": "5.15.0-46-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @fredericoschardong, Requests isn't able to change the response from the server. If different inputs are resulting in different outputs, that's a product of your flask application. I'd recommend taking a look at the contents of the response for differences.

It's also important to note your curl request and Requests call are not the same. `data` is `application/x-www-form-urlencoded` not json. We'd recommend checking on [StackOverflow](https://stackoverflow.com/) for further assistance with debugging.

**Comment by fredericoschardong** [comment]
Hey @nateprewitt. Thanks for the reply. I have used `curlify` to fix the curl request. It still produces the expected result, while `Requests` does not:

```
curl -s -k -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 3' -H 'Content-Type: application/x-www-form-urlencoded' -H 'User-Agent: python-requests/2.28.1' -d a=b https://127.0.0.1:5000/ | wc -m
100020
```

Upon further investigation, as you suggested, `urllib3` might be to blame:
```python
>>> requests.post('https://127.0.0.1:5000/', data={'a':'b'}, verify=False).raw.tell()
81920
```
