### ISSUE TITLE
`❯` character becomes `â¯` in data after post

### ISSUE THREAD

**Issue by pcroland** [psf/requests#6231]
Code: https://github.com/pcroland/deew/blob/main/dev_scripts/post/doom9.py
On other sites it worked fine but on this site it changed the input character to gibberish. I guess it's related to urlencoding.

If I urlencode
```
Help:
❯ deew -h
```
urlencoder.org creates
```
Help%3A%0A%E2%9D%AF%20deew%20-h
```
while chrome creates
```
Help%3A%0A%u276F%20deew%20-h
```
Is there a way to mimic how Chrome encodes it?

**Comment by verhovsky** [comment]
The "`%u276F`" in "`Help%3A%0A%u276F%20deew%20-h`" that you say you're getting from Chrome is not url encoding, something somewhere is getting broken, possibly you are converting the string to its JavaScript representation and then url encoding that. You should ask this question on [StackOverflow](https://stackoverflow.com/) and make sure to share more details about what exactly you are doing when you say "chrome creates" to help others debug your issue.

Your issue has nothing to do with Requests.

**Comment by nateprewitt** [comment]
Hi @pcroland, it looks like this is a request for help. The question here doesn't appear to be related to a defect in Requests. We'd suggest making a post on [StackOverflow](https://stackoverflow.com/) to get further assistance.

**Comment by pcroland** [comment]
requests encodes this character differently than Chrome and Firefox, isn't it possible that it's a bug?

**Comment by nateprewitt** [comment]
If you have a minimal reproducible example showing a defect in Requests, please provide more details.

What's currently been provided doesn't have any clear indication there's a defect.

**Comment by pcroland** [comment]
requests uses normal urlencoding while Firefox and Chrome uses unicode escape for this character and apparantly some sites don't like the regular urlencoding for this character (and possibly others).

**Comment by ghost** [comment]
According to https://stackoverflow.com/q/912811/492203 it's a non-standard escape method that has been rejected by the W3C, but as we know Chrome has the monopoly... Maybe it would be worth adding it as an option. Here's some code I threw together quickly for it:

```py
import urllib.parse


def urlquote_chrome(text: str, *_: Any) -> str:
    escaped = (
        urllib.parse.quote(text, encoding="unicode-escape")
        .replace("%5Ca", "%07")
        .replace("%5Cb", "%08")
        .replace("%5Cf", "%0C")
        .replace("%5Cn", "%0A")
        .replace("%5Cr", "%0D")
        .replace("%5Cu", "%u")
        .replace("%5Cv", "%0B")
        .replace("%5Cx", "%")
    )

    # These are probably not needed but just in case
    escaped = re.sub(r"%[a-f0-9]{2}", lambda m: m[0].upper(), escaped)
    escaped = re.sub(r"%u([a-f0-9]{4})", lambda m: f"%u{m[1].upper()}", escaped)

    return escaped


r = session.post(
    url=url,
    data=urllib.parse.urlencode(data, quote_via=urlquote_chrome),
)
```
