### ISSUE TITLE
Can not send json and files same as data and files

### ISSUE THREAD

**Issue by sssanikhani** [psf/requests#6233]
Some scenarios with requests can not be done straightforward.
For example when I want to send json and files in multipart form, I use `data` and `files` parameters in requests method.
But if data has some `None` values, it will be dropped from request body. So for this problem I use `json` parameter instead of `data`.
Now with `json` parameter, `files` parameter will overwrite request body and json body will be removed from request.

## Expected Result

I want to send json and files with multipart form request, while json body has some None values.

## Actual Result

This expectation can not be done straightforward. Some solutions are messy and will change request body to another schema. like [this](https://stackoverflow.com/a/35946962/11926259)

## Reproduction Steps

```python
import requests
data = {"key": None}
requests.patch(url, json=data, files=files_data)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": "3.4.8"
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.4"
  },
  "platform": {
    "release": "5.15.0-47-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30000020",
    "version": "21.0.0"
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "1.26.5"
  },
  "using_pyopenssl": true
}

```

**Comment by sigmavirus24** [comment]
That's not how this works and it's documented as multipart only working with data and files parameters. If you need to send JSON inside a multipart field you need to encode it yourself and pass it to data with a field name.
