### ISSUE TITLE
Documentation Translation Guide

### ISSUE THREAD

**Issue by kennethreitz** [psf/requests#624]

**Comment by toutouastro** [comment]
Yes we need it because I might translate the documentation to arabic sometime

**Comment by kennethreitz** [comment]
@toutouastro that would be fantastic!

**Comment by kennethreitz** [comment]
Japanese is underway: http://ja.python-requests.org

**Comment by toutouastro** [comment]
The summer break is coming and I'll hack on this project a lot this summer !

**Comment by serpulga** [comment]
How popular is `requests` among the Hispanic community?

**Comment by kennethreitz** [comment]
Awesome! I cannot wait :)

**Comment by serpulga** [comment]
Any advise on how I should start?

**Comment by qoh** [comment]
I'd be willing to do a Danish translation.

**Comment by kennethreitz** [comment]
Thanks for the all the help, guys! 

I created a bunch of repos here: https://github.com/requests

I've created a new 'Translations Team', and added all of you to it. You should be able to push to any of the translation repositories. :)

:sparkles: :cake: :sparkles:

**Comment by serpulga** [comment]
Am I doing it right?
What do I need to do to have the Spanish version published like the Japanese one? (http://ja.python-requests.org)

Thanks

**Comment by duailibe** [comment]
@kennethreitz any chance for a Portuguese repository? :)

**Comment by kennethreitz** [comment]
@duailibe are you volunteering? :)

**Comment by duailibe** [comment]
@kennethreitz yes! :)

**Comment by kennethreitz** [comment]
I'm on it!

**Comment by kennethreitz** [comment]
@duailibe thanks so much! Just push here :) https://github.com/requests/requests-docs-pt

**Comment by serpulga** [comment]
That's funny. A lot of translating going on, but the translating guide never got written. 
I'm basically translating anything under docs/

**Comment by duailibe** [comment]
@kennethreitz awesome! Thanks! :cake:

**Comment by omederos** [comment]
@serpulga I'd like to contribute to the Spanish translation too. I see you're doing it now, but I think some things have to be changed, and I'd also like to help you finish the entire translation if you haven't. What should be the procedure?

**Comment by serpulga** [comment]
Hi @omederos. I think regular git-flow / pull requests would be the way to go.
I think I pushed the one document that was left, and I honestly don't know
what's next. Let's see if we can get some pointers from @kennethreitz  for the
other translators.

Thanks,

Sergio

**Comment by Kwpolska** [comment]
I’d love to help out with Polish.  Requests is awesome and it needs more docs translations.

**Comment by kennethreitz** [comment]
@Kwpolska all set! Let me know when you have an update so I can make it official :)

https://github.com/requests/requests-docs-pl

Thanks so much :)

**Comment by galihmelon** [comment]
Can I volunteer to translate the docs to Indonesian, please?

**Comment by esparta** [comment]
Can I ask what does it need to put the spanish documentation online, @kennethreitz ? 
(Besides some update, it has 9 months old, as I see here: https://github.com/requests/requests-docs-es)

**Comment by SefaOray** [comment]
I can translate to Turkish. How do i start?

**Comment by sigmavirus24** [comment]
@deusExCore start a fork and start translating the documentation in place. When we can grab his attention, we'll have @kennethreitz add you to the requests organization and help you move your fork to github.com/requests/requests-docs-tr and then he, or I will have to set up DNS to resolve that for you

**Comment by csparpa** [comment]
Hi guys, here you have a candidate for translating the docs to Italian!
@kennethreitz @sigmavirus24 if it's a good thing, I can start working on that on a fork

**Comment by kennethreitz** [comment]
@csparpa go for it!

**Comment by csparpa** [comment]
yep :)

**Comment by csparpa** [comment]
@kennethreitz would you setup a specific repo under https://github.com/requests for the IT translation? I'll wait for that if you're going to create it

**Comment by sigmavirus24** [comment]
@csparpa please start translating and as soon as it's mostly done is when we usually import your fork into the @requests org

**Comment by csparpa** [comment]
Got it, thanks ;)

Claudio Sparpaglione
http://csparpa.github.io

**Comment by csparpa** [comment]
Hi @sigmavirus24 I'm done with the Italian translation - this is on a dedicated branch on my fork. What's the next step? Thanks

**Comment by sigmavirus24** [comment]
So now's the time when @Lukasa or @kennethreitz should add you (@csparpa) to the translators team. They also need to set up a repository for the translation and import it from your fork. I'll set up the stuff so that it appears on python-requests.org, once they've taken care of that. (I'm not an owner/admin on the @requests org so I can't do that stuff for you.)

**Comment by Lukasa** [comment]
@sigmavirus24 That's a terrible oversight, I'll add you as an admin as well.

**Comment by Lukasa** [comment]
@csparpa You are now the proud father of [one repository of Italian-translated docs](https://github.com/requests/requests-docs-it)!

**Comment by Lukasa** [comment]
And it gets better: http://it.python-requests.org/en/latest/

**Comment by csparpa** [comment]
:)))
Great!!!

**Comment by csparpa** [comment]
@Lukasa I'll keep on working on the translation (there are lots of typos and possible rephrasings).
Can you add the repo https://github.com/requests/requests-docs-it to the Translation Team repositories?Thanks

**Comment by Lukasa** [comment]
@csparpa Sorry, done =)

**Comment by csparpa** [comment]
No probs ;)

**Comment by pbrinkmeier** [comment]
Hi guys, I could do a translation to German!
How should I start? Fork or wait for a dedicated repo?

**Comment by Lukasa** [comment]
@reg4in I'm afraid we already have a translation [here](http://docs.python-requests.org/de/latest/). Help might be required to keep it up-to-date though!

**Comment by carlosvargas** [comment]
Hi guys, is there anything missing in order to get http://es.python-requests.org/ up and running?

**Comment by Lukasa** [comment]
That's a bit more @sigmavirus24's area of expertise. Ping ping. =)

**Comment by sigmavirus24** [comment]
@carlosvargas sorry about that. I didn't realize we were missing that. I just set up the CNAME for that so it should hopefully be fixed shortly

**Comment by csparpa** [comment]
@sigmavirus24 can I take the chance to notify that on the main Requests
page (http://www.python-requests.org/en/latest/) there is no link to the
Italian translation of the documentation (http://it.python-requests.org/) ?
;-)

Thank you

Cla

**Comment by sigmavirus24** [comment]
@csparpa I think that's merely a matter of sending a PR here to add it. ;)

**Comment by csparpa** [comment]
Of course ;) I just wanted to notify the issue so it gets tracked somewhere
but I had better track it on a github issue instead of here... Sorry guys,
I'll do it! Ciao

Cla

**Comment by pbrinkmeier** [comment]
Oh wow I somehow couldn't find it :+1:
Looks like people did a great job there

**Comment by caizixian** [comment]
@kennethreitz @Lukasa @sigmavirus24 Can help with Chinese (Simplified) and Chinese (Traditional)

**Comment by caizixian** [comment]
@kennethreitz @Lukasa @sigmavirus24 
I'm a native speaker of Chinese (Simplified) and Chinese (Traditional) .
Current translation is kinda outdated. Could you please add me to the organization, so that I can work on it?

**Comment by kennethreitz** [comment]
That would be great! The Chinese translation gets a lot of traffic.

**Comment by caizixian** [comment]
@kennethreitz Could you please add me to the organization, so that I can push my translation to the repos.

**Comment by caizixian** [comment]
@kennethreitz @Lukasa @sigmavirus24 Could you please add me to the organization, so that I can push my translation to the repos.

**Comment by yangbeom** [comment]
[https://github.com/yangbeom/requests-docs-kr](https://github.com/yangbeom/requests-docs-kr)
it's my 1st translation, so i wanna get many feedback =) if i more do something, please mention it

**Comment by Brausepaul** [comment]
Am I right that there is no direct link between the translation repos and Requests itself? If I want to add something to the German translation I can commit without having to address a specific release, e. g.?

**Comment by Lukasa** [comment]
Correct.

**Comment by ferozah83** [comment]
Hello, I'd like to translate docs to Korean. so, I start a fork and start translating. could i join here?

**Comment by kennethreitz** [comment]
@ferozah83 go for it!

**Comment by umarbrowser** [comment]
hello there me too i want to translate request to my Language Hausa can you guide

**Comment by sf4500000** [comment]
hello

**Comment by sf4500000** [comment]
hello

**Comment by sf4500000** [comment]
hello!

**Comment by sf4500000** [comment]
hello!

**Comment by sf4500000** [comment]
hello!

**Comment by sf4500000** [comment]
hello!

**Comment by sf4500000** [comment]
hello!

**Comment by sf4500000** [comment]
hello!

**Comment by kbsat** [comment]
Is this project over? If not, I would like to participate in Korean translation.

**Comment by sigmavirus24** [comment]
Given that we no longer have a domain, I think it's safe to say this is over until we find another way to provide translations
