### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by lucas-ccc** [psf/requests#6242]
## This bug does not affect usage, but it does exist
the bug code is in the "setup.py" file, line 78
here is code:
```python
with open(os.path.join(here, "requests", "__version__.py"), "r", "utf-8") as f:
    exec(f.read(), about)
```
## It's an issue about function open()
I got this from Python Documentation
```python
open(file, mode='r', buffering=- 1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
```
The argument ```"utf-8"``` should be passing by ```keyword```, but actually it's passed by ```position```, 
and the third argument is ```buffering```(a int) . 
So the system throws an ```TypeError```: 'str' object cannot be interpreted as an integer

## Fix
```python
with open(os.path.join(here, "requests", "__version__.py"), "r", encoding="utf-8") as f:
    exec(f.read(), about)
```

## Reproduction Steps
open any file with the code, you will get the TypeError.

## System Information

    TypeError: 'str' object cannot be interpreted as an integer

```python
here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, "requests", "__version__.py"), "r", "utf-8") as f:
    exec(f.read(), about)
```

**Comment by Ali-Xoerex** [comment]
The function `open()` used in this context was imported from `codecs` and is not the built-in `open()` function in Python itself.
`codecs.open(filename, mode='r', encoding=None, errors='strict', buffering=- 1)` , from [codecs official documentations](https://docs.python.org/3/library/codecs.html#codecs.open)

**Comment by Ali-Xoerex** [comment]
@sigmavirus24
I think this issue can be closed now
