### ISSUE TITLE
authentication via netrc has a different outcome than auth argument

### ISSUE THREAD

**Issue by itcarroll** [psf/requests#6246]
NASA Earthdata uses basic authentication and cookies to respond to GET requests. When I use a `Session()` in combination with a `~/.netrc` file, the session object holds the cookies and everything works. When I use a `Session()` but supply my credentials with the `auth` argument, the session cannot hold its cookies. Authentication failure results. It would be great if the `auth` argument could do whatever the session does for netrc authentication.

To reproduce, you will have to have to follow these instructions for a free account: https://disc.gsfc.nasa.gov/earthdata-login

## Expected Result

```
<Response [200]>
```
## Actual Result

```
<Response [401]>
```
## Reproduction Steps

Have a NASA Earthdata account with `<USERNAME>` and `<PASSWORD>` stored in a text file at `~/.netrc` with permissions `-rw-------` and containing the line:
```
machine urs.earthdata.nasa.gov login <USERNAME> password <PASSWORD>
```

The following returns the expected result

```python
from requests import Session

resource = 'https://reason.gesdisc.eosdis.nasa.gov/data/nobm/NOBM_DAY.R2017/2015/day20151201.R2017.nc4'
with Session() as session:
    response = session.get(resource)
response
```

The following returns the actual result
```python
from requests import Session

resource = 'https://reason.gesdisc.eosdis.nasa.gov/data/nobm/NOBM_DAY.R2017/2015/day20151201.R2017.nc4'
with Session() as session:
    response = session.get(resource, auth=('<USERNAME>', '<PASSWORD>'))
response
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": "38.0.1"
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.6"
  },
  "platform": {
    "release": "21.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "30000050",
    "version": "22.0.0"
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": true
}
```

**Comment by georgruetsche** [comment]
Maybe HTTPBasicAuth helps.. Try: 

from requests.auth import HTTPBasicAuth
auth = HTTPBasicAuth(username, password

**Comment by itcarroll** [comment]
Ah, my problem was actually #2949.

**Comment by itcarroll** [comment]
For future reference, here is a workaround. I still think it's better to use a netrc file, but if you really want to avoid it...

```python
class EarthdataSession(Session):

    def should_strip_auth(self, old_url, new_url):
        parsed_url = urlparse(new_url)
        if parsed_url.hostname == "urs.earthdata.nasa.gov":
            return False
        else:
            return super().should_strip_auth(old_url, new_url)
```

Use in place of `Session`.
