### ISSUE TITLE
requests.delete does not support body parameter

### ISSUE THREAD

**Issue by aamir-remotebaser** [psf/requests#6247]
Requests is not accepting feature requests at this time.
I just figured out that delete method does not support data payload
I have a requirement in my project that accepts json data in delete 
It actually supports in other http clients like axios for frontend but not this one when I am using with Flask
Can you please add this feature ASAP.

**Comment by sethmlarson** [comment]
Per HTTP RFC's, DELETE with a body has no defined semantics and should be avoided which is the same reasoning we don't support it natively. You can always pass `"DELETE"` and a `body` to the `request()` method yourself.
