### ISSUE TITLE
Requests stops parsing of headers after illegal space in header name.

### ISSUE THREAD

**Issue by JannisBush** [psf/requests#6249]
Spaces are not allowed in header names: https://www.rfc-editor.org/rfc/rfc9112.html#name-field-line-parsing
When requests encounters such invalid header names, it will not only throw away the invalid header, but also stops parsing all following headers.
When the invalid header comes before headers such as `Content-Length`, this can lead to requests getting stuck indefinitely.

## Expected Result

Requests ignores the invalid header (or shows/fixes it; the RFC is only defining behavior for servers and proxies, it is unclear what the correct behavior for clients is and different clients behave differently) and continues parsing of the response.

## Actual Result

Requests ignores the invalid header and all headers after the invalid one. This can lead to requests getting stuck.

## Reproduction Steps
- `pip install wptserve`: server that allows us to send invalid responses
- `python test.py`

`test.py`:
```python
import wptserve
from wptserve.handlers import handler, as_is_handler
import requests
from requests.exceptions import ConnectionError
import subprocess

http1 = wptserve.WebTestHttpd(port=8081,
                            routes=[("*", "*.asis", as_is_handler)],
                            use_ssl=False,
                            key_file=None,
                            certificate=None,
                            )
http1.start()

@handler 
def space_after_length(request, response):
    return 200, [("Content-Length", 14), ("SPACE ",'space'), ("hidden", "hidden")], '<div>ABC</div>'
http1.router.register("*", "/space_after_length", space_after_length)

@handler 
def space_first(request, response):
    return 200, [("SPACE ",'space'), ("Content-Length", 14), ("hidden", "hidden")], '<div>ABC</div>'
http1.router.register("*", "/space_first", space_first)


for path in ["/space_first", "/space_after_length"]:
    url = f"http://localhost:8081{path}"
    curl = subprocess.check_output(["curl", "-s", "-I", url]).decode("utf-8")
    try:
        r = requests.get(url, timeout=1)
        # r = requests.get(url)  # Stuck forever
        headers = r.headers
    except ConnectionError:
        headers = "Hangs forever or timeout"
    finally:
        print(f"{path}\ncurl output:\n{curl}requests output:\n{headers}\n")

```
`Output`:
```
/space_first
curl output:
HTTP/1.1 200 OK
SPACE : space
Content-Length: 14
hidden: hidden
Server: BaseHTTP/0.6 Python/3.9.6
Date: Thu, 29 Sep 2022 13:46:58 GMT

requests output:
Hangs forever or timeout

/space_after_length
curl output:
HTTP/1.1 200 OK
Content-Length: 14
SPACE : space
hidden: hidden
Server: BaseHTTP/0.6 Python/3.9.6
Date: Thu, 29 Sep 2022 13:46:59 GMT

requests output:
{'Content-Length': '14'}
```

## System Information

    $ python -m requests.help

```json                                                            
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.6"
  },
  "platform": {
    "release": "21.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
I'm 99% certain this has been reported before and has in fact a problem with http.client which we depend on, not requests.

In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by JannisBush** [comment]
I had searched for this issue including closed ones and could not find any duplicates.
After searching again, I now found a corresponding issue with a rather non-informative name: https://github.com/psf/requests/issues/3133

Indeed, it is a problem of http.client and is rather unlikely to get fixed anytime soon: https://github.com/python/cpython/issues/69725
