### ISSUE TITLE
Response library in python give me back a wrong response status code when trying to request a JavaScript file

### ISSUE THREAD

**Issue by malekmahmed** [psf/requests#6253]
<h3>Describe the bug</h3>
Hello,<br>
When I use the response library in python I get the wrong response status code but I get the right one when I use urllib.request

<br>Code Using Response library:

```
import requests
try:
    r = requests.head("https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js")
    print(r.status_code)
    # prints the int of the status code. Find more at httpstatusrappers.com :)
except requests.ConnectionError:
    print("failed to connect")
```

This URL `https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js` gives me back `404` status code even though it gives me 200 when I visit the URL in the browser and I can see the javascript response.

When I used the urllib.request library it gave back the right status code which is 200

Code Using urllib.request library:

```
from urllib.request import urlopen
urls = ['https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js','https://www.codecademy.com/idontexist.js']
results={}
for url in urls:
    try:
        ret = urlopen(url)
        if ret.code == 200:
            state="Exists"
            print(url+' : {}'.format(state))
    except:
        state="Not exists"
        print(url+' : {}'.format(state))

    results[url]=state
```

<h3>Additional context</h3>
Maybe there are more situations where this happens than just JavaSript files I didn't try more URLs.

<h3>Version of responses</h3>
0.21.0

<h3>Steps to Reproduce</h3>

1- Go to this URL https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js in your browser and you will get a 200 response.

2- Run this code and you will get 404 not found
```
import requests
try:
    r = requests.head("https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js")
    print(r.status_code)
    # prints the int of the status code. Find more at httpstatusrappers.com :)
except requests.ConnectionError:
    print("failed to connect")
```

<h3>Expected Result</h3>
The code should have given back a 200 status code.

<h3>Actual Result</h3>
The code gives back 404 a status code.

**Comment by markonose** [comment]
You are sending a HEAD request, change it to a GET request

`r = requests.get("https://www.codecademy.com/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js")`

Also you haven't even bothered to change your issue https://github.com/getsentry/responses/issues/591

**Comment by malekmahmed** [comment]
Thanks, it's working now. If may I ask why HEAD doesn't give the right status code?

**Comment by nateprewitt** [comment]
The server hasn't implemented consistent responses for different http methods. We aren't able to control this as it all happens server side.

I'm going to resolve this as it's unrelated to Requests. If you have further questions, StackOverflow is likely the best place to check.
