### ISSUE TITLE
Requests __init__.py emits warnings about version numbers

### ISSUE THREAD

**Issue by bje-** [psf/requests#6264]
## Background

I have the following package versions installed alongside requests:

```
urllib3            1.26.12
charset-normalizer 3.0.0
```
This complies with the version constraints in the requests `setup.py`.

The `__init__.py` code in requests does not match what is in `setup.py` and so warns about the versions of both of these packages. `__init__.py` wants `urllib3 >= 1.21.1, <= 1.26` and `charset_normalizer >= 2.0.0 < 3.0.0`.

## Expected Result

No warning.

## Actual Result

A slightly confusing runtime warning appears!

## Reproduction Steps

```
$ python3 -m requests.help
/home/bje/source/nemo/myenv/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.0.0) doesn't match a supported version!
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.6"
  },
  "platform": {
    "release": "5.15.0-47-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

**Comment by nateprewitt** [comment]
Hi @bje-, please check open and closed issues before opening new ones. The current release of Requests doesn't support charset_normalizer 3.0, hence the warning. It will be updated in the next release.

**Comment by bje-** [comment]
Thanks, but why isn't this reflected in `setup.py` so that `pip` would have alerted me to the issue?

**Comment by nateprewitt** [comment]
It is, the supported range in setup.py for 2.28.1 is `<3`. You've upgraded the package independently of Requests which is creating the conflict.
