### ISSUE TITLE
Using a custom CA certificate

### ISSUE THREAD

**Issue by chriskim06** [psf/requests#6267]
hi, i was hoping to use the `SSL_CERT_DIR` env var to use a custom ca, but it seems like this feature isn't actually in requests just yet based on this comment https://github.com/psf/requests/pull/2903#issuecomment-279012869. is there a way to use a custom ca with requests?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
