### ISSUE TITLE
charset-normalizer 3 is out, but unfortunately is incompatible with the current version of the requests.

### ISSUE THREAD

**Issue by thisisamirv** [psf/requests#6268]
Please support this new version.

**Comment by nateprewitt** [comment]
Please check open and closed issues before opening new ones.

**Comment by gaby64** [comment]
requests 2.28.1 requires charset-normalizer<3,>=2, but you have charset-normalizer 3.0.0 which is incompatible.

**Comment by intgr** [comment]
Already fixed in #6261, pending a release.
