### ISSUE TITLE
`content-length` is missing in headers of a `head` request while `curl` fetches it

### ISSUE THREAD

**Issue by dilawar** [psf/requests#6271]
## Expected Result

`content-length` missing in headers returned by a `requests.head` request while `curl` fetches it from the same URL. I was expecting headers to be (almost) the same whether I use `curl` or python-requests library.

## Actual Result

`content-length` doesn't show up in  the headers of a `head` request. However `curl` returns the `contrent-length`. 

## Reproduction Steps

```python
>>> import requests
>>> r  = requests.head("https://gitlab.subcom.tech/bitia/bitia-cli/-/raw/29a1d1c0d2f0aaea833d429b9bdd9aef7184db8b/README.md")
>>> r.headers
{'Server': 'nginx', 'Date': 'Wed, 26 Oct 2022 16:58:58 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Accept', 'Cache-Control': 'max-age=60, public', 'Content-Disposition': 'inline', 'Content-Security-Policy': '', 'Etag': 'W/"a6753ef41292910c06e5130c0d22bc3d"', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Frame-Options': 'SAMEORIGIN', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-Request-Id': '01GGAKQ6S9082M6NCJ7GPX3H33', 'X-Runtime': '0.122800', 'X-Ua-Compatible': 'IE=edge', 'X-Xss-Protection': '1; mode=block', 'Strict-Transport-Security': 'max-age=63072000', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Content-Encoding': 'gzip'}

>>> 'content-length' in r.headers
False
```

Note that I don't have `content-length` in the header above. However, `curl` returns `content-length` in the headers.

```bash
$ curl -I https://gitlab.subcom.tech/bitia/bitia-cli/-/raw/29a1d1c0d2f0aaea833d429b9bdd9aef7184db8b/README.md
HTTP/2 200 
server: nginx
date: Wed, 26 Oct 2022 16:59:54 GMT
content-type: text/plain; charset=utf-8
content-length: 725
vary: Accept-Encoding
cache-control: max-age=60, public
content-disposition: inline
content-security-policy: 
etag: W/"a6753ef41292910c06e5130c0d22bc3d"
vary: Accept
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 01GGAKRXFZHN4YK9F67Y5YFS6X
x-runtime: 0.068579
x-ua-compatible: IE=edge
x-xss-protection: 1; mode=block
strict-transport-security: max-age=63072000
referrer-policy: strict-origin-when-cross-origin
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.14"
  },
  "platform": {
    "release": "5.19.10-1-default",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by rollingonroad** [comment]
@dilawar you can try append the gzip enable header in your curl. you can see the same headers with requests get. so it's not issue.

David

% curl -H "Accept-Encoding: gzip" -I https://gitlab.subcom.tech/bitia/bitia-cli/-/raw/29a1d1c0d2f0aaea833d429b9bdd9aef7184db8b/README.md
HTTP/2 200 
server: nginx
date: Mon, 31 Oct 2022 17:47:55 GMT
content-type: text/plain; charset=utf-8
vary: Accept-Encoding
cache-control: max-age=60, public
content-disposition: inline
content-security-policy: 
etag: W/"a6753ef41292910c06e5130c0d22bc3d"
vary: Accept
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 01GGQJGDSPMB202JK6TAXVQMCT
x-runtime: 0.071671
x-ua-compatible: IE=edge
x-xss-protection: 1; mode=block
strict-transport-security: max-age=63072000
referrer-policy: strict-origin-when-cross-origin
content-encoding: gzip
