### ISSUE TITLE
"proxy_request_buffering off" in NGINX proxy causes ConnectionAbortedError

### ISSUE THREAD

**Issue by ercymiranda** [psf/requests#6276]
Hello guys. I've searched a lot about this error and ended up not finding any answer elsewhere. So I decided to ask here, in case anyone can help.
I'm getting this error whenever I use lib Requests on NGINX proxies with the parameter "proxy_request_buffering off" configured in nginx.conf:

The error happens when uploading any file.
At first, I take an HTTP 200 (OK) when I establish the connection and a 307 (Temporary Redirect) to send the file to the final destination.
But after a few seconds, I get the error: ConnectionAbortedError; [WinError 10053] An established connection was aborted by the software in your host machine

By Curl I can send the file normally without problems.

Any suggestions that don't involve stripping the "proxy_request_buffering off" parameter from the NGINX proxy? (I need him)

Thanks

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
