### ISSUE TITLE
downloading 125 KB file hangs lib

### ISSUE THREAD

**Issue by geetee24** [psf/requests#6284]
https://raw.githubusercontent.com/MycroftAI/mycroft-skills-data/21.02/skill-metadata.json

# hangs at this line
r = requests.get(market_info_url)
# never gets here.

Checked OS memory and have like 2 GB free.

Any clue how to fix this and me debug the lib?

is ver 2.28.1

thank you.

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com/) for general usage questions.
