### ISSUE TITLE
Move to urllib3 version 2.0.0 and Move Requests to version 2

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#6286]
With urllib3 releasing the alpha of 2.0.0, is it time to consider moving requests to version 2.0.0 and make the long standing changes that are needed to improve the library?

**Comment by nateprewitt** [comment]
Requests is already on 2.x. Thanks for the feedback, we're aware of the upcoming changes to urllib3 and are finishing up preparations for the release. We may look at major version bumping Requests at a later date but have no immediate plans.
