### ISSUE TITLE
Requests sends garbage when requesting to a web server on the same machine 

### ISSUE THREAD

**Issue by inyourface34456** [psf/requests#6287]
## Summery

When sending to a web server located on the same machine as the python code is executing, it will send garbage data on all of the fields, the request itself, exiting with the error  `Invalid SSL version`.  The server logs show what looks like garbage data.

![image](https://user-images.githubusercontent.com/62214409/202252392-8fa13e5a-91a1-4f9c-8d66-c33d21a8b703.png)

## Expected Result

I thought that it would work normally and just send a normal web request rather then garbage data.

## Actual Result

It sent a lot of garbage data and the server returned Status Code 400.
## Reproduction Steps
Shell Commands:
```bash
python -m http.server 8080
```
Python Code:
```python
import requests

requests.get('https://0.0.0.0:8080')

# you could also use https://127.0.0.1:8080, and https://localhost:8080 and you will get the same result. Using HTTP protocol also produces the same result. 
```

## System Information

    $ python -m requests.help

```json
{
  {
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.12"
  },
  "platform": {
    "release": "5.15.0-1021-gcp",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "101010df"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

}
```

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com/) for general usage and network fundamentals questions.
