### ISSUE TITLE
JS Render

### ISSUE THREAD

**Issue by KHannnnn05** [psf/requests#6293]
Greetings to all! I have a suggestion to create the possibility of rendering js scripts in requests. Yes, I know that there is a requests-html project, but it is abandoned, and somehow you need to cope with js

**Comment by JakobDev** [comment]
Requests is just a lib for (as the name suggests) http requests.Not more. It is not a Browser and will never be. You should take a look at Selenium, which allows you to control a Browser like Firefox or Chrome.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
