### ISSUE TITLE
Where does the file download to?

### ISSUE THREAD

**Issue by jonbeacherdomuso** [psf/requests#6297]
I cant find it

**Comment by nateprewitt** [comment]
This appears to be a general Python question. Accessing response content is covered in the docs but if you have further questions, [StackOverflow](https://stackoverflow.com) is the best place for those.

**Comment by ghost** [comment]
```python
def download_file(filename, url):
	r = requests.get(str(url))
	open(filename, 'wb').write(r.content)
```
