### ISSUE TITLE
How to change Keep-Alive parameters?

### ISSUE THREAD

**Issue by mehtaanshul** [psf/requests#6299]
We have tried setting these headers ->

Connection: keep-alive
Keep-Alive: timeout=5, max=2

But it is not working as expected

**Comment by mehtaanshul** [comment]
https://requests.readthedocs.io/en/latest/user/advanced/#keep-alive

Documentation does not specify how to change the keep-alive parameters

**Comment by sigmavirus24** [comment]
Hi there,

Thanks for reaching out. Unfortunately, there's too little detail in this issue to be able to help you and it's not reproducible. That indicates a likely problem in your environment which we are not responsible for debugging and which the maintainers of this project do not have the time to help you with. As a result, I'm closing this issue.
