### ISSUE TITLE
response.reason is None instead of the expected reason string

### ISSUE THREAD

**Issue by westy92** [psf/requests#6303]
`response.reason` is `None` instead of the expected reason string.

## Expected Result
Print `'INTERNAL SERVER ERROR'` or something similar

## Actual Result

`'None'` is printed

## Reproduction Steps

```python
    requests_mock.get(
        'https://google.com',
        json={},
        status_code=500
    )

    response = requests.get('https://google.com')
    print(response.reason)
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.0"
  },
  "platform": {
    "release": "22.1.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010113f"
  },
  "urllib3": {
    "version": "1.26.13"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
If the mocking library doesn't set it on the Response it creates, why do you think this is a bug in requests?

**Comment by westy92** [comment]
Because the [docs](https://requests.readthedocs.io/en/latest/api/?highlight=reaso#requests.Response.reason) claim it will be there and the response reason phrase is [optional](https://stackoverflow.com/questions/17517086/can-an-http-response-omit-the-reason-phrase).

If this is indeed not planned, this should at least be reopened as a docs request to improve the documentation, claiming that the value will be `None` unless the server specifies a value.

**Comment by sigmavirus24** [comment]
You don't understand. Requests is not creating the response, requests-mock a separate unrelated project does https://github.com/jamielennox/requests-mock/blob/c19c3343d3a70a57427bd37fbb5fcffb0b7def1c/requests_mock/response.py#L142
