### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [psf/requests#6307]
The sdist at PyPI is missing `tox.ini` file.  Please add the file to sdist to make downstream testing easier.  Thank you.

**Comment by sigmavirus24** [comment]
It should be in the GitHub tarball associated with the tag which most downstairs use to my knowledge

**Comment by mtelka** [comment]
I understand.  The small problem with tarball at github is that it is not easily possible to find it automatically using PyPI API.
