### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by lmilbaum** [psf/requests#6311]
When `CaseInsensitiveDict` being used as a function return type hint with python 3.7 and 3.8, the error is thrown when linting with mypy. 
The error is not thrown with python 3.9, 3.10 and 3.11.

## Expected Result

The error is not thrown 

## Actual Result

See example:
https://github.com/python-gitlab/python-gitlab/actions/runs/3726391254/jobs/6319811114

**Comment by nateprewitt** [comment]
Hi @lmilbaum, you'll want to report this to GitLab. This is not code maintained by this project.

**Comment by lmilbaum** [comment]
> Hi @lmilbaum, you'll want to report this to GitLab. This is not code maintained by this project.

@nateprewitt nateprewitt  Apologies. i'm not following. Which code is not maintained by this project?
The issue I reported refers to a class which is declared by the `requests` package and being used by another project.

**Comment by nateprewitt** [comment]
The type definition in the GitLab code for requests_backend.py is incorrect. Mypy [does not support abc.collections](https://mypy.readthedocs.io/en/latest/builtin_types.html#generic-types) before 3.9, so your definition is only compatible in 3.9+.

We don't intend to change the superclass for CaseInsensitiveDict, so the typing will need to be updated in the GitLab code. There are multiple options to work with this but we'll leave that decision to the code owners.

**Comment by lmilbaum** [comment]
Thank you for your feedback. I will work out with the project maintainers.
