### ISSUE TITLE
RequestsDependencyWarning

### ISSUE THREAD

**Issue by thetechnodino** [psf/requests#6314]
Windows 11 (Professional); Pycharm 2022.3
Getting dependency warning in both Python 3.10 (latest) and Python 3.11 (latest). The code produces the desired results as well as a  dependency warning is generated.
[python code]
<import requests
quote = requests.get(url="https://api.kanye.rest")
quote.raise_for_status()
kanye = quote.json()
print(kanye)>

Error message (copy & paste from console)
C:\Users\XXX\AppData\Local\Programs\Python\Python310\python.exe E:\Python_Projects\Kanye\scratch.py 

C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (None)/charset_normalizer (3.0.1) doesn't match a supported version!
  warnings.warn(

{'quote': "I don't wanna see no woke tweets or hear no woke raps ... it's show time ... it's a whole different energy right now"}

Process finished with exit code 0

Installed Packages

![Packages_2022-12-19 201204](https://user-images.githubusercontent.com/47829077/209002429-52793a32-b48f-4127-81e2-ac88c2195c6e.png)

**Comment by nateprewitt** [comment]
Duplicate #6261
