### ISSUE TITLE
Result from browser JS blocked site does not replicate iin Requests

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [psf/requests#6318]
I'm having trouble understanding a java issue.
My browser has javascript blocker extension, and the site comes up normal with JS fully blocked.
When using requests, however I get 403.

I know Selenium should be used for Java driven sites, but my understanding is that Requests should work if the site comes up with al JS blocked in browser?

Perhaps it's a cookies issue? But the initial / first request can't have any cookies, so...
Also, does `requests.Session()` automatically retain cookies through iterations or do cookies need to be extracted and passed-on in the next iteration?

EDIT: Perhaps this issue is caused by an https problem? I notice that only system_ssl is populated in System Information below.

## PY Code
```
session = requests.Session()
session.headers.update(headers)
cookies = ''
response = session.get(url, cookies =cookies, headers=headers)
```

## Actual Result
<403 forbidden>
Enable JavaScript and cookies to continue

## System Information

```
{
  "chardet": {
    "version": "4.0.0"
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.7"
  },
  "platform": {
    "release": "5.19.0-26-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "30000050"
  },
  "urllib3": {
    "version": "1.26.9"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

Thank you.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
