### ISSUE TITLE
Bump certifi dependencie to v2022.12.7 or higher due to Security Vulnerability

### ISSUE THREAD

**Issue by MefhigosetH** [psf/requests#6320]
Affected versions of certifi<=2022.12.7 package are vulnerable to Insufficient Verification of Data Authenticity resulting in Certifi root certificate removal from TrustCor. The root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. 

## Expected Result

You must update the `certifi` version in `requests` dependencies.

## Actual Result

"certifi>=2017.4.17" in https://github.com/psf/requests/blob/ec553c275fe915ab8c179a530907b564892d2922/setup.py#L65

## More info

See: https://security.snyk.io/vuln/SNYK-PYTHON-CERTIFI-3164749
See: https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ

**Comment by nateprewitt** [comment]
Hi @MefhigosetH, Requests already supports the patched version of Certifi. Raising the floor will unnecessarily break users as they may be unaffected by the TrustCor issue.

**Comment by Masquerainsley** [comment]
Hey there, I contacted privately not having seen this and didn't want raise an issue as it was linked to a vuln (_albeit, moderate_) so apologies for the unnecessary message Nate. So I've been trying to upgrade to the patched version of Certifi on one of our projects but get `Because requests (2.28.1) depends on certifi (2022.12.07) which doesn't match any versions, requests is forbidden`. Where could I go from here?

**Comment by nateprewitt** [comment]
Hi @Masquerainsley, looking at the screenshot you provided, it appears you need to update your poetry.lock file. certifi `2022.12.7` (note 7 not 07) is available on [PyPI](https://pypi.org/project/certifi/2022.12.7/) with the fix. Requests will use that or any other version you install. You'll want to make sure you're using Python 3.6+ and running `poetry upgrade` to get the latest version.

**Comment by Masquerainsley** [comment]
I changed it to 7 instead of 07 after checking the PyPi site and still got the same error, I was in the process of upgrading the lock file when this happened. Turns out I had some weird caching thing - deleted and regenerated the file and it's fine now! thanks for your support :).
