### ISSUE TITLE
Validation of header type makes it imposible to use a str subclass

### ISSUE THREAD

**Issue by startmat** [psf/requests#6321]
Hi,
the validation of header type makes it impossible to use a str subclass.

code of validation:
https://github.com/psf/requests/blob/ec553c275fe915ab8c179a530907b564892d2922/requests/utils.py#L1036

I am rendering a the header by using the Django Template engine which returns a django.utils.safestring.SafeString. When using this as a header I get the

requests.exceptions.InvalidHeader: Header part ('application/xml') from {'accept': 'application/xml'} must be of type str or bytes, not <class 'django.utils.safestring.SafeString'>
exception.

May be using a construct with isinstance(ret, tuple(HEADER_VALIDATORS)):
could solve the problem.

thx & br
Matthias

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
