### ISSUE TITLE
Allow charset-normalizer 3.x

### ISSUE THREAD

**Issue by JayBazuzi** [psf/requests#6322]
requests does not work with charset-normalizer 3.0.0 or 3.0.1, blocking users of requests from updating to the latest charset-normalizer.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by nateprewitt** [comment]
Duplicate #6261. Please check existing issues before opening new ones, thanks.
