### ISSUE TITLE
From Expecting value: line 1 column 1 (char 0) to Response content not in json format

### ISSUE THREAD

**Issue by hasnainhakim** [psf/requests#6323]
Hi Please run:

        res = self.session.post(url=self.url, data=json.dumps(data), headers=self.h, verify=False)
        try:
            js = res.json()
            token = js['token']
            self.cookie['reese84'] = token
            print(fg + ' (success)')
            return token
        except ValueError:
            print("Response content is not valid JSON")

I am getting this :

[*] Fetching TokenResponse content is not valid JSON

**Comment by sethmlarson** [comment]
We can't help you debug general Python code, this issue tracker is only for defects in the Requests library. I recommend trying stackoverflow.com/ or the [Python Discord](https://www.pythondiscord.com/).
