### ISSUE TITLE
Please do not put upper bounds on your requirements constraints

### ISSUE THREAD

**Issue by pombredanne** [psf/requests#6328]
See https://iscinumpy.dev/post/bound-version-constraints/ as for why this is a problem.
This is a source of byzantine issues such as https://github.com/nexB/scancode-toolkit/issues/3195

**Comment by pombredanne** [comment]
For reference these are looking like this for now https://github.com/psf/requests/blob/2745db131a667a3d5457957cb3ed6adeb9b9949a/setup.py#L61:L65
```
requires = [
    "charset_normalizer>=2,<4",
    "idna>=2.5,<4",
    "urllib3>=1.21.1,<1.27",
    "certifi>=2017.4.17",
```

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by pombredanne** [comment]
@sigmavirus24 sorry for the churn then! I guess you meant this https://github.com/psf/requests/issues/6328#event-8200957254 , repasted here for reference:

> To be clear, jessemyers our position is the following:
> 
> - Requests is critical infrastructure for many projects and the larger Python community (pip, pipenv, twine, and so many other core workflows rely on it).
> 
> - urllib3 has the right to make minorly breaking changes to itself in between releases. Requests digs into urllib3 in certain places for certain workflows. Given that, we have to ensure things don't break when a new version of urllib3 came out, and we no longer vendor urllib3 into Requests, we need to be certain that the rest of the world won't burst into flames.
> 
> No software can guarantee future proof compatibility. We're very explicitly stating what we support. We could leave the upper bound off but we'd be implicitly supporting everything urllib3 releases. And when that would break, it would inevitably end up with us being painted as the worst people in the world.
> 
> Furthermore, there are two of us working on this project actively and both of us have very little time to keep up with other projects' release schedules. The most honest way we can communicate what we are capable of supporting at a given time is with these version constraints. We're far from the only open source project to take this stance. It would seem, then, that the more projects your project(s) use, the more they will encounter this and the more you will need to take a more measured approach to upgrading your dependencies.
[...]

**Comment by sigmavirus24** [comment]
There are _many_ past discussions of this. That's but one
