### ISSUE TITLE
urllib3 breaking changes

### ISSUE THREAD

**Issue by mkozakov** [psf/requests#6337]
The Requests library does not pin urllib3 to a version, but it exposes its classes. this means that if you use the exposed classes you might get different behavior, depending on which urllib3 version you have installed. Specifically, google Colab has an old version of urllib3 installed, so when using imports from `requests.adapters` it broke our library

## Expected Result

No error when using the `allowed_methods` param with Retry

## Actual Result

`TypeError: unexpected keyword argument 'allowed_methods'

## Reproduction Steps

```
pip install urllib3==1.24.3 # the version that Google Colab uses
pip install requests
```

```python
from requests.adapters import Retry

Retry(allowed_methods=['GET']) # a param that replaced `method_whitelist` in one of the versions of urllib3
```

**Comment by nateprewitt** [comment]
> The Requests library does not pin urllib3 to a version, _but it exposes its classes_.

Hi @mkozakov, I'm not sure this statement makes sense. Requests does [pin urllib3](https://github.com/psf/requests/blob/main/setup.py#L64) to a supported range. Requests imports a class into the adapters module for internal use within the module. That's how any import works. We explicitly document if you want to change retries you should import `Retry` from urllib3 and pass it to the adapter. That's a dependency that you need to manage within your code at that point.

> If you need granular control over the conditions under which we retry a request, import urllib3's ``Retry`` class and pass that instead.

Using transitive imports of undocumented classes is a high risk decision and will likely lead to unexpected breakages like this. If this is code you've written, I'd advise following our documentation and ensure you're pinning for your API requirements. If this is managed by Google, you'll need to reach out to them for adjustments.

**Comment by mkozakov** [comment]
@nateprewitt got it. Should I not be importing `HTTPAdapter` either?
This is how we added retries, but maybe that's wrong? 

```python
from requests.adapters import HTTPAdapter, Retry

session = requests.Session()
retries = Retry(
    total=self.max_retries,
    backoff_factor=0.5,
    allowed_methods=['POST', 'GET'],
    status_forcelist=[429, 500, 502, 503, 504]
)
session.mount('https://', HTTPAdapter(max_retries=retries))
session.mount('http://', HTTPAdapter(max_retries=retries))

response = session.request('POST', url, headers=headers, json=json, **self.request_dict)
```

**Comment by sigmavirus24** [comment]
Our documentation clearly states what is our code and safe to import. Anything not documented you shouldn't be importing. We will not answer questions one by one about what you're importing and whether or not it's safe
