### ISSUE TITLE
Can't properly DL this particular image although it works with urllib

### ISSUE THREAD

**Issue by stephanebruckert** [psf/requests#6338]
This code would normally work for other images but for this [specific image URL](https://i.discogs.com/UzkDSQACNmbykQvWO0B9JGVajps7_MULzdwP9RK-o94/rs:fit/g:sm/q:90/h:591/w:589/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTk3NzE1/LTE2MjA2NjkwNzQt/MjMxMS5qcGVn.jpeg) it doesn't. The image is downloaded but the file is corrupt.

```python
url = "https://i.discogs.com/UzkDSQACNmbykQvWO0B9JGVajps7_MULzdwP9RK-o94/rs:fit/g:sm/q:90/h:591/w:589/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTk3NzE1/LTE2MjA2NjkwNzQt/MjMxMS5qcGVn.jpeg"

# doesn't work with requests
import requests  # 2.28.1
img_data = requests.get(url).content
with open('image_requests.jpeg', 'wb') as handler:
    handler.write(img_data)

# it works with urllib
import urllib
urllib.request.urlretrieve(url, "image_urllib.jpeg")
```

Result:

<img width="562" alt="Screenshot 2023-01-22 at 12 52 00" src="https://user-images.githubusercontent.com/1932338/213916740-0611c0c3-3660-47b9-a15f-a8c4d54b5aac.png">

We can see the `requests` one doesn't have a preview and doesn't have the same size.

<img width="372" alt="Screenshot 2023-01-22 at 12 52 46" src="https://user-images.githubusercontent.com/1932338/213916766-fde189c4-5390-40ca-a3de-09dadaef67f8.png">

Here are other examples:

- https://i.discogs.com/O0MU8c-zTjW0H_YWugum_KKdJzk1UNZok1xbeY0C1wo/rs:fit/g:sm/q:90/h:580/w:580/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTg4OTQ5/LTE0MzQ2NDQ2MTct/Nzc1Mi5qcGVn.jpeg
- https://i.discogs.com/b9vVXUMd_KhK8fZsoZ9nZR47HQ15m_t0fmG1GqHjl2Q/rs:fit/g:sm/q:90/h:356/w:472/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9MLTQ4LTE2/MTAwNTEzNjgtOTQ4/OS5qcGVn.jpeg

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
