### ISSUE TITLE
session.verify not working when variable 'REQUESTS_CA_BUNDLE', is set

### ISSUE THREAD

**Issue by ggmoura** [psf/requests#6342]
I defined the verify parameter to False in the session object, I have the env 'REQEUSTS_CA_BUNDLE' defined as './ca_bondle.cer', in the request, it should respect the value that was assigned in the session object

## Use the verify parameter that was defined in the session object, which should be mandatory

when I assign a value to the verify parameter of the session object, the api should use this parameter to make the request, and not the value that was defined in the environment variable 'REQUESTS_CA_BOUNDLE'

## It is currently using the 'REQUESTS_CA_BOUNDLE' environment variable to define the value of the verify parameter during the request

Usou a variável de ambiente 'REQUESTS_CA_BOUNDLE', para definir o valor do parâmetro verify durante a requisição

## Define the 'REQUESTS_CA_BUNDLE' environment variable and make two requests, one that must use the certificate, and the second that must not be used, before making the second request, define the verify parameter of the session object as False, this value should be respected , however, the api is using the parameter that was defined in the environment variable, damaging the request!

```python
import requests

conf={'url': required(KAFKA_REGISTRY), 'ssl.ca.location': False}
session = Session()
session.verify = False
response = session.request(method, url="/".join([self.base_url, url]), headers=headers, data=body, params=query)
```

in the sessions.py line 532
```python
verify = merge_setting(verify, self.verify)
```

in the sessions.py line 532
```python
settings = self.merge_environment_settings(
    prep.url, proxies, stream, verify, cert
)
```

in the sessions.py line 701
```python
verify = merge_setting(verify, self.verify)
```

in the sessions.py line 717
```python
if verify is True or verify is None:
    verify = (os.environ.get('REQUESTS_CA_BUNDLE') or
              os.environ.get('CURL_CA_BUNDLE'))
```

in the sessions.py line 724
```python
verify = merge_setting(verify, self.verify)
```

in the sessions.py line 50 the session_setting is not null, need return this value
```python
if session_setting is None:
    return request_setting

if request_setting is None:
    return session_setting

# Bypass if not a dictionary (e.g. verify)
if not (
        isinstance(session_setting, Mapping) and
        isinstance(request_setting, Mapping)
):
    return request_setting
```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

- Requests v2.26.0
- Python 3.7

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
