### ISSUE TITLE
Request don't return value while curl does

### ISSUE THREAD

**Issue by Ohadkaiser** [psf/requests#6352]
Hi, I have an issue while making a post request.
I'm doing the following curl:
curl -X POST MY_ADDRESS -d SOME_JSON --connect-timeout 2000

After 15 minutes I get the response from the server but when I try to do so in python, nothing returns (request was timed out).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
