### ISSUE TITLE
Response class does not pickle _next attribute

### ISSUE THREAD

**Issue by peterezzo** [psf/requests#6361]
When using requests without following redirects the Response objects do not retain the _next PreparedRequest when pickled.

## Actual Result

```
>>> res = pickle.loads(pickle.dumps(requests.Response()))
>>> res.next
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pete/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 788, in next
    return self._next
AttributeError: 'Response' object has no attribute '_next'
```

## Fix?

```
>>> requests.models.Response.__attrs__ += ['_next']
>>> res = pickle.loads(pickle.dumps(requests.Response()))
>>> res.next
>>>
```

**Comment by sigmavirus24** [comment]
What you have here is a bug without a use case to motivate it. Why are you pickling responses and trying to follow redirects in another place after unpickling? The next attribute would be unwise to try to pickle and unpickle.

In short, we almost certainly don't want to support this. But you haven't told us why you think we should

**Comment by peterezzo** [comment]
I have a script that makes requests without following redirects and caches the objects for offline replay. It's not transferring responses to another place. It does consume the Response.next.url if it is present.

If you don't want to make it pickleable, you could just init the _next attribute in __setstate__ like raw.

**Comment by sigmavirus24** [comment]
Next is deprecated because it should never have been implemented. You want the value of the Location header

**Comment by peterezzo** [comment]
Did you just make that up? Anyway, I just thought you should know.

**Comment by sigmavirus24** [comment]
The issue tracker has plenty of bugs including one with a plan to get rid of the attribute. No I didn't just make it up.
