### ISSUE TITLE
Please consider making a public interface for `requests.utils._parse_content_type_header`

### ISSUE THREAD

**Issue by nboullis** [psf/requests#6362]
Hi,

I have some code using `requests` where I want to check that the response the response has the expected content-type, but I don’t care about the encoding. Parsing the Content-Type header is not very complicated, but `requests` already does it in its `requests.utils._parse_content_type_header` function, that is used to find the encoding in `requests.utils.get_encoding_from_headers`. I’d rather not reinvent the wheel.

However, as far as I can tell, that `requests.utils._parse_content_type_header` function is undocumented and, given its name starts with an underscore, it looks like a private function that might be removed in a future release.

It seems to me it that it is a common need to parse a Content-Type header and, given `requests` already had a function to do so, would you consider making a public interface for this?

**Comment by sigmavirus24** [comment]
Requests is in feature freeze at the moment and not expanding or changing the public API. As such, we will not guarantee the stability of availability of that function, nor will we be making it public
