### ISSUE TITLE
InvalidHeader exception when using subclass of str or bytes

### ISSUE THREAD

**Issue by hpierre001** [psf/requests#6372]
An InvalidHeader is raised while preparing a request using a subclass of `str` instead of `str` or `bytes` in headers.

## Origin
This is due to type checking in check_header_validity in utils.py. This type check uses `type` instead of `isinstance`.

## Context
The need of using subclass of str instead of str comes from the need to have 2 "Authorization" header and not just one with 2 tokens separeated by a comma.

PS: I didn't build the API i am requesting, don't blame me.

**Comment by hpierre001** [comment]
A correction could be:
```python
def check_header_validity(header):
    """Verifies that header parts don't contain leading whitespace
    reserved characters, or return characters.

    :param header: tuple, in the format (name, value).
    """
    
    name, value = header
    types = {}

    for part in header:
        for valid_type in HEADER_VALIDATORS:
            if isinstance(part, valid_type):
                types[part] = valid_type
                break
        else:
            raise InvalidHeader(
                f"Header part ({part!r}) from {{{name!r}: {value!r}}} must be "
                f"of type str, bytes or subclasses of them, not {type(part)}"
            )

    _validate_header_part(name, "name", HEADER_VALIDATORS[types[name]][0])
    _validate_header_part(value, "value", HEADER_VALIDATORS[types[value]][1])
```

**Comment by nateprewitt** [comment]
Hi @hpierre001, please check open and closed issues before creating new ones. Thanks!
