### ISSUE TITLE
How to setup local dev environment and run the tests?

### ISSUE THREAD

**Issue by szabgab** [psf/requests#6378]
As I have not seen any details about it (beyond the cloning of the repo) in the README I put together a short blog posts on [Development environment for the Python requests package](https://dev.to/szabgab/development-environment-for-the-python-requests-package-eae) If you are interested, I'd be glad to send a PR for the README file to include some similar information.

**Comment by APolevanov** [comment]
To set up a local development environment for the Python Requests library and run tests, you can follow these steps:
Fork the Requests repository (https://github.com/psf/requests) on GitHub.
git clone https://github.com/<your_username>/requests.git
cd requests
python -m venv venv
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install -e .
pip install -r requirements-dev.txt
pytest
