### ISSUE TITLE
Not possible to specify positional params in URLs

### ISSUE THREAD

**Issue by ghpqans** [psf/requests#6382]
Currently it's not possible to supply values for positional only parameters in request URLs.
E.g Http requests like this are not supported:
`URL?param1=value,some_other_param`

Currently it is possible to specify a key-value pair for `param1` but not only a value for `some_other_param`.
It's possible to concatenate the URL by oneself, but I doubt this is the recommended way to do so.

## Expected Result
Example:
`req = requests.get(URL, {"param1": "value1"}, positional_params = ["some_other_param"])`

## Actual Result
Only possible to concatenate the URL by oneself:
`req = requests.get(f"URL?param1={value},some_other_param")`, which is OK for simple requests but not OK
for complex requests.

The same goes for POST requests.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
