### ISSUE TITLE
Can choose whether to perform automatic url encoding and decoding

### ISSUE THREAD

**Issue by heikanet** [psf/requests#6385]
When I request with get, the content in the url will be automatically encoded or decoded or some other processing will be performed
Here are two examples:
[Example 1]
My real need is to send ' http://examole.com/1.jsp ;? Id=1 ', but in this example, the'; 'in the url Will be automatically ignored
```
import requests
url = ' http://examole.com/1.jsp ;? id=1'
res = requests.get(url, proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```
When I try to manually encode the url first, the actual request becomes' http://examole.com/1.jsp%3b%3fid%3d1 '
```
url = ' http://examole.com/%31%2e%6a%73%70%3b%3f%69%64%3d%31 '
res = requests.get(url, proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```
[Example 2]
My real need is to send ' http://examole.com/1.jsp?id=1 |Tid=2 ', in this example,' | 'will be encoded as'% 7C'
```
import requests
url = ' http://examole.com/1.jsp?id=1 |tid=2'
res = requests.get(url, proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```
When I try to manually encode the url first, the actual request becomes' http://examole.com/1.jsp%3fid%3d1%7ctid%3d2 '
```
url = ' http://examole.com/%31%2e%6a%73%70%3f%69%64%3d%31%7c%74%69%64%3d%32 '
res = requests.get(url, proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```

I cannot modify the source code of requests because it will affect the functionality of other businesses. Therefore, I hope you can provide an optional parameter to determine whether to send the original URL request.

For example:
```
res = requests.get(url, no_encode=False,proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```
When no_ The default value of encode is True, which has the same effect as the current version. If no_ Encode=False, then the original url is sent without any processing.

**Comment by nateprewitt** [comment]
Hi @heikanet, this is already possible with the PrepareRequest workflow described in our docs.

https://docs.python-requests.org/en/latest/user/advanced/#prepared-requests

**Comment by heikanet** [comment]
```
import requests

url = 'http://www.example.com/api;'

# Set the proxy for requests
proxies = {
    'http': '127.0.0.1:8080',
    'https': '127.0.0.1:8080'
}

# Create a session object with the proxy
session = requests.Session()
session.proxies = proxies

# Create a prepared request object
request = requests.Request('GET', url, params={'key': 'value|a=2'}, headers={'User-Agent': 'Mozilla/5.0'})

# Prepare the request
prepared_request = session.prepare_request(request)

# Send the request
response = session.send(prepared_request)

print(response.text)

```
我尝试了下，发现并不能满足需求
