### ISSUE TITLE
requests prepare_request Valid on MacOS but not on Linux

### ISSUE THREAD

**Issue by heikanet** [psf/requests#6392]
I referred to https://github.com/psf/requests/issues/6385 , using PrepareRequest workflow to implement the method of retaining original characters in urls

The following code, which I run on my local MacOS, actually sends a URL of ' http://example.com/?unix:abc | http://127.0.0.1/ ', but when I ran it on Linux, the actual URL changed to' http://example.com/?unix:abc%7Chttp://127.0.0.1/ ', I checked that the versions of the requests library are the same, they are all 2.28.2. Why

```
import requests
s = requests.Session()
prepped = s.prepare_request(requests.Request('POST', 'http://example.com/', data={"a":"1"}, headers={'User-Agent':'test'}))
prepped.url = 'http://example.com/?unix:abc|http://127.0.0.1/'
res = s.send(prepped,proxies={'http': '127.0.0.1:8080', 'https': '127.0.0.1:8080'})
```
<img width="502" alt="image" src="https://user-images.githubusercontent.com/48439183/227627197-01ef12d5-2a25-411c-8a60-f3aa714c7369.png">

**Comment by ssrsec** [comment]
I have found the reason. Requests rely on urllib3 to process urls. urllib3=1.22 can meet my requirements, but the new version won't work. Therefore, when using the new version of urllib3, it is still necessary for me to https://github.com/psf/requests/issues/6385 Suggestions

**Comment by sigmavirus24** [comment]
If it's necessary for you to use a pipe like that unencoded something you're interacting with isn't a well implemented server that respects how it should behave. Requests can only give you so much ability to do the wrong thing. At this point requests has no way to prevent urllib3 from also doing the right thing (nor do we really want to prevent it from doing the right thing).
