### ISSUE TITLE
Request() not defined

### ISSUE THREAD

**Issue by ferrariaria** [psf/requests#6396]
I have been using the Request() function for months in this form:

 req = Request(
    url=url_c, 
    headers={'User-Agent': 'Mozilla/5.0'})
    with urlopen(req) as response:
        webpage=response.read()
        soup = BeautifulSoup(webpage)

Until yesterday, my code above returned a beautiful soup object and then all of a sudden yesterday the Request() function just stopped working.

It returned this name error:

NameError: name 'Request' is not defined

I tried re-importing and  reinstalling requests and restarting my kernel several times but to no avail.
I am using Python 3.10.8- and requests version 2.28.1

I see that that there is a requests.get function but I want to know why the function was working fine for months and then all of a sudden it wasn't recognized anymore.

**Comment by nateprewitt** [comment]
hi @ferrariaria, nothing has changed with Requests. I would suggest double checking your local environment and code again. If Request is not defined, you've failed to import it properly. Unfortunately we aren't able to help with setup debugging on this issue tracker, we recommend posting on [StackOverflow](https://stackoverflow.com/) with further questions. Thanks!
