### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by maritogaleano** [psf/requests#6405]
When trying to post to an API I get the following error: 

` raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[17/Apr/2023 10:52:46] "POST /Depositos/crear HTTP/1.1" 500 187142`.

The code I'm trying to run is:

`x = session.post(url, data = json.dumps(data))
        message = x.json()
        print(message)

        if x.status_code == 201:
            sweetify.success(request, 'Deposito creado correctamente')
            return redirect('deposito_nuevo')
        else:
            sweetify.error(request, 'Ha ocurrido un error', text=message["error"]["message"]["value"])
        return redirect('deposito_nuevo')`

The libraries that I am using are the following:
sgiref               3.6.0
certifi               2020.6.20
chardet               3.0.4
charset-normalizer    3.1.0
Django                4.1.7
django-simple-history 3.3.0
django-widget-tweaks  1.4.8
gunicorn              20.0.4
idna                  2.10
pip                   23.0.1
psycopg2              2.9.5
psycopg2-binary       2.9.5
pytz                  2020.1
requests              2.28.2
setuptools            67.6.0
six                   1.15.0
sqlparse              0.3.1
sweetify              2.3.1
tzdata                2022.7
urllib3               1.25.9
wheel                 0.38.4

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

Note that the remote end is closing the socket in violation of the protocol. This isn't a bug in requests
