### ISSUE TITLE
vague comment in `help.py`

### ISSUE THREAD

**Issue by jelgun** [psf/requests#6410]
The comment in https://github.com/psf/requests/blob/main/requests/help.py#L60 is difficult to understand. Is it possible to provide a clear explanation?

**Comment by aqyuki** [comment]
Do you mean `#Complete Guess`?

**Comment by nateprewitt** [comment]
This is a comment Kenneth made stating he shipped this without testing it. As in "This is entirely a guess".

This is an ancillary file not intended for use outside of Requests, so it's unlikely we'll make an material changes to what's in there.
