### ISSUE TITLE
github actions on ubuntu 18.04 fail to start because the image was removed

### ISSUE THREAD

**Issue by graingert** [psf/requests#6417]
github actions on ubuntu 18.04 fail to start because the image was removed: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

this might be a challenge because the tests fail with SSLError: https://github.com/psf/requests/issues/5662

**Comment by nateprewitt** [comment]
Resolved in #6418
