### ISSUE TITLE
Event-stream response encoding should be detected as utf-8

### ISSUE THREAD

**Issue by yannrouillard** [psf/requests#6427]
When from an event stream, requests detects the encoding as being ISO-8859-1, which can leads to improper character decoding if that information is used. 
It seems that event stream should always be encoded with utf-8 according to https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream, so the response encoding information should probably be set to utf-8 when the content-type is text/event-stream

## Expected Result

The encoding should be detected as being utf-8

## Actual Result

The encoding is detected as ISO-8859-1, probably because of this code https://github.com/psf/requests/blob/51716c4ef390136b0d4b800ec7665dd5503e64fc/requests/utils.py#L555 and the presence of the `text` in the content-type.

**Comment by nateprewitt** [comment]
Hi @yannrouillard, Event Streams are an HTML specification from WHATWG, not an http specification. Requests is not a browser and will likely never support the full range of behaviors built on top of HTTP.

This should be relatively straight forward to solve for any project using Requests. You can either directly set the `encoding` on the Response before calling `text` to avoid guessing, or the server can supply `; charset=utf-8` on the end of the Content-Type to explicitly define this behavior.

**Comment by yannrouillard** [comment]
Thanks for the answer @nateprewitt.

In that case, it may have been nicer to not return 'ISO-8859-1' encoding since the encoding was, in fact, not known, but I see this is already the subject of existing issue https://github.com/psf/requests/issues/2086 and not a simple issue.
