### ISSUE TITLE
GBK Encoding Error

### ISSUE THREAD

**Issue by liyanes** [psf/requests#6433]
I encounter an encoding error when use requests to send request (method:post&get).

## Expected Result

![image](https://user-images.githubusercontent.com/30283620/234916977-b17da668-9e72-469a-bae2-ad7c75dc13cf.png)

## Actual Result

![image](https://user-images.githubusercontent.com/30283620/234920176-2017d8be-a855-44f0-a7a2-39ae9a169528.png)

![image](https://user-images.githubusercontent.com/30283620/234916387-7ce65506-ddad-44d7-a014-0ae23cd15445.png)

The return text is wrong.
Exactly, the ret.content is wrong, too.
I think the error happens when reading content.

## Reproduction Steps

```python
import requests
print(requests.post(url, params={'method':'pageInfo'}, data={'queryString':queryString}).text)
# Note: My URL is a local area network website, and it send data with gbk encoding.
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.1"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.29.0"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.13"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
`Response.content` is the exact bytes we read off the wire, it has no encoding applied.

You might check whether the payload is gzip compressed. Other than that though, Requests cannot affect what the server returns. If you're getting back unexpected bytes, it may be the server attempting to limit web scraping or a misconfiguration. We won't be able to help with that unfortunately.
