### ISSUE TITLE
cannot use request.get when there is "//" in url

### ISSUE THREAD

**Issue by jarunyawat** [psf/requests#6435]
I'm using FastAPI to request the status of my robot, and I'm also using my fleet manager to request its status. However, I encountered an error that says 'Cannot mix str and non-str argument' when my URL is constructed as follows:
url = 'http://' + str(self.robot_ip[robot_name]) + ':' + str('5000') + '/status/'
I deduced that this may be because of the double forward slashes (//) following http:
How to fix or could you recommend me other API

**Comment by sigmavirus24** [comment]
Your deduction is wholly incorrect. Without additional information which you haven't provided, we can't help you.

Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
