### ISSUE TITLE
dependency conflict: botocore 1.29.127 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.2 which is incompatible.

### ISSUE THREAD

**Issue by AlexanderNewell** [psf/requests#6444]
I am a new developer and am having an issue with my API gateway API. 

It returns the following error:

{"errorMessage": "Unable to import module 'app': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)", "errorType": "Runtime.ImportModuleError"

and I'm pretty sure it has something to do with the dependency conflict: botocore 1.29.127 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.0.2 which is incompatible.

Does this sound familiar to anyone?

**Comment by achapkowski** [comment]
botocore needs to update the setup requirements to have urllib3<2.

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
