### ISSUE TITLE
WinError 10053 recved when send data to client

### ISSUE THREAD

**Issue by programsalon** [psf/requests#6446]
I used stream=True,timeout=60 in client, and when I use iter_content, it's failed for timeout, so I try get it again, but the connection closed by it (the client). I think of that the connection should not be closed so I can use iter_content for many times in while()
 
## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
