### ISSUE TITLE
POST no longer detects the correct charset

### ISSUE THREAD

**Issue by el-dge** [psf/requests#6447]
With new version, the header _Content-Type_ is not set good (not set at all).
I have an **é** in the data post.

## Expected Result
In the headers :
`'Content-Type': 'text/plain; charset=UTF-8'`

## Actual Result
Header _Content-Type_ is not set, Requests not recognize **é** in data and don't add  `'Content-Type': 'text/plain; charset=UTF-8'`

## Reproduction Steps

```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ").text
```
bad response: `'[2,"\\u00C3\\u00A9"]'`
[Here for explication of the response](https://www.warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/09_Analysing_data#encoding)

I must specify header (not need before, one week ago):
```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ", headers={'Content-Type': 'text/plain; charset=UTF-8'}).text
```
good response : `'[1,"\\u00E9"]'`
## System Information

    $ python -m requests.help

```json
/usr/lib64/python3.9/site-packages/requests/help.py:24: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in urllib3 v2.1.0. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib import pyopenssl
{
  "chardet": {
    "version": "5.1.0"
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": "40.0.2"
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.16"
  },
  "platform": {
    "release": "5.15.94",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30100000",
    "version": "23.1.1"
  },
  "requests": {
    "version": "2.30.0"
  },
  "system_ssl": {
    "version": "1010114f"
  },
  "urllib3": {
    "version": "2.0.2"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}

```
Thx in advance.

**Comment by nateprewitt** [comment]
Hi @el-dge, 

This behavior isn't handled by Requests, but a dependency charset-normalizer.

Without context on a larger body of text, that could be a number of possible encoding.

Your best bet is to set `encoding` on the response before calling `text()` if you want to enforce utf-8 when content-type isn't set.

**Comment by el-dge** [comment]
Ok, thanks for your rapid response. charset-normalizer is the good way for a resolution.

The encoding of the response is not the problem.
(Server attempt a header charset of utf-8 if  my data's request has non ASCII character, thing that _charset-normalizer_ no longer does)
```python
>>> requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ", headers={'Content-Type': 'text/plain; charset=UTF-8'}).json()
[1, 'é']
>>> requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ").json()
[2, 'Ã©']
```

An another bypass solution is:
```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'%C3%A9' DUP SIZE ").text
```
