### ISSUE TITLE
No possibility to provide raw urls 

### ISSUE THREAD

**Issue by SaturnIC** [psf/requests#6466]
Since requests is the major python library for web requests and python is used for web testing
it is unacceptable, that requests does not provide a way to define raw urls for web requests.

And malformed url behavior is one essential aspect of web testing, so it must be provided.

And to just close a previous issue on this topic by saying it is not our responsibility is brazen and tone deaf.

Closed, unresolved issues regarding this problem:
https://github.com/psf/requests/issues/5739
https://github.com/psf/requests/issues/5907

Please keep this issue open until this basic feature is working again.

**Comment by SaturnIC** [comment]
Do you all have a character disorder to close it again?

**Comment by sigmavirus24** [comment]
The library is provided as is. Please read the license

**Comment by SaturnIC** [comment]
Gaslighting won't work, try something more clever,
this bug has nothing to do with the license.

You even documented some workaround here once:
https://github.com/urllib3/urllib3/issues/1790

**Comment by sigmavirus24** [comment]
> this bug has nothing to do with the license.
> Please keep this issue open until this basic feature is working again.

We're closing this because the library is provided as is. It's not gaslighting.
