### ISSUE TITLE
Runtime.ImportModuleError after upgraded to 2.31.0

### ISSUE THREAD

**Issue by jack1220** [psf/requests#6468]
Found below error from logs after auto-upgraded (by Renovate) from 2.28.1 to 2.31.0 :
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
```

## System Information

Running python version 3.8 in docker image python:3.8-alpine

**Comment by nateprewitt** [comment]
Hi @jack1220, the error doesn't appear to be related to Requests. You're importing code that's trying to access `libc` files. Requests does not provide any C code, so this is stemming from some other dependency.
