### ISSUE TITLE
Redirect from doi.org to onlinelibrary.wiley.com fails

### ISSUE THREAD

**Issue by goekce** [psf/requests#6471]
If I visit `https://doi.org/10.1002/jccs.200600142` with my browser, everything is fine. But both requests fails:

```sh
python -c "import requests; print(requests.head('https://doi.org/10.1002/jccs.200600142', allow_redirects=True))"

<Response [403]>
```

I also tried accepting cookies and changing the user-agent, which also did not help:
```py
import requests
with requests.Session() as s:
    print(s.get('https://doi.org/10.1002/jccs.200600142', allow_redirects=True, headers={'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0'}))

<Response [403]>
```

Does someone know what `requests` does differently than Firefox? Or should I include more headers?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by goekce** [comment]
Sorry I did not know that requests for helps are not welcome here @sigmavirus24 . I recommend locking the button here to avoid future help requests:

![image](https://github.com/psf/requests/assets/18174744/5f66344a-28e1-45e1-a65a-3889b1600262)

---

BTW I asked on SO: <https://stackoverflow.com/questions/76466113/redirect-from-doi-org-to-onlinelibrary-wiley-com-fails>
