### ISSUE TITLE
Requests changes the case of hex letters in percent encodings

### ISSUE THREAD

**Issue by MrQubo** [psf/requests#6473]
## Summary

Requests changes the case of hex letters in percent encodings in URLs.

Requests should always send the request target exactly as it was passed.

### Reproduction

```py3
import requests

print(requests.Request('GET', 'https://example.com/?example=%2f').prepare().url)
```

## Rationale

I wouldn't even absolutely ever not even in my worst nightmares ever consider this an issue.
That was until I met this beautiful http server, which won't work if you don't send **exactly** the same URL on http redirections.

See screenshots below:
![Screenshot showing successful response to request with lowercase hex](https://i.ibb.co/T2JnYhY/Screenshot-20230626-135150.png "Screenshot lowercase hex")
![Screenshot showing 404 response to request with uppercase hex](https://i.ibb.co/bmpjSG1/Screenshot-20230626-135128.png "Screenshot uppercase hex")
The only difference between the two requests is casing of hex characters, but the response from the server is completely different.

I would want to say that this issue is caused by a very weird design decision of this website (which is a wi-fi login page by the way), but who am I to argue with the server.

I don't have control nor access to the source of the server, but I suspect that the parameter `md` in the request is a hash of some part of the URI. So the request target must be sent exactly as it was passed in the `Location:` header (of a different request, not part of the screenshots).

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.2"
  },
  "platform": {
    "release": "6.3.8-zen1-1-zen",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30100010"
  },
  "urllib3": {
    "version": "2.0.3"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by MrQubo** [comment]
Seems like the bug lies in urllib3.

```py3
import urllib3.util

print(urllib3.util.parse_url('https://example.com/?example=%2f').query)
```

**Comment by nateprewitt** [comment]
I'm not sure there's much we can do here. There was a decision from the urllib3 team a handful of years ago where URLs started getting unilaterally standardized which broke a handful of workflows with PreparedRequests. I saw Quentin's reply on the urllib3 ticket but I don't think we can utilize that escape hatch in a backwards compatible manner.

Given this has only appeared a few times in the last ~5 years, I think we can safely say it's an unfortunate but rare edge case. I'm going to resolve this for now since it's unactionable. If the situation changes with what urllib3 exposes in the future we may be able to revisit it.

**Comment by MrQubo** [comment]
In case someone encounters this issue: I switched to httpx, which doesn't use urllib3 and doesn't have this bug.
