### ISSUE TITLE
Support passing request headers as multi-line strings

### ISSUE THREAD

**Issue by arry-lee** [psf/requests#6474]
Title: Support passing request headers as multi-line strings

Description:
Currently, when using the requests library to send HTTP requests, we need to pass the request headers as a dictionary to the headers parameter. However, in practical development, it is common to directly copy request headers from a browser and parse them into a dictionary, rather than manually editing a dictionary, which is more convenient and elegant.

I suggest an improvement to requests that allows the headers parameter to accept multi-line strings as input. This would enable developers to directly copy request headers from a browser, provide them as a string input, and have requests internally parse them into a dictionary.

Here's an example code snippet that demonstrates parsing multi-line strings into a dictionary:

```
headers = """
Host: example.com
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
"""
headers = dict(x.split(": ", 1) for x in headers.splitlines() if x)

```
This improvement would enhance the usability and flexibility of requests, aligning it better with real-world development needs. I hope to see this feature implemented in future versions.

Thank you for considering and accepting this suggestion!

**Comment by sigmavirus24** [comment]
Requests has been under a feature freeze for years now, so the answer is definitely No.

Regardless, if we were implementing new features I would be strongly against this feature because it allows for too many potential issues that could create security problems for users. It may seem like an improvement in user experience but it would be bad for security
