### ISSUE TITLE
URLQUICK needs adapters.py HTTPResponse

### ISSUE THREAD

**Issue by joaopa00** [psf/requests#6480]
## Expected Result

URLQUICK does not fail importing
 from requests.adapters import HTTPResponse

## Actual Result
fails badly:
File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 13, in
import urlquick
File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/urlquick.py", line 63, in
from requests.adapters import HTTPResponse
ImportError: cannot import name 'HTTPResponse' from 'requests.adapters' (/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.requests/lib/requests/adapters.py)

## Reproduction Steps
Install catchuptvandmore in github. Upadte to the latest request package

## System Information

Android, Kodi Nexus 20.1
```

<!-- This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c). -->

**Comment by SecT0uch** [comment]
I've just submited PRs to:
- urlquick module: https://github.com/willforde/urlquick/pull/118
- codequick kodi addon (embeds `codequick.py`): https://github.com/willforde/script.module.codequick/pull/53

**Comment by joaopa00** [comment]
Thanks for these PR. Unfortunately, I'm pretty scared these addons are not maintained no longer.

**Comment by SecT0uch** [comment]
Well I see activity from willforde on June 2023. He may not develop them anymore, but still be able to merge PRs.

Next step will be Kodi team to package the new version of `script.module.codequick`

**Comment by joaopa00** [comment]
That's not Kodi Team who package the modules. Maintainers of a module pull request them into xbmc repo script github.

**Comment by sigmavirus24** [comment]
HTTPResponse was never a documented portion of the adapters module and should never have been imported from there. This is not a bug in requests
