### ISSUE TITLE
session post set allow_redirects=False failed

### ISSUE THREAD

**Issue by sixiaobing** [psf/requests#6481]
I want to get redirected location，But although I set ：
s = requests.Session() 
response = s.post(url,data=datas,headers=headers,allow_redirects=False)
response.status_code is 200， not 302，why???

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
