### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE Python 3.11 and OpenSSL 3

### ISSUE THREAD

**Issue by utkonos** [psf/requests#6482]
This is an intermittent exception that is raised under certain conditions and not any other time. There is another closed issue similar to this one:
https://github.com/psf/requests/issues/4753
But I think this is a new issue.

What would be the recommended steps for isolating the source of the problem? The site this request connects to only supports TLS. SSL is not an option.

## Expected Result

Connection success and TLS like all other requests.

## Actual Result

error:
```
SSL Error: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /query/sha256 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)')))
```

## Reproduction Steps

```python
import requests
response = requests.get(url, auth=(username, password))
```
Just a basic standard request. Nothing special.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.2.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.4"
  },
  "platform": {
    "release": "6.2.0-24-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30000080"
  },
  "urllib3": {
    "version": "1.26.16"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
This comes directly from the standard library raising the error on the specified line returned from trying to perform the handshake [here](https://github.com/python/cpython/blob/7dead6a33ac786465c3d927d5c2025caf0c1a71b/Modules/_ssl.c#L964). Literally, OpenSSL cannot complete the handshake.

Without knowing anything about the server, it's possible there are multiple backends or multiple intermediaries, one of which is leading to this particular error for you. The client configuration and the server configuration cannot agree on how to connect thus the handshake fails. I recall a time in the past when OpenSSL used `SSLv3` to refer to `TLS1.0` but I don't believe Python 3.11, OpenSSL 3, nor the versions of urllib3 and requests you're using allow for 1.0 or really anything below 1.2. This genuinely seems to be an intermediary or server issue that is unlikely possible for you to resolve.

In the future, though, please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by Batgerel53** [comment]
@utkonos  how to fixed problem, i same error, Help me please
