### ISSUE TITLE
SSL ERROR on jiotv login in KODI app.

### ISSUE THREAD

**Issue by brg1993** [psf/requests#6483]
Below error show during login jio tv I  KODI application 

[HTTPSConnectionPool(host='api.jio.com', port=443): Max retries exceeded with url: /v3/dip/user/otp/send (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:992)')))  ]

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
