### ISSUE TITLE
PayLoad trucated when using french special characters like é, è, à

### ISSUE THREAD

**Issue by stephanerenoult** [psf/requests#6487]
Hi,

I m using requests-2.31.0

Here is 3 examples of my Python variable used to send a payload : 

Below with no special character :
Python variable = **{"updateGroups":true,"groups":[],"user":{"displayName":"TONI eric","email":"xxxxxx@xxxxxxx.com","name":"anto1","password":"anto1","accountRoleIds":[1677,1680,1683]}}**

Below with 2 special characters :
Python variable = **{"updateGroups":true,"groups":[],"user":{"displayName":"TONé éric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683]}}**

Below with 3 special characters :
Python variable = **{"updateGroups":true,"groups":[],"user":{"displayName":"èTONé éric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683]}}**

The 3 variables are well formatted than i expect with good informations.

But here is the content sent by the module requests-2.31.0 WHEN THE PAYLOAD CONTAINS special french characters (Fiddler RAW)

## Actual Result

{"updateGroups":true,"groups":[],"user":{"displayName":"ANTONéN Ayméric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683]

{"updateGroups":true,"groups":[],"user":{"displayName":"ANèTONéN Ayméric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683

## Expected Result

{"updateGroups":true,"groups":[],"user":{"displayName":"ANTONéN Ayméric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683]}}

{"updateGroups":true,"groups":[],"user":{"displayName":"ANèTONéN Ayméric","email":"xxxxxx@xxxxxxx.com","name":"anto3","password":"anto3","accountRoleIds":[1677,1680,1683]}}

Regarding the count of special characters, the payload is truncated of this count of characters.

Regards

**Comment by sigmavirus24** [comment]
You haven't described how you're sending the payload with requests, the version of python, environment, or anything else that would help diagnose this.

**Comment by stephanerenoult** [comment]
Hi,
sorry for send you few informations.

I precise that when there is NO special characters, the request and the payloas are OK (http200)

I m running Python 3.9.0 on a windows machine

Here is an extract of my code.

    MesHeaders3 = {'X-CSRF-TOKEN': Tolkien,'Accept': 'application/json, text/plain, */*','Content-Type': 'application/json;charset=UTF-8','Accept-Language': 'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7'}
    PayloadJson = '{"updateGroups":true,"groups":[],"user":{"displayName":"' + UserFullName + '","email":"' + UserEmail + '","name":"'+ UserName + '","password":"' + UserName + '","accountRoleIds":[' + IDRoles2use + ']}}'

    print (PayloadJson)
    
    MyRequest3 = requests.post(Url_UsersCreate, headers=MesHeaders3,cookies=Biscuit2Send, data=PayloadJson)

Regards

**Comment by sigmavirus24** [comment]
Formatting JSON by hand is a perfect way to end up with invalid JSON and unexpected behavior. I strongly suggest you create a dictionary and then pass that via the `json` parameter to `requests.post` and allow that to convert your data to JSON. I expect that will fix your problem.

As the saying goes, junk in, junk out.
