### ISSUE TITLE
NewConnectionError 

### ISSUE THREAD

**Issue by mustansirgodhrawala** [psf/requests#6489]
When I pass in a request url for a url that does not respond I get a 

```python3
request = requests.get(
            "url"       
            proxies=proxies,
        )
```

```
Error: SOCKSHTTPSConnectionPool(host='atxdyqbqutne3q0hoidwnjkxzxzyogtw0boudm7ztiwrdxrucedrsolw.onion', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0xffff8fbf9690>: Failed to establish a new connection: 0x01: General SOCKS server failure'))
```

But when I also kill my proxies I get the same error. This should not be, how can I catch the different errors and understand what I'm dealing with? Is this behaviour expected? If so, why?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

**Comment by mustansirgodhrawala** [comment]
Hi, I'm not very well versed with the requests module and the error seems like a urllib3 error of some sort. Is this expected behaviour or a bug?
