### ISSUE TITLE
Wrong HTTP verb is used when sending a request

### ISSUE THREAD

**Issue by BSpirit** [psf/requests#6495]
I'm not sure what is causing this, but when I try to send a POST request, the library sends a GET instead.

I expected requests lib to send a POST.

```python
Python 3.10.3 (v3.10.3:a342a49189, Mar 16 2022, 09:34:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> response = requests.post("https://docs.python.org/")
>>> response.status_code
200
>>> response.request.__dict__
{'method': 'GET', 'url': 'https://docs.python.org/3/', 'headers': {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, '_cookies': <RequestsCookieJar[]>, 'body': None, 'hooks': {'response': []}, '_body_position': None}
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.2.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.3"
  },
  "platform": {
    "release": "20.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "101010ef"
  },
  "urllib3": {
    "version": "2.0.4"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

In the future, please search **closed and** open issues before creating new ones that are duplicates.


It's likely you're encountering a redirect and the semantically correct behavior is to change the method to a GET. Check the history of the response

**Comment by BSpirit** [comment]
What do you mean it's a request for help ?

Did you read the code ? I'm using `requests.post` to send a POST and you can clearly see in the answer it sends a GET.

**Comment by BSpirit** [comment]
When I print `response.is_redirect` the value is `False`

Is this the expected behavior as well ?

**Comment by BSpirit** [comment]
Also I don't use this issue when using curl with the exact same endpoint, headers and body

**Comment by sigmavirus24** [comment]
> When I print `response.is_redirect` the value is `False`
> 
> Is this the expected behavior as well ?

Check `response.history` as I said. `response.is_redirect` doesn't indicate a response is the result of following a redirect.

**Comment by BSpirit** [comment]
Just some complementary informations : 
- it's a private API, I don't have any control on how the backend works
- When I use curl or urllib3 on the same endpoint, I don't get redirected. Using requests I get redirected.
