### ISSUE TITLE
Proper TypeAnnotation for proxies

### ISSUE THREAD

**Issue by Cosmicoppai** [psf/requests#6514]
### Proposal

I propose enhancing the type annotations for proxy settings in the `requests` library to specify a dictionary of string keys and string values. This would provide clearer type expectations to users and improve the development experience when configuring proxies for HTTP requests. As it is not much needed, but it would be great if proper Annotations are present.

Currently, the type annotation for proxies in the `requests` class is defined as: 

```python
proxies: Any | None
```

### Desired State

I suggest updating the type annotation for proxies to be more specific:

```python
proxies: Optional[Dict[str, str]]
```

**Comment by sigmavirus24** [comment]
There are no type annotations in this library. The error likely lies in typeshed if there's anything
