### ISSUE TITLE
upload a photo and copy link

### ISSUE THREAD

**Issue by Pana11** [psf/requests#6521]
import requests
url = 'https://scanqr.org/'
responde2 = requests.get(url)
files = {'file': open('ph.jpg', 'rb')}
response = requests.post(url, files=files)
print(response.text)
print(responde2.text)

This is a site for scanning the QR code, that is, you upload the picture of the QR code, then it shows the link related to the QR code.
I uploaded a photo using the requests library and got the output before and after, but there is no difference between the outputs
If I expected, give me the link in the output after uploading

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
