### ISSUE TITLE
Getting 500 with Requests.get whereas Postman gives 400

### ISSUE THREAD

**Issue by dbellani** [psf/requests#6525]
Summary: For a Get API, The same url and token gives 400 status code in postman and when tried with pytest-bdd with requests library, I get 500

## Expected Result

 For a invalid param, should be giving status code 400 in the response

## Actual Result

We get 500 status code though the request is exactly the same used in both places, please see below images

## Reproduction Steps

<img width="1273" alt="image"
<img width="694" alt="Screenshot 2023-09-11 at 6 28 37 PM" src="https://github.com/psf/requests/assets/42774628/5f66eacc-5fe6-4af6-b489-84f32081752f">
 src="https://github.com/psf/requests/assets/42774628/86da23bb-5943-4bbb-9a11-84361155474b">

## System Information
pytest --version:  6.2.5
Python3 --version: 3.9.6
MacOS

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

The server is returning a 500, not requests. Something is wrong in your setup

**Comment by dbellani** [comment]
<img width="1273" alt="image" src="https://github.com/psf/requests/assets/42774628/a016bd9d-51ea-4afa-9bc8-c125f8930faa">


But my request is same in both places, please refer this image.

**Comment by sigmavirus24** [comment]
Your images do not prove what you want them to nor are they searchable or accessible to those who need to use assistive devices like a screen reader. The requests are not identical and there are any number of prior issues here and answers on StackOverflow that can help you diagnose what the difference is.
