### ISSUE TITLE
open core legacy patcher

### ISSUE THREAD

**Issue by baquer147** [psf/requests#6526]
hello, i am facing a error while downloading the ventura file from open core legacy patcher, it downloads 2GB from 11.9 gb  and a error comes     Download failed: 
HTTPSConnectionPool(host='swcdn.apple.com', port=443): Read timed out

please help me with this 

thankyou

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
