### ISSUE TITLE
Automatically Close Requests Session After Specified Timeout, Even with Retries

### ISSUE THREAD

**Issue by shoval-c** [psf/requests#6530]
**Desc**
Currently, when using the requests library in Python to create a session with a timeout and there are retries implemented within the request, the session remains open even after the specified timeout has elapsed. This behavior can lead to resource leakage and unexpected behavior when managing sessions with timeouts.

**Proposal:**
Add functionality to automatically close a requests session after a specified timeout, even if there are retries in the request itself. This enhancement would improve the library's usability and ensure that sessions are properly managed, even in cases involving retries.

**Use Case:**
As a developer, I often need to make HTTP requests with retries in case of transient errors. However, I also need to ensure that the session is closed after a certain timeout to prevent resource leaks. This feature would enable me to have both retry functionality and automatic session closure without having to implement custom solutions.

**Suggested Implementation:**
One way to implement this feature is to introduce an optional session_timeout parameter when creating a session or making requests. This parameter would specify the maximum duration the session can remain open, and if the timeout is reached, the session would be closed automatically, regardless of ongoing retries.

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
