### ISSUE TITLE
How can I translate a page to English when scraping with requests python

### ISSUE THREAD

**Issue by Kamal-Moha** [psf/requests#6531]
I'm trying to scrape the site [roca](https://roca.com.br/imovel/locacao/casas/sao-carlos/jardim-sao-carlos/66857?hl=en). This page is in Portuguese language, but I want to have translated into English so that I can capture English content when scraping with requests.

I have tried doing the below option of using Accepted-Language as I saw on [stackoverflow] (https://stackoverflow.com/questions/43572267/i-get-translated-text-when-i-do-a-get-request-in-python-how-to-get-english-co) 

```
url = r'https://roca.com.br/imovel/locacao/casas/sao-carlos/jardim-sao-carlos/66857'
headers = {"Accept-Language": "en-US,en;q=0.5"}
response = requests.get(url, headers=headers).text # get content of URL (webpage), save to variable response
soup = BeautifulSoup(response,'html.parser')    # create a new object using html parse
name = soup.select('div.Divisor__StyledDiv-sc-gc9tdc-1 h1')
print(f'House Name: {name[0].text}')
```
But when I run the above code, it still prints in Portuguese which I don't want. Please help

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
