### ISSUE TITLE
Requests are blocked by cloudflare inside docker

### ISSUE THREAD

**Issue by GabrielYudenich** [psf/requests#6536]
Hello to all, i need some help here

I have a code where i need to post a URL to get the autorization of the cookies and then i get this cookies and do another request in the website

It's a goverment thing, and i really need some help

When i use this script on my computer i can use it normally but when i upload in the container on docker (in my vps) i get "403" and i cannot continue my code

Someone can help me?

Anyone had an similar issue?

Everything is correct, the certificate path, the user and password, everything... But i keep being blocked by cloudflare

![image](https://github.com/psf/requests/assets/51841352/55cbeb4d-5cf7-4dbb-8a55-b49990acf398)

The HTML message of cloudflare and the 403 on docker:

![image](https://github.com/psf/requests/assets/51841352/955d84ef-ec2b-4b8b-81e0-6fadec01da5a)

Thank you all!

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
