### ISSUE TITLE
Versions at requests.readthedocs.io flyout menu are outdated

### ISSUE THREAD

**Issue by fohrloop** [psf/requests#6539]
The https://requests.readthedocs.io/ webpage flyout menu versions are currently:

- [latest](https://requests.readthedocs.io/en/latest/) [stable](https://requests.readthedocs.io/en/stable/) [v3.0.0](https://requests.readthedocs.io/en/v3.0.0/) [v2.9.1](https://requests.readthedocs.io/en/v2.9.1/) [v2.8.1](https://requests.readthedocs.io/en/v2.8.1/) [v2.7.0](https://requests.readthedocs.io/en/v2.7.0/) [v2.6.2](https://requests.readthedocs.io/en/v2.6.2/) [v2.5.3](https://requests.readthedocs.io/en/v2.5.3/) [v2.4.3](https://requests.readthedocs.io/en/v2.4.3/) [v2.3.0](https://requests.readthedocs.io/en/v2.3.0/) [v2.2.1](https://requests.readthedocs.io/en/v2.2.1/) [v2.1.0](https://requests.readthedocs.io/en/v2.1.0/) [v2.0.0](https://requests.readthedocs.io/en/v2.0.0/) [v1.2.3](https://requests.readthedocs.io/en/v1.2.3/) [v1.1.0](https://requests.readthedocs.io/en/v1.1.0/) [v1.0.4](https://requests.readthedocs.io/en/v1.0.4/)

Screenshot:

![image](https://github.com/psf/requests/assets/17479683/0ec2240b-6b41-42a0-8448-6391321fa2b2)

There are few problems with the versions:
- First, some of the selected versions in the flyout menu are really old. The 2.9.1 [is from December 2015](https://github.com/psf/requests/releases/tag/v2.9.1). I would expect to see 2.31.0, 2.30.0, 2.29.0 and perhaps 2.28.2 on the list.
- The 3.0.0 links to documentation for v.2.10.0.

**Comment by Rjchauhan18** [comment]
I would like to work on this issue. 
I am not much clear about the issue description, so could please elaborate on it.

**Comment by fohrloop** [comment]
The flyout menu is the black box in the bottom right corner:
![image](https://github.com/psf/requests/assets/17479683/31296583-000b-4112-bec2-bdbd955148e5)

This has old versions listed. It is missing recent versions like 2.31.0, 2.30.0, 2.29.0. In addition, the link for 3.0.0 in the flyout menu -- this:

![image](https://github.com/psf/requests/assets/17479683/6a9d76af-48ca-404d-b260-b303c65059a2)

..points to documentation of v.2.10.0:

![image](https://github.com/psf/requests/assets/17479683/949a6ba1-884e-4e87-96c2-9643c3369b68)

**Comment by Rjchauhan18** [comment]
So issue says that, 
- Add the remaining versions like 2.31.0, 2.30.0, 2.29.0. 
- Correct the link for 3.0.0

Is it correct or i left with anything else ?

**Comment by fohrloop** [comment]
I think what summarizes the issue well! :)

**Comment by Rjchauhan18** [comment]
Hey while going through the code i am not able to locate the flyout menu.
Could you please locate it.

**Comment by fohrloop** [comment]
I'm not familiar with the requests repository, but it could be also that it is configured somewhere in the readthedocs settings. I hope someone else here knows what should be edited.

**Comment by nateprewitt** [comment]
These settings are managed form the administration panel in RTD. The older versions have been removed and we'll only be providing flyout links for stable (latest release) and latest (main branch). Thanks for the issue @fohrloop.
