### ISSUE TITLE
Cookies with `Secure` are not sent for `localhost` via unencrypted `http`

### ISSUE THREAD

**Issue by 42triangles** [psf/requests#6542]
See the title, `Secure` cookies are not sent in requests to `localhost` if those requests are not encrypted. There should probably be an exception for `localhost` (as there is in browsers, as well) to aid in developing servers.

## Expected Result

The cookies should be sent with the request.

## Actual Result

They aren't.

## Reproduction Steps

```python
import requests

session = requests.Session()
session.post("http://localhost:8080/login")
session.get("http://localhost:8080/only-with-login").raise_for_status()
```

and

```python
from flask import Flask, request, make_response

app = Flask(__name__)


@app.route("/login")
def login():
    resp = make_response("Logged in")
    resp.set_cookie("token", "token", secure=True)
    return resp


@app.route("/only-with-login")
def only_with_login():
    if request.cookies.get("token") != "token":
        return "Not logged in", 403
    return "Logged in"
```

Running the flask app with `flask --app server run --port 8080` and then running the requests with `python3 do_requests.py` throws an exception in `do_requests`, while in a browser the page does show "Logged in" after visiting `http://localhost:8080/login`.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "5.2.0"
  },
  "charset_normalizer": {
    "version": "3.2.0"
  },
  "cryptography": {
    "version": "41.0.3"
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.5"
  },
  "platform": {
    "release": "6.5.4-arch2-1",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30100020",
    "version": "23.2.0"
  },
  "requests": {
    "version": "2.28.2"
  },
  "system_ssl": {
    "version": "30100030"
  },
  "urllib3": {
    "version": "1.26.15"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}
```

**Comment by sigmavirus24** [comment]
No we'll not be introducing code to handle this. Use something like trustme to generate certs and validate them with requests instead and you'll get the correct behavior 100% of the time.

**Comment by markhobson** [comment]
This resolution is counterintuitive since it puts Requests at odds with browser behaviour:

* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1648993
* Chromium: https://issues.chromium.org/issues/40120372

[MDN also documents this special-case](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#secure):

> The `https:` requirements are ignored when the `Secure` attribute is set by localhost (since Chrome 89 and Firefox 75).
