### ISSUE TITLE
Conflicting requirements for urllib3

### ISSUE THREAD

**Issue by xypron** [psf/requests#6544]
In origin/main ee93fac6b2f7 I find conflicting required urllib3 version information:

```
setup.cfg:10:    urllib3>=1.21.1,<1.27
setup.py:64:    "urllib3>=1.21.1,<3",
```

Shouldn't both files have the same restrictions?

Best regards

Heinrich

**Comment by nateprewitt** [comment]
They should, good catch xypron. We'll work on getting those aligned.
