### ISSUE TITLE
@ethanroy No additional consideration beyond my suggestion of using a session-level auth handler, in the comment directly above yours.

### ISSUE THREAD

**Issue by skeggse** [psf/requests#6546]
> @ethanroy No additional consideration beyond my suggestion of using a session-level auth handler, in the comment directly above yours.

_Originally posted by @Lukasa in https://github.com/psf/requests/issues/2949#issuecomment-234553490_

I'm not sure if this used to work, or if something broke in the interim, but attaching an auth handler to a session does not cause the handler to get invoked for each redirect after the first request. Oddly, it seems like that's also the case for adapters, so it doesn't seem that there's a way to correctly set auth headers after a redirect.

**Comment by sigmavirus24** [comment]
Responding to a conversation by opening an issue is not a valid bug report. If you need assistance with your auth handler, please use StackOverflow
