### ISSUE TITLE
Certificates are printed to stdout when running requests.get

### ISSUE THREAD

**Issue by alexiswl** [psf/requests#6556]
## Expected Result

Any warnings not to be printed to stdout, (stderr instead)

## Actual Result

Certificate line is printed to stdout

## Reproduction Steps

```python
import requests

a = requests.get("https://github.com")
b = requests.get("https://github.com", verify=False)
```

Returns

```
/home/cwl_ica_user/.icav2-cli-plugins/pyenv/lib/pypy3.9/site-packages/certifi/cacert.pem None
/etc/ssl/certs/ca-certificates.crt /etc/ssl/certs
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "PyPy",
    "version": "7.3.13"
  },
  "platform": {
    "release": "6.2.0-35-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30100030"
  },
  "urllib3": {
    "version": "1.26.18"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
I can't reproduce this. Something is clearly missing from your reproduction steps

**Comment by alexiswl** [comment]
Hmm, seems to be an issue with Python 3.9.18 when packaged by conda-forge (not an issue when using 3.9.17).  My clipboard from terminal also appears to be broken so I cannot currently share my outputs. 

I don't believe this is a requests library issue, but something underneath.  

Closing for now.

**Comment by alexiswl** [comment]
@sigmavirus24 I have found the offending code - nothing to do with the requests library - but from https://github.com/pypy/pypy/issues/4009. Credit to @elliotwutingfeng for the link
