### ISSUE TITLE
Include NOTICE file in distribution

### ISSUE THREAD

**Issue by stevecj** [psf/requests#6559]
Since the Apache license requires inclusion of the copyright notice, it would be really helpful to have the NOTICE file included in the distribution along with the LICENSE file so it can be collected from there by scripts instead of having to retrieve it separately from the source repository.

**Comment by nateprewitt** [comment]
Hi @stevecj, the NOTICE file is currently available in the source distribution on PyPI and the published release assets on GitHub:
* [PyPI .tar.gz](https://files.pythonhosted.org/packages/9d/be/10918a2eac4ae9f02f6cfe6414b7a155ccd8f7f9d4380d62fd5b955065c3/requests-2.31.0.tar.gz)
* [GitHub release .tar.gz](https://github.com/psf/requests/archive/refs/tags/v2.31.0.tar.gz)


Both of these should be straight forward to automate, could you clarify where you're expecting to see it?

**Comment by nateprewitt** [comment]
Resolving since we haven't heard back.
