### ISSUE TITLE
HTTP/2 support - For real (even HTTP/3 is a reality right now!)

### ISSUE THREAD

**Issue by rfc-st** [psf/requests#6564]
Hi!,

[HTTP/2](https://en.wikipedia.org/wiki/HTTP/2) was introduced 8 years ago!.

Is there any intention to support it, its characteristics, in the **short** term?.

If not: is it for lack of time, interest, people?. Perhaps it would be interesting, in this case, to transfer this library to an organization that would have the necessary resources to update it; or, at least, to provide it with the required resources: has it been tried, is it of interest?. Anchoring in the past, I think, has never been a good idea.

If the answer is "**no**", or **"never**", I think the best option would be to abandon, and give up, this project so that others can make it even **bigger**.

Thank you (really) from someone who appreciates your work.

**Comment by sethmlarson** [comment]
Going to mark this as a "answered" by https://github.com/urllib3/urllib3/pull/3030, which has an extremely thorough description of what it would take for HTTP/2 support in urllib3, the underlying library of Requests. There is a lack of people and time, so if you have access to those things and want to solve the problem it would be much appreciated.

**Comment by rfc-st** [comment]
Thank you for your response. I still think that investing time in maintaining an already obsolete library is a waste of time.

But it is your time. I assure you it won't be mine :).

Thanks for speeding up my decision. And good luck, always.

Regards,

**Comment by nateprewitt** [comment]
> maintaining an already obsolete library is a waste of time.

Given it's the 4th most downloaded Python package globally, it must be serving _some_ purpose :) We wish you well.

**Comment by rfc-st** [comment]
Hi!,

Of course it is, of course this library is important, of course it is (or was?) necessary ... but you are eight years late. At least you are. And that, in our young ecosystem, is too long. And living on past achievements has never ensured either the present or the future.

And I am sorry, my apologies, if I sounded rude, but I insist on my idea: I sincerely believe that you are wasting your time. And, by extension, ours.

Of course I am not able to match what you have achieved, I do not have that knowledge, but I have ideas, some absurd: that this library, today, does not even allow me to carry them out.

Therefore, I repeat: Thank you, ample. For everything. And that perhaps it would be interesting to point out in your page that you have no intention to support neither the present nor the future, at least in the short term.

Since we are sincere, let's be completely sincere. Don't you agree? :).

Regards,

**Comment by abebeos** [comment]
@rfc-st , maybe take a look at https://github.com/jawah/urllib3.future
