### ISSUE TITLE
Requests doesn't work on emscripten / webassembly

### ISSUE THREAD

**Issue by joemarshall** [psf/requests#6567]
This is maybe verging on a feature request, I'm not sure...

Webassembly with emscripten is now an official python platform. However because it runs inside a browser sandbox environment, networking doesn't work normally, and hence nothing in requests works at all. However there is easy access to http(s) requests via the environment it is running in.

Right now, we have a monkeypatch module which patches a new BaseAdapter subclass into `Session.__init__` (see link below).

https://github.com/koenvo/pyodide-http/blob/main/pyodide_http/_requests.py

It isn't masses of code, because most of the stuff that is handled by lower level things in requests is just passed directly off to the browser fetch. 

It would be really nice if a version of this adapter could be added to requests (and the emscripten platform added to requests CI also, so we can see how much functionality works and how much doesn't.)

I did a bunch of work on the monkeypatch code above, so I'd be happy to help on this, but obviously I don't want to spend the time doing a PR for it if it isn't going to have a chance of being merged, hence opening this issue to discuss.

**Comment by sethmlarson** [comment]
Hey @joemarshall, thanks for opening this issue. We actually have a very similar issue on urllib3 (the underlying library of Requests) that has a bounty available. If you wanted to contribute there then many libraries would gain the ability to use WASM Python.

https://github.com/urllib3/urllib3/issues/2951

**Comment by sethmlarson** [comment]
I'm going to close this one now that https://github.com/urllib3/urllib3/issues/2951 is closed, Emscripten support isn't stable yet but should be at least possible once urllib3 is released.
