### ISSUE TITLE
HTTPSConnectionPool(port=443): Max retries exceeded with url:(Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by Hsgngr** [psf/requests#6569]
I having a long lasting problem with my request connection is getting shutdown using Cloud Run. I couldnt solve it yet so here I am to get support.

Here is the full error:
```
Error occurred: HTTPSConnectionPool(host='google.serper.dev', port=443): Max retries exceeded with url: /search (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))
```

Here is how I use request:

```
def serper_search(self, arguments):
        query = arguments["q"]
        url = "https://google.serper.dev/search"
        payload = json.dumps({"q": query})
        headers = {
            'X-API-KEY': self.api_key,
            'Content-Type': 'application/json'
        }

        try:
            response = requests.request(
                "POST", url, headers=headers, data=payload)
            # Will raise an HTTPError if the HTTP request returned an unsuccessful status code
            response.raise_for_status()


            # Parse the response and make it ready 
            parsed_response = self.parse_response(response, number_of_results=3)
            return parsed_response  # Assuming the response content is in JSON format
        except requests.exceptions.HTTPError as http_err:
            logger.error(f"HTTP error occurred: {http_err}")
            return None
        except Exception as e:
            logger.error(f"Error occurred: {e}")
            return None

```

This only happens in Cloud Run although the error should be on those side, there must a setting to override this issue on the request side as well. 

**I tried:**
- verify = False

didnt help.

**More info:**
Also I use this with fastapi and adding as a backgroundTask.
fastapi==0.103.1
requests==2.31.0

**Comment by gchux** [comment]
Saw your comment in:
https://github.com/psf/requests/issues/6429

Just wanted to remind anyone reading that Cloud Run does not allocate CPU outside request unless the revision is explicitly configured to do so; here are the docs:

https://cloud.google.com/run/docs/configuring/cpu-allocation

and here's a sample:

![image](https://github.com/psf/requests/assets/107634081/21afe839-5943-47d0-b2fe-7f15fa9efaaa)
