### ISSUE TITLE
Possible regression with how MaxRetryError is handled

### ISSUE THREAD

**Issue by mike406** [psf/requests#6576]
Since requests does not retry failed connections, a somewhat confusion exception is encountered by doing something like this.
```
>>> requests.get('http://localhost:12121')
...
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=12121): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029B47D92CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

I found in my searches about this exception that years ago this issue was reported and resolved in urllib3 by adding the ability to specify `retries=False` in the request: https://github.com/psf/requests/issues/1198#issuecomment-34582901

The result of the change back then gave a nicer exception output: https://github.com/psf/requests/issues/1198#issuecomment-57952852

Is this a regression, and if possible, could there once again be a way to get a cleaner exception message for this case? Thank you.

**Comment by sigmavirus24** [comment]
There is no regression here. That thread allows that for retries=False but requests always configures retries by default. You'll want to customize an HTTPAdapter to specify different behavior if you don't want to see a MaxRetryError in the exception message

**Comment by mike406** [comment]
So how many retries does requests configure? The docs say requests does not do any unless you use Session() https://requests.readthedocs.io/en/latest/user/advanced/#example-automatic-retries

Also I tried configuring HTTPAdapter with max_retries=0 or max_retries=False and the exception did not change. Am I doing something incorrectly?

```
from requests import Session
from requests.adapters import HTTPAdapter

s = Session()
a = HTTPAdapter(max_retries=0)
s.mount('http://', a)
s.get('http://localhost:12121')
```
