### ISSUE TITLE
Improper URL serialization of boolean GET parameters

### ISSUE THREAD

**Issue by mspi21** [psf/requests#6577]
Constructing a GET request with a boolean parameter `foo` set to `True` results in `&foo=True` being appended to the URL path, instead of just `&foo`. This makes it inoperable with some APIs (such as the [NIST CVE API](https://nvd.nist.gov/developers/vulnerabilities)) that return an error when a string value is set for a boolean GET parameter.

Example:
```py
>>> import requests
>>> API_URL = "https://services.nvd.nist.gov/rest/json/cves/2.0"
>>> res = requests.get(API_URL, params={"noRejected": True})
>>> res
<Response [404]>
>>> res.headers["message"]
'noRejected parameter cannot have a value.'
```

It's a mystery to me how such a basic feature of the de-facto standard library for making HTTP requests in Python hasn't yet been addressed and I would greatly appreciate if it could be fixed, or at least if a special value/object was added that could be passed as a value in `params` to produce the expected result. Working around this limitation by constructing the URL with all its parameters myself as a programmer does not inspire confidence in the security and correctness of the code.

## Expected Result

```py
>>> res.request.path_url
'/rest/json/cves/2.0?noRejected'
```

## Actual Result

```py
>>> res.request.path_url
'/rest/json/cves/2.0?noRejected=True'
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "5.1.0"
  },
  "charset_normalizer": {
    "version": "3.0.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.2"
  },
  "platform": {
    "release": "6.1.0-13-amd64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "300000b0"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by mspi21** [comment]
> In the future, please search **closed and** open issues before creating new ones that are duplicates.

What makes you think I haven't done that? Instead of lecturing me, the minimum you can do is provide a link or an ID. @sigmavirus24
