### ISSUE TITLE
Status Code 425 named incorrectly

### ISSUE THREAD

**Issue by mephinet** [psf/requests#6584]
HTTP status code 425 is defined as "too early". While the defining RFC defines the code in the context of TLS, I regularly find APIs that use this status code to indicate to a client that an asynchronous job that has been started is still being processed, so the result can not yet be provided.

requests.status_codes however doesn't know the reason "too early", and instead calls 425 "unordered_collection" and "unordered". I believe, this is a bug.

The defendent: https://github.com/psf/requests/blob/main/src/requests/status_codes.py#L82

I call to the witness stand:
* https://datatracker.ietf.org/doc/html/rfc8470
* https://http.cat/425
* https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors

## Expected Result
>>> requests.codes.get("TOO_EARLY")
425
## Actual Result
>>> requests.codes.get("TOO_EARLY")

## Reproduction Steps

```python
import requests
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.6"
  },
  "platform": {
    "release": "6.6.1-arch1-1",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30100040"
  },
  "urllib3": {
    "version": "2.0.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

```

**Comment by sigmavirus24** [comment]
I would merge a change to add that to the type definition. Keep in mind unordered was in wide use before that rfc though which is why it has that definition. I doubt anyone is using it from us but we can't remove it.

**Comment by atatuzuner61** [comment]
Implementing this in an upcoming PR.

**Comment by atatuzuner61** [comment]
Here is a PR with relevant changes that I believe are backwards compatible and generalizable. Could you take a look and give your initial thoughts? @nateprewitt

**Comment by nateprewitt** [comment]
Resolving now that #6592 is merged.
