### ISSUE TITLE
the first response history url is incorrect

### ISSUE THREAD

**Issue by xtremebeing** [psf/requests#6602]
The first url returned from response.url is different than the url passed to requests.get
## Expected Result

I expected the first history url to be that same as passed into requests.get

```
Redirect #1
URL: http://google.com
```

## Actual Result

The first redirected  url is always the same as the the first response.headers.get('Location')
```python resp.py         
requests.__version__ 2.31.0
initial url: http://google.com

Redirect #1
URL: http://google.com/
Status Code: 301
Redirect: http://www.google.com/

Redirect #2
URL: http://www.google.com/
Status Code: 302
Redirect: https://www.google.com/?gws_rd=ssl

URL: https://www.google.com/?gws_rd=ssl
Status Code: 200
Redirect: None
```

## Reproduction Steps

```python
import requests

url = "http://google.com"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
}
response = requests.get(url, headers=headers, allow_redirects=True)
print(f"requests.__version__ {requests.__version__}")
print(f"initial url: {url}\n")

for index, resp in enumerate(response.history, start=1):
    print(f"Redirect #{index}")
    print(f"URL: {resp.url}")
    print(f"Status Code: {resp.status_code}")
    print(f"Redirect: {resp.headers.get('Location')}\n")

print(f"URL: {response.url}")
print(f"Status Code: {response.status_code}")
print(f"Redirect: {response.headers.get('Location')}")

```

## System Information

 {
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.12"
  },
  "platform": {
    "release": "22.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "1010115f"
  },
  "urllib3": {
    "version": "2.0.7"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}

**Comment by nateprewitt** [comment]
Hi @xtremebeing,

I'm assuming you're referring to the trailing `/` in `https://google.com/`? That's a standard semantic of url normalization, and is identical to what you provided. This should be treated the same by a properly functioning server.

>  In general, a URI that uses the generic syntax for authority with an
   empty path should be normalized to a path of "/".

\- [RFC 3986 6.2.3](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.3)

You may try setting the URL again with the [PreparedRequest workflow](https://requests.readthedocs.io/en/latest/user/advanced.html#prepared-requests), but my hunch without having looked is this is happening in urllib3. If that's the case, this won't be adjustable.
