### ISSUE TITLE
Links at docs site return 404

### ISSUE THREAD

**Issue by mishankov** [psf/requests#6604]
At https://requests.readthedocs.io/en/latest/ all links under "Usefull links" lead to 404 page

## Expected Result

Open corresponding docs page

## Actual Result

404 page

## Reproduction Steps

- Open https://requests.readthedocs.io/en/latest/
- Click on "[Quickstart](https://requests.readthedocs.io/en/latest/user/quickstart/)"

## System Information
Not applicable

**Comment by mishankov** [comment]
Looks like `.html` at the end of link is what's missing

**Comment by jaikishpai** [comment]
Working on it.

**Comment by nateprewitt** [comment]
Resolved in #6605.
