### ISSUE TITLE
I don't think the name of this function is appropriate, because the return value of this function is a ConnectionPool object, and the first sentence of the comment is also wrong, which makes it a huge difficulty for me to read!!

### ISSUE THREAD

**Issue by gitlGl** [psf/requests#6610]
def get_connection(self, url, proxies=None):
        """Returns a urllib3 connection for the given URL. This should not be
        called from user code, and is only exposed for use when subclassing the
        :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.

        :param url: The URL to connect to.
        :param proxies: (optional) A Requests-style dictionary of proxies used on this request.
        :rtype: urllib3.ConnectionPool

**Comment by gitlGl** [comment]
come  from   adapters.py

HTTPAdapter(BaseAdapter)

**Comment by gitlGl** [comment]
adapters.HTTPAdapter.get_connection

**Comment by sigmavirus24** [comment]
You're right. As documented we are returning a connection pool which behaves almost identically to a connection. Alas, that method and that contract has existed for over a decade at this point, so we will not be changing it
