### ISSUE TITLE
python requests.get() stuck

### ISSUE THREAD

**Issue by mominurr** [psf/requests#6614]
url=links[x]
        
        try:
            response=requests.get(url,headers=HEADERLISTS,proxies={"http":proxy_lists[prox_index]},timeout=(10,10))
        except Exception as e:
            print("Error : ",e)
            sys.stderr = open('error.log', 'a+', encoding='utf-8')
            traceback.print_exc()
            sys.stderr.close()
            prox_index+=1
            time.sleep(1)
            continue
        if response.status_code==404:
            print("status code 404")
            prox_index+=1
            CURRENT_NUMBER+=1
            x+=1
            time.sleep(1)
            continue
        if response.status_code!=200:
            print("status code: ",response.status_code)
            prox_index+=1
            time.sleep(1)
            continue
        time.sleep(1)
        prox_index+=1
        CURRENT_NUMBER+=1
        x+=1
        

**This is my code. Script running After sometime response is not comming and get stuck. Next iteration is not going. Please give me solution.**

**Comment by Mariatta** [comment]
This doesn't look like a bug with requests library but with your code. Please ask in StackOverflow and using the `python-requests` tag.
