### ISSUE TITLE
Kenneth Reitz, Take care of yourself.

### ISSUE THREAD

**Issue by hackware1993** [psf/requests#6627]
I am also the author of a popular open-source library (MagicIndicator, 10K stars). Similarly, I have experienced manic depression (bipolar disorder), but I have overcome it and now lead a normal, positive life. I hope you recover soon too. Keep fighting!

**Comment by sethmlarson** [comment]
Closing this issue as it's not an issue in Requests. Please consider avenues of messaging folks directly, opening GitHub issues pings thousands of unrelated people.
