### ISSUE TITLE
Multipart/form-data requests creates mismatched boundaries between request body and headers

### ISSUE THREAD

**Issue by p1gyy** [psf/requests#6630]
## Expected Result
multipart/form-data requests should have the same boundary in the request content-type headers and request body:

Content-Type header: `multipart/form-data; boundary=bb8517293e3e961b2e7dfbd4e303fe56`
Boundary for request body: `--bb8517293e3e961b2e7dfbd4e303fe56`
## Actual Result
multipart/form-data requests have different boundaries in the request content-type headers and request body:

Content-Type header: `multipart/form-data; boundary=bb8517293e3e961b2e7dfbd4e303fe56`
Boundary for request body: `--42fdbee1e9d775f1239dda28331699a7`

## Reproduction Steps

```python
import requests
session = requests.session()

data = {
  "name": "test",
  "description": "test",
}
files = {'upload_file': open("yourfile.txt", "rb")}
req = session.post("https://example.com", files=files, data=data)

print("Request Headers: " + str(req.request.headers))
print("Request Body: " + str(req.request.body))
print("Status Code: " + str(req.status_code))
print("Response Headers: " + str(req.headers))
print("Response Body: " + str(req.text))
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "charset_normalizer": {
    "version": "2.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.7"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.11"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
I cannot reproduce this at all. The only time the boundary tends to differ in the header from what's in the body is when the user overrides the Content-Type header manually.

In the future, please search **closed and** open issues before creating new ones that are duplicates.
