### ISSUE TITLE
`params` might be misnamed?

### ISSUE THREAD

**Issue by Matthew1471** [psf/requests#6631]
### Summary

Being a bit pedantic but isn't it that the `parameters` of a URL are a ";<parameters>" affair inside the path e.g. `https://example.com/document;language=english?documentID=5` ([RFC source](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) and [summary](https://stackoverflow.com/a/39294675)) and what Requests calls `params` is actually the `query`.. which I long have been calling the "querystring" thanks to my days of Classic ASP programming referencing the "query string" (https://www.w3schools.com/asp/coll_querystring.asp and https://en.wikipedia.org/wiki/Query_string).

[Documentation calls them part of the query string too](https://requests.readthedocs.io/en/latest/user/quickstart/#passing-parameters-in-urls).

### What you expected

Good question, maybe the keyword to be `query`? But I highly doubt there will be any aspiration to start renaming the library's keywords at this late stage in a way that would cause a breaking change (unless both were accepted and one was mapped to the other). Validation I guess that I am right (or a correction if I am wrong)?

**Comment by sigmavirus24** [comment]
Parameters is another common name for the parsed (not encoded) pieces of the query string. `params` are meant to be passed as a native python object (e.g., dictionary of string to string, sequence of tuples of length 2, etc). So if you parsed a query string into parameters on the server side, the client side would take parameters and encode them into the query string 

Edit to add: 

- https://www.botify.com/learn/basics/what-are-url-parameters#:~:text=URL%20parameters%20(also%20known%20as,by%20the%20'%26'%20symbol.
- https://rapidapi.com/blog/api-glossary/parameters/#:~:text=API%20parameters%20are%20the%20variable,present%20in%20the%20API%20endpoint.
- https://support.google.com/google-ads/answer/6277564?hl=en
- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
- https://docs.oracle.com/en/cloud/saas/marketing/eloqua-develop/Developers/GettingStarted/APIRequests/URL-parameters.htm
- https://sentry.io/answers/how-to-get-values-from-urls-in-javascript/
- https://www.w3docs.com/snippets/javascript/how-to-get-url-parameters.html

None of this is to say you're wrong and we're right, just that it's not uncommon for the query string to be called query parameters or parameters for short
