### ISSUE TITLE
Getting warning while running databricks cli command in azure devops

### ISSUE THREAD

**Issue by AGpta** [psf/requests#6633]
Hello team,

i am using Databricks Cli for deployment of notebooks on azure and it is throwing below warning. Could you help me to resolve warning? Also i am using pip install --upgrade urllib3 chardet command to upgrade but still it is giving warning.
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.0) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

## Expected Result
 I want to ignore/resolve the warning.

## Actual Result
 It is throwing warning as below
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.0) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
