### ISSUE TITLE
IPv6 address change for sequential gets

### ISSUE THREAD

**Issue by Gezzo42** [psf/requests#6635]
I'm not sure, if the following issue is caused by requests or one of the underlying libraries. 
The library [python-fritzhome](https://github.com/hthiery/python-fritzhome/) uses requests to connect to the HTTP interface of a router called FRITZ!Box. During sequential get calls, the IPv6 address is switched.
I already opened an [issue](https://github.com/hthiery/python-fritzhome/issues/92) for the mentioned library, but got no solution.

## Expected Result

All connections of the same session object are made using the same IPv6 address.

## Actual Result

The third get request uses a different IPv6 address (extract of a tcpdump record):
![grafik](https://github.com/psf/requests/assets/31780740/2833bf6a-0a23-44ed-97d8-8c639023adf5)

## Reproduction Steps

```python
import requests
import time

s = requests.Session()
rsp = s.get('http://fritz.box/login_sid.lua')
rsp.raise_for_status()
time.sleep(0.5)
rsp = s.get('http://fritz.box/login_sid.lua')
rsp.raise_for_status()
time.sleep(0.5)
rsp = s.get('http://fritz.box/login_sid.lua')
rsp.raise_for_status()
print(rsp.text.strip())
```

## System Information

Hardware and OS: Raspberry Pi 5, Raspberry Pi OS Lite 64 based on Debian 12

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": "41.0.7"
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.2"
  },
  "platform": {
    "release": "6.1.0-rpi8-rpi-2712",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30100040",
    "version": "23.2.0"
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "300000b0"
  },
  "urllib3": {
    "version": "2.1.0"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": true
}
```

**Comment by Gezzo42** [comment]
Removing the sleep calls did not change anything:
![grafik](https://github.com/psf/requests/assets/31780740/615a4144-ea6d-4eb8-9f7b-c37fa72391ea)

**Comment by sigmavirus24** [comment]
@Gezzo42 this is not a bug. It's not ideal that when looking up the DNS for a hostname we only ever use 1 address. It's also not clear why you consider this a bug. Even still, this can likely be reproduced with just `urllib3` and potentially even with _any_ http client in Python (aiohttp, httpx, etc.) If you want to pin to a given IP address, you will want to specify it yourself. These all seem to be local addresses.

To get the ideal behaviour, you likely want to ensure:
* The library you're using isn't disabling keep-alive
* The server you're communicating with supports keep-alive
* Anything you have between you and the server isn't preventing keep-alive.
