### ISSUE TITLE
[BUG] pytest error in python:3.8- (only work in 3.7) because httpbin uses deprecated werkzeug function 'parse_authorization_header'

### ISSUE THREAD

**Issue by bgb10** [psf/requests#6637]
# Summary
pytest error happens in python:3.8- (only work in 3.7) because httpbin uses **deprecated werkzeug function 'parse_authorization_header'**. Because of this, pytest don't work above python 3.8 version, and it could be a serious problem for requests.py contributers. 

I'm new to open source contributing, so if you have any suggestions, I'd appreciate it :)

# How I found this error?
As python newcomer, I thought requests.py is the best library to learn about python, OOP, networking. So I cloned a code and ran pytest.

## Expected Result
I expected pytest working well, but the error occured.

## Actual Result
![image](https://github.com/psf/requests/assets/25452313/2a842496-82e4-4c76-aa15-42fee77c5229)
this is the error stacktrace I've got, and it says ImportError from 'httpbin' library when importing werkzeug.http 'parse_authorization_header' function. 

# Problem Analysis
## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.7"
  },
  "platform": {
    "release": "5.15.49-linuxkit",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "1010117f"
  },
  "urllib3": {
    "version": "2.2.0"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

## Installation

```bash
git clone https://github.com/psf/requests.git
cd requests
pip install .
pip install -r requirements-dev.txt
pytest
```

## Works in python:3.7 but higher versions are not
I used docker environment(not venv, but working same in venv!) to reproduce the problem, and I found only python:3.7 works but higher versions are not. 

In python:3.7, pytest running well.
![image](https://github.com/psf/requests/assets/25452313/5f2631bb-521a-497e-a8e0-d1abfd5bc1c2)

But in python:3.8 and 3.10, pytest errors ImportError!
![image](https://github.com/psf/requests/assets/25452313/cf9d8120-c34c-41a6-b6f8-29e291b20ead)
![image](https://github.com/psf/requests/assets/25452313/17be1a4c-b18f-4409-8a63-881012a5924f)

## Reason of Error
'httpbin' is using 'werkzeug's parse_authorization_header from http.py. However, parse_authorization_header is deprecated since 3.0 and .Authorization.from_header should be used instead.

Requests.py uses Werkzeug 3.0.1 since python 3.8 and this is causing compatibility issues with httpbin

# How to solve it?
I think the best one is fixing httpbin source code so I'll upload an issue to them. 

This error is not directly related with requests.py because the error cause is in another library, but I think error could be a problem for contributers, so I think a solution is needed.
**In my case, changing the werkzeug version to v2.2.3 solved it (flask throws a warning, but pytest in requests.py works fine).** 
I would like contributors to be aware of the issues I mentioned. Thank you!

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Comment by bgb10** [comment]
> In the future, please search **closed and** open issues before creating new ones that are duplicates.

Thank you for your response, I will be more careful.
