### ISSUE TITLE
pytest.warns(None) is no longer supported

### ISSUE THREAD

**Issue by wRAR** [psf/requests#6679]
Not sure what was this code supposed to mean (making sure that there are no warnings? I don't think it ever did that?), but on pytest 8 it no longer works: "TypeError: exceptions must be derived from Warning, not <class 'NoneType'>"

https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests

**Comment by frenzymadness** [comment]
From the pytest's changelog:

> #8645: pytest.warns(None) is now deprecated because many people used it to mean “this code does not emit warnings”, but it actually had the effect of checking that the code emits at least one warning of any type - like pytest.warns() or pytest.warns(Warning).

**Comment by frenzymadness** [comment]
And this is the code we are talking about:

https://github.com/psf/requests/blob/2a438c27b5a5828c8ea0dc958112eecffca70b12/tests/test_requests.py#L1006-L1008

**Comment by frenzymadness** [comment]
In our testing environment with pytest 8.1.1 and urllib3 < 2.0 removing the None from `pytest.warns` fixes the problem.

**Comment by kloczek** [comment]
> In our testing environment with pytest 8.1.1 and urllib3 < 2.0 removing the None from `pytest.warns` fixes the problem.

Can you open PR with that fix? 🤔

**Comment by frenzymadness** [comment]
I'm not sure why the last comment by @kloczek has been removed but PR with the simple fix is ready.
