### ISSUE TITLE
Can't access trailers with the Request library

### ISSUE THREAD

**Issue by fmurray-r7** [psf/requests#6697]
Requests doesn't seem to support processing [Trailer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer) response headers.  While I know that Trailer support has been [discussed](https://github.com/psf/requests/issues/3613) [previously](https://github.com/psf/requests/issues/2281), some time has passed since then and I hope the issue can be reconsidered. 

The desired use case is to add Trailer header to API responses but we cannot read them using the Request library.
Other frameworks in other languages ([Vert.x](https://vertx.io/docs/vertx-core/java/#_chunked_http_responses_and_trailers) for example) support Trailers, but not Python Requests.

## Expected Result
A Trailer response header has been added to a response, which is then read using Requests, the Trailer should be accessible.

## Actual Result
There is no way to access the Trailer in the response using Requests.

**Comment by sigmavirus24** [comment]
Nothing has changed since that thread. We still rely on httplib and httplib (or now http.client) does not support trailers for HTTP/1.1. i suspect some other http clients may be able to support this as they are built on h11 but whether they do or don't I couldn't tell you
