### ISSUE TITLE
inconsistent handling of verify and REQUESTS_CA_BUNDLE

### ISSUE THREAD

**Issue by houtmanj** [psf/requests#6742]
The interaction between the `verify`  parameter and REQUESTS_CA_BUNDLE is inconsistent when using a `Session`. 

Assuming the REQUESTS_CA_BUNDLE  environment variable is set.

will NOT result in ssl verification:
```
sess = requests.Session()
sess.get("https://illegalcert.com", verify=False)
```
will verify the ssl verification:
```
sess = requests.Session()
sess.verify = False
sess.get("https://illegalcert.com")
```

## Expected Result
I would expect both scenario's not to verify the ssl certificate. 

## Actual Result
When session.verify is set to False, it is overruled by the existence of the REQUESTS_CA_BUNDLE environment variable. 

## Reproduction Steps

export REQUESTS_CA_BUNDLE=/path/to/ca
```python
sess = requests.Session()

# Will not verify the ssl certificate
sess.get("https://illegalcert.com", verify=False)

# will verify the ssl certificate
sess.verify = False
sess.get("https://illegalcert.com")
```

This is governed by:  https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/sessions.py#L766

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.6"
  },
  "platform": {
    "release": "5.15.146.1-microsoft-standard-WSL2",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "2.2.1"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
In the future, please search **closed and** open issues before creating new ones that are duplicates.
