### ISSUE TITLE
requests > 2.31.0 - Unhashable type 'list' for 'cert' parameter

### ISSUE THREAD

**Issue by greateggsgreg** [psf/requests#6751]
### Subject

The requests.get() parameter used to accept 'cert' as a tuple or list, and this may be a regression from #1165 

### Environment

All

### Steps to Reproduce

```
>>> import requests
>>> requests.get('https://localhost:8080/asdf', cert=['client-cert.pem', 'client-key.pem'], verify='ca-cert.pem')
Traceback (most recent call last):
<snip>
TypeError: unhashable type: 'list'
>>> requests.get('https://localhost:8080/asdf', cert=('client-cert.pem', 'client-key.pem'), verify='ca-cert.pem')
<Response [200]>
```

### Expected Behavior

From requests == 2.31.0:
```
>>> import requests
>>> requests.get('https://localhost:8080/asdf'', cert=['client-cert.pem', 'client-key.pem'], verify='ca-cert.pem')
<Response [200]>
```

**Comment by sigmavirus24** [comment]
It's always been documented as a tuple, and there's never been testing for accepting a list. I understand this seems like a regression but in reality it's an accidental improvement in what we accept to better match what we have documented since before 1.0

**Comment by rayjlinden** [comment]
It broke shit. Thanks for that.  Particularly, since you also improved nothing...
