### ISSUE TITLE
Possible .get bug in version 2.32.3

### ISSUE THREAD

**Issue by mhenrichsen** [psf/requests#6753]
When executing a file named ast.py which  .get(url) it fails with `AttributeError: partially initialized module 'requests' has no attribute 'get' (most likely due to a circular import)`
## Expected Result

To fetch the contents.

1. Create a file named ast.py
2. 

```import requests

x = requests.get('https://w3schools.com')
print(x.status_code)
```
3. rename the file for success.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.12.4"
  },
  "platform": {
    "release": "23.2.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.32.3"
  },
  "system_ssl": {
    "version": "30300010"
  },
  "urllib3": {
    "version": "2.2.1"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
[`ast`](https://docs.python.org/3/library/ast.html) is a module in the standard library. Shadowing commonly used modules will lead to breakages in most Python libraries. This isn't something we can address in Requests, this is a fundamental of the language.

**Comment by mhenrichsen** [comment]
@nateprewitt thanks for letting me know. It was driving me crazy.
