### ISSUE TITLE
CURL and Requests.session() returning different values during SSL and CA verification

### ISSUE THREAD

**Issue by mittal-umang** [psf/requests#6832]
I don't know if anyone has seen this happen. but when i'm using Requests.Session() for making a requests to HTTPS URL with SSL certificate and CA cert verification it doesn't give correct response. 
Whereas when i use the same certs(SSL and CA Cert) with CURL command it works seamlessly.  

This is causing https://github.com/confluentinc/confluent-kafka-python/issues/1850

## Expected Result

Requests.Session() should work and not respond with a SSL Verification Error

## Actual Result

SSLVerificationError

## Reproduction Steps
No actual steps but try making a API call to HTTPS url with SSL Verification and CA Cert.

**Comment by sigmavirus24** [comment]
I have no issues verifying TLS with a proper trust bundle and a server providing the full chain. Is this specific to Kafka or are you experiencing this with something other than Kafka as well?

**Comment by allamiro** [comment]
Could you specify the versions of the Schema Registry and Kafka you are using? Additionally, did this issue arise following a certificate update or library /client updates, or did it occur suddenly without any recent changes?

**Comment by sigmavirus24** [comment]
Let's keep all of the discussion in the original issue instead. I'm certain this isn't an issue with requests. I use it with a custom trust store and private PKI as well as with certifi and normal websites daily. Whatever the problem is more relevant to the kafka library
