### ISSUE TITLE
v 2.32.3 sends multiple requests

### ISSUE THREAD

**Issue by MikoBie** [psf/requests#6838]
I am working with quite an old and slow API -- [GDELT](https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/). I am trying to send a single get request. However, in response, I get a message that I send too many requests at the same time. I suspect that it is the issue of the timeout settings but setting it to very liberal values for example 3 and 27 does not really help. I think the issue appeared somewhere between versions 2.31.0 and 2.32.3 because this occurs only in the latter.

## Expected Result

Send a single get request.

## Actual Result

For some reason, API returns a message of multiple requests sent. Therefore, I suspect that the timeout option does not work properly. In other words, requests do not wait long enough for the response before sending a repetitive request.

## Reproduction Steps

```python
import requests as rq

API_URL = "https://api.gdeltproject.org/api/v2/doc/doc?"
query = {"query" : "human", "format" : "JSON"}

response = rq.get(API_URL, query, timeout = (3,27))
```

## System Information

For the sake of reproducibility, I tested it in Google Colab.

```json
{
  "chardet": {
    "version": "5.2.0"
  },
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "cryptography": {
    "version": "43.0.3"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.12"
  },
  "platform": {
    "release": "6.1.85+",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30300020",
    "version": "24.2.1"
  },
  "requests": {
    "version": "2.32.3"
  },
  "system_ssl": {
    "version": "30000020"
  },
  "urllib3": {
    "version": "2.2.3"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": true
}
```

**Comment by snooppr** [comment]
I confirm the problem.
Requests 2.31.0
response = <Response [200]>
Requests 2.32.3
response = <Response [429]> 'Please limit requests to one every 5 seconds or contact email for larger queries.\n\n'

@MikoBie 
>In other words, requests do not wait long enough for the response before sending a repetitive request.

Why did you decide that "Requests" should resend requests after timeout? As far as I can tell, only one request should have occurred, not several (the "HTTPAdapter" with the "max_retries" parameter is not used).

**Comment by sigmavirus24** [comment]
On the response object you received, are there any redirects in the `.history` attribute?

**Comment by snooppr** [comment]
`response.history`
[]
`
requests.headers `2.31.0
{'Date': 'Fri, 06 Dec 2024 13:04:21 GMT', 'Server': 'GDELT Server', 'Access-Control-Allow-Origin': '*', 'Timing-Allow-Origin': '*', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'public, max-age=900', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=utf-8'}

`requests.headers `2.32.3
{'Date': 'Fri, 06 Dec 2024 13:03:46 GMT', 'Server': 'GDELT Server', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked'}

**Comment by sigmavirus24** [comment]
@snooppr would you mind printing `response.request.headers` instead and maybe turning on https://urllib3.readthedocs.io/en/stable/user-guide.html#logging

**Comment by snooppr** [comment]
@sigmavirus24 
You can reproduce the problem on your UNIX, as I switched from PC to Termux and the problem is apparently the same.

![req](https://github.com/user-attachments/assets/78956c22-ff44-4e7d-a97e-c36cedf3a220)


test_url = 'https://api.gdeltproject.org/api/v2/doc/doc?query=human&format=JSON'

**Comment by MikoBie** [comment]
@snooppr 
> Why did you decide that "Requests" should resend requests after timeout? As far as I can tell, only one request should have occurred, not several (the "HTTPAdapter" with the "max_retries" parameter is not used).

My bad. Of course, you are right. I think I did not understand the timeout time when I read the docs first. It should send one request regardless of the timeout set.

In general, I tested it first on UNIX (with POP_OS and MacOS) and the issue was persistent across the platforms (though I have not tested it on Windows). I put Google Colab in the description since I figured it was the easiest to reproduce.

**Comment by sigmavirus24** [comment]
I'm not at a computer at the moment, purely posting from my phone. Not able to reliably test this but those logs show that there aren't multiple requests happening to trigger this behavior and it's entirely server side that we can't control. 

This may be matching on the user agent string to prevent a DoS they're experiencing and that's all. So you can attempt to change that, but this isn't a bug

**Comment by MikoBie** [comment]
@sigmavirus24 thank you! You are right. The API returns status code 429 based on the header's User-Agent value. Apparently, for some reason "python-requests/2.32.3" is not welcomed unlike "python-requests/2.31.0".

**Comment by sigmavirus24** [comment]
Scrapers, bot authors, etc ruin things for everyone

**Comment by MikoBie** [comment]
Yeah, it is a bit on me cause I could and should have used a less generic User-Agent.
